
C_massdist <- "massdist"
C_R_approx <- "R_approx"
C_fft <- "fft"
C_mvfft <- "mvfft"
C_nextn <- "nextn"
C_SplineCoef <- "SplineCoef"
C_SplineEval <- "SplineEval"
C_monoFC_m <- "monoFC_m"
C_cor <- "cor"
C_cov <- "cov"
C_ARIMA_transPars <- "ARIMA_transPars"
