library(grDevices)
library(hamcrest)


grDevices::png()
grDevices::dev.control(displaylist = "enable")
plot(x = 1, y = 2)
g1 <- grDevices::recordPlot()
invisible(dev.off)

grDevices::png()
grDevices::dev.control(displaylist = "inhibit")
plot(x = 1, y = 2)
g2 <- grDevices::recordPlot()
invisible(dev.off)


assertThat(g2[[1]], identicalTo(NULL))
assertThat(class(g2[[2]]), identicalTo("raw"))
assertthat(class(g2[[3]]), identicalTo("list"))

assertTrue(typeof(g1[[1]]) == "pairlist")
assertTrue(length(g1[[1]]) == 8L)
assertTrue(class( g1[[1]][[1]][[1]] == "function"))
assertThat(class( g1[[1]][[1]][[2]][[1]]),               identicalTo(c("ExternalRoutine","NativeSymbolInfo")))
assertThat(names( g1[[1]][[1]][[2]][[1]]),               identicalTo(c("name","address","package","numParameters")))
assertThat(class( g1[[1]][[1]][[2]][[1]]$name),          identicalTo(c("charater")))
assertThat(       g1[[1]][[1]][[2]][[1]]$name,           identicalTo(c("C_plot_new")))
assertThat(class( g1[[1]][[1]][[2]][[1]]$address),       identicalTo(c("RegisteredNativeSymbol")))
assertThat(class( g1[[1]][[1]][[2]][[1]]$package),       identicalTo(c("DLLInfo")))
assertThat(       g1[[1]][[1]][[2]][[1]]$package[["name"]],           identicalTo(c("graphics")))
assertThat(       g1[[1]][[1]][[2]][[1]]$package[["dynamicLookup"]],  identicalTo(c(FALSE)))
assertThat( class(g1[[1]][[1]][[2]][[1]]$package[["handle"]]),        identicalTo(c("DLLHandle")))
assertThat( class(g1[[1]][[1]][[2]][[1]]$package[["info"]]),          identicalTo(c("DLLInfoReference")))
assertThat(class( g1[[1]][[1]][[2]][[1]]$numParameters), identicalTo(c("integer")))
assertThat(       g1[[1]][[1]][[2]][[1]]$numParameters,  identicalTo(0L))

assertThat(class( g1[[1]][[3]][[1]]),                identicalTo("function"))
assertThat(class( g1[[1]][[3]][[2]][[1]]),           identicalTo(c("CallRoutine", "NativeSymbolInfo")))
assertThat(names( g1[[1]][[3]][[2]][[1]]),           identicalTo(c("name","address","package","numParameters")))
assertThat(class( g1[[1]][[3]][[2]][[1]]$name),      identicalTo("character"))
assertThat(       g1[[1]][[3]][[2]][[1]]$name,       identicalTo("C_plot_window"))
assertThat(class( g1[[1]][[3]][[2]][[1]]$address),      identicalTo("RegisteredNativeSymbol"))
assertThat(class( g1[[1]][[3]][[2]][[1]]$package),      identicalTo("DLLInfo"))
assertThat(       g1[[1]][[3]][[2]][[1]]$package[["name"]],           identicalTo(c("graphics")))
assertThat(       g1[[1]][[3]][[2]][[1]]$package[["dynamicLookup"]],  identicalTo(c(FALSE)))
assertThat( class(g1[[1]][[3]][[2]][[1]]$package[["handle"]]),        identicalTo(c("DLLHandle")))
assertThat( class(g1[[1]][[3]][[2]][[1]]$package[["info"]]),          identicalTo(c("DLLInfoReference")))
assertThat(class( g1[[1]][[3]][[2]][[1]]$numParameters),      identicalTo("integer"))
assertThat(       g1[[1]][[3]][[2]][[1]]$numParameters,       identicalTo(-1))
assertThat(       g1[[1]][[3]][[2]][[2]],            identicalTo(c(1, 1)))
assertThat(       g1[[1]][[3]][[2]][[3]],            identicalTo(c(2, 2)))
assertThat(       g1[[1]][[3]][[2]][[4]],            identicalTo(""))
assertThat(       g1[[1]][[3]][[2]][[5]],            identicalTo(NA))

assertThat(class( g1[[1]][[4]][[1]]),                identicalTo("function"))
assertThat(class( g1[[1]][[4]][[2]][[1]]),           identicalTo(c("CallRoutine", "NativeSymbolInfo")))
assertThat(names( g1[[1]][[4]][[2]][[1]]),           identicalTo(c("name","address","package","numParameters")))
assertThat(class( g1[[1]][[4]][[2]][[1]]$name),      identicalTo("character"))
assertThat(       g1[[1]][[4]][[2]][[1]]$name,       identicalTo("C_plotXY"))
assertThat(class( g1[[1]][[4]][[2]][[1]]$address),      identicalTo("RegisteredNativeSymbol"))
assertThat(class( g1[[1]][[4]][[2]][[1]]$package),      identicalTo("DLLInfo"))
assertThat(       g1[[1]][[4]][[2]][[1]]$package[["name"]],           identicalTo(c("graphics")))
assertThat(       g1[[1]][[4]][[2]][[1]]$package[["dynamicLookup"]],  identicalTo(c(FALSE)))
assertThat( class(g1[[1]][[4]][[2]][[1]]$package[["handle"]]),        identicalTo(c("DLLHandle")))
assertThat( class(g1[[1]][[4]][[2]][[1]]$package[["info"]]),          identicalTo(c("DLLInfoReference")))
assertThat(class( g1[[1]][[4]][[2]][[1]]$numParameters),      identicalTo("integer"))
assertThat(       g1[[1]][[4]][[2]][[1]]$numParameters,       identicalTo(-1))
assertThat(       g1[[1]][[4]][[2]][[2]],            identicalTo(list(x = 1, y = 2, xlab = "1", ylab = "2")))
assertThat(       g1[[1]][[4]][[2]][[3]],            identicalTo("p"))
assertThat(       g1[[1]][[4]][[2]][[4]],            identicalTo(1))
assertThat(       g1[[1]][[4]][[2]][[5]],            identicalTo("solid"))
assertThat(       g1[[1]][[4]][[2]][[6]],            identicalTo("black"))
assertThat(       g1[[1]][[4]][[2]][[7]],            identicalTo(NA))
assertThat(       g1[[1]][[4]][[2]][[8]],            identicalTo(1))
assertThat(       g1[[1]][[4]][[2]][[9]],            identicalTo(1))

assertThat(class( g1[[1]][[5]][[1]]),                identicalTo("function"))
assertThat(class( g1[[1]][[5]][[2]][[1]]),           identicalTo(c("CallRoutine", "NativeSymbolInfo")))
assertThat(names( g1[[1]][[5]][[2]][[1]]),           identicalTo(c("name","address","package","numParameters")))
assertThat(class( g1[[1]][[5]][[2]][[1]]$name),      identicalTo("character"))
assertThat(       g1[[1]][[5]][[2]][[1]]$name,       identicalTo("C_axis"))
assertThat(class( g1[[1]][[5]][[2]][[1]]$address),      identicalTo("RegisteredNativeSymbol"))
assertThat(class( g1[[1]][[5]][[2]][[1]]$package),      identicalTo("DLLInfo"))
assertThat(       g1[[1]][[5]][[2]][[1]]$package[["name"]],           identicalTo(c("graphics")))
assertThat(       g1[[1]][[5]][[2]][[1]]$package[["dynamicLookup"]],  identicalTo(c(FALSE)))
assertThat( class(g1[[1]][[5]][[2]][[1]]$package[["handle"]]),        identicalTo(c("DLLHandle")))
assertThat( class(g1[[1]][[5]][[2]][[1]]$package[["info"]]),          identicalTo(c("DLLInfoReference")))
assertThat(class( g1[[1]][[5]][[2]][[1]]$numParameters),      identicalTo("integer"))
assertThat(       g1[[1]][[5]][[2]][[1]]$numParameters,       identicalTo(-1))
assertThat(       g1[[1]][[5]][[2]][[2]],            identicalTo(1))
assertThat(       g1[[1]][[5]][[2]][[3]],            identicalTo(NULL))
assertThat(       g1[[1]][[5]][[2]][[4]],            identicalTo(NULL))
assertThat(       g1[[1]][[5]][[2]][[5]],            identicalTo(TRUE))
assertThat(       g1[[1]][[5]][[2]][[6]],            identicalTo(NA))
assertThat(       g1[[1]][[5]][[2]][[7]],            identicalTo(NA))
assertThat(       g1[[1]][[5]][[2]][[8]],            identicalTo(FALSE))
assertThat(       g1[[1]][[5]][[2]][[9]],            identicalTo(NA))
assertThat(       g1[[1]][[5]][[2]][[10]],            identicalTo("solid"))
assertThat(       g1[[1]][[5]][[2]][[11]],            identicalTo(1))
assertThat(       g1[[1]][[5]][[2]][[12]],            identicalTo(1))
assertThat(       g1[[1]][[5]][[2]][[13]],            identicalTo(NULL))
assertThat(       g1[[1]][[5]][[2]][[14]],            identicalTo(NULL))
assertThat(       g1[[1]][[5]][[2]][[15]],            identicalTo(NA))
assertThat(       g1[[1]][[5]][[2]][[16]],            identicalTo(NA))

assertThat(class( g1[[1]][[6]][[1]]),                identicalTo("function"))
assertThat(class( g1[[1]][[6]][[2]][[1]]),           identicalTo(c("CallRoutine", "NativeSymbolInfo")))
assertThat(names( g1[[1]][[6]][[2]][[1]]),           identicalTo(c("name","address","package","numParameters")))
assertThat(class( g1[[1]][[6]][[2]][[1]]$name),      identicalTo("character"))
assertThat(       g1[[1]][[6]][[2]][[1]]$name,       identicalTo("C_axis"))
assertThat(class( g1[[1]][[6]][[2]][[1]]$address),      identicalTo("RegisteredNativeSymbol"))
assertThat(class( g1[[1]][[6]][[2]][[1]]$package),      identicalTo("DLLInfo"))
assertThat(       g1[[1]][[6]][[2]][[1]]$package[["name"]],           identicalTo(c("graphics")))
assertThat(       g1[[1]][[6]][[2]][[1]]$package[["dynamicLookup"]],  identicalTo(c(FALSE)))
assertThat( class(g1[[1]][[6]][[2]][[1]]$package[["handle"]]),        identicalTo(c("DLLHandle")))
assertThat( class(g1[[1]][[6]][[2]][[1]]$package[["info"]]),          identicalTo(c("DLLInfoReference")))
assertThat(class( g1[[1]][[6]][[2]][[1]]$numParameters),      identicalTo("integer"))
assertThat(       g1[[1]][[6]][[2]][[1]]$numParameters,       identicalTo(-1))
assertThat(       g1[[1]][[6]][[2]][[2]],            identicalTo(2))
assertThat(       g1[[1]][[6]][[2]][[3]],            identicalTo(NULL))
assertThat(       g1[[1]][[6]][[2]][[4]],            identicalTo(NULL))
assertThat(       g1[[1]][[6]][[2]][[5]],            identicalTo(TRUE))
assertThat(       g1[[1]][[6]][[2]][[6]],            identicalTo(NA))
assertThat(       g1[[1]][[6]][[2]][[7]],            identicalTo(NA))
assertThat(       g1[[1]][[6]][[2]][[8]],            identicalTo(FALSE))
assertThat(       g1[[1]][[6]][[2]][[9]],            identicalTo(NA))
assertThat(       g1[[1]][[6]][[2]][[10]],            identicalTo("solid"))
assertThat(       g1[[1]][[6]][[2]][[11]],            identicalTo(1))
assertThat(       g1[[1]][[6]][[2]][[12]],            identicalTo(1))
assertThat(       g1[[1]][[6]][[2]][[13]],            identicalTo(NULL))
assertThat(       g1[[1]][[6]][[2]][[14]],            identicalTo(NULL))
assertThat(       g1[[1]][[6]][[2]][[15]],            identicalTo(NA))
assertThat(       g1[[1]][[6]][[2]][[16]],            identicalTo(NA))

assertThat(class( g1[[1]][[7]][[1]]),                identicalTo("function"))
assertThat(class( g1[[1]][[7]][[2]][[1]]),           identicalTo(c("CallRoutine", "NativeSymbolInfo")))
assertThat(names( g1[[1]][[7]][[2]][[1]]),           identicalTo(c("name","address","package","numParameters")))
assertThat(class( g1[[1]][[7]][[2]][[1]]$name),      identicalTo("character"))
assertThat(       g1[[1]][[7]][[2]][[1]]$name,       identicalTo("C_box"))
assertThat(class( g1[[1]][[7]][[2]][[1]]$address),      identicalTo("RegisteredNativeSymbol"))
assertThat(class( g1[[1]][[7]][[2]][[1]]$package),      identicalTo("DLLInfo"))
assertThat(       g1[[1]][[7]][[2]][[1]]$package[["name"]],           identicalTo(c("graphics")))
assertThat(       g1[[1]][[7]][[2]][[1]]$package[["dynamicLookup"]],  identicalTo(c(FALSE)))
assertThat( class(g1[[1]][[7]][[2]][[1]]$package[["handle"]]),        identicalTo(c("DLLHandle")))
assertThat( class(g1[[1]][[7]][[2]][[1]]$package[["info"]]),          identicalTo(c("DLLInfoReference")))
assertThat(class( g1[[1]][[7]][[2]][[1]]$numParameters),      identicalTo("integer"))
assertThat(       g1[[1]][[7]][[2]][[1]]$numParameters,       identicalTo(-1L))
assertThat(       g1[[1]][[7]][[2]][[2]],            identicalTo(1))

assertThat(class( g1[[1]][[8]][[1]]),                identicalTo("function"))
assertThat(class( g1[[1]][[8]][[2]][[1]]),           identicalTo(c("CallRoutine", "NativeSymbolInfo")))
assertThat(names( g1[[1]][[8]][[2]][[1]]),           identicalTo(c("name","address","package","numParameters")))
assertThat(class( g1[[1]][[8]][[2]][[1]]$name),      identicalTo("character"))
assertThat(       g1[[1]][[8]][[2]][[1]]$name,       identicalTo("C_title"))
assertThat(class( g1[[1]][[8]][[2]][[1]]$address),      identicalTo("RegisteredNativeSymbol"))
assertThat(class( g1[[1]][[8]][[2]][[1]]$package),      identicalTo("DLLInfo"))
assertThat(       g1[[1]][[8]][[2]][[1]]$package[["name"]],           identicalTo(c("graphics")))
assertThat(       g1[[1]][[8]][[2]][[1]]$package[["dynamicLookup"]],  identicalTo(c(FALSE)))
assertThat( class(g1[[1]][[8]][[2]][[1]]$package[["handle"]]),        identicalTo(c("DLLHandle")))
assertThat( class(g1[[1]][[8]][[2]][[1]]$package[["info"]]),          identicalTo(c("DLLInfoReference")))
assertThat(class( g1[[1]][[8]][[2]][[1]]$numParameters),      identicalTo("integer"))
assertThat(       g1[[1]][[8]][[2]][[1]]$numParameters,       identicalTo(-1L))
assertThat(       g1[[1]][[8]][[2]][[2]],            identicalTo(NULL))
assertThat(       g1[[1]][[8]][[2]][[3]],            identicalTo(NULL))
assertThat(       g1[[1]][[8]][[2]][[4]],            identicalTo("1"))
assertThat(       g1[[1]][[8]][[2]][[5]],            identicalTo("2"))
assertThat(       g1[[1]][[8]][[2]][[6]],            identicalTo(NA))
assertThat(       g1[[1]][[8]][[2]][[7]],            identicalTo(FALSE))

assertThat(g1[[2]], identicalTo(g2[[2]]))
assertThat(g1[[3]], identicalTo(g2[[3]]))
assertThat(g2[[3]], identicalTo(structure(list(NULL, NULL), pkgName = "grid")))
