      DOUBLE PRECISION FUNCTION DCABS1(Z)

      DOUBLE COMPLEX Z
      INTRINSIC ABS,DBLE,DIMAG

      DCABS1 = ABS(DBLE(Z)) + ABS(DIMAG(Z))
      RETURN
      END
            
      DOUBLE COMPLEX FUNCTION DCONST1(Z)
      DOUBLE COMPLEX Z
      DOUBLE COMPLEX TEMP
      INTRINSIC DCONJG
            
      TEMP = (1.0D+0,2.0D+0)
      DCONST1 = DCONJG(TEMP)
      RETURN
      END
