library(hamcrest)

 
 
expected <- structure(list("$" = structure(list(), .Names = character(0)), 
    "$<-" = structure(list(), .Names = character(0)), Arith = list(), 
    Compare = list(), Complex = list(), Logic = list(), Math2 = structure(list(), .Names = character(0)), 
    Math = structure(list(), .Names = character(0)), Ops = structure(list(), .Names = character(0)), 
    Summary = list(), "[" = structure(list(), .Names = character(0)), 
    "[<-" = structure(list(), .Names = character(0)), "[[<-" = structure(list(), .Names = character(0)), 
    addNextMethod = structure(list(), .Names = character(0)), 
    "body<-" = structure(list(), .Names = character(0)), cbind2 = structure(list(), .Names = character(0)), 
    coerce = structure(list("oldClass#S3" = structure(c("oldClass", 
    "S3"), .Names = c("from", "to"))), .Names = "oldClass#S3"), 
    "coerce<-" = structure(list(), .Names = character(0)), initialize = structure(list(
        oldClass = structure("oldClass", .Names = ".Object")), .Names = "oldClass"), 
    kronecker = structure(list(), .Names = character(0)), loadMethod = structure(list(), .Names = character(0)), 
    rbind2 = structure(list(), .Names = character(0)), show = structure(list(
        oldClass = structure("oldClass", .Names = "object")), .Names = "oldClass"), 
    slotsFromS3 = structure(list(oldClass = structure("oldClass", .Names = "object")), .Names = "oldClass")), .Names = c("$", 
"$<-", "Arith", "Compare", "Complex", "Logic", "Math2", "Math", 
"Ops", "Summary", "[", "[<-", "[[<-", "addNextMethod", "body<-", 
"cbind2", "coerce", "coerce<-", "initialize", "kronecker", "loadMethod", 
"rbind2", "show", "slotsFromS3")) 


assertThat(base:::mapply(FUN=function (elt, geom) 
elt[geom],structure(list("$" = structure(list("C++Class" = NULL, envRefClass = NULL, 
    refObjectGenerator = NULL, Module = NULL, ANY = NULL), .Names = c("C++Class", 
"envRefClass", "refObjectGenerator", "Module", "ANY")), "$<-" = structure(list(
    localRefClass = NULL, data.frame = NULL, envRefClass = NULL, 
    refObjectGenerator = NULL, ANY = NULL), .Names = c("localRefClass", 
"data.frame", "envRefClass", "refObjectGenerator", "ANY")), Arith = list(), 
    Compare = list(), Complex = list(), Logic = list(), Math2 = structure(list(
        structure = NULL, nonStructure = NULL), .Names = c("structure", 
    "nonStructure")), Math = structure(list(structure = NULL, 
        nonStructure = NULL), .Names = c("structure", "nonStructure"
    )), Ops = structure(list("vector#nonStructure" = NULL, "structure#vector" = NULL, 
        "structure#array" = NULL, "vector#structure" = NULL, 
        "array#array" = NULL, "nonStructure#vector" = NULL, "array#structure" = NULL, 
        "structure#structure" = NULL, "nonStructure#nonStructure" = NULL), .Names = c("vector#nonStructure", 
    "structure#vector", "structure#array", "vector#structure", 
    "array#array", "nonStructure#vector", "array#structure", 
    "structure#structure", "nonStructure#nonStructure")), Summary = list(), 
    "[" = structure(list(nonStructure = NULL, ANY = NULL), .Names = c("nonStructure", 
    "ANY")), "[<-" = structure(list(data.frame = NULL, ANY = NULL), .Names = c("data.frame", 
    "ANY")), "[[<-" = structure(list(data.frame = NULL, ANY = NULL), .Names = c("data.frame", 
    "ANY")), addNextMethod = structure(list(MethodWithNext = NULL, 
        MethodDefinition = NULL), .Names = c("MethodWithNext", 
    "MethodDefinition")), "body<-" = structure(list(MethodDefinition = NULL, 
        ANY = NULL), .Names = c("MethodDefinition", "ANY")), 
    cbind2 = structure(list("ANY#missing" = NULL, "ANY#ANY" = NULL), .Names = c("ANY#missing", 
    "ANY#ANY")), coerce = structure(list("derivedDefaultMethod#function" = NULL, 
        "ANY#expression" = NULL, "ANY#vector" = NULL, "ANY#NULL" = NULL, 
        "ANY#logical" = NULL, "function#classGeneratorFunction" = NULL, 
        "ANY#call" = NULL, "ANY#array" = NULL, "ANY#ts" = NULL, 
        "NULL#OptionalFunction" = NULL, "function#OptionalFunction" = NULL, 
        "ANY#list" = NULL, "NULL#optionalMethod" = NULL, "groupGenericFunction#genericFunction" = NULL, 
        "ANY#environment" = NULL, "ANY#function" = NULL, "ANY#complex" = NULL, 
        "oldClass#S3" = structure(c("oldClass", "S3"), .Names = c("from", 
        "to")), "character#signature" = NULL, "ANY#name" = NULL, 
        "character#SuperClassMethod" = NULL, "ANY#integer" = NULL, 
        "ANY#character" = NULL, "ANY#S3" = NULL, "ANY#S4" = NULL, 
        "ANY#numeric" = NULL, "ANY#matrix" = NULL), .Names = c("derivedDefaultMethod#function", 
    "ANY#expression", "ANY#vector", "ANY#NULL", "ANY#logical", 
    "function#classGeneratorFunction", "ANY#call", "ANY#array", 
    "ANY#ts", "NULL#OptionalFunction", "function#OptionalFunction", 
    "ANY#list", "NULL#optionalMethod", "groupGenericFunction#genericFunction", 
    "ANY#environment", "ANY#function", "ANY#complex", "oldClass#S3", 
    "character#signature", "ANY#name", "character#SuperClassMethod", 
    "ANY#integer", "ANY#character", "ANY#S3", "ANY#S4", "ANY#numeric", 
    "ANY#matrix")), "coerce<-" = structure(list("groupGenericFunction#function" = NULL, 
        "genericFunction#function" = NULL, "ClassUnionRepresentation#classRepresentation" = NULL, 
        "signature#character" = NULL, "ObjectsWithPackage#character" = NULL, 
        "MethodDefinition#function" = NULL, "classGeneratorFunction#function" = NULL, 
        "refMethodDef#function" = NULL, "refClassRepresentation#classRepresentation" = NULL, 
        "refObjectGenerator#classGeneratorFunction" = NULL), .Names = c("groupGenericFunction#function", 
    "genericFunction#function", "ClassUnionRepresentation#classRepresentation", 
    "signature#character", "ObjectsWithPackage#character", "MethodDefinition#function", 
    "classGeneratorFunction#function", "refMethodDef#function", 
    "refClassRepresentation#classRepresentation", "refObjectGenerator#classGeneratorFunction"
    )), initialize = structure(list(mts = NULL, array = NULL, 
        environment = NULL, traceable = NULL, matrix = NULL, 
        externalRefMethod = NULL, envRefClass = NULL, MethodsList = NULL, 
        Module = NULL, signature = NULL, ANY = NULL, ts = NULL, 
        oldClass = structure("oldClass", .Names = ".Object")), .Names = c("mts", 
    "array", "environment", "traceable", "matrix", "externalRefMethod", 
    "envRefClass", "MethodsList", "Module", "signature", "ANY", 
    "ts", "oldClass")), kronecker = structure(list(ANY = NULL), .Names = "ANY"), 
    loadMethod = structure(list(MethodWithNext = NULL, MethodDefinition = NULL, 
        ANY = NULL), .Names = c("MethodWithNext", "MethodDefinition", 
    "ANY")), rbind2 = structure(list("ANY#missing" = NULL, "ANY#ANY" = NULL), .Names = c("ANY#missing", 
    "ANY#ANY")), show = structure(list(MethodWithNext = NULL, 
        refClassRepresentation = NULL, genericFunction = NULL, 
        refMethodDef = NULL, signature = NULL, "C++Function" = NULL, 
        classRepresentation = NULL, ObjectsWithPackage = NULL, 
        MethodDefinition = NULL, "C++Object" = NULL, externalRefMethod = NULL, 
        sourceEnvironment = NULL, MethodDefinitionWithTrace = NULL, 
        namedList = NULL, envRefClass = NULL, genericFunctionWithTrace = NULL, 
        refObjectGenerator = NULL, "C++Class" = NULL, oldClass = structure("oldClass", .Names = "object"), 
        ANY = NULL, traceable = NULL, Module = NULL, classGeneratorFunction = NULL, 
        MethodWithNextWithTrace = NULL, MethodSelectionReport = NULL), .Names = c("MethodWithNext", 
    "refClassRepresentation", "genericFunction", "refMethodDef", 
    "signature", "C++Function", "classRepresentation", "ObjectsWithPackage", 
    "MethodDefinition", "C++Object", "externalRefMethod", "sourceEnvironment", 
    "MethodDefinitionWithTrace", "namedList", "envRefClass", 
    "genericFunctionWithTrace", "refObjectGenerator", "C++Class", 
    "oldClass", "ANY", "traceable", "Module", "classGeneratorFunction", 
    "MethodWithNextWithTrace", "MethodSelectionReport")), slotsFromS3 = structure(list(
        data.frame = NULL, factor = NULL, ANY = NULL, ts = NULL, 
        oldClass = structure("oldClass", .Names = "object")), .Names = c("data.frame", 
    "factor", "ANY", "ts", "oldClass"))), .Names = c("$", "$<-", 
"Arith", "Compare", "Complex", "Logic", "Math2", "Math", "Ops", 
"Summary", "[", "[<-", "[[<-", "addNextMethod", "body<-", "cbind2", 
"coerce", "coerce<-", "initialize", "kronecker", "loadMethod", 
"rbind2", "show", "slotsFromS3")),structure(list("$" = structure(c(FALSE, FALSE, FALSE, FALSE, 
FALSE), .Names = c("C++Class", "envRefClass", "refObjectGenerator", 
"Module", "ANY")), "$<-" = structure(c(FALSE, FALSE, FALSE, FALSE, 
FALSE), .Names = c("localRefClass", "data.frame", "envRefClass", 
"refObjectGenerator", "ANY")), Arith = logical(0), Compare = logical(0), 
    Complex = logical(0), Logic = logical(0), Math2 = structure(c(FALSE, 
    FALSE), .Names = c("structure", "nonStructure")), Math = structure(c(FALSE, 
    FALSE), .Names = c("structure", "nonStructure")), Ops = structure(c(FALSE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE), .Names = c("vector#nonStructure", 
    "structure#vector", "structure#array", "vector#structure", 
    "array#array", "nonStructure#vector", "array#structure", 
    "structure#structure", "nonStructure#nonStructure")), Summary = logical(0), 
    "[" = structure(c(FALSE, FALSE), .Names = c("nonStructure", 
    "ANY")), "[<-" = structure(c(FALSE, FALSE), .Names = c("data.frame", 
    "ANY")), "[[<-" = structure(c(FALSE, FALSE), .Names = c("data.frame", 
    "ANY")), addNextMethod = structure(c(FALSE, FALSE), .Names = c("MethodWithNext", 
    "MethodDefinition")), "body<-" = structure(c(FALSE, FALSE
    ), .Names = c("MethodDefinition", "ANY")), cbind2 = structure(c(FALSE, 
    FALSE), .Names = c("ANY#missing", "ANY#ANY")), coerce = structure(c(FALSE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE), .Names = c("derivedDefaultMethod#function", 
    "ANY#expression", "ANY#vector", "ANY#NULL", "ANY#logical", 
    "function#classGeneratorFunction", "ANY#call", "ANY#array", 
    "ANY#ts", "NULL#OptionalFunction", "function#OptionalFunction", 
    "ANY#list", "NULL#optionalMethod", "groupGenericFunction#genericFunction", 
    "ANY#environment", "ANY#function", "ANY#complex", "oldClass#S3", 
    "character#signature", "ANY#name", "character#SuperClassMethod", 
    "ANY#integer", "ANY#character", "ANY#S3", "ANY#S4", "ANY#numeric", 
    "ANY#matrix")), "coerce<-" = structure(c(FALSE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE), .Names = c("groupGenericFunction#function", 
    "genericFunction#function", "ClassUnionRepresentation#classRepresentation", 
    "signature#character", "ObjectsWithPackage#character", "MethodDefinition#function", 
    "classGeneratorFunction#function", "refMethodDef#function", 
    "refClassRepresentation#classRepresentation", "refObjectGenerator#classGeneratorFunction"
    )), initialize = structure(c(FALSE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE
    ), .Names = c("mts", "array", "environment", "traceable", 
    "matrix", "externalRefMethod", "envRefClass", "MethodsList", 
    "Module", "signature", "ANY", "ts", "oldClass")), kronecker = structure(FALSE, .Names = "ANY"), 
    loadMethod = structure(c(FALSE, FALSE, FALSE), .Names = c("MethodWithNext", 
    "MethodDefinition", "ANY")), rbind2 = structure(c(FALSE, 
    FALSE), .Names = c("ANY#missing", "ANY#ANY")), show = structure(c(FALSE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, FALSE), .Names = c("MethodWithNext", 
    "refClassRepresentation", "genericFunction", "refMethodDef", 
    "signature", "C++Function", "classRepresentation", "ObjectsWithPackage", 
    "MethodDefinition", "C++Object", "externalRefMethod", "sourceEnvironment", 
    "MethodDefinitionWithTrace", "namedList", "envRefClass", 
    "genericFunctionWithTrace", "refObjectGenerator", "C++Class", 
    "oldClass", "ANY", "traceable", "Module", "classGeneratorFunction", 
    "MethodWithNextWithTrace", "MethodSelectionReport")), slotsFromS3 = structure(c(FALSE, 
    FALSE, FALSE, FALSE, TRUE), .Names = c("data.frame", "factor", 
    "ANY", "ts", "oldClass"))), .Names = c("$", "$<-", "Arith", 
"Compare", "Complex", "Logic", "Math2", "Math", "Ops", "Summary", 
"[", "[<-", "[[<-", "addNextMethod", "body<-", "cbind2", "coerce", 
"coerce<-", "initialize", "kronecker", "loadMethod", "rbind2", 
"show", "slotsFromS3")))
,  equalTo( expected ) ) 
 

