
# Common functions for generating
# test cases

deparse0 <- function(x) paste(deparse(x), collapse = "")

deparseExpected <- function(x) {
   if(typeof(x) == "language") {
    sprintf("quote(%s)", deparse(x))
   } else if(typeof(x) == "expression") {
    sprintf("as.expression(%s)", deparse0(as.list(x)))
   } else if(typeof(x) == "symbol") {
    sprintf("as.name(%s)", deparse(x)) 
   } else {
    if(typeof(x) == "list") {
      for(i in seq_along(x)) {
        if(typeof(x[[i]]) == "symbol") {
          x[[i]] <- call("quote", x[[i]])
        }
      }  
    }
    deparse0(x)
   }
}

callWithQuotedArgs <- function(fn, ...) {
  call <- as.call(c(as.name(fn), list(...)))
  for(i in seq.int(from = 2, to = length(call))) {
    arg <- call[[i]]
    if(typeof(arg) == "symbol" || typeof(arg) == "language") {
      call[[i]] <- call("quote", arg)
    } 
  }
  call
}

literal <- function(x) {
  stopifnot(is.character(x))
  class(x) <- "literal"
  x
}

test.open <- function(generatorScript, name) {
  filename <- sprintf("src/test/R/test.%s.R", fn)
  cat(sprintf("Opening test case %s...\n", filename))
  test <- new.env()
  test$fd <- file(filename, open="w")
  test$index <- 1
  class(test) <- "test"
  writeln(test, "# Generated by %s using GNU %s", 
          generatorScript, R.Version()$version.string)
  test
} 

writeln <- function(test, format, ...) {
  writeLines(test$fd, text = sprintf(format, ...))
}

writeFixture <- function(test, format, ...) {
  expr <- sprintf(format, ...)
  writeln(test, expr)
  eval(parse(text = expr), envir = .GlobalEnv)
}

writeTest <- function(test, fn, ..., tol = NULL) {
  call <- callWithQuotedArgs(fn, ...)

  expected <- tryCatch(eval(call, envir = .GlobalEnv), error = function(e) e)

  if(inherits(expected, "error")) {
    matcher <- "throwsError()"
    
  } else if(typeof(expected) %in% c("symbol", "language", "expression")) {
    matcher <- sprintf("deparsesTo(%s)", deparse0(deparse0(expected)))
  
  } else if(is.null(tol) || !is.double(expected)) {
    matcher <- sprintf("identicalTo(%s)", deparseExpected(expected))
  } else {
    matcher <- sprintf("identicalTo(%s, tol = %f)", deparseExpected(expected), tol)
  }
  writeln(test, "test.%s.%d <- function() assertThat(%s, %s)",
                            fn, test$index, deparse0(call), matcher)
  test$index <- test$index + 1
}

close.test <- function(test) {
  close(test$fd)
}

