library(hamcrest)
as.ordered.foo <- function(x) 41
Math.bar <- function(x) 44
test.as.ordered.1 <- function() assertThat(as.ordered(NULL), identicalTo(structure(integer(0), .Label = character(0), class = c("ordered", "factor"))))
test.as.ordered.2 <- function() assertThat(as.ordered(logical(0)), identicalTo(structure(integer(0), .Label = character(0), class = c("ordered", "factor"))))
test.as.ordered.3 <- function() assertThat(as.ordered(c(TRUE, TRUE, FALSE, FALSE, TRUE)), identicalTo(structure(c(2L, 2L, 1L, 1L, 2L), .Label = c("FALSE", "TRUE"), class = c("ordered", "factor"))))
test.as.ordered.4 <- function() assertThat(as.ordered(structure(c(TRUE, FALSE), .Names = c("a", ""))), identicalTo(structure(c(2L, 1L), .Names = c("a", ""), .Label = c("FALSE", "TRUE"), class = c("ordered", "factor"))))
test.as.ordered.5 <- function() assertThat(as.ordered(c(TRUE, FALSE, NA)), identicalTo(structure(c(2L, 1L, NA), .Label = c("FALSE", "TRUE"), class = c("ordered", "factor"))))
test.as.ordered.6 <- function() assertThat(as.ordered(integer(0)), identicalTo(structure(integer(0), .Label = character(0), class = c("ordered", "factor"))))
test.as.ordered.7 <- function() assertThat(as.ordered(structure(integer(0), .Names = character(0))), identicalTo(structure(integer(0), .Names = character(0), .Label = character(0), class = c("ordered", "factor"))))
test.as.ordered.8 <- function() assertThat(as.ordered(1:3), identicalTo(structure(1:3, .Label = c("1", "2", "3"), class = c("ordered", "factor"))))
test.as.ordered.9 <- function() assertThat(as.ordered(c(1L, NA, 4L, NA, 999L)), identicalTo(structure(c(1L, NA, 2L, NA, 3L), .Label = c("1", "4", "999"), class = c("ordered", "factor"))))
test.as.ordered.10 <- function() assertThat(as.ordered(c(1L, 2L, 1073741824L, 1073741824L)), identicalTo(structure(c(1L, 2L, 3L, 3L), .Label = c("1", "2", "1073741824"), class = c("ordered", "factor"))))
test.as.ordered.11 <- function() assertThat(as.ordered(numeric(0)), identicalTo(structure(integer(0), .Label = character(0), class = c("ordered", "factor"))))
test.as.ordered.12 <- function() assertThat(as.ordered(c(3.14159, 6.28319, 9.42478, 12.5664, 15.708)), identicalTo(structure(1:5, .Label = c("3.14159", "6.28319", "9.42478", "12.5664", "15.708"), class = c("ordered", "factor"))))
test.as.ordered.13 <- function() assertThat(as.ordered(c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708)), identicalTo(structure(c(5L, 4L, 3L, 2L, 1L), .Label = c("-15.708", "-12.5664", "-9.42478", "-6.28319", "-3.14159"), class = c("ordered", "factor"))))
test.as.ordered.14 <- function() assertThat(as.ordered(structure(1:2, .Names = c("a", "b"))), identicalTo(structure(1:2, .Names = c("a", "b"), .Label = c("1", "2"), class = c("ordered", "factor"))))
test.as.ordered.15 <- function() assertThat(as.ordered(structure(c(1.5, 2.5), .Names = c("a", "b"))), identicalTo(structure(1:2, .Names = c("a", "b"), .Label = c("1.5", "2.5"), class = c("ordered", "factor"))))
test.as.ordered.16 <- function() assertThat(as.ordered(character(0)), identicalTo(structure(integer(0), .Label = character(0), class = c("ordered", "factor"))))
test.as.ordered.17 <- function() assertThat(as.ordered(c("4.1", "blahh", "99.9", "-413", NA)), identicalTo(structure(c(1L, 4L, 3L, 2L, NA), .Label = c("4.1", "-413", "99.9", "blahh"), class = c("ordered", "factor"))))
test.as.ordered.18 <- function() assertThat(as.ordered(list(1, 2, 3)), throwsError())
test.as.ordered.19 <- function() assertThat(as.ordered(list(1, 2, NULL)), throwsError())
test.as.ordered.20 <- function() assertThat(as.ordered(list(1L, 2L, 3L)), throwsError())
test.as.ordered.21 <- function() assertThat(as.ordered(list(1L, 2L, NULL)), throwsError())
test.as.ordered.22 <- function() assertThat(as.ordered(list(1, 2, list(3, 4))), throwsError())
test.as.ordered.23 <- function() assertThat(as.ordered(structure(1:12, .Dim = 3:4)), identicalTo(structure(1:12, .Label = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"), class = c("ordered", "factor"))))
test.as.ordered.24 <- function() assertThat(as.ordered(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(    x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))), identicalTo(structure(1:12, .Label = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"), class = c("ordered", "factor"))))
test.as.ordered.25 <- function() assertThat(as.ordered(structure(1:3, rando.attrib = 941L)), identicalTo(structure(1:3, .Label = c("1", "2", "3"), class = c("ordered", "factor"))))
test.as.ordered.26 <- function() assertThat(as.ordered(structure(1:3, .Dim = 3L, .Dimnames = list(c("a", "b", "c")))), identicalTo(structure(1:3, .Names = c("a", "b", "c"), .Label = c("1", "2", "3"), class = c("ordered", "factor"))))
test.as.ordered.27 <- function() assertThat(as.ordered(structure(list("foo"), class = "foo")), throwsError())
test.as.ordered.28 <- function() assertThat(as.ordered(structure(list("bar"), class = "foo")), throwsError())
test.as.ordered.29 <- function() assertThat(as.ordered(xyz), throwsError())
test.as.ordered.30 <- function() assertThat(as.ordered(sin(3.14)), identicalTo(structure(1L, .Label = "0.00159265291648683", class = c("ordered", "factor"))))
test.as.ordered.31 <- function() assertThat(as.ordered(structure("foo", class = "foo")), identicalTo(structure(NA_integer_, .Label = "foo", class = c("ordered", "factor"))))
test.as.ordered.32 <- function() assertThat(as.ordered(structure(list(1L, "bar"), class = "bar")), throwsError())
