#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2019 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-dist-tests.R using GNU R version 3.3.1 (2016-06-21)
library(hamcrest)
library(stats)
set.seed(1)
test.rf.1 <- function() assertThat({set.seed(1);rf(n = 0x1p+0, df1 = c(0x1p+0, 0x1p+1, 0x1.4p+2, 0x1.4p+3), df2 = c(0x1p+0, 0x1p+1, 0x1.4p+2, 0x1.4p+3))}, identicalTo(0x1.6cc7280ab9e45p-3, tol = 0.000100))
test.rf.2 <- function() assertThat({set.seed(1);rf(n = 1:5, df1 = c(0x1p+0, 0x1p+1, 0x1.4p+2, 0x1.4p+3), df2 = c(0x1p+0, 0x1p+1, 0x1.4p+2, 0x1.4p+3))}, identicalTo(c(0x1.6cc7280ab9e45p-3, 0x1.4411edea73137p-2, 0x1.8bae40b0cc25ep+0, 0x1.afcb07bdd6863p-1, 0x1.8b6804e5889fp-2), tol = 0.000100))
test.rf.3 <- function() assertThat({set.seed(1);rf(n = 0x1.ep+3, df1 = c(0x1p+0, 0x1p+1, 0x1.4p+2, 0x1.4p+3),     df2 = c(0x1p+0, 0x1p+1, 0x1.4p+2, 0x1.4p+3))}, identicalTo(c(0x1.6cc7280ab9e45p-3, 0x1.4411edea73137p-2, 0x1.8bae40b0cc25ep+0, 0x1.afcb07bdd6863p-1, 0x1.8b6804e5889fp-2, 0x1.20e4afe309ecdp+0, 0x1.7f093c62bf91fp+3, 0x1.963bc1fe3b23ap-1, 0x1.83a7012cc22a1p+2, 0x1.8967c32840b32p+0, 0x1.90924ded2612dp+0, 0x1.32d965f0424f3p-2, 0x1.7708e2c6fbd95p-1, 0x1.4a3611e94ab4bp+1, 0x1.f85692cd6c263p-2), tol = 0.000100))
test.rf.4 <- function() assertThat({set.seed(1);rf(n = numeric(0), df1 = c(0x1p+0, 0x1p+1, 0x1.4p+2, 0x1.4p+3), df2 = c(0x1p+0, 0x1p+1, 0x1.4p+2, 0x1.4p+3))}, identicalTo(numeric(0)))
test.rf.5 <- function() assertThat({set.seed(1);rf(n = 0x1.8p+1, df1 = c(NA, 0x1p+1, 0x1.4p+2, 0x1.4p+3), df2 = c(0x1p+0, 0x1p+1, 0x1.4p+2, 0x1.4p+3))}, identicalTo(c(NaN, 0x1.5194309250896p-4, 0x1.99554477ca28ep+0)))
