#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2018 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-dist-tests.R using GNU R version 3.3.1 (2016-06-21)
library(hamcrest)
library(stats)
set.seed(1)
test.rnorm.1 <- function() assertThat({set.seed(1);rnorm(n = 0x1p+0, mean = c(0x1.4p+3, 0x1.4p+4, 0x1.ep+4, 0x1.bcp+5), sd = c(0x1.4p+1, 0x1.4p+2, 0x1p+3, 0x1p-1, 0x1.199999999999ap+3))}, identicalTo(0x1.0de239d840919p+3, tol = 0.000100))
test.rnorm.2 <- function() assertThat({set.seed(1);rnorm(n = 1:5, mean = c(0x1.4p+3, 0x1.4p+4, 0x1.ep+4, 0x1.bcp+5), sd = c(0x1.4p+1, 0x1.4p+2, 0x1p+3, 0x1p-1, 0x1.199999999999ap+3))}, identicalTo(c(0x1.0de239d840919p+3, 0x1.4eb103e965016p+4, 0x1.750a1f230c6a2p+4, 0x1.c261914a64795p+5, 0x1.9cca155e18e7ap+3), tol = 0.000100))
test.rnorm.3 <- function() assertThat({set.seed(1);rnorm(n = 0x1.ep+3, mean = c(0x1.4p+3, 0x1.4p+4, 0x1.ep+4, 0x1.bcp+5), sd = c(0x1.4p+1, 0x1.4p+2, 0x1p+3, 0x1p-1, 0x1.199999999999ap+3))}, identicalTo(c(0x1.0de239d840919p+3, 0x1.4eb103e965016p+4, 0x1.750a1f230c6a2p+4, 0x1.c261914a64795p+5, 0x1.9cca155e18e7ap+3, 0x1.1f2e675bf0724p+4, 0x1.037f4603e4065p+5, 0x1.eb40b64396f72p+5, 0x1.49366681aff99p+3, 0x1.1500562f859afp+4, 0x1.0e3c51d02819ep+5, 0x1.cb97fea75627ep+5, 0x1.41ecc12f3ff2cp+2, 0x1.2e484b6cf0f12p+4, 0x1.3f31f4798358cp+5), tol = 0.000100))
test.rnorm.4 <- function() assertThat({set.seed(1);rnorm(n = numeric(0), mean = c(0x1.4p+3, 0x1.4p+4, 0x1.ep+4, 0x1.bcp+5), sd = c(0x1.4p+1, 0x1.4p+2, 0x1p+3, 0x1p-1, 0x1.199999999999ap+3))}, identicalTo(numeric(0)))
test.rnorm.5 <- function() assertThat({set.seed(1);rnorm(n = 0x1.8p+1, mean = c(NA, 0x1.4p+4, 0x1.ep+4, 0x1.bcp+5), sd = c(0x1.4p+1, 0x1.4p+2, 0x1p+3, 0x1p-1, 0x1.199999999999ap+3))}, identicalTo(c(NaN, 0x1.0de239d840919p+4, 0x1.f7819fdbd4cfp+4)))
