#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2016 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-dist-tests.R using GNU R version 3.3.1 (2016-06-21)
library(hamcrest)
library(stats)
set.seed(1)
test.runif.1 <- function() assertThat({set.seed(1);runif(n = 0x1p+0, min = c(0x1p+0, 0x1p+1, 0x1.8p+1, 0x1p+2, 0x1.6p+2), max = c(0x1.8p+2, 0x1.4p+3, 0x1.ep+3, 0x1.f59999999999ap+6, 0x1p+3))}, identicalTo(0x1.29ecf07a8p+1, tol = 0.000100))
test.runif.2 <- function() assertThat({set.seed(1);runif(n = 1:5, min = c(0x1p+0, 0x1p+1, 0x1.8p+1, 0x1p+2, 0x1.6p+2), max = c(0x1.8p+2, 0x1.4p+3, 0x1.ep+3, 0x1.f59999999999ap+6, 0x1p+3))}, identicalTo(c(0x1.6e28c79b8p+1, 0x1.a54d093ap+2, 0x1.bcc07566p+3, 0x1.c7bf3a4493334p+4, 0x1.efbe0a9f8p+2), tol = 0.000100))
test.runif.3 <- function() assertThat({set.seed(1);runif(n = 0x1.ep+3, min = c(0x1p+0, 0x1p+1, 0x1.8p+1, 0x1p+2, 0x1.6p+2), max = c(0x1.8p+2, 0x1.4p+3, 0x1.ep+3, 0x1.f59999999999ap+6, 0x1p+3))}, identicalTo(c(0x1.6e4bcc4ap+2, 0x1.d2541698p+2, 0x1.51946d4ep+3, 0x1.7006fd5cecccdp+3, 0x1.80f4b7f56p+2, 0x1.e1fe1ddep+0, 0x1.dfc17564p+2, 0x1.e6fddd24p+2, 0x1.85d5c2232b334p+6, 0x1.afa1c2cep+2, 0x1.25a34ee6p+2, 0x1.3ded8ecep+3, 0x1.e3ddf4e1p+2, 0x1.898703a6ep+6, 0x1.f58d86b96p+2), tol = 0.000100))
test.runif.4 <- function() assertThat({set.seed(1);runif(n = numeric(0), min = c(0x1p+0, 0x1p+1, 0x1.8p+1, 0x1p+2, 0x1.6p+2), max = c(0x1.8p+2, 0x1.4p+3, 0x1.ep+3, 0x1.f59999999999ap+6, 0x1p+3))}, identicalTo(numeric(0)))
test.runif.5 <- function() assertThat({set.seed(1);runif(n = 0x1.8p+1, min = c(NA, 0x1p+1, 0x1.8p+1, 0x1p+2, 0x1.6p+2), max = c(0x1.8p+2, 0x1.4p+3, 0x1.ep+3, 0x1.f59999999999ap+6, 0x1p+3))}, identicalTo(c(NaN, 0x1.d93be39cp+1, 0x1.5a3e234d8p+3)))
