#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2016 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-unary-tests.R using GNU R version 3.3.1 (2016-06-21)
library(hamcrest)
Sys.setlocale('LC_COLLATE', 'C')
is.infinite.foo <- function(...) 41L
as.vector.foo <- function(...) 99
Math.bar <- function(...) 44
Summary.bar <- function(...) 45
Ops.bar <- function(...) 46
test.is.infinite.1 <- function() assertThat(is.infinite(NULL), identicalTo(logical(0)))
test.is.infinite.2 <- function() assertThat(is.infinite(logical(0)), identicalTo(logical(0)))
test.is.infinite.3 <- function() assertThat(is.infinite(c(TRUE, TRUE, FALSE, FALSE, TRUE)), identicalTo(c(FALSE, FALSE, FALSE, FALSE, FALSE)))
test.is.infinite.4 <- function() assertThat(is.infinite(structure(c(TRUE, FALSE), .Names = c("a", ""))), identicalTo(structure(c(FALSE, FALSE), .Names = c("a", ""))))
test.is.infinite.5 <- function() assertThat(is.infinite(c(TRUE, FALSE, NA)), identicalTo(c(FALSE, FALSE, FALSE)))
test.is.infinite.6 <- function() assertThat(is.infinite(integer(0)), identicalTo(logical(0)))
test.is.infinite.7 <- function() assertThat(is.infinite(structure(integer(0), .Names = character(0))), identicalTo(structure(logical(0), .Names = character(0))))
test.is.infinite.8 <- function() assertThat(is.infinite(1:3), identicalTo(c(FALSE, FALSE, FALSE)))
test.is.infinite.9 <- function() assertThat(is.infinite(c(1L, NA, 4L, NA, 999L)), identicalTo(c(FALSE, FALSE, FALSE, FALSE, FALSE)))
test.is.infinite.10 <- function() assertThat(is.infinite(c(1L, 2L, 1073741824L, 1073741824L)), identicalTo(c(FALSE, FALSE, FALSE, FALSE)))
test.is.infinite.11 <- function() assertThat(is.infinite(numeric(0)), identicalTo(logical(0)))
test.is.infinite.12 <- function() assertThat(is.infinite(c(3.14159, 6.28319, 9.42478, 12.5664, 15.708)), identicalTo(c(FALSE, FALSE, FALSE, FALSE, FALSE)))
test.is.infinite.13 <- function() assertThat(is.infinite(c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708)), identicalTo(c(FALSE, FALSE, FALSE, FALSE, FALSE)))
test.is.infinite.14 <- function() assertThat(is.infinite(structure(1:2, .Names = c("a", "b"))), identicalTo(structure(c(FALSE, FALSE), .Names = c("a", "b"))))
test.is.infinite.15 <- function() assertThat(is.infinite(structure(c(1.5, 2.5), .Names = c("a", "b"))), identicalTo(structure(c(FALSE, FALSE), .Names = c("a", "b"))))
test.is.infinite.16 <- function() assertThat(is.infinite(c(1.5, 1.51, 0, 1.49, -30)), identicalTo(c(FALSE, FALSE, FALSE, FALSE, FALSE)))
test.is.infinite.17 <- function() assertThat(is.infinite(c(1.5, 1.51, 0, 1.49, -30, NA)), identicalTo(c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE)))
test.is.infinite.18 <- function() assertThat(is.infinite(c(1.5, 1.51, 0, 1.49, -30, NaN)), identicalTo(c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE)))
test.is.infinite.19 <- function() assertThat(is.infinite(c(1.5, 1.51, 0, 1.49, -30, Inf)), identicalTo(c(FALSE, FALSE, FALSE, FALSE, FALSE, TRUE)))
test.is.infinite.20 <- function() assertThat(is.infinite(c(1.5, 1.51, 0, 1.49, -30, -Inf)), identicalTo(c(FALSE, FALSE, FALSE, FALSE, FALSE, TRUE)))
test.is.infinite.21 <- function() assertThat(is.infinite(character(0)), identicalTo(logical(0)))
test.is.infinite.22 <- function() assertThat(is.infinite(c("4.1", "blahh", "99.9", "-413", NA)), identicalTo(c(FALSE, FALSE, FALSE, FALSE, FALSE)))
test.is.infinite.23 <- function() assertThat(is.infinite(complex(0)), identicalTo(logical(0)))
test.is.infinite.24 <- function() assertThat(is.infinite(list(1, 2, 3)), throwsError())
test.is.infinite.25 <- function() assertThat(is.infinite(list(1, 2, NULL)), throwsError())
test.is.infinite.26 <- function() assertThat(is.infinite(list(1L, 2L, 3L)), throwsError())
test.is.infinite.27 <- function() assertThat(is.infinite(list(1L, 2L, NULL)), throwsError())
test.is.infinite.28 <- function() assertThat(is.infinite(list(1, 2, list(3, 4))), throwsError())
test.is.infinite.29 <- function() assertThat(is.infinite(list(3, "a", structure(list("b", z = list(TRUE, "c")), .Names = c("", "z")))), throwsError())
test.is.infinite.30 <- function() assertThat(is.infinite(structure(list(`NA` = 1, 2, b = 3), .Names = c(NA, "", "b"))), throwsError())
test.is.infinite.31 <- function() assertThat(is.infinite(pairlist(41, "a", 21L)), throwsError())
test.is.infinite.32 <- function() assertThat(is.infinite(pairlist(a = 41, 42)), throwsError())
test.is.infinite.33 <- function() assertThat(is.infinite(pairlist(a = 41, NULL)), throwsError())
test.is.infinite.34 <- function() assertThat(is.infinite(structure(1:12, .Dim = 3:4)), identicalTo(structure(c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE), .Dim = 3:4)))
test.is.infinite.35 <- function() assertThat(is.infinite(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(    x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))), identicalTo(structure(c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE), .Dim = 3:4, .Dimnames = structure(list(    x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))))
test.is.infinite.36 <- function() assertThat(is.infinite(structure(1:3, rando.attrib = 941L)), identicalTo(c(FALSE, FALSE, FALSE)))
test.is.infinite.37 <- function() assertThat(is.infinite(structure(1:3, .Dim = 3L, .Dimnames = list(c("a", "b", "c")))), identicalTo(structure(c(FALSE, FALSE, FALSE), .Dim = 3L, .Dimnames = list(    c("a", "b", "c")))))
test.is.infinite.38 <- function() assertThat(is.infinite(structure(1:3, .Dim = 3L, .Dimnames = structure(list(    z = c("a", "b", "c")), .Names = "z"))), identicalTo(structure(c(FALSE, FALSE, FALSE), .Dim = 3L, .Dimnames = structure(list(    z = c("a", "b", "c")), .Names = "z"))))
test.is.infinite.39 <- function() assertThat(is.infinite(structure(list("foo"), class = "foo")), identicalTo(41L))
test.is.infinite.40 <- function() assertThat(is.infinite(structure(list("bar"), class = "foo")), identicalTo(41L))
test.is.infinite.41 <- function() assertThat(is.infinite(quote(xyz)), throwsError())
test.is.infinite.42 <- function() assertThat(is.infinite(quote(sin(3.14))), throwsError())
test.is.infinite.43 <- function() assertThat(is.infinite(structure("foo", class = "foo")), identicalTo(41L))
test.is.infinite.44 <- function() assertThat(is.infinite(structure(list(1L, "bar"), class = "bar")), throwsError())
