#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2016 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-dist-tests.R using GNU R version 3.3.1 (2016-06-21)
library(hamcrest)
library(stats)
set.seed(1)
test.rnorm.1 <- function() assertThat({set.seed(1);rnorm(n = 0x1p+0, mean = c(0x1.4p+3, 0x1.4p+4, 0x1.ep+4, 0x1.bcp+5), sd = c(0x1.4p+1, 0x1.4p+2, 0x1p+3, 0x1p-1, 0x1.199999999999ap+3))}, identicalTo(0x1.0de239d840919p+3, tol = 0.000100))
test.rnorm.2 <- function() assertThat({set.seed(1);rnorm(n = 1:5, mean = c(0x1.4p+3, 0x1.4p+4, 0x1.ep+4, 0x1.bcp+5), sd = c(0x1.4p+1, 0x1.4p+2, 0x1p+3, 0x1p-1, 0x1.199999999999ap+3))}, identicalTo(c(0x1.4eb103e965016p+3, 0x1.fa4ca6ebcf84ap+3, 0x1.561914a64794ep+5, 0x1.bd516a7c3ee63p+5, 0x1.63d30cac5e7d2p+1), tol = 0.000100))
test.rnorm.3 <- function() assertThat({set.seed(1);rnorm(n = 0x1.ep+3, mean = c(0x1.4p+3, 0x1.4p+4, 0x1.ep+4, 0x1.bcp+5), sd = c(0x1.4p+1, 0x1.4p+2, 0x1p+3, 0x1p-1, 0x1.199999999999ap+3))}, identicalTo(c(0x1.66fe8c07c80c9p+3, 0x1.7b10e3d47cb4ep+4, 0x1.14d99a06bfe63p+5, 0x1.bac7484442575p+5, 0x1.74dbd9907678fp+4, 0x1.4f97fea75627ep+4, 0x1.ae4cfe2f61fdfp+4, 0x1.2e425b6787893p+5, 0x1.51ffb78ffaf14p+3, 0x1.39ac60865565bp+4, 0x1.df5a36325b0e4p+4, 0x1.e1c0e1ff02f5p+5, 0x1.091dc6afdd39cp+4, 0x1.44c04f55fd717p+4, 0x1.30b22d832038ep+5), tol = 0.000100))
test.rnorm.4 <- function() assertThat({set.seed(1);rnorm(n = numeric(0), mean = c(0x1.4p+3, 0x1.4p+4, 0x1.ep+4, 0x1.bcp+5), sd = c(0x1.4p+1, 0x1.4p+2, 0x1p+3, 0x1p-1, 0x1.199999999999ap+3))}, identicalTo(numeric(0)))
test.rnorm.5 <- function() assertThat({set.seed(1);rnorm(n = 0x1.8p+1, mean = c(NA, 0x1.4p+4, 0x1.ep+4, 0x1.bcp+5), sd = c(0x1.4p+1, 0x1.4p+2, 0x1p+3, 0x1p-1, 0x1.199999999999ap+3))}, identicalTo(c(NaN, 0x1.7e9226c4b4593p+4, 0x1.e98b586a7d79cp+4)))
