#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2018 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-unary-tests.R using GNU R version 3.3.3 (2017-03-06)
library(hamcrest)
Sys.setlocale('LC_COLLATE', 'C')
is.language.foo <- function(...) 41L
as.vector.foo <- function(...) 99
Math.bar <- function(...) 44
Summary.bar <- function(...) 45
Ops.bar <- function(...) 46
test.is.language.1 <- function() assertThat(is.language(NULL), identicalTo(FALSE))
test.is.language.2 <- function() assertThat(is.language(logical(0)), identicalTo(FALSE))
test.is.language.3 <- function() assertThat(is.language(c(TRUE, TRUE, FALSE, FALSE, TRUE)), identicalTo(FALSE))
test.is.language.4 <- function() assertThat(is.language(structure(c(TRUE, FALSE), .Names = c("a", ""))), identicalTo(FALSE))
test.is.language.5 <- function() assertThat(is.language(c(TRUE, FALSE, NA)), identicalTo(FALSE))
test.is.language.6 <- function() assertThat(is.language(integer(0)), identicalTo(FALSE))
test.is.language.7 <- function() assertThat(is.language(structure(integer(0), .Names = character(0))), identicalTo(FALSE))
test.is.language.8 <- function() assertThat(is.language(1:3), identicalTo(FALSE))
test.is.language.9 <- function() assertThat(is.language(c(1L, NA, 4L, NA, 999L)), identicalTo(FALSE))
test.is.language.10 <- function() assertThat(is.language(c(1L, 2L, 1073741824L, 1073741824L)), identicalTo(FALSE))
test.is.language.11 <- function() assertThat(is.language(numeric(0)), identicalTo(FALSE))
test.is.language.12 <- function() assertThat(is.language(c(3.14159, 6.28319, 9.42478, 12.5664, 15.708)), identicalTo(FALSE))
test.is.language.13 <- function() assertThat(is.language(c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708)), identicalTo(FALSE))
test.is.language.14 <- function() assertThat(is.language(structure(1:2, .Names = c("a", "b"))), identicalTo(FALSE))
test.is.language.15 <- function() assertThat(is.language(structure(c(1.5, 2.5), .Names = c("a", "b"))), identicalTo(FALSE))
test.is.language.16 <- function() assertThat(is.language(c(1.5, 1.51, 0, 1.49, -30)), identicalTo(FALSE))
test.is.language.17 <- function() assertThat(is.language(c(1.5, 1.51, 0, 1.49, -30, NA)), identicalTo(FALSE))
test.is.language.18 <- function() assertThat(is.language(c(1.5, 1.51, 0, 1.49, -30, NaN)), identicalTo(FALSE))
test.is.language.19 <- function() assertThat(is.language(c(1.5, 1.51, 0, 1.49, -30, Inf)), identicalTo(FALSE))
test.is.language.20 <- function() assertThat(is.language(c(1.5, 1.51, 0, 1.49, -30, -Inf)), identicalTo(FALSE))
test.is.language.21 <- function() assertThat(is.language(character(0)), identicalTo(FALSE))
test.is.language.22 <- function() assertThat(is.language(c("4.1", "blahh", "99.9", "-413", NA)), identicalTo(FALSE))
test.is.language.23 <- function() assertThat(is.language(complex(0)), identicalTo(FALSE))
test.is.language.24 <- function() assertThat(is.language(list(1, 2, 3)), identicalTo(FALSE))
test.is.language.25 <- function() assertThat(is.language(list(1, 2, NULL)), identicalTo(FALSE))
test.is.language.26 <- function() assertThat(is.language(list(1L, 2L, 3L)), identicalTo(FALSE))
test.is.language.27 <- function() assertThat(is.language(list(1L, 2L, NULL)), identicalTo(FALSE))
test.is.language.28 <- function() assertThat(is.language(list(1, 2, list(3, 4))), identicalTo(FALSE))
test.is.language.29 <- function() assertThat(is.language(list(1, 2, numeric(0))), identicalTo(FALSE))
test.is.language.30 <- function() assertThat(is.language(list(3, "a", structure(list("b", z = list(TRUE, "c")), .Names = c("", "z")))), identicalTo(FALSE))
test.is.language.31 <- function() assertThat(is.language(structure(list(`NA` = 1, 2, b = 3), .Names = c(NA, "", "b"))), identicalTo(FALSE))
test.is.language.32 <- function() assertThat(is.language(pairlist(41, "a", 21L)), identicalTo(FALSE))
test.is.language.33 <- function() assertThat(is.language(pairlist(a = 41, 42)), identicalTo(FALSE))
test.is.language.34 <- function() assertThat(is.language(pairlist(a = 41, NULL)), identicalTo(FALSE))
test.is.language.35 <- function() assertThat(is.language(structure(1:12, .Dim = 3:4)), identicalTo(FALSE))
test.is.language.36 <- function() assertThat(is.language(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(    x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))), identicalTo(FALSE))
test.is.language.37 <- function() assertThat(is.language(structure(1:3, rando.attrib = 941L)), identicalTo(FALSE))
test.is.language.38 <- function() assertThat(is.language(structure(1:3, .Dim = 3L, .Dimnames = list(c("a", "b", "c")))), identicalTo(FALSE))
test.is.language.39 <- function() assertThat(is.language(structure(1:3, .Dim = 3L, .Dimnames = structure(list(    z = c("a", "b", "c")), .Names = "z"))), identicalTo(FALSE))
test.is.language.40 <- function() assertThat(is.language(structure(list("foo"), class = "foo")), identicalTo(FALSE))
test.is.language.41 <- function() assertThat(is.language(structure(list("bar"), class = "foo")), identicalTo(FALSE))
test.is.language.42 <- function() assertThat(is.language(quote(xyz)), identicalTo(TRUE))
test.is.language.43 <- function() assertThat(is.language(quote(sin(3.14))), identicalTo(TRUE))
test.is.language.44 <- function() assertThat(is.language("NaN"), identicalTo(FALSE))
test.is.language.45 <- function() assertThat(is.language("NABOOM!"), identicalTo(FALSE))
test.is.language.46 <- function() assertThat(is.language("NaNaNabooboo"), identicalTo(FALSE))
test.is.language.47 <- function() assertThat(is.language("-Inf"), identicalTo(FALSE))
test.is.language.48 <- function() assertThat(is.language("+Infinity"), identicalTo(FALSE))
test.is.language.49 <- function() assertThat(is.language("Infinity and beyond!"), identicalTo(FALSE))
test.is.language.50 <- function() assertThat(is.language("Infi"), identicalTo(FALSE))
test.is.language.51 <- function() assertThat(is.language("0.03f"), identicalTo(FALSE))
test.is.language.52 <- function() assertThat(is.language("  0.0330   "), identicalTo(FALSE))
test.is.language.53 <- function() assertThat(is.language(structure("foo", class = "foo")), identicalTo(FALSE))
test.is.language.54 <- function() assertThat(is.language(structure(list(1L, "bar"), class = "bar")), identicalTo(FALSE))
