#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2018 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-unary-tests.R using GNU R version 3.3.3 (2017-03-06)
library(hamcrest)
Sys.setlocale('LC_COLLATE', 'C')
is.table.foo <- function(...) 41L
as.vector.foo <- function(...) 99
Math.bar <- function(...) 44
Summary.bar <- function(...) 45
Ops.bar <- function(...) 46
test.is.table.1 <- function() assertThat(is.table(NULL), identicalTo(FALSE))
test.is.table.2 <- function() assertThat(is.table(logical(0)), identicalTo(FALSE))
test.is.table.3 <- function() assertThat(is.table(c(TRUE, TRUE, FALSE, FALSE, TRUE)), identicalTo(FALSE))
test.is.table.4 <- function() assertThat(is.table(structure(c(TRUE, FALSE), .Names = c("a", ""))), identicalTo(FALSE))
test.is.table.5 <- function() assertThat(is.table(c(TRUE, FALSE, NA)), identicalTo(FALSE))
test.is.table.6 <- function() assertThat(is.table(integer(0)), identicalTo(FALSE))
test.is.table.7 <- function() assertThat(is.table(structure(integer(0), .Names = character(0))), identicalTo(FALSE))
test.is.table.8 <- function() assertThat(is.table(1:3), identicalTo(FALSE))
test.is.table.9 <- function() assertThat(is.table(c(1L, NA, 4L, NA, 999L)), identicalTo(FALSE))
test.is.table.10 <- function() assertThat(is.table(c(1L, 2L, 1073741824L, 1073741824L)), identicalTo(FALSE))
test.is.table.11 <- function() assertThat(is.table(numeric(0)), identicalTo(FALSE))
test.is.table.12 <- function() assertThat(is.table(c(3.14159, 6.28319, 9.42478, 12.5664, 15.708)), identicalTo(FALSE))
test.is.table.13 <- function() assertThat(is.table(c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708)), identicalTo(FALSE))
test.is.table.14 <- function() assertThat(is.table(structure(1:2, .Names = c("a", "b"))), identicalTo(FALSE))
test.is.table.15 <- function() assertThat(is.table(structure(c(1.5, 2.5), .Names = c("a", "b"))), identicalTo(FALSE))
test.is.table.16 <- function() assertThat(is.table(c(1.5, 1.51, 0, 1.49, -30)), identicalTo(FALSE))
test.is.table.17 <- function() assertThat(is.table(c(1.5, 1.51, 0, 1.49, -30, NA)), identicalTo(FALSE))
test.is.table.18 <- function() assertThat(is.table(c(1.5, 1.51, 0, 1.49, -30, NaN)), identicalTo(FALSE))
test.is.table.19 <- function() assertThat(is.table(c(1.5, 1.51, 0, 1.49, -30, Inf)), identicalTo(FALSE))
test.is.table.20 <- function() assertThat(is.table(c(1.5, 1.51, 0, 1.49, -30, -Inf)), identicalTo(FALSE))
test.is.table.21 <- function() assertThat(is.table(character(0)), identicalTo(FALSE))
test.is.table.22 <- function() assertThat(is.table(c("4.1", "blahh", "99.9", "-413", NA)), identicalTo(FALSE))
test.is.table.23 <- function() assertThat(is.table(complex(0)), identicalTo(FALSE))
test.is.table.24 <- function() assertThat(is.table(list(1, 2, 3)), identicalTo(FALSE))
test.is.table.25 <- function() assertThat(is.table(list(1, 2, NULL)), identicalTo(FALSE))
test.is.table.26 <- function() assertThat(is.table(list(1L, 2L, 3L)), identicalTo(FALSE))
test.is.table.27 <- function() assertThat(is.table(list(1L, 2L, NULL)), identicalTo(FALSE))
test.is.table.28 <- function() assertThat(is.table(list(1, 2, list(3, 4))), identicalTo(FALSE))
test.is.table.29 <- function() assertThat(is.table(list(1, 2, numeric(0))), identicalTo(FALSE))
test.is.table.30 <- function() assertThat(is.table(list(3, "a", structure(list("b", z = list(TRUE, "c")), .Names = c("", "z")))), identicalTo(FALSE))
test.is.table.31 <- function() assertThat(is.table(structure(list(`NA` = 1, 2, b = 3), .Names = c(NA, "", "b"))), identicalTo(FALSE))
test.is.table.32 <- function() assertThat(is.table(pairlist(41, "a", 21L)), identicalTo(FALSE))
test.is.table.33 <- function() assertThat(is.table(pairlist(a = 41, 42)), identicalTo(FALSE))
test.is.table.34 <- function() assertThat(is.table(pairlist(a = 41, NULL)), identicalTo(FALSE))
test.is.table.35 <- function() assertThat(is.table(structure(1:12, .Dim = 3:4)), identicalTo(FALSE))
test.is.table.36 <- function() assertThat(is.table(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(    x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))), identicalTo(FALSE))
test.is.table.37 <- function() assertThat(is.table(structure(1:3, rando.attrib = 941L)), identicalTo(FALSE))
test.is.table.38 <- function() assertThat(is.table(structure(1:3, .Dim = 3L, .Dimnames = list(c("a", "b", "c")))), identicalTo(FALSE))
test.is.table.39 <- function() assertThat(is.table(structure(1:3, .Dim = 3L, .Dimnames = structure(list(    z = c("a", "b", "c")), .Names = "z"))), identicalTo(FALSE))
test.is.table.40 <- function() assertThat(is.table(structure(list("foo"), class = "foo")), identicalTo(FALSE))
test.is.table.41 <- function() assertThat(is.table(structure(list("bar"), class = "foo")), identicalTo(FALSE))
test.is.table.42 <- function() assertThat(is.table(quote(xyz)), identicalTo(FALSE))
test.is.table.43 <- function() assertThat(is.table(quote(sin(3.14))), identicalTo(FALSE))
test.is.table.44 <- function() assertThat(is.table("NaN"), identicalTo(FALSE))
test.is.table.45 <- function() assertThat(is.table("NABOOM!"), identicalTo(FALSE))
test.is.table.46 <- function() assertThat(is.table("NaNaNabooboo"), identicalTo(FALSE))
test.is.table.47 <- function() assertThat(is.table("-Inf"), identicalTo(FALSE))
test.is.table.48 <- function() assertThat(is.table("+Infinity"), identicalTo(FALSE))
test.is.table.49 <- function() assertThat(is.table("Infinity and beyond!"), identicalTo(FALSE))
test.is.table.50 <- function() assertThat(is.table("Infi"), identicalTo(FALSE))
test.is.table.51 <- function() assertThat(is.table("0.03f"), identicalTo(FALSE))
test.is.table.52 <- function() assertThat(is.table("  0.0330   "), identicalTo(FALSE))
test.is.table.53 <- function() assertThat(is.table(structure("foo", class = "foo")), identicalTo(FALSE))
test.is.table.54 <- function() assertThat(is.table(structure(list(1L, "bar"), class = "bar")), identicalTo(FALSE))
