#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2016 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-unary-tests.R using GNU R version 3.3.2 (2016-10-31)
library(hamcrest)
Sys.setlocale('LC_COLLATE', 'C')
as.list.foo <- function(...) 41L
as.vector.foo <- function(...) 99
Math.bar <- function(...) 44
Summary.bar <- function(...) 45
Ops.bar <- function(...) 46
test.as.list.1 <- function() assertThat(as.list(NULL), identicalTo(list()))
test.as.list.2 <- function() assertThat(as.list(logical(0)), identicalTo(list()))
test.as.list.3 <- function() assertThat(as.list(c(TRUE, TRUE, FALSE, FALSE, TRUE)), identicalTo(list(TRUE, TRUE, FALSE, FALSE, TRUE)))
test.as.list.4 <- function() assertThat(as.list(structure(c(TRUE, FALSE), .Names = c("a", ""))), identicalTo(structure(list(a = TRUE, FALSE), .Names = c("a", ""))))
test.as.list.5 <- function() assertThat(as.list(c(TRUE, FALSE, NA)), identicalTo(list(TRUE, FALSE, NA)))
test.as.list.6 <- function() assertThat(as.list(integer(0)), identicalTo(list()))
test.as.list.7 <- function() assertThat(as.list(structure(integer(0), .Names = character(0))), identicalTo(structure(list(), .Names = character(0))))
test.as.list.8 <- function() assertThat(as.list(1:3), identicalTo(list(1L, 2L, 3L)))
test.as.list.9 <- function() assertThat(as.list(c(1L, NA, 4L, NA, 999L)), identicalTo(list(1L, NA_integer_, 4L, NA_integer_, 999L)))
test.as.list.10 <- function() assertThat(as.list(c(1L, 2L, 1073741824L, 1073741824L)), identicalTo(list(1L, 2L, 1073741824L, 1073741824L)))
test.as.list.11 <- function() assertThat(as.list(numeric(0)), identicalTo(list()))
test.as.list.12 <- function() assertThat(as.list(c(3.14159, 6.28319, 9.42478, 12.5664, 15.708)), identicalTo(list(3.14159, 6.28319, 9.42478, 12.5664, 15.708)))
test.as.list.13 <- function() assertThat(as.list(c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708)), identicalTo(list(-3.14159, -6.28319, -9.42478, -12.5664, -15.708)))
test.as.list.14 <- function() assertThat(as.list(structure(1:2, .Names = c("a", "b"))), identicalTo(structure(list(a = 1L, b = 2L), .Names = c("a", "b"))))
test.as.list.15 <- function() assertThat(as.list(structure(c(1.5, 2.5), .Names = c("a", "b"))), identicalTo(structure(list(a = 1.5, b = 2.5), .Names = c("a", "b"))))
test.as.list.16 <- function() assertThat(as.list(c(1.5, 1.51, 0, 1.49, -30)), identicalTo(list(1.5, 1.51, 0, 1.49, -30)))
test.as.list.17 <- function() assertThat(as.list(c(1.5, 1.51, 0, 1.49, -30, NA)), identicalTo(list(1.5, 1.51, 0, 1.49, -30, NA_real_)))
test.as.list.18 <- function() assertThat(as.list(c(1.5, 1.51, 0, 1.49, -30, NaN)), identicalTo(list(1.5, 1.51, 0, 1.49, -30, NaN)))
test.as.list.19 <- function() assertThat(as.list(c(1.5, 1.51, 0, 1.49, -30, Inf)), identicalTo(list(1.5, 1.51, 0, 1.49, -30, Inf)))
test.as.list.20 <- function() assertThat(as.list(c(1.5, 1.51, 0, 1.49, -30, -Inf)), identicalTo(list(1.5, 1.51, 0, 1.49, -30, -Inf)))
test.as.list.21 <- function() assertThat(as.list(character(0)), identicalTo(list()))
test.as.list.22 <- function() assertThat(as.list(c("4.1", "blahh", "99.9", "-413", NA)), identicalTo(list("4.1", "blahh", "99.9", "-413", NA_character_)))
test.as.list.23 <- function() assertThat(as.list(complex(0)), identicalTo(list()))
test.as.list.24 <- function() assertThat(as.list(list(1, 2, 3)), identicalTo(list(1, 2, 3)))
test.as.list.25 <- function() assertThat(as.list(list(1, 2, NULL)), identicalTo(list(1, 2, NULL)))
test.as.list.26 <- function() assertThat(as.list(list(1L, 2L, 3L)), identicalTo(list(1L, 2L, 3L)))
test.as.list.27 <- function() assertThat(as.list(list(1L, 2L, NULL)), identicalTo(list(1L, 2L, NULL)))
test.as.list.28 <- function() assertThat(as.list(list(1, 2, list(3, 4))), identicalTo(list(1, 2, list(3, 4))))
test.as.list.29 <- function() assertThat(as.list(list(3, "a", structure(list("b", z = list(TRUE, "c")), .Names = c("", "z")))), identicalTo(list(3, "a", structure(list("b", z = list(TRUE, "c")), .Names = c("", "z")))))
test.as.list.30 <- function() assertThat(as.list(structure(list(`NA` = 1, 2, b = 3), .Names = c(NA, "", "b"))), identicalTo(structure(list("NA" = 1, 2, b = 3), .Names = c(NA, "", "b"))))
test.as.list.31 <- function() assertThat(as.list(pairlist(41, "a", 21L)), identicalTo(list(41, "a", 21L)))
test.as.list.32 <- function() assertThat(as.list(pairlist(a = 41, 42)), identicalTo(structure(list(a = 41, 42), .Names = c("a", ""))))
test.as.list.33 <- function() assertThat(as.list(pairlist(a = 41, NULL)), identicalTo(structure(list(a = 41, NULL), .Names = c("a", ""))))
test.as.list.34 <- function() assertThat(as.list(structure(1:12, .Dim = 3:4)), identicalTo(list(1L, 2L, 3L, 4L, 5L, 6L, 7L, 8L, 9L, 10L, 11L, 12L)))
test.as.list.35 <- function() assertThat(as.list(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(    x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))), identicalTo(list(1L, 2L, 3L, 4L, 5L, 6L, 7L, 8L, 9L, 10L, 11L, 12L)))
test.as.list.36 <- function() assertThat(as.list(structure(1:3, rando.attrib = 941L)), identicalTo(list(1L, 2L, 3L)))
test.as.list.37 <- function() assertThat(as.list(structure(1:3, .Dim = 3L, .Dimnames = list(c("a", "b", "c")))), identicalTo(structure(list(a = 1L, b = 2L, c = 3L), .Names = c("a", "b", "c"))))
test.as.list.38 <- function() assertThat(as.list(structure(1:3, .Dim = 3L, .Dimnames = structure(list(    z = c("a", "b", "c")), .Names = "z"))), identicalTo(structure(list(a = 1L, b = 2L, c = 3L), .Names = c("a", "b", "c"))))
test.as.list.39 <- function() assertThat(as.list(structure(list("foo"), class = "foo")), identicalTo(41L))
test.as.list.40 <- function() assertThat(as.list(structure(list("bar"), class = "foo")), identicalTo(41L))
test.as.list.41 <- function() assertThat(as.list(quote(xyz)), identicalTo(list(quote(xyz))))
test.as.list.42 <- function() assertThat(as.list(quote(sin(3.14))), identicalTo(list(quote(sin), 3.14)))
test.as.list.43 <- function() assertThat(as.list(structure("foo", class = "foo")), identicalTo(41L))
test.as.list.44 <- function() assertThat(as.list(structure(list(1L, "bar"), class = "bar")), identicalTo(structure(list(1L, "bar"), class = "bar")))
