#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2019 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-math-unary-tests.R using GNU R version 3.2.0 (2015-04-16)
library(hamcrest)
cos.foo <- function(...) 41
Math.bar <- function(...) 44
test.cos.1 <- function() assertThat(cos(-0.01), identicalTo(0.999950000416665, tol = 0.000100))
test.cos.2 <- function() assertThat(cos(-0.1), identicalTo(0.995004165278026, tol = 0.000100))
test.cos.3 <- function() assertThat(cos(-1), identicalTo(0.54030230586814, tol = 0.000100))
test.cos.4 <- function() assertThat(cos(-1.5), identicalTo(0.0707372016677029, tol = 0.000100))
test.cos.5 <- function() assertThat(cos(-2), identicalTo(-0.416146836547142, tol = 0.000100))
test.cos.6 <- function() assertThat(cos(-2.5), identicalTo(-0.801143615546934, tol = 0.000100))
test.cos.7 <- function() assertThat(cos(-4), identicalTo(-0.653643620863612, tol = 0.000100))
test.cos.8 <- function() assertThat(cos(-10), identicalTo(-0.839071529076452, tol = 0.000100))
test.cos.9 <- function() assertThat(cos(-100), identicalTo(0.862318872287684, tol = 0.000100))
test.cos.10 <- function() assertThat(cos(-0.785398), identicalTo(0.707106896725982, tol = 0.000100))
test.cos.11 <- function() assertThat(cos(-1.5708), identicalTo(-3.67320510334657e-06, tol = 0.000100))
test.cos.12 <- function() assertThat(cos(-3.14159), identicalTo(-0.999999999996479, tol = 0.000100))
test.cos.13 <- function() assertThat(cos(-6.28319), identicalTo(0.999999999988989, tol = 0.000100))
test.cos.14 <- function() assertThat(cos(0.01), identicalTo(0.999950000416665, tol = 0.000100))
test.cos.15 <- function() assertThat(cos(0.1), identicalTo(0.995004165278026, tol = 0.000100))
test.cos.16 <- function() assertThat(cos(1), identicalTo(0.54030230586814, tol = 0.000100))
test.cos.17 <- function() assertThat(cos(1.5), identicalTo(0.0707372016677029, tol = 0.000100))
test.cos.18 <- function() assertThat(cos(2), identicalTo(-0.416146836547142, tol = 0.000100))
test.cos.19 <- function() assertThat(cos(2.5), identicalTo(-0.801143615546934, tol = 0.000100))
test.cos.20 <- function() assertThat(cos(4), identicalTo(-0.653643620863612, tol = 0.000100))
test.cos.21 <- function() assertThat(cos(10), identicalTo(-0.839071529076452, tol = 0.000100))
test.cos.22 <- function() assertThat(cos(100), identicalTo(0.862318872287684, tol = 0.000100))
test.cos.23 <- function() assertThat(cos(0.785398), identicalTo(0.707106896725982, tol = 0.000100))
test.cos.24 <- function() assertThat(cos(1.5708), identicalTo(-3.67320510334657e-06, tol = 0.000100))
test.cos.25 <- function() assertThat(cos(3.14159), identicalTo(-0.999999999996479, tol = 0.000100))
test.cos.26 <- function() assertThat(cos(6.28319), identicalTo(0.999999999988989, tol = 0.000100))
test.cos.27 <- function() assertThat(cos(NULL), throwsError())
test.cos.28 <- function() assertThat(cos(c(0.01, 0.1, 1, 1.5)), identicalTo(c(0.999950000416665, 0.995004165278026, 0.54030230586814, 0.0707372016677029), tol = 0.000100))
test.cos.29 <- function() assertThat(cos(integer(0)), identicalTo(numeric(0)))
test.cos.30 <- function() assertThat(cos(numeric(0)), identicalTo(numeric(0)))
test.cos.31 <- function() assertThat(cos(NaN), identicalTo(NaN))
test.cos.32 <- function() assertThat(cos(NA_real_), identicalTo(NA_real_))
test.cos.33 <- function() assertThat(cos(Inf), identicalTo(NaN))
test.cos.34 <- function() assertThat(cos(-Inf), identicalTo(NaN))
test.cos.35 <- function() assertThat(cos(c(1L, 4L)), identicalTo(c(0.54030230586814, -0.653643620863612), tol = 0.000100))
test.cos.36 <- function() assertThat(cos(structure(1, class = "foo")), identicalTo(41))
test.cos.37 <- function() assertThat(cos(structure(1, class = "bar")), identicalTo(44))
test.cos.38 <- function() assertThat(cos(structure(list("a"), class = "foo")), identicalTo(41))
test.cos.39 <- function() assertThat(cos(structure(list("b"), class = "bar")), identicalTo(44))
test.cos.40 <- function() assertThat(cos(structure(c(1, 2, 3), .Names = c("a", "b", "c"))), identicalTo(structure(c(0.54030230586814, -0.416146836547142, -0.989992496600445), .Names = c("a", "b", "c")), tol = 0.000100))
test.cos.41 <- function() assertThat(cos(structure(c(1, 2), .Names = c("x", ""))), identicalTo(structure(c(0.54030230586814, -0.416146836547142), .Names = c("x", "")), tol = 0.000100))
test.cos.42 <- function() assertThat(cos(structure(1:12, .Dim = 3:4)), identicalTo(structure(c(0.54030230586814, -0.416146836547142, -0.989992496600445, -0.653643620863612, 0.283662185463226, 0.960170286650366, 0.753902254343305, -0.145500033808614, -0.911130261884677, -0.839071529076452, 0.00442569798805079, 0.843853958732492), .Dim = 3:4), tol = 0.000100))
test.cos.43 <- function() assertThat(cos(structure(0, rando.attr = 4L)), identicalTo(structure(1, rando.attr = 4L)))
test.cos.44 <- function() assertThat(cos(structure(0, class = "zinga")), identicalTo(structure(1, class = "zinga")))
