#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2016 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-dist-tests.R using GNU R version 3.3.1 (2016-06-21)
library(hamcrest)
library(stats)
set.seed(1)
test.rchisq.1 <- function() assertThat({set.seed(1);rchisq(n = 0x1p+0, df = c(0x1p+0, 0x1p+1, 0x1.8p+1, 0x1p+2))}, identicalTo(0x1.94bd88c398c42p-3, tol = 0.000100))
test.rchisq.2 <- function() assertThat({set.seed(1);rchisq(n = 1:5, df = c(0x1p+0, 0x1p+1, 0x1.8p+1, 0x1p+2))}, identicalTo(c(0x1.94bd88c398c42p-3, 0x1.46cd823ef4d7ep+0, 0x1.5b132294fbe7fp-1, 0x1.068100b13bcdap+2, 0x1.5eb0939be9dd7p-7), tol = 0.000100))
test.rchisq.3 <- function() assertThat({set.seed(1);rchisq(n = 0x1.ep+3, df = c(0x1p+0, 0x1p+1, 0x1.8p+1, 0x1p+2))}, identicalTo(c(0x1.94bd88c398c42p-3, 0x1.46cd823ef4d7ep+0, 0x1.5b132294fbe7fp-1, 0x1.068100b13bcdap+2, 0x1.5eb0939be9dd7p-7, 0x1.e306a9618224cp-4, 0x1.dfe626302fd5fp+1, 0x1.24df5b420433ap+2, 0x1.9e9b6af708fb9p-2, 0x1.11f75bd9ab545p+2, 0x1.6d86c51058b56p+1, 0x1.abd6e04a61b6fp+0, 0x1.a3c1b1643823p-2, 0x1.637523ae26e75p+0, 0x1.3a53a48fe671ep-1), tol = 0.000100))
test.rchisq.4 <- function() assertThat({set.seed(1);rchisq(n = numeric(0), df = c(0x1p+0, 0x1p+1, 0x1.8p+1, 0x1p+2))}, identicalTo(numeric(0)))
test.rchisq.5 <- function() assertThat({set.seed(1);rchisq(n = 0x1.8p+1, df = c(NA, 0x1p+1, 0x1.8p+1, 0x1p+2))}, identicalTo(c(NaN, 0x1.3dbac065e1d86p-2, 0x1.62cd513230be6p+2)))
