#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2018 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-unary-tests.R using GNU R version 3.5.3 (2019-03-11)
library(hamcrest)
Sys.setlocale('LC_COLLATE', 'C')
as.symbol.foo <- function(...) 41L
as.vector.foo <- function(...) 99
as.vector.bar <- function(...) 98
Math.bar <- function(...) 44
Summary.bar <- function(...) 45
Ops.bar <- function(...) 46
test.as.symbol.1 <- function() assertThat(as.symbol(NULL), throwsError())
test.as.symbol.2 <- function() assertThat(as.symbol(logical(0)), throwsError())
test.as.symbol.3 <- function() assertThat(as.symbol(c(TRUE, TRUE, FALSE, FALSE, TRUE)), identicalTo(as.name("TRUE")))
test.as.symbol.4 <- function() assertThat(as.symbol(structure(c(TRUE, FALSE), .Names = c("a", ""))), identicalTo(as.name("TRUE")))
test.as.symbol.5 <- function() assertThat(as.symbol(c(TRUE, FALSE, NA)), identicalTo(as.name("TRUE")))
test.as.symbol.6 <- function() assertThat(as.symbol(integer(0)), throwsError())
test.as.symbol.7 <- function() assertThat(as.symbol(structure(integer(0), .Names = character(0))), throwsError())
test.as.symbol.8 <- function() assertThat(as.symbol(1:3), identicalTo(as.name("1")))
test.as.symbol.9 <- function() assertThat(as.symbol(c(1L, NA, 4L, NA, 999L)), identicalTo(as.name("1")))
test.as.symbol.10 <- function() assertThat(as.symbol(c(1L, 2L, 1073741824L, 1073741824L)), identicalTo(as.name("1")))
test.as.symbol.11 <- function() assertThat(as.symbol(numeric(0)), throwsError())
test.as.symbol.12 <- function() assertThat(as.symbol(c(3.14159, 6.28319, 9.42478, 12.5664, 15.708)), identicalTo(as.name("3.14159")))
test.as.symbol.13 <- function() assertThat(as.symbol(c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708)), identicalTo(as.name("-3.14159")))
test.as.symbol.14 <- function() assertThat(as.symbol(structure(1:2, .Names = c("a", "b"))), identicalTo(as.name("1")))
test.as.symbol.15 <- function() assertThat(as.symbol(structure(c(1.5, 2.5), .Names = c("a", "b"))), identicalTo(as.name("1.5")))
test.as.symbol.16 <- function() assertThat(as.symbol(c(1.5, 1.51, 0, 1.49, -30)), identicalTo(as.name("1.5")))
test.as.symbol.17 <- function() assertThat(as.symbol(c(1.5, 1.51, 0, 1.49, -30, NA)), identicalTo(as.name("1.5")))
test.as.symbol.18 <- function() assertThat(as.symbol(c(1.5, 1.51, 0, 1.49, -30, NaN)), identicalTo(as.name("1.5")))
test.as.symbol.19 <- function() assertThat(as.symbol(c(1.5, 1.51, 0, 1.49, -30, Inf)), identicalTo(as.name("1.5")))
test.as.symbol.20 <- function() assertThat(as.symbol(c(1.5, 1.51, 0, 1.49, -30, -Inf)), identicalTo(as.name("1.5")))
test.as.symbol.21 <- function() assertThat(as.symbol(character(0)), throwsError())
test.as.symbol.22 <- function() assertThat(as.symbol(c("4.1", "blahh", "99.9", "-413", NA)), identicalTo(as.name("4.1")))
test.as.symbol.23 <- function() assertThat(as.symbol(complex(0)), throwsError())
test.as.symbol.24 <- function() assertThat(as.symbol(list(1, 2, 3)), throwsError())
test.as.symbol.25 <- function() assertThat(as.symbol(list(1, 2, NULL)), throwsError())
test.as.symbol.26 <- function() assertThat(as.symbol(list(1L, 2L, 3L)), throwsError())
test.as.symbol.27 <- function() assertThat(as.symbol(list(1L, 2L, NULL)), throwsError())
test.as.symbol.28 <- function() assertThat(as.symbol(list(1, 2, list(3, 4))), throwsError())
test.as.symbol.29 <- function() assertThat(as.symbol(list(1, 2, numeric(0))), throwsError())
test.as.symbol.30 <- function() assertThat(as.symbol(list(3, "a", structure(list("b", list(TRUE, "c")), .Names = c("", "z")))), throwsError())
test.as.symbol.31 <- function() assertThat(as.symbol(structure(list(1, 2, 3), .Names = c(NA, "", "b"))), throwsError())
test.as.symbol.32 <- function() assertThat(as.symbol(pairlist(41, "a", 21L)), throwsError())
test.as.symbol.33 <- function() assertThat(as.symbol(structure(pairlist(a = 41, 42))), throwsError())
test.as.symbol.34 <- function() assertThat(as.symbol(structure(pairlist(a = 41, NULL))), throwsError())
test.as.symbol.35 <- function() assertThat(as.symbol(structure(1:12, .Dim = 3:4)), identicalTo(as.name("1")))
test.as.symbol.36 <- function() assertThat(as.symbol(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(    c("a", "b", "c"), c("d", "e", "f", "g")), .Names = c("x", "y")))), identicalTo(as.name("1")))
test.as.symbol.37 <- function() assertThat(as.symbol(structure(1:3, rando.attrib = 941L)), identicalTo(as.name("1")))
test.as.symbol.38 <- function() assertThat(as.symbol(structure(1:3, .Dim = 3L, .Dimnames = list(c("a", "b", "c")))), identicalTo(as.name("1")))
test.as.symbol.39 <- function() assertThat(as.symbol(structure(1:3, .Dim = 3L, .Dimnames = structure(list(    c("a", "b", "c")), .Names = "z"))), identicalTo(as.name("1")))
test.as.symbol.40 <- function() assertThat(as.symbol(structure(list("foo"), class = "foo")), identicalTo(99))
test.as.symbol.41 <- function() assertThat(as.symbol(structure(list("bar"), class = "foo")), identicalTo(99))
test.as.symbol.42 <- function() assertThat(as.symbol(quote(xyz)), identicalTo(as.name("xyz")))
test.as.symbol.43 <- function() assertThat(as.symbol(quote(sin(3.14))), throwsError())
test.as.symbol.44 <- function() assertThat(as.symbol("NaN"), identicalTo(as.name("NaN")))
test.as.symbol.45 <- function() assertThat(as.symbol("NABOOM!"), identicalTo(as.name("NABOOM!")))
test.as.symbol.46 <- function() assertThat(as.symbol("NaNaNabooboo"), identicalTo(as.name("NaNaNabooboo")))
test.as.symbol.47 <- function() assertThat(as.symbol("-Inf"), identicalTo(as.name("-Inf")))
test.as.symbol.48 <- function() assertThat(as.symbol("+Infinity"), identicalTo(as.name("+Infinity")))
test.as.symbol.49 <- function() assertThat(as.symbol("Infinity and beyond!"), identicalTo(as.name("Infinity and beyond!")))
test.as.symbol.50 <- function() assertThat(as.symbol("Infi"), identicalTo(as.name("Infi")))
test.as.symbol.51 <- function() assertThat(as.symbol("0.03f"), identicalTo(as.name("0.03f")))
test.as.symbol.52 <- function() assertThat(as.symbol("  0.0330   "), identicalTo(as.name("  0.0330   ")))
test.as.symbol.53 <- function() assertThat(as.symbol(structure("foo", class = "foo")), identicalTo(99))
test.as.symbol.54 <- function() assertThat(as.symbol(structure(list(1L, "bar"), class = "bar")), identicalTo(98))
