#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2016 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-unary-tests.R using GNU R version 3.3.1 (2016-06-21)
library(hamcrest)
t.foo <- function(...) 41L
as.vector.foo <- function(...) 99
Math.bar <- function(...) 44
Summary.bar <- function(...) 45
Ops.bar <- function(...) 46
test.t.1 <- function() assertThat(t(NULL), throwsError())
test.t.2 <- function() assertThat(t(logical(0)), identicalTo(structure(logical(0), .Dim = c(1L, 0L))))
test.t.3 <- function() assertThat(t(c(TRUE, TRUE, FALSE, FALSE, TRUE)), identicalTo(structure(c(TRUE, TRUE, FALSE, FALSE, TRUE), .Dim = c(1L, 5L))))
test.t.4 <- function() assertThat(t(structure(c(TRUE, FALSE), .Names = c("a", ""))), identicalTo(structure(c(TRUE, FALSE), .Dim = 1:2, .Dimnames = list(NULL,     c("a", "")))))
test.t.5 <- function() assertThat(t(c(TRUE, FALSE, NA)), identicalTo(structure(c(TRUE, FALSE, NA), .Dim = c(1L, 3L))))
test.t.6 <- function() assertThat(t(integer(0)), identicalTo(structure(integer(0), .Dim = c(1L, 0L))))
test.t.7 <- function() assertThat(t(structure(integer(0), .Names = character(0))), identicalTo(structure(integer(0), .Dim = c(1L, 0L), .Dimnames = list(NULL,     NULL))))
test.t.8 <- function() assertThat(t(1:3), identicalTo(structure(1:3, .Dim = c(1L, 3L))))
test.t.9 <- function() assertThat(t(c(1L, NA, 4L, NA, 999L)), identicalTo(structure(c(1L, NA, 4L, NA, 999L), .Dim = c(1L, 5L))))
test.t.10 <- function() assertThat(t(c(1L, 2L, 1073741824L, 1073741824L)), identicalTo(structure(c(1L, 2L, 1073741824L, 1073741824L), .Dim = c(1L, 4L))))
test.t.11 <- function() assertThat(t(numeric(0)), identicalTo(structure(numeric(0), .Dim = c(1L, 0L))))
test.t.12 <- function() assertThat(t(c(3.14159, 6.28319, 9.42478, 12.5664, 15.708)), identicalTo(structure(c(3.14159, 6.28319, 9.42478, 12.5664, 15.708), .Dim = c(1L, 5L)), tol = 0.000100))
test.t.13 <- function() assertThat(t(c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708)), identicalTo(structure(c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708), .Dim = c(1L, 5L)), tol = 0.000100))
test.t.14 <- function() assertThat(t(structure(1:2, .Names = c("a", "b"))), identicalTo(structure(1:2, .Dim = 1:2, .Dimnames = list(NULL, c("a", "b")))))
test.t.15 <- function() assertThat(t(structure(c(1.5, 2.5), .Names = c("a", "b"))), identicalTo(structure(c(1.5, 2.5), .Dim = 1:2, .Dimnames = list(NULL, c("a", "b"))), tol = 0.000100))
test.t.16 <- function() assertThat(t(c(1.5, 1.51, 0, 1.49, -30)), identicalTo(structure(c(1.5, 1.51, 0, 1.49, -30), .Dim = c(1L, 5L)), tol = 0.000100))
test.t.17 <- function() assertThat(t(c(1.5, 1.51, 0, 1.49, -30, NA)), identicalTo(structure(c(1.5, 1.51, 0, 1.49, -30, NA), .Dim = c(1L, 6L)), tol = 0.000100))
test.t.18 <- function() assertThat(t(c(1.5, 1.51, 0, 1.49, -30, NaN)), identicalTo(structure(c(1.5, 1.51, 0, 1.49, -30, NaN), .Dim = c(1L, 6L)), tol = 0.000100))
test.t.19 <- function() assertThat(t(c(1.5, 1.51, 0, 1.49, -30, Inf)), identicalTo(structure(c(1.5, 1.51, 0, 1.49, -30, Inf), .Dim = c(1L, 6L)), tol = 0.000100))
test.t.20 <- function() assertThat(t(c(1.5, 1.51, 0, 1.49, -30, -Inf)), identicalTo(structure(c(1.5, 1.51, 0, 1.49, -30, -Inf), .Dim = c(1L, 6L)), tol = 0.000100))
test.t.21 <- function() assertThat(t(character(0)), identicalTo(structure(character(0), .Dim = c(1L, 0L))))
test.t.22 <- function() assertThat(t(c("4.1", "blahh", "99.9", "-413", NA)), identicalTo(structure(c("4.1", "blahh", "99.9", "-413", NA), .Dim = c(1L, 5L))))
test.t.23 <- function() assertThat(t(complex(0)), identicalTo(structure(complex(0), .Dim = c(1L, 0L))))
test.t.24 <- function() assertThat(t(list(1, 2, 3)), identicalTo(structure(list(1, 2, 3), .Dim = c(1L, 3L))))
test.t.25 <- function() assertThat(t(list(1, 2, NULL)), identicalTo(structure(list(1, 2, NULL), .Dim = c(1L, 3L))))
test.t.26 <- function() assertThat(t(list(1L, 2L, 3L)), identicalTo(structure(list(1L, 2L, 3L), .Dim = c(1L, 3L))))
test.t.27 <- function() assertThat(t(list(1L, 2L, NULL)), identicalTo(structure(list(1L, 2L, NULL), .Dim = c(1L, 3L))))
test.t.28 <- function() assertThat(t(list(1, 2, list(3, 4))), identicalTo(structure(list(1, 2, list(3, 4)), .Dim = c(1L, 3L))))
test.t.29 <- function() assertThat(t(list(3, "a", structure(list("b", z = list(TRUE, "c")), .Names = c("", "z")))), identicalTo(structure(list(3, "a", structure(list("b", z = list(TRUE, "c")), .Names = c("", "z"))), .Dim = c(1L, 3L))))
test.t.30 <- function() assertThat(t(structure(list(`NA` = 1, 2, b = 3), .Names = c(NA, "", "b"))), identicalTo(structure(list(1, 2, 3), .Dim = c(1L, 3L), .Dimnames = list(NULL,     c(NA, "", "b")))))
test.t.31 <- function() assertThat(t(pairlist(41, "a", 21L)), throwsError())
test.t.32 <- function() assertThat(t(pairlist(a = 41, 42)), throwsError())
test.t.33 <- function() assertThat(t(pairlist(a = 41, NULL)), throwsError())
test.t.34 <- function() assertThat(t(structure(1:12, .Dim = 3:4)), identicalTo(structure(c(1L, 4L, 7L, 10L, 2L, 5L, 8L, 11L, 3L, 6L, 9L, 12L), .Dim = c(4L, 3L))))
test.t.35 <- function() assertThat(t(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))), identicalTo(structure(c(1L, 4L, 7L, 10L, 2L, 5L, 8L, 11L, 3L, 6L, 9L, 12L), .Dim = c(4L, 3L), .Dimnames = structure(list(y = c("d", "e", "f", "g"), x = c("a", "b", "c")), .Names = c("y", "x")))))
test.t.36 <- function() assertThat(t(structure(1:3, rando.attrib = 941L)), identicalTo(structure(1:3, .Dim = c(1L, 3L), rando.attrib = 941L)))
test.t.37 <- function() assertThat(t(structure(1:3, .Dim = 3L, .Dimnames = list(c("a", "b", "c")))), identicalTo(structure(1:3, .Dim = c(1L, 3L), .Dimnames = list(NULL, c("a", "b", "c")))))
test.t.38 <- function() assertThat(t(structure(1:3, .Dim = 3L, .Dimnames = structure(list(z = c("a", "b", "c")), .Names = "z"))), identicalTo(structure(1:3, .Dim = c(1L, 3L), .Dimnames = structure(list(NULL,     z = c("a", "b", "c")), .Names = c("", "z")))))
test.t.39 <- function() assertThat(t(structure(list("foo"), class = "foo")), identicalTo(41L))
test.t.40 <- function() assertThat(t(structure(list("bar"), class = "foo")), identicalTo(41L))
test.t.41 <- function() assertThat(t(quote(xyz)), throwsError())
test.t.42 <- function() assertThat(t(quote(sin(3.14))), throwsError())
test.t.43 <- function() assertThat(t(structure("foo", class = "foo")), identicalTo(41L))
test.t.44 <- function() assertThat(t(structure(list(1L, "bar"), class = "bar")), identicalTo(structure(list(1L, "bar"), .Dim = 1:2, class = "bar")))
