library(hamcrest)
is.array.foo <- function(x) 41
Math.bar <- function(x) 44
test.is.array.1 <- function() assertThat(is.array(NULL), identicalTo(FALSE))
test.is.array.2 <- function() assertThat(is.array(logical(0)), identicalTo(FALSE))
test.is.array.3 <- function() assertThat(is.array(c(TRUE, TRUE, FALSE, FALSE, TRUE)), identicalTo(FALSE))
test.is.array.4 <- function() assertThat(is.array(structure(c(TRUE, FALSE), .Names = c("a", ""))), identicalTo(FALSE))
test.is.array.5 <- function() assertThat(is.array(c(TRUE, FALSE, NA)), identicalTo(FALSE))
test.is.array.6 <- function() assertThat(is.array(integer(0)), identicalTo(FALSE))
test.is.array.7 <- function() assertThat(is.array(structure(integer(0), .Names = character(0))), identicalTo(FALSE))
test.is.array.8 <- function() assertThat(is.array(1:3), identicalTo(FALSE))
test.is.array.9 <- function() assertThat(is.array(c(1L, NA, 4L, NA, 999L)), identicalTo(FALSE))
test.is.array.10 <- function() assertThat(is.array(c(1L, 2L, 1073741824L, 1073741824L)), identicalTo(FALSE))
test.is.array.11 <- function() assertThat(is.array(numeric(0)), identicalTo(FALSE))
test.is.array.12 <- function() assertThat(is.array(c(3.14159, 6.28319, 9.42478, 12.5664, 15.708)), identicalTo(FALSE))
test.is.array.13 <- function() assertThat(is.array(c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708)), identicalTo(FALSE))
test.is.array.14 <- function() assertThat(is.array(structure(1:2, .Names = c("a", "b"))), identicalTo(FALSE))
test.is.array.15 <- function() assertThat(is.array(structure(c(1.5, 2.5), .Names = c("a", "b"))), identicalTo(FALSE))
test.is.array.16 <- function() assertThat(is.array(character(0)), identicalTo(FALSE))
test.is.array.17 <- function() assertThat(is.array(c("4.1", "blahh", "99.9", "-413", NA)), identicalTo(FALSE))
test.is.array.18 <- function() assertThat(is.array(list(1, 2, 3)), identicalTo(FALSE))
test.is.array.19 <- function() assertThat(is.array(list(1, 2, NULL)), identicalTo(FALSE))
test.is.array.20 <- function() assertThat(is.array(list(1L, 2L, 3L)), identicalTo(FALSE))
test.is.array.21 <- function() assertThat(is.array(list(1L, 2L, NULL)), identicalTo(FALSE))
test.is.array.22 <- function() assertThat(is.array(list(1, 2, list(3, 4))), identicalTo(FALSE))
test.is.array.23 <- function() assertThat(is.array(structure(1:12, .Dim = 3:4)), identicalTo(TRUE))
test.is.array.24 <- function() assertThat(is.array(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(    x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))), identicalTo(TRUE))
test.is.array.25 <- function() assertThat(is.array(structure(1:3, rando.attrib = 941L)), identicalTo(FALSE))
test.is.array.26 <- function() assertThat(is.array(structure(1:3, .Dim = 3L, .Dimnames = list(c("a", "b", "c")))), identicalTo(TRUE))
test.is.array.27 <- function() assertThat(is.array(structure(list("foo"), class = "foo")), identicalTo(41, tol = 0.000100))
test.is.array.28 <- function() assertThat(is.array(structure(list("bar"), class = "foo")), identicalTo(41, tol = 0.000100))
test.is.array.29 <- function() assertThat(is.array(xyz), throwsError())
test.is.array.30 <- function() assertThat(is.array(sin(3.14)), identicalTo(FALSE))
test.is.array.31 <- function() assertThat(is.array(structure("foo", class = "foo")), identicalTo(41))
test.is.array.32 <- function() assertThat(is.array(structure(list(1L, "bar"), class = "bar")), identicalTo(FALSE))
