#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2016 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-dist-tests.R using GNU R version 3.3.1 (2016-06-21)
library(hamcrest)
library(stats)
set.seed(1)
test.rweibull.1 <- function() assertThat({set.seed(1);rweibull(n = 0x1p+0, shape = c(0x1.999999999999ap-4, 0x1p-1, 0x1.4p+2), scale = c(0x0p+0, 0x1p+0, 0x1p-1, 0x1.4p+2))}, identicalTo(0x0p+0))
test.rweibull.2 <- function() assertThat({set.seed(1);rweibull(n = 1:5, shape = c(0x1.999999999999ap-4, 0x1p-1, 0x1.4p+2), scale = c(0x0p+0, 0x1p+0, 0x1p-1, 0x1.4p+2))}, identicalTo(c(0x0p+0, 0x1.c2311d3670c55p+0, 0x1.fed1e3cd69812p-2, 0x1.d80252d6027acp-7, 0x0p+0), tol = 0.000100))
test.rweibull.3 <- function() assertThat({set.seed(1);rweibull(n = 0x1.ep+3, shape = c(0x1.999999999999ap-4, 0x1p-1, 0x1.4p+2), scale = c(0x0p+0, 0x1p+0, 0x1p-1, 0x1.4p+2))}, identicalTo(c(0x0p+0, 0x1.2fc467bc3d8f2p-7, 0x1.1944d4d5b2a2p-1, 0x1.12364ba403312p-30, 0x0p+0, 0x1.209c949abcb8ap-1, 0x1.38813efa363a2p-14, 0x1.12ead60b53695p+0, 0x0p+0, 0x1.b525bdd2173dfp+14, 0x1.3f8a4c5bb5d2bp+0, 0x1.653e923bb8c13p+2, 0x0p+0, 0x1.20988a8561c34p-3, 0x1.fb809abf25044p-2), tol = 0.000100))
test.rweibull.4 <- function() assertThat({set.seed(1);rweibull(n = numeric(0), shape = c(0x1.999999999999ap-4, 0x1p-1, 0x1.4p+2), scale = c(0x0p+0, 0x1p+0, 0x1p-1, 0x1.4p+2))}, identicalTo(numeric(0)))
test.rweibull.5 <- function() assertThat({set.seed(1);rweibull(n = 0x1.8p+1, shape = c(NA, 0x1p-1, 0x1.4p+2), scale = c(0x0p+0, 0x1p+0, 0x1p-1, 0x1.4p+2))}, identicalTo(c(0x0p+0, 0x1.183ec8307120bp-4, 0x1.dc717272f6ae1p-2)))
