#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2016 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-unary-tests.R using GNU R version 3.3.3 (2017-03-06)
library(hamcrest)
Sys.setlocale('LC_COLLATE', 'C')
as.expression.foo <- function(...) 41L
as.vector.foo <- function(...) 99
Math.bar <- function(...) 44
Summary.bar <- function(...) 45
Ops.bar <- function(...) 46
test.as.expression.1 <- function() assertThat(as.expression(NULL), deparsesTo("expression(NULL)"))
test.as.expression.2 <- function() assertThat(as.expression(logical(0)), deparsesTo("expression()"))
test.as.expression.3 <- function() assertThat(as.expression(c(TRUE, TRUE, FALSE, FALSE, TRUE)), deparsesTo("expression(TRUE, TRUE, FALSE, FALSE, TRUE)"))
test.as.expression.4 <- function() assertThat(as.expression(structure(c(TRUE, FALSE), .Names = c("a", ""))), deparsesTo("expression(TRUE, FALSE)"))
test.as.expression.5 <- function() assertThat(as.expression(c(TRUE, FALSE, NA)), deparsesTo("expression(TRUE, FALSE, NA)"))
test.as.expression.6 <- function() assertThat(as.expression(integer(0)), deparsesTo("expression()"))
test.as.expression.7 <- function() assertThat(as.expression(structure(integer(0), .Names = character(0))), deparsesTo("expression()"))
test.as.expression.8 <- function() assertThat(as.expression(1:3), deparsesTo("expression(1L, 2L, 3L)"))
test.as.expression.9 <- function() assertThat(as.expression(c(1L, NA, 4L, NA, 999L)), deparsesTo("expression(1L, NA_integer_, 4L, NA_integer_, 999L)"))
test.as.expression.10 <- function() assertThat(as.expression(c(1L, 2L, 1073741824L, 1073741824L)), deparsesTo("expression(1L, 2L, 1073741824L, 1073741824L)"))
test.as.expression.11 <- function() assertThat(as.expression(numeric(0)), deparsesTo("expression()"))
test.as.expression.12 <- function() assertThat(as.expression(c(3.14159, 6.28319, 9.42478, 12.5664, 15.708)), deparsesTo("expression(3.14159, 6.28319, 9.42478, 12.5664, 15.708)"))
test.as.expression.13 <- function() assertThat(as.expression(c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708)), deparsesTo("expression(-3.14159, -6.28319, -9.42478, -12.5664, -15.708)"))
test.as.expression.14 <- function() assertThat(as.expression(structure(1:2, .Names = c("a", "b"))), deparsesTo("expression(1L, 2L)"))
test.as.expression.15 <- function() assertThat(as.expression(structure(c(1.5, 2.5), .Names = c("a", "b"))), deparsesTo("expression(1.5, 2.5)"))
test.as.expression.16 <- function() assertThat(as.expression(c(1.5, 1.51, 0, 1.49, -30)), deparsesTo("expression(1.5, 1.51, 0, 1.49, -30)"))
test.as.expression.17 <- function() assertThat(as.expression(c(1.5, 1.51, 0, 1.49, -30, NA)), deparsesTo("expression(1.5, 1.51, 0, 1.49, -30, NA_real_)"))
test.as.expression.18 <- function() assertThat(as.expression(c(1.5, 1.51, 0, 1.49, -30, NaN)), deparsesTo("expression(1.5, 1.51, 0, 1.49, -30, NaN)"))
test.as.expression.19 <- function() assertThat(as.expression(c(1.5, 1.51, 0, 1.49, -30, Inf)), deparsesTo("expression(1.5, 1.51, 0, 1.49, -30, Inf)"))
test.as.expression.20 <- function() assertThat(as.expression(c(1.5, 1.51, 0, 1.49, -30, -Inf)), deparsesTo("expression(1.5, 1.51, 0, 1.49, -30, -Inf)"))
test.as.expression.21 <- function() assertThat(as.expression(character(0)), deparsesTo("expression()"))
test.as.expression.22 <- function() assertThat(as.expression(c("4.1", "blahh", "99.9", "-413", NA)), deparsesTo("expression(\"4.1\", \"blahh\", \"99.9\", \"-413\", NA_character_)"))
test.as.expression.23 <- function() assertThat(as.expression(complex(0)), deparsesTo("expression()"))
test.as.expression.24 <- function() assertThat(as.expression(list(1, 2, 3)), deparsesTo("expression(1, 2, 3)"))
test.as.expression.25 <- function() assertThat(as.expression(list(1, 2, NULL)), deparsesTo("expression(1, 2, NULL)"))
test.as.expression.26 <- function() assertThat(as.expression(list(1L, 2L, 3L)), deparsesTo("expression(1L, 2L, 3L)"))
test.as.expression.27 <- function() assertThat(as.expression(list(1L, 2L, NULL)), deparsesTo("expression(1L, 2L, NULL)"))
test.as.expression.28 <- function() assertThat(as.expression(list(1, 2, list(3, 4))), deparsesTo("expression(1, 2, list(3, 4))"))
test.as.expression.29 <- function() assertThat(as.expression(list(1, 2, numeric(0))), deparsesTo("expression(1, 2, numeric(0))"))
test.as.expression.30 <- function() assertThat(as.expression(list(3, "a", structure(list("b", z = list(TRUE,     "c")), .Names = c("", "z")))), deparsesTo("expression(3, \"a\", list(\"b\", z = list(TRUE, \"c\")))"))
test.as.expression.31 <- function() assertThat(as.expression(structure(list(`NA` = 1, 2, b = 3), .Names = c(NA, "", "b"))), deparsesTo("structure(expression(`NA` = 1, 2, b = 3), .Names = c(NA, \"\", \"b\"))"))
test.as.expression.32 <- function() assertThat(as.expression(pairlist(41, "a", 21L)), deparsesTo("expression(pairlist(41, \"a\", 21L))"))
test.as.expression.33 <- function() assertThat(as.expression(pairlist(a = 41, 42)), deparsesTo("expression(pairlist(a = 41, 42))"))
test.as.expression.34 <- function() assertThat(as.expression(pairlist(a = 41, NULL)), deparsesTo("expression(pairlist(a = 41, NULL))"))
test.as.expression.35 <- function() assertThat(as.expression(structure(1:12, .Dim = 3:4)), deparsesTo("expression(1L, 2L, 3L, 4L, 5L, 6L, 7L, 8L, 9L, 10L, 11L, 12L)"))
test.as.expression.36 <- function() assertThat(as.expression(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(    x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))), deparsesTo("expression(1L, 2L, 3L, 4L, 5L, 6L, 7L, 8L, 9L, 10L, 11L, 12L)"))
test.as.expression.37 <- function() assertThat(as.expression(structure(1:3, rando.attrib = 941L)), deparsesTo("expression(1L, 2L, 3L)"))
test.as.expression.38 <- function() assertThat(as.expression(structure(1:3, .Dim = 3L, .Dimnames = list(c("a", "b", "c")))), deparsesTo("expression(1L, 2L, 3L)"))
test.as.expression.39 <- function() assertThat(as.expression(structure(1:3, .Dim = 3L, .Dimnames = structure(list(    z = c("a", "b", "c")), .Names = "z"))), deparsesTo("expression(1L, 2L, 3L)"))
test.as.expression.40 <- function() assertThat(as.expression(structure(list("foo"), class = "foo")), identicalTo(41L))
test.as.expression.41 <- function() assertThat(as.expression(structure(list("bar"), class = "foo")), identicalTo(41L))
test.as.expression.42 <- function() assertThat(as.expression(quote(xyz)), deparsesTo("expression(xyz)"))
test.as.expression.43 <- function() assertThat(as.expression(quote(sin(3.14))), deparsesTo("expression(sin(3.14))"))
test.as.expression.44 <- function() assertThat(as.expression("NaN"), deparsesTo("expression(\"NaN\")"))
test.as.expression.45 <- function() assertThat(as.expression("NABOOM!"), deparsesTo("expression(\"NABOOM!\")"))
test.as.expression.46 <- function() assertThat(as.expression("NaNaNabooboo"), deparsesTo("expression(\"NaNaNabooboo\")"))
test.as.expression.47 <- function() assertThat(as.expression("-Inf"), deparsesTo("expression(\"-Inf\")"))
test.as.expression.48 <- function() assertThat(as.expression("+Infinity"), deparsesTo("expression(\"+Infinity\")"))
test.as.expression.49 <- function() assertThat(as.expression("Infinity and beyond!"), deparsesTo("expression(\"Infinity and beyond!\")"))
test.as.expression.50 <- function() assertThat(as.expression("Infi"), deparsesTo("expression(\"Infi\")"))
test.as.expression.51 <- function() assertThat(as.expression("0.03f"), deparsesTo("expression(\"0.03f\")"))
test.as.expression.52 <- function() assertThat(as.expression("  0.0330   "), deparsesTo("expression(\"  0.0330   \")"))
test.as.expression.53 <- function() assertThat(as.expression(structure("foo", class = "foo")), identicalTo(41L))
test.as.expression.54 <- function() assertThat(as.expression(structure(list(1L, "bar"), class = "bar")), deparsesTo("structure(expression(1L, \"bar\"), class = \"bar\")"))
