#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2016 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-matrices-sum.R using GNU R version 3.2.0 (2015-04-16)
library(hamcrest)
test.rowMeans.1 <- function() assertThat(rowMeans(1:3), throwsError())
test.rowMeans.2 <- function() assertThat(rowMeans(structure(1:12, .Dim = 3:4)), identicalTo(c(5.5, 6.5, 7.5), tol = 0.000001))
test.rowMeans.3 <- function() assertThat(rowMeans(structure(1:12, .Dim = 3:4, .Dimnames = list(c("a", "b", "c"), c("d", "e", "f", "g")))), identicalTo(structure(c(5.5, 6.5, 7.5), .Names = c("a", "b", "c")), tol = 0.000001))
test.rowMeans.4 <- function() assertThat(rowMeans(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(    x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))), identicalTo(structure(c(5.5, 6.5, 7.5), .Names = c("a", "b", "c")), tol = 0.000001))
test.rowMeans.5 <- function() assertThat(rowMeans(structure(c(1, NA, NA, 3), .Dim = c(2L, 2L))), identicalTo(c(NA_real_, NA_real_), tol = 0.000001))
test.rowMeans.6 <- function() assertThat(rowMeans(structure(c(1, NA, NA, 3), .Dim = c(2L, 2L), .Dimnames = list(    c("r1", "r2"), c("c1", "c2")))), identicalTo(structure(c(NA_real_, NA_real_), .Names = c("r1", "r2")), tol = 0.000001))
test.rowMeans.7 <- function() assertThat(rowMeans(structure(c(1, NA, NA, 3), .Dim = c(2L, 2L), .Dimnames = structure(list(    x = c("r1", "r2"), y = c("c1", "c2")), .Names = c("x", "y")))), identicalTo(structure(c(NA_real_, NA_real_), .Names = c("r1", "r2")), tol = 0.000001))
test.rowMeans.8 <- function() assertThat(rowMeans(structure(1:3, .Dim = c(3L, 1L))), identicalTo(c(1, 2, 3), tol = 0.000001))
test.rowMeans.9 <- function() assertThat(rowMeans(structure(1:3, .Dim = c(3L, 1L), .Dimnames = list(c("a", "b", "c"), NULL))), identicalTo(structure(c(1, 2, 3), .Names = c("a", "b", "c")), tol = 0.000001))
test.rowMeans.10 <- function() assertThat(rowMeans(structure(1:3, .Dim = c(3L, 1L), .Dimnames = structure(list(    x = c("a", "b", "c"), y = NULL), .Names = c("x", "y")))), identicalTo(structure(c(1, 2, 3), .Names = c("a", "b", "c")), tol = 0.000001))
test.rowMeans.11 <- function() assertThat(rowMeans(1:3, na.rm = TRUE), throwsError())
test.rowMeans.12 <- function() assertThat(rowMeans(structure(1:12, .Dim = 3:4), na.rm = TRUE), identicalTo(c(5.5, 6.5, 7.5), tol = 0.000001))
test.rowMeans.13 <- function() assertThat(rowMeans(structure(1:12, .Dim = 3:4, .Dimnames = list(c("a", "b", "c"), c("d", "e", "f", "g"))), na.rm = TRUE), identicalTo(structure(c(5.5, 6.5, 7.5), .Names = c("a", "b", "c")), tol = 0.000001))
test.rowMeans.14 <- function() assertThat(rowMeans(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(    x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y"))), na.rm = TRUE), identicalTo(structure(c(5.5, 6.5, 7.5), .Names = c("a", "b", "c")), tol = 0.000001))
test.rowMeans.15 <- function() assertThat(rowMeans(structure(c(1, NA, NA, 3), .Dim = c(2L, 2L)), na.rm = TRUE), identicalTo(c(1, 3), tol = 0.000001))
test.rowMeans.16 <- function() assertThat(rowMeans(structure(c(1, NA, NA, 3), .Dim = c(2L, 2L), .Dimnames = list(    c("r1", "r2"), c("c1", "c2"))), na.rm = TRUE), identicalTo(structure(c(1, 3), .Names = c("r1", "r2")), tol = 0.000001))
test.rowMeans.17 <- function() assertThat(rowMeans(structure(c(1, NA, NA, 3), .Dim = c(2L, 2L), .Dimnames = structure(list(    x = c("r1", "r2"), y = c("c1", "c2")), .Names = c("x", "y"))), na.rm = TRUE), identicalTo(structure(c(1, 3), .Names = c("r1", "r2")), tol = 0.000001))
test.rowMeans.18 <- function() assertThat(rowMeans(structure(1:3, .Dim = c(3L, 1L)), na.rm = TRUE), identicalTo(c(1, 2, 3), tol = 0.000001))
test.rowMeans.19 <- function() assertThat(rowMeans(structure(1:3, .Dim = c(3L, 1L), .Dimnames = list(c("a", "b", "c"), NULL)), na.rm = TRUE), identicalTo(structure(c(1, 2, 3), .Names = c("a", "b", "c")), tol = 0.000001))
test.rowMeans.20 <- function() assertThat(rowMeans(structure(1:3, .Dim = c(3L, 1L), .Dimnames = structure(list(    x = c("a", "b", "c"), y = NULL), .Names = c("x", "y"))),     na.rm = TRUE), identicalTo(structure(c(1, 2, 3), .Names = c("a", "b", "c")), tol = 0.000001))
test.dotrowMeans.1 <- function() assertThat(.rowMeans(matrix(1:12, ncol=3, dimnames=list(c("a","b","c","d"), c("E","F","G"))),4,3), identicalTo(c(5, 6, 7, 8)))
