#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2016 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-math-unary-tests.R using GNU R version 3.2.0 (2015-04-16)
library(hamcrest)
sqrt.foo <- function(...) 41
Math.bar <- function(...) 44
test.sqrt.1 <- function() assertThat(sqrt(-0.01), identicalTo(NaN))
test.sqrt.2 <- function() assertThat(sqrt(-0.1), identicalTo(NaN))
test.sqrt.3 <- function() assertThat(sqrt(-1), identicalTo(NaN))
test.sqrt.4 <- function() assertThat(sqrt(-1.5), identicalTo(NaN))
test.sqrt.5 <- function() assertThat(sqrt(-2), identicalTo(NaN))
test.sqrt.6 <- function() assertThat(sqrt(-2.5), identicalTo(NaN))
test.sqrt.7 <- function() assertThat(sqrt(-4), identicalTo(NaN))
test.sqrt.8 <- function() assertThat(sqrt(-10), identicalTo(NaN))
test.sqrt.9 <- function() assertThat(sqrt(-100), identicalTo(NaN))
test.sqrt.10 <- function() assertThat(sqrt(-0.785398), identicalTo(NaN))
test.sqrt.11 <- function() assertThat(sqrt(-1.5708), identicalTo(NaN))
test.sqrt.12 <- function() assertThat(sqrt(-3.14159), identicalTo(NaN))
test.sqrt.13 <- function() assertThat(sqrt(-6.28319), identicalTo(NaN))
test.sqrt.14 <- function() assertThat(sqrt(0.01), identicalTo(0.1, tol = 0.000100))
test.sqrt.15 <- function() assertThat(sqrt(0.1), identicalTo(0.316227766016838, tol = 0.000100))
test.sqrt.16 <- function() assertThat(sqrt(1), identicalTo(1))
test.sqrt.17 <- function() assertThat(sqrt(1.5), identicalTo(1.22474487139159, tol = 0.000100))
test.sqrt.18 <- function() assertThat(sqrt(2), identicalTo(1.4142135623731, tol = 0.000100))
test.sqrt.19 <- function() assertThat(sqrt(2.5), identicalTo(1.58113883008419, tol = 0.000100))
test.sqrt.20 <- function() assertThat(sqrt(4), identicalTo(2))
test.sqrt.21 <- function() assertThat(sqrt(10), identicalTo(3.16227766016838, tol = 0.000100))
test.sqrt.22 <- function() assertThat(sqrt(100), identicalTo(10))
test.sqrt.23 <- function() assertThat(sqrt(0.785398), identicalTo(0.886226833265615, tol = 0.000100))
test.sqrt.24 <- function() assertThat(sqrt(1.5708), identicalTo(1.25331560271146, tol = 0.000100))
test.sqrt.25 <- function() assertThat(sqrt(3.14159), identicalTo(1.7724531023415, tol = 0.000100))
test.sqrt.26 <- function() assertThat(sqrt(6.28319), identicalTo(2.50662921071306, tol = 0.000100))
test.sqrt.27 <- function() assertThat(sqrt(NULL), throwsError())
test.sqrt.28 <- function() assertThat(sqrt(c(0.01, 0.1, 1, 1.5)), identicalTo(c(0.1, 0.316227766016838, 1, 1.22474487139159), tol = 0.000100))
test.sqrt.29 <- function() assertThat(sqrt(integer(0)), identicalTo(numeric(0)))
test.sqrt.30 <- function() assertThat(sqrt(numeric(0)), identicalTo(numeric(0)))
test.sqrt.31 <- function() assertThat(sqrt(NaN), identicalTo(NaN))
test.sqrt.32 <- function() assertThat(sqrt(NA_real_), identicalTo(NA_real_))
test.sqrt.33 <- function() assertThat(sqrt(Inf), identicalTo(Inf))
test.sqrt.34 <- function() assertThat(sqrt(-Inf), identicalTo(NaN))
test.sqrt.35 <- function() assertThat(sqrt(c(1L, 4L)), identicalTo(c(1, 2)))
test.sqrt.36 <- function() assertThat(sqrt(structure(1, class = "foo")), identicalTo(41))
test.sqrt.37 <- function() assertThat(sqrt(structure(1, class = "bar")), identicalTo(44))
test.sqrt.38 <- function() assertThat(sqrt(structure(list("a"), class = "foo")), identicalTo(41))
test.sqrt.39 <- function() assertThat(sqrt(structure(list("b"), class = "bar")), identicalTo(44))
test.sqrt.40 <- function() assertThat(sqrt(structure(c(1, 2, 3), .Names = c("a", "b", "c"))), identicalTo(structure(c(1, 1.4142135623731, 1.73205080756888), .Names = c("a", "b", "c")), tol = 0.000100))
test.sqrt.41 <- function() assertThat(sqrt(structure(c(1, 2), .Names = c("x", ""))), identicalTo(structure(c(1, 1.4142135623731), .Names = c("x", "")), tol = 0.000100))
test.sqrt.42 <- function() assertThat(sqrt(structure(1:12, .Dim = 3:4)), identicalTo(structure(c(1, 1.4142135623731, 1.73205080756888, 2, 2.23606797749979, 2.44948974278318, 2.64575131106459, 2.82842712474619, 3, 3.16227766016838, 3.3166247903554, 3.46410161513775), .Dim = 3:4), tol = 0.000100))
test.sqrt.43 <- function() assertThat(sqrt(structure(0, rando.attr = 4L)), identicalTo(structure(0, rando.attr = 4L)))
test.sqrt.44 <- function() assertThat(sqrt(structure(0, class = "zinga")), identicalTo(structure(0, class = "zinga")))
