#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2016 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-dist-tests.R using GNU R version 3.3.1 (2016-06-21)
library(hamcrest)
library(stats)
set.seed(1)
test.rt.1 <- function() assertThat({set.seed(1);rt(n = 0x1p+0, df = c(0x0p+0, 0x1p-1, 0x1.4p+2, 0x1p+0))}, identicalTo(NaN))
test.rt.2 <- function() assertThat({set.seed(1);rt(n = 1:5, df = c(0x0p+0, 0x1p-1, 0x1.4p+2, 0x1p+0))}, identicalTo(c(NaN, -0x1.0d23658e11af2p-2, 0x1.09b1858f379b7p-1, -0x1.6a2891f323f1fp-2, NaN), tol = 0.000100))
test.rt.3 <- function() assertThat({set.seed(1);rt(n = 0x1.ep+3, df = c(0x0p+0, 0x1p-1, 0x1.4p+2, 0x1p+0))}, identicalTo(c(NaN, -0x1.0d23658e11af2p-2, 0x1.09b1858f379b7p-1, -0x1.6a2891f323f1fp-2, NaN, 0x1.ffb554f8d32a6p+5, -0x1.7299a63858d16p-2, -0x1.bd71ac6be900fp-5, NaN, 0x1.413a17afe5db4p-1, 0x1.9c18ea95c1de2p-1, 0x1.e8a50a3f52aadp+0, NaN, -0x1.f649d60a66ab5p-4, 0x1.d2de4c5c91291p-5), tol = 0.000100))
test.rt.4 <- function() assertThat({set.seed(1);rt(n = numeric(0), df = c(0x0p+0, 0x1p-1, 0x1.4p+2, 0x1p+0))}, identicalTo(numeric(0)))
test.rt.5 <- function() assertThat({set.seed(1);rt(n = 0x1.8p+1, df = c(NA, 0x1p-1, 0x1.4p+2, 0x1p+0))}, identicalTo(c(NaN, -0x1.0d23658e11af2p-2, 0x1.09b1858f379b7p-1)))
