#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2016 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-unary-tests.R using GNU R version 3.3.1 (2016-06-21)
library(hamcrest)
is.loaded.foo <- function(...) 41L
as.vector.foo <- function(...) 99
Math.bar <- function(...) 44
Summary.bar <- function(...) 45
Ops.bar <- function(...) 46
test.is.loaded.1 <- function() assertThat(is.loaded(NULL), throwsError())
test.is.loaded.2 <- function() assertThat(is.loaded(logical(0)), throwsError())
test.is.loaded.3 <- function() assertThat(is.loaded(c(TRUE, TRUE, FALSE, FALSE, TRUE)), throwsError())
test.is.loaded.4 <- function() assertThat(is.loaded(structure(c(TRUE, FALSE), .Names = c("a", ""))), throwsError())
test.is.loaded.5 <- function() assertThat(is.loaded(c(TRUE, FALSE, NA)), throwsError())
test.is.loaded.6 <- function() assertThat(is.loaded(integer(0)), throwsError())
test.is.loaded.7 <- function() assertThat(is.loaded(structure(integer(0), .Names = character(0))), throwsError())
test.is.loaded.8 <- function() assertThat(is.loaded(1:3), throwsError())
test.is.loaded.9 <- function() assertThat(is.loaded(c(1L, NA, 4L, NA, 999L)), throwsError())
test.is.loaded.10 <- function() assertThat(is.loaded(c(1L, 2L, 1073741824L, 1073741824L)), throwsError())
test.is.loaded.11 <- function() assertThat(is.loaded(numeric(0)), throwsError())
test.is.loaded.12 <- function() assertThat(is.loaded(c(3.14159, 6.28319, 9.42478, 12.5664, 15.708)), throwsError())
test.is.loaded.13 <- function() assertThat(is.loaded(c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708)), throwsError())
test.is.loaded.14 <- function() assertThat(is.loaded(structure(1:2, .Names = c("a", "b"))), throwsError())
test.is.loaded.15 <- function() assertThat(is.loaded(structure(c(1.5, 2.5), .Names = c("a", "b"))), throwsError())
test.is.loaded.16 <- function() assertThat(is.loaded(c(1.5, 1.51, 0, 1.49, -30)), throwsError())
test.is.loaded.17 <- function() assertThat(is.loaded(c(1.5, 1.51, 0, 1.49, -30, NA)), throwsError())
test.is.loaded.18 <- function() assertThat(is.loaded(c(1.5, 1.51, 0, 1.49, -30, NaN)), throwsError())
test.is.loaded.19 <- function() assertThat(is.loaded(c(1.5, 1.51, 0, 1.49, -30, Inf)), throwsError())
test.is.loaded.20 <- function() assertThat(is.loaded(c(1.5, 1.51, 0, 1.49, -30, -Inf)), throwsError())
test.is.loaded.21 <- function() assertThat(is.loaded(character(0)), throwsError())
test.is.loaded.22 <- function() assertThat(is.loaded(c("4.1", "blahh", "99.9", "-413", NA)), identicalTo(FALSE))
test.is.loaded.23 <- function() assertThat(is.loaded(complex(0)), throwsError())
test.is.loaded.24 <- function() assertThat(is.loaded(list(1, 2, 3)), throwsError())
test.is.loaded.25 <- function() assertThat(is.loaded(list(1, 2, NULL)), throwsError())
test.is.loaded.26 <- function() assertThat(is.loaded(list(1L, 2L, 3L)), throwsError())
test.is.loaded.27 <- function() assertThat(is.loaded(list(1L, 2L, NULL)), throwsError())
test.is.loaded.28 <- function() assertThat(is.loaded(list(1, 2, list(3, 4))), throwsError())
test.is.loaded.29 <- function() assertThat(is.loaded(list(3, "a", structure(list("b", z = list(TRUE, "c")), .Names = c("", "z")))), throwsError())
test.is.loaded.30 <- function() assertThat(is.loaded(structure(list(`NA` = 1, 2, b = 3), .Names = c(NA, "", "b"))), throwsError())
test.is.loaded.31 <- function() assertThat(is.loaded(pairlist(41, "a", 21L)), throwsError())
test.is.loaded.32 <- function() assertThat(is.loaded(pairlist(a = 41, 42)), throwsError())
test.is.loaded.33 <- function() assertThat(is.loaded(pairlist(a = 41, NULL)), throwsError())
test.is.loaded.34 <- function() assertThat(is.loaded(structure(1:12, .Dim = 3:4)), throwsError())
test.is.loaded.35 <- function() assertThat(is.loaded(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(    x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))), throwsError())
test.is.loaded.36 <- function() assertThat(is.loaded(structure(1:3, rando.attrib = 941L)), throwsError())
test.is.loaded.37 <- function() assertThat(is.loaded(structure(1:3, .Dim = 3L, .Dimnames = list(c("a", "b", "c")))), throwsError())
test.is.loaded.38 <- function() assertThat(is.loaded(structure(1:3, .Dim = 3L, .Dimnames = structure(list(    z = c("a", "b", "c")), .Names = "z"))), throwsError())
test.is.loaded.39 <- function() assertThat(is.loaded(structure(list("foo"), class = "foo")), throwsError())
test.is.loaded.40 <- function() assertThat(is.loaded(structure(list("bar"), class = "foo")), throwsError())
test.is.loaded.41 <- function() assertThat(is.loaded(quote(xyz)), throwsError())
test.is.loaded.42 <- function() assertThat(is.loaded(quote(sin(3.14))), throwsError())
test.is.loaded.43 <- function() assertThat(is.loaded(structure("foo", class = "foo")), identicalTo(FALSE))
test.is.loaded.44 <- function() assertThat(is.loaded(structure(list(1L, "bar"), class = "bar")), throwsError())
