#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2016 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-unary-tests.R using GNU R version 3.3.2 (2016-10-31)
library(hamcrest)
Sys.setlocale('LC_COLLATE', 'C')
as.ordered.foo <- function(...) 41L
as.vector.foo <- function(...) 99
Math.bar <- function(...) 44
Summary.bar <- function(...) 45
Ops.bar <- function(...) 46
test.as.ordered.1 <- function() assertThat(as.ordered(NULL), identicalTo(structure(integer(0), .Label = character(0), class = c("ordered", "factor"))))
test.as.ordered.2 <- function() assertThat(as.ordered(logical(0)), identicalTo(structure(integer(0), .Label = character(0), class = c("ordered", "factor"))))
test.as.ordered.3 <- function() assertThat(as.ordered(c(TRUE, TRUE, FALSE, FALSE, TRUE)), identicalTo(structure(c(2L, 2L, 1L, 1L, 2L), .Label = c("FALSE", "TRUE"), class = c("ordered", "factor"))))
test.as.ordered.4 <- function() assertThat(as.ordered(structure(c(TRUE, FALSE), .Names = c("a", ""))), identicalTo(structure(c(2L, 1L), .Names = c("a", ""), .Label = c("FALSE", "TRUE"), class = c("ordered", "factor"))))
test.as.ordered.5 <- function() assertThat(as.ordered(c(TRUE, FALSE, NA)), identicalTo(structure(c(2L, 1L, NA), .Label = c("FALSE", "TRUE"), class = c("ordered", "factor"))))
test.as.ordered.6 <- function() assertThat(as.ordered(integer(0)), identicalTo(structure(integer(0), .Label = character(0), class = c("ordered", "factor"))))
test.as.ordered.7 <- function() assertThat(as.ordered(structure(integer(0), .Names = character(0))), identicalTo(structure(integer(0), .Names = character(0), .Label = character(0), class = c("ordered", "factor"))))
test.as.ordered.8 <- function() assertThat(as.ordered(1:3), identicalTo(structure(1:3, .Label = c("1", "2", "3"), class = c("ordered", "factor"))))
test.as.ordered.9 <- function() assertThat(as.ordered(c(1L, NA, 4L, NA, 999L)), identicalTo(structure(c(1L, NA, 2L, NA, 3L), .Label = c("1", "4", "999"), class = c("ordered", "factor"))))
test.as.ordered.10 <- function() assertThat(as.ordered(c(1L, 2L, 1073741824L, 1073741824L)), identicalTo(structure(c(1L, 2L, 3L, 3L), .Label = c("1", "2", "1073741824"), class = c("ordered", "factor"))))
test.as.ordered.11 <- function() assertThat(as.ordered(numeric(0)), identicalTo(structure(integer(0), .Label = character(0), class = c("ordered", "factor"))))
test.as.ordered.12 <- function() assertThat(as.ordered(c(3.14159, 6.28319, 9.42478, 12.5664, 15.708)), identicalTo(structure(1:5, .Label = c("3.14159", "6.28319", "9.42478", "12.5664", "15.708"), class = c("ordered", "factor"))))
test.as.ordered.13 <- function() assertThat(as.ordered(c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708)), identicalTo(structure(c(5L, 4L, 3L, 2L, 1L), .Label = c("-15.708", "-12.5664", "-9.42478", "-6.28319", "-3.14159"), class = c("ordered", "factor"))))
test.as.ordered.14 <- function() assertThat(as.ordered(structure(1:2, .Names = c("a", "b"))), identicalTo(structure(1:2, .Names = c("a", "b"), .Label = c("1", "2"), class = c("ordered", "factor"))))
test.as.ordered.15 <- function() assertThat(as.ordered(structure(c(1.5, 2.5), .Names = c("a", "b"))), identicalTo(structure(1:2, .Names = c("a", "b"), .Label = c("1.5", "2.5"), class = c("ordered", "factor"))))
test.as.ordered.16 <- function() assertThat(as.ordered(c(1.5, 1.51, 0, 1.49, -30)), identicalTo(structure(c(4L, 5L, 2L, 3L, 1L), .Label = c("-30", "0", "1.49", "1.5", "1.51"), class = c("ordered", "factor"))))
test.as.ordered.17 <- function() assertThat(as.ordered(c(1.5, 1.51, 0, 1.49, -30, NA)), identicalTo(structure(c(4L, 5L, 2L, 3L, 1L, NA), .Label = c("-30", "0", "1.49", "1.5", "1.51"), class = c("ordered", "factor"))))
test.as.ordered.18 <- function() assertThat(as.ordered(c(1.5, 1.51, 0, 1.49, -30, NaN)), identicalTo(structure(c(4L, 5L, 2L, 3L, 1L, 6L), .Label = c("-30", "0", "1.49", "1.5", "1.51", "NaN"), class = c("ordered", "factor"))))
test.as.ordered.19 <- function() assertThat(as.ordered(c(1.5, 1.51, 0, 1.49, -30, Inf)), identicalTo(structure(c(4L, 5L, 2L, 3L, 1L, 6L), .Label = c("-30", "0", "1.49", "1.5", "1.51", "Inf"), class = c("ordered", "factor"))))
test.as.ordered.20 <- function() assertThat(as.ordered(c(1.5, 1.51, 0, 1.49, -30, -Inf)), identicalTo(structure(c(5L, 6L, 3L, 4L, 2L, 1L), .Label = c("-Inf", "-30", "0", "1.49", "1.5", "1.51"), class = c("ordered", "factor"))))
test.as.ordered.21 <- function() assertThat(as.ordered(character(0)), identicalTo(structure(integer(0), .Label = character(0), class = c("ordered", "factor"))))
test.as.ordered.22 <- function() assertThat(as.ordered(c("4.1", "blahh", "99.9", "-413", NA)), identicalTo(structure(c(2L, 4L, 3L, 1L, NA), .Label = c("-413", "4.1", "99.9", "blahh"), class = c("ordered", "factor"))))
test.as.ordered.23 <- function() assertThat(as.ordered(complex(0)), identicalTo(structure(integer(0), .Label = character(0), class = c("ordered", "factor"))))
test.as.ordered.24 <- function() assertThat(as.ordered(list(1, 2, 3)), throwsError())
test.as.ordered.25 <- function() assertThat(as.ordered(list(1, 2, NULL)), throwsError())
test.as.ordered.26 <- function() assertThat(as.ordered(list(1L, 2L, 3L)), throwsError())
test.as.ordered.27 <- function() assertThat(as.ordered(list(1L, 2L, NULL)), throwsError())
test.as.ordered.28 <- function() assertThat(as.ordered(list(1, 2, list(3, 4))), throwsError())
test.as.ordered.29 <- function() assertThat(as.ordered(list(3, "a", structure(list("b", z = list(TRUE, "c")), .Names = c("", "z")))), throwsError())
test.as.ordered.30 <- function() assertThat(as.ordered(structure(list(`NA` = 1, 2, b = 3), .Names = c(NA, "", "b"))), throwsError())
test.as.ordered.31 <- function() assertThat(as.ordered(pairlist(41, "a", 21L)), throwsError())
test.as.ordered.32 <- function() assertThat(as.ordered(pairlist(a = 41, 42)), throwsError())
test.as.ordered.33 <- function() assertThat(as.ordered(pairlist(a = 41, NULL)), throwsError())
test.as.ordered.34 <- function() assertThat(as.ordered(structure(1:12, .Dim = 3:4)), identicalTo(structure(1:12, .Label = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"), class = c("ordered", "factor"))))
test.as.ordered.35 <- function() assertThat(as.ordered(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(    x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))), identicalTo(structure(1:12, .Label = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"), class = c("ordered", "factor"))))
test.as.ordered.36 <- function() assertThat(as.ordered(structure(1:3, rando.attrib = 941L)), identicalTo(structure(1:3, .Label = c("1", "2", "3"), class = c("ordered", "factor"))))
test.as.ordered.37 <- function() assertThat(as.ordered(structure(1:3, .Dim = 3L, .Dimnames = list(c("a", "b", "c")))), identicalTo(structure(1:3, .Names = c("a", "b", "c"), .Label = c("1", "2", "3"), class = c("ordered", "factor"))))
test.as.ordered.38 <- function() assertThat(as.ordered(structure(1:3, .Dim = 3L, .Dimnames = structure(list(    z = c("a", "b", "c")), .Names = "z"))), identicalTo(structure(1:3, .Names = c("a", "b", "c"), .Label = c("1", "2", "3"), class = c("ordered", "factor"))))
test.as.ordered.39 <- function() assertThat(as.ordered(structure(list("foo"), class = "foo")), throwsError())
test.as.ordered.40 <- function() assertThat(as.ordered(structure(list("bar"), class = "foo")), throwsError())
test.as.ordered.41 <- function() assertThat(as.ordered(quote(xyz)), throwsError())
test.as.ordered.42 <- function() assertThat(as.ordered(quote(sin(3.14))), throwsError())
test.as.ordered.43 <- function() assertThat(as.ordered(structure("foo", class = "foo")), identicalTo(structure(NA_integer_, .Label = "foo", class = c("ordered", "factor"))))
test.as.ordered.44 <- function() assertThat(as.ordered(structure(list(1L, "bar"), class = "bar")), throwsError())
