#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2016 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-math-unary-tests.R using GNU R version 3.2.0 (2015-04-16)
library(hamcrest)
sign.foo <- function(...) 41
Math.bar <- function(...) 44
test.sign.1 <- function() assertThat(sign(-0.01), identicalTo(-1))
test.sign.2 <- function() assertThat(sign(-0.1), identicalTo(-1))
test.sign.3 <- function() assertThat(sign(-1), identicalTo(-1))
test.sign.4 <- function() assertThat(sign(-1.5), identicalTo(-1))
test.sign.5 <- function() assertThat(sign(-2), identicalTo(-1))
test.sign.6 <- function() assertThat(sign(-2.5), identicalTo(-1))
test.sign.7 <- function() assertThat(sign(-4), identicalTo(-1))
test.sign.8 <- function() assertThat(sign(-10), identicalTo(-1))
test.sign.9 <- function() assertThat(sign(-100), identicalTo(-1))
test.sign.10 <- function() assertThat(sign(-0.785398), identicalTo(-1))
test.sign.11 <- function() assertThat(sign(-1.5708), identicalTo(-1))
test.sign.12 <- function() assertThat(sign(-3.14159), identicalTo(-1))
test.sign.13 <- function() assertThat(sign(-6.28319), identicalTo(-1))
test.sign.14 <- function() assertThat(sign(0.01), identicalTo(1))
test.sign.15 <- function() assertThat(sign(0.1), identicalTo(1))
test.sign.16 <- function() assertThat(sign(1), identicalTo(1))
test.sign.17 <- function() assertThat(sign(1.5), identicalTo(1))
test.sign.18 <- function() assertThat(sign(2), identicalTo(1))
test.sign.19 <- function() assertThat(sign(2.5), identicalTo(1))
test.sign.20 <- function() assertThat(sign(4), identicalTo(1))
test.sign.21 <- function() assertThat(sign(10), identicalTo(1))
test.sign.22 <- function() assertThat(sign(100), identicalTo(1))
test.sign.23 <- function() assertThat(sign(0.785398), identicalTo(1))
test.sign.24 <- function() assertThat(sign(1.5708), identicalTo(1))
test.sign.25 <- function() assertThat(sign(3.14159), identicalTo(1))
test.sign.26 <- function() assertThat(sign(6.28319), identicalTo(1))
test.sign.27 <- function() assertThat(sign(NULL), throwsError())
test.sign.28 <- function() assertThat(sign(c(0.01, 0.1, 1, 1.5)), identicalTo(c(1, 1, 1, 1)))
test.sign.29 <- function() assertThat(sign(integer(0)), identicalTo(numeric(0)))
test.sign.30 <- function() assertThat(sign(numeric(0)), identicalTo(numeric(0)))
test.sign.31 <- function() assertThat(sign(NaN), identicalTo(NaN))
test.sign.32 <- function() assertThat(sign(NA_real_), identicalTo(NA_real_))
test.sign.33 <- function() assertThat(sign(Inf), identicalTo(1))
test.sign.34 <- function() assertThat(sign(-Inf), identicalTo(-1))
test.sign.35 <- function() assertThat(sign(c(1L, 4L)), identicalTo(c(1, 1)))
test.sign.36 <- function() assertThat(sign(structure(1, class = "foo")), identicalTo(41))
test.sign.37 <- function() assertThat(sign(structure(1, class = "bar")), identicalTo(44))
test.sign.38 <- function() assertThat(sign(structure(list("a"), class = "foo")), identicalTo(41))
test.sign.39 <- function() assertThat(sign(structure(list("b"), class = "bar")), identicalTo(44))
test.sign.40 <- function() assertThat(sign(structure(c(1, 2, 3), .Names = c("a", "b", "c"))), identicalTo(structure(c(1, 1, 1), .Names = c("a", "b", "c"))))
test.sign.41 <- function() assertThat(sign(structure(c(1, 2), .Names = c("x", ""))), identicalTo(structure(c(1, 1), .Names = c("x", ""))))
test.sign.42 <- function() assertThat(sign(structure(1:12, .Dim = 3:4)), identicalTo(structure(c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1), .Dim = 3:4)))
test.sign.43 <- function() assertThat(sign(structure(0, rando.attr = 4L)), identicalTo(structure(0, rando.attr = 4L)))
test.sign.44 <- function() assertThat(sign(structure(0, class = "zinga")), identicalTo(structure(0, class = "zinga")))
