library(hamcrest)
as.call.foo <- function(x) 41
Math.bar <- function(x) 44
test.as.call.1 <- function() assertThat(as.call(NULL), throwsError())
test.as.call.2 <- function() assertThat(as.call(logical(0)), throwsError())
test.as.call.3 <- function() assertThat(as.call(c(TRUE, TRUE, FALSE, FALSE, TRUE)), throwsError())
test.as.call.4 <- function() assertThat(as.call(structure(c(TRUE, FALSE), .Names = c("a", ""))), throwsError())
test.as.call.5 <- function() assertThat(as.call(c(TRUE, FALSE, NA)), throwsError())
test.as.call.6 <- function() assertThat(as.call(integer(0)), throwsError())
test.as.call.7 <- function() assertThat(as.call(structure(integer(0), .Names = character(0))), throwsError())
test.as.call.8 <- function() assertThat(as.call(1:3), throwsError())
test.as.call.9 <- function() assertThat(as.call(c(1L, NA, 4L, NA, 999L)), throwsError())
test.as.call.10 <- function() assertThat(as.call(c(1L, 2L, 1073741824L, 1073741824L)), throwsError())
test.as.call.11 <- function() assertThat(as.call(numeric(0)), throwsError())
test.as.call.12 <- function() assertThat(as.call(c(3.14159, 6.28319, 9.42478, 12.5664, 15.708)), throwsError())
test.as.call.13 <- function() assertThat(as.call(c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708)), throwsError())
test.as.call.14 <- function() assertThat(as.call(structure(1:2, .Names = c("a", "b"))), throwsError())
test.as.call.15 <- function() assertThat(as.call(structure(c(1.5, 2.5), .Names = c("a", "b"))), throwsError())
test.as.call.16 <- function() assertThat(as.call(character(0)), throwsError())
test.as.call.17 <- function() assertThat(as.call(c("4.1", "blahh", "99.9", "-413", NA)), throwsError())
test.as.call.18 <- function() assertThat(as.call(list(1, 2, 3)), identicalTo(1(2, 3)))
test.as.call.19 <- function() assertThat(as.call(list(1, 2, NULL)), identicalTo(1(2, NULL)))
test.as.call.20 <- function() assertThat(as.call(list(1L, 2L, 3L)), identicalTo(1L(2L, 3L)))
test.as.call.21 <- function() assertThat(as.call(list(1L, 2L, NULL)), identicalTo(1L(2L, NULL)))
test.as.call.22 <- function() assertThat(as.call(list(1, 2, list(3, 4))), identicalTo(1(2, list(3, 4))))
test.as.call.23 <- function() assertThat(as.call(structure(1:12, .Dim = 3:4)), throwsError())
test.as.call.24 <- function() assertThat(as.call(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(    x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))), throwsError())
test.as.call.25 <- function() assertThat(as.call(structure(1:3, rando.attrib = 941L)), throwsError())
test.as.call.26 <- function() assertThat(as.call(structure(1:3, .Dim = 3L, .Dimnames = list(c("a", "b", "c")))), throwsError())
test.as.call.27 <- function() assertThat(as.call(structure(list("foo"), class = "foo")), identicalTo("foo"()))
test.as.call.28 <- function() assertThat(as.call(structure(list("bar"), class = "foo")), identicalTo("bar"()))
test.as.call.29 <- function() assertThat(as.call(xyz), throwsError())
test.as.call.30 <- function() assertThat(as.call(sin(3.14)), throwsError())
test.as.call.31 <- function() assertThat(as.call(structure("foo", class = "foo")), throwsError())
test.as.call.32 <- function() assertThat(as.call(structure(list(1L, "bar"), class = "bar")), identicalTo(1L("bar")))
