#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2016 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-unary-tests.R using GNU R version 3.3.1 (2016-06-21)
library(hamcrest)
Sys.setlocale('LC_COLLATE', 'C')
is.character.foo <- function(...) 41L
as.vector.foo <- function(...) 99
Math.bar <- function(...) 44
Summary.bar <- function(...) 45
Ops.bar <- function(...) 46
test.is.character.1 <- function() assertThat(is.character(NULL), identicalTo(FALSE))
test.is.character.2 <- function() assertThat(is.character(logical(0)), identicalTo(FALSE))
test.is.character.3 <- function() assertThat(is.character(c(TRUE, TRUE, FALSE, FALSE, TRUE)), identicalTo(FALSE))
test.is.character.4 <- function() assertThat(is.character(structure(c(TRUE, FALSE), .Names = c("a", ""))), identicalTo(FALSE))
test.is.character.5 <- function() assertThat(is.character(c(TRUE, FALSE, NA)), identicalTo(FALSE))
test.is.character.6 <- function() assertThat(is.character(integer(0)), identicalTo(FALSE))
test.is.character.7 <- function() assertThat(is.character(structure(integer(0), .Names = character(0))), identicalTo(FALSE))
test.is.character.8 <- function() assertThat(is.character(1:3), identicalTo(FALSE))
test.is.character.9 <- function() assertThat(is.character(c(1L, NA, 4L, NA, 999L)), identicalTo(FALSE))
test.is.character.10 <- function() assertThat(is.character(c(1L, 2L, 1073741824L, 1073741824L)), identicalTo(FALSE))
test.is.character.11 <- function() assertThat(is.character(numeric(0)), identicalTo(FALSE))
test.is.character.12 <- function() assertThat(is.character(c(3.14159, 6.28319, 9.42478, 12.5664, 15.708)), identicalTo(FALSE))
test.is.character.13 <- function() assertThat(is.character(c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708)), identicalTo(FALSE))
test.is.character.14 <- function() assertThat(is.character(structure(1:2, .Names = c("a", "b"))), identicalTo(FALSE))
test.is.character.15 <- function() assertThat(is.character(structure(c(1.5, 2.5), .Names = c("a", "b"))), identicalTo(FALSE))
test.is.character.16 <- function() assertThat(is.character(c(1.5, 1.51, 0, 1.49, -30)), identicalTo(FALSE))
test.is.character.17 <- function() assertThat(is.character(c(1.5, 1.51, 0, 1.49, -30, NA)), identicalTo(FALSE))
test.is.character.18 <- function() assertThat(is.character(c(1.5, 1.51, 0, 1.49, -30, NaN)), identicalTo(FALSE))
test.is.character.19 <- function() assertThat(is.character(c(1.5, 1.51, 0, 1.49, -30, Inf)), identicalTo(FALSE))
test.is.character.20 <- function() assertThat(is.character(c(1.5, 1.51, 0, 1.49, -30, -Inf)), identicalTo(FALSE))
test.is.character.21 <- function() assertThat(is.character(character(0)), identicalTo(TRUE))
test.is.character.22 <- function() assertThat(is.character(c("4.1", "blahh", "99.9", "-413", NA)), identicalTo(TRUE))
test.is.character.23 <- function() assertThat(is.character(complex(0)), identicalTo(FALSE))
test.is.character.24 <- function() assertThat(is.character(list(1, 2, 3)), identicalTo(FALSE))
test.is.character.25 <- function() assertThat(is.character(list(1, 2, NULL)), identicalTo(FALSE))
test.is.character.26 <- function() assertThat(is.character(list(1L, 2L, 3L)), identicalTo(FALSE))
test.is.character.27 <- function() assertThat(is.character(list(1L, 2L, NULL)), identicalTo(FALSE))
test.is.character.28 <- function() assertThat(is.character(list(1, 2, list(3, 4))), identicalTo(FALSE))
test.is.character.29 <- function() assertThat(is.character(list(3, "a", structure(list("b", z = list(TRUE,     "c")), .Names = c("", "z")))), identicalTo(FALSE))
test.is.character.30 <- function() assertThat(is.character(structure(list(`NA` = 1, 2, b = 3), .Names = c(NA, "", "b"))), identicalTo(FALSE))
test.is.character.31 <- function() assertThat(is.character(pairlist(41, "a", 21L)), identicalTo(FALSE))
test.is.character.32 <- function() assertThat(is.character(pairlist(a = 41, 42)), identicalTo(FALSE))
test.is.character.33 <- function() assertThat(is.character(pairlist(a = 41, NULL)), identicalTo(FALSE))
test.is.character.34 <- function() assertThat(is.character(structure(1:12, .Dim = 3:4)), identicalTo(FALSE))
test.is.character.35 <- function() assertThat(is.character(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(    x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))), identicalTo(FALSE))
test.is.character.36 <- function() assertThat(is.character(structure(1:3, rando.attrib = 941L)), identicalTo(FALSE))
test.is.character.37 <- function() assertThat(is.character(structure(1:3, .Dim = 3L, .Dimnames = list(c("a", "b", "c")))), identicalTo(FALSE))
test.is.character.38 <- function() assertThat(is.character(structure(1:3, .Dim = 3L, .Dimnames = structure(list(    z = c("a", "b", "c")), .Names = "z"))), identicalTo(FALSE))
test.is.character.39 <- function() assertThat(is.character(structure(list("foo"), class = "foo")), identicalTo(FALSE))
test.is.character.40 <- function() assertThat(is.character(structure(list("bar"), class = "foo")), identicalTo(FALSE))
test.is.character.41 <- function() assertThat(is.character(quote(xyz)), identicalTo(FALSE))
test.is.character.42 <- function() assertThat(is.character(quote(sin(3.14))), identicalTo(FALSE))
test.is.character.43 <- function() assertThat(is.character(structure("foo", class = "foo")), identicalTo(TRUE))
test.is.character.44 <- function() assertThat(is.character(structure(list(1L, "bar"), class = "bar")), identicalTo(FALSE))
