#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2016 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-dist-tests.R using GNU R version 3.3.1 (2016-06-21)
library(hamcrest)
library(stats)
set.seed(1)
test.rgeom.1 <- function() assertThat({set.seed(1);rgeom(n = 0x1p+0, prob = c(0x1.999999999999ap-4, 0x1p-1, 0x1p+0))}, identicalTo(6L))
test.rgeom.2 <- function() assertThat({set.seed(1);rgeom(n = 1:5, prob = c(0x1.999999999999ap-4, 0x1p-1, 0x1p+0))}, identicalTo(c(6L, 1L, 0L, 5L, 2L)))
test.rgeom.3 <- function() assertThat({set.seed(1);rgeom(n = 0x1.ep+3, prob = c(0x1.999999999999ap-4, 0x1p-1, 0x1p+0))}, identicalTo(c(6L, 1L, 0L, 5L, 2L, 0L, 13L, 1L, 0L, 37L, 1L, 0L, 7L, 0L, 0L)))
test.rgeom.4 <- function() assertThat({set.seed(1);rgeom(n = numeric(0), prob = c(0x1.999999999999ap-4, 0x1p-1, 0x1p+0))}, identicalTo(integer(0)))
test.rgeom.5 <- function() assertThat({set.seed(1);rgeom(n = 0x1.8p+1, prob = c(NA, 0x1p-1, 0x1p+0))}, identicalTo(c(NA, 0L, 0L)))
