#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2016 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-unary-tests.R using GNU R version 3.3.2 (2016-10-31)
library(hamcrest)
Sys.setlocale('LC_COLLATE', 'C')
is.function.foo <- function(...) 41L
as.vector.foo <- function(...) 99
Math.bar <- function(...) 44
Summary.bar <- function(...) 45
Ops.bar <- function(...) 46
test.is.function.1 <- function() assertThat(is.function(NULL), identicalTo(FALSE))
test.is.function.2 <- function() assertThat(is.function(logical(0)), identicalTo(FALSE))
test.is.function.3 <- function() assertThat(is.function(c(TRUE, TRUE, FALSE, FALSE, TRUE)), identicalTo(FALSE))
test.is.function.4 <- function() assertThat(is.function(structure(c(TRUE, FALSE), .Names = c("a", ""))), identicalTo(FALSE))
test.is.function.5 <- function() assertThat(is.function(c(TRUE, FALSE, NA)), identicalTo(FALSE))
test.is.function.6 <- function() assertThat(is.function(integer(0)), identicalTo(FALSE))
test.is.function.7 <- function() assertThat(is.function(structure(integer(0), .Names = character(0))), identicalTo(FALSE))
test.is.function.8 <- function() assertThat(is.function(1:3), identicalTo(FALSE))
test.is.function.9 <- function() assertThat(is.function(c(1L, NA, 4L, NA, 999L)), identicalTo(FALSE))
test.is.function.10 <- function() assertThat(is.function(c(1L, 2L, 1073741824L, 1073741824L)), identicalTo(FALSE))
test.is.function.11 <- function() assertThat(is.function(numeric(0)), identicalTo(FALSE))
test.is.function.12 <- function() assertThat(is.function(c(3.14159, 6.28319, 9.42478, 12.5664, 15.708)), identicalTo(FALSE))
test.is.function.13 <- function() assertThat(is.function(c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708)), identicalTo(FALSE))
test.is.function.14 <- function() assertThat(is.function(structure(1:2, .Names = c("a", "b"))), identicalTo(FALSE))
test.is.function.15 <- function() assertThat(is.function(structure(c(1.5, 2.5), .Names = c("a", "b"))), identicalTo(FALSE))
test.is.function.16 <- function() assertThat(is.function(c(1.5, 1.51, 0, 1.49, -30)), identicalTo(FALSE))
test.is.function.17 <- function() assertThat(is.function(c(1.5, 1.51, 0, 1.49, -30, NA)), identicalTo(FALSE))
test.is.function.18 <- function() assertThat(is.function(c(1.5, 1.51, 0, 1.49, -30, NaN)), identicalTo(FALSE))
test.is.function.19 <- function() assertThat(is.function(c(1.5, 1.51, 0, 1.49, -30, Inf)), identicalTo(FALSE))
test.is.function.20 <- function() assertThat(is.function(c(1.5, 1.51, 0, 1.49, -30, -Inf)), identicalTo(FALSE))
test.is.function.21 <- function() assertThat(is.function(character(0)), identicalTo(FALSE))
test.is.function.22 <- function() assertThat(is.function(c("4.1", "blahh", "99.9", "-413", NA)), identicalTo(FALSE))
test.is.function.23 <- function() assertThat(is.function(complex(0)), identicalTo(FALSE))
test.is.function.24 <- function() assertThat(is.function(list(1, 2, 3)), identicalTo(FALSE))
test.is.function.25 <- function() assertThat(is.function(list(1, 2, NULL)), identicalTo(FALSE))
test.is.function.26 <- function() assertThat(is.function(list(1L, 2L, 3L)), identicalTo(FALSE))
test.is.function.27 <- function() assertThat(is.function(list(1L, 2L, NULL)), identicalTo(FALSE))
test.is.function.28 <- function() assertThat(is.function(list(1, 2, list(3, 4))), identicalTo(FALSE))
test.is.function.29 <- function() assertThat(is.function(list(3, "a", structure(list("b", z = list(TRUE, "c")), .Names = c("", "z")))), identicalTo(FALSE))
test.is.function.30 <- function() assertThat(is.function(structure(list(`NA` = 1, 2, b = 3), .Names = c(NA, "", "b"))), identicalTo(FALSE))
test.is.function.31 <- function() assertThat(is.function(pairlist(41, "a", 21L)), identicalTo(FALSE))
test.is.function.32 <- function() assertThat(is.function(pairlist(a = 41, 42)), identicalTo(FALSE))
test.is.function.33 <- function() assertThat(is.function(pairlist(a = 41, NULL)), identicalTo(FALSE))
test.is.function.34 <- function() assertThat(is.function(structure(1:12, .Dim = 3:4)), identicalTo(FALSE))
test.is.function.35 <- function() assertThat(is.function(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(    x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))), identicalTo(FALSE))
test.is.function.36 <- function() assertThat(is.function(structure(1:3, rando.attrib = 941L)), identicalTo(FALSE))
test.is.function.37 <- function() assertThat(is.function(structure(1:3, .Dim = 3L, .Dimnames = list(c("a", "b", "c")))), identicalTo(FALSE))
test.is.function.38 <- function() assertThat(is.function(structure(1:3, .Dim = 3L, .Dimnames = structure(list(    z = c("a", "b", "c")), .Names = "z"))), identicalTo(FALSE))
test.is.function.39 <- function() assertThat(is.function(structure(list("foo"), class = "foo")), identicalTo(FALSE))
test.is.function.40 <- function() assertThat(is.function(structure(list("bar"), class = "foo")), identicalTo(FALSE))
test.is.function.41 <- function() assertThat(is.function(quote(xyz)), identicalTo(FALSE))
test.is.function.42 <- function() assertThat(is.function(quote(sin(3.14))), identicalTo(FALSE))
test.is.function.43 <- function() assertThat(is.function("NaN"), identicalTo(FALSE))
test.is.function.44 <- function() assertThat(is.function("NABOOM!"), identicalTo(FALSE))
test.is.function.45 <- function() assertThat(is.function("NaNaNabooboo"), identicalTo(FALSE))
test.is.function.46 <- function() assertThat(is.function("-Inf"), identicalTo(FALSE))
test.is.function.47 <- function() assertThat(is.function("+Infinity"), identicalTo(FALSE))
test.is.function.48 <- function() assertThat(is.function("Infinity and beyond!"), identicalTo(FALSE))
test.is.function.49 <- function() assertThat(is.function("Infi"), identicalTo(FALSE))
test.is.function.50 <- function() assertThat(is.function("0.03f"), identicalTo(FALSE))
test.is.function.51 <- function() assertThat(is.function("  0.0330   "), identicalTo(FALSE))
test.is.function.52 <- function() assertThat(is.function(structure("foo", class = "foo")), identicalTo(FALSE))
test.is.function.53 <- function() assertThat(is.function(structure(list(1L, "bar"), class = "bar")), identicalTo(FALSE))
