#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2019 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by generate-apply-tests.R using GNU R version 3.2.0 (2015-04-16)
library(hamcrest)
f1 <- function(x) x
f2 <- function(x) x*2
f3 <- function(x) NULL
test.lapply.1 <- function() assertThat(lapply(integer(0), "f1"), identicalTo(list()))
test.lapply.2 <- function() assertThat(lapply(integer(0), "f2"), identicalTo(list()))
test.lapply.3 <- function() assertThat(lapply(integer(0), "f3"), identicalTo(list()))
test.lapply.4 <- function() assertThat(lapply(1:15, "f1"), identicalTo(list(1L, 2L, 3L, 4L, 5L, 6L, 7L, 8L, 9L, 10L, 11L, 12L, 13L,     14L, 15L)))
test.lapply.5 <- function() assertThat(lapply(1:15, "f2"), identicalTo(list(2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30)))
test.lapply.6 <- function() assertThat(lapply(1:15, "f3"), identicalTo(list(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,     NULL, NULL, NULL, NULL, NULL)))
test.lapply.7 <- function() assertThat(lapply(character(0), "f1"), identicalTo(list()))
test.lapply.8 <- function() assertThat(lapply(character(0), "f2"), identicalTo(list()))
test.lapply.9 <- function() assertThat(lapply(character(0), "f3"), identicalTo(list()))
test.lapply.10 <- function() assertThat(lapply(c("a", "b", "c", "d"), "f1"), identicalTo(list("a", "b", "c", "d")))
test.lapply.11 <- function() assertThat(lapply(c("a", "b", "c", "d"), "f2"), throwsError())
test.lapply.12 <- function() assertThat(lapply(c("a", "b", "c", "d"), "f3"), identicalTo(list(NULL, NULL, NULL, NULL)))
test.lapply.13 <- function() assertThat(lapply(structure(c("a", "b"), .Names = c("x", "y")), "f1"), identicalTo(structure(list(x = "a", y = "b"), .Names = c("x", "y"))))
test.lapply.14 <- function() assertThat(lapply(structure(c("a", "b"), .Names = c("x", "y")), "f2"), throwsError())
test.lapply.15 <- function() assertThat(lapply(structure(c("a", "b"), .Names = c("x", "y")), "f3"), identicalTo(structure(list(x = NULL, y = NULL), .Names = c("x", "y"))))
test.lapply.16 <- function() assertThat(lapply(list(), "f1"), identicalTo(list()))
test.lapply.17 <- function() assertThat(lapply(list(), "f2"), identicalTo(list()))
test.lapply.18 <- function() assertThat(lapply(list(), "f3"), identicalTo(list()))
test.lapply.19 <- function() assertThat(lapply(structure(list(a = 1, b = 2), .Names = c("a", "b")), "f1"), identicalTo(structure(list(a = 1, b = 2), .Names = c("a", "b"))))
test.lapply.20 <- function() assertThat(lapply(structure(list(a = 1, b = 2), .Names = c("a", "b")), "f2"), identicalTo(structure(list(a = 2, b = 4), .Names = c("a", "b"))))
test.lapply.21 <- function() assertThat(lapply(structure(list(a = 1, b = 2), .Names = c("a", "b")), "f3"), identicalTo(structure(list(a = NULL, b = NULL), .Names = c("a", "b"))))
test.lapply.22 <- function() assertThat(lapply(structure(1:12, .Dim = 3:4), "f1"), identicalTo(list(1L, 2L, 3L, 4L, 5L, 6L, 7L, 8L, 9L, 10L, 11L, 12L)))
test.lapply.23 <- function() assertThat(lapply(structure(1:12, .Dim = 3:4), "f2"), identicalTo(list(2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24)))
test.lapply.24 <- function() assertThat(lapply(structure(1:12, .Dim = 3:4), "f3"), identicalTo(list(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,     NULL, NULL)))
