#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2018 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-dist-tests.R using GNU R version 3.3.1 (2016-06-21)
library(hamcrest)
library(stats)
set.seed(1)
test.rcauchy.1 <- function() assertThat({set.seed(1);rcauchy(n = 0x1p+0, location = c(0x0p+0, -0x1p+1), scale = c(0x0p+0, 0x1p-1, 0x1p+0, 0x1p+1))}, identicalTo(0x0p+0))
test.rcauchy.2 <- function() assertThat({set.seed(1);rcauchy(n = 1:5, location = c(0x0p+0, -0x1p+1), scale = c(0x0p+0, 0x1p-1, 0x1p+0, 0x1p+1))}, identicalTo(c(0x0p+0, -0x1.72e0a0b80357fp+0, 0x1.2d4a522fd8097p+1, -0x1.52ba636d7d983p+3, 0x0p+0), tol = 0.000100))
test.rcauchy.3 <- function() assertThat({set.seed(1);rcauchy(n = 0x1.ep+3, location = c(0x0p+0, -0x1p+1), scale = c(0x0p+0, 0x1p-1, 0x1p+0, 0x1p+1))}, identicalTo(c(0x0p+0, -0x1.72e0a0b80357fp+0, 0x1.2d4a522fd8097p+1, -0x1.52ba636d7d983p+3, 0x0p+0, -0x1.12fc311089676p+1, 0x1.7823a22701e7ap-1, -0x1.549d16e5b9976p+1, 0x0p+0, -0x1.0b3cb14612b8ap+1, -0x1.cee904beced09p+0, -0x1.aa105d3584364p+2, 0x0p+0, -0x1.e6d662fc9d07ep+0, 0x1.82e09f9ecfcccp-1), tol = 0.000100))
test.rcauchy.4 <- function() assertThat({set.seed(1);rcauchy(n = numeric(0), location = c(0x0p+0, -0x1p+1), scale = c(0x0p+0, 0x1p-1, 0x1p+0, 0x1p+1))}, identicalTo(numeric(0)))
test.rcauchy.5 <- function() assertThat({set.seed(1);rcauchy(n = 0x1.8p+1, location = c(NA, -0x1p+1), scale = c(0x0p+0, 0x1p-1, 0x1p+0, 0x1p+1))}, identicalTo(c(NaN, -0x1.72e0a0b80357fp+0, NaN)))
