#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2016 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-unary-tests.R using GNU R version 3.2.0 (2015-04-16)
library(hamcrest)
Mod.foo <- function(...) 41
Complex.bar <- function(...) 45
test.Mod.1 <- function() assertThat(Mod(NULL), throwsError())
test.Mod.2 <- function() assertThat(Mod(logical(0)), identicalTo(numeric(0)))
test.Mod.3 <- function() assertThat(Mod(c(TRUE, TRUE, FALSE, FALSE, TRUE)), identicalTo(c(1, 1, 0, 0, 1)))
test.Mod.4 <- function() assertThat(Mod(structure(c(TRUE, FALSE), .Names = c("a", ""))), identicalTo(structure(c(1, 0), .Names = c("a", ""))))
test.Mod.5 <- function() assertThat(Mod(c(TRUE, FALSE, NA)), identicalTo(c(1, 0, NA)))
test.Mod.6 <- function() assertThat(Mod(integer(0)), identicalTo(numeric(0)))
test.Mod.7 <- function() assertThat(Mod(structure(integer(0), .Names = character(0))), identicalTo(structure(numeric(0), .Names = character(0))))
test.Mod.8 <- function() assertThat(Mod(1:3), identicalTo(c(1, 2, 3)))
test.Mod.9 <- function() assertThat(Mod(c(1L, NA, 4L, NA, 999L)), identicalTo(c(1, NA, 4, NA, 999)))
test.Mod.10 <- function() assertThat(Mod(c(1L, 2L, 1073741824L, 1073741824L)), identicalTo(c(1, 2, 1073741824, 1073741824), tol = 0.000100))
test.Mod.11 <- function() assertThat(Mod(numeric(0)), identicalTo(numeric(0)))
test.Mod.12 <- function() assertThat(Mod(NaN), identicalTo(NaN))
test.Mod.13 <- function() assertThat(Mod(NA_real_), identicalTo(NA_real_))
test.Mod.14 <- function() assertThat(Mod(1), identicalTo(1))
test.Mod.15 <- function() assertThat(Mod(1.5), identicalTo(1.5, tol = 0.000100))
test.Mod.16 <- function() assertThat(Mod(-1.5), identicalTo(1.5, tol = 0.000100))
test.Mod.17 <- function() assertThat(Mod(3.14), identicalTo(3.14, tol = 0.000100))
test.Mod.18 <- function() assertThat(Mod(Inf), identicalTo(Inf))
test.Mod.19 <- function() assertThat(Mod(-Inf), identicalTo(Inf))
test.Mod.20 <- function() assertThat(Mod(complex(0)), identicalTo(numeric(0)))
test.Mod.21 <- function() assertThat(Mod(structure(complex(0), .Names = character(0))), identicalTo(structure(numeric(0), .Names = character(0))))
test.Mod.22 <- function() assertThat(Mod(NA_complex_), identicalTo(NA_real_))
test.Mod.23 <- function() assertThat(Mod(NA_complex_), identicalTo(NA_real_))
test.Mod.24 <- function() assertThat(Mod(1.5+3i), identicalTo(3.35410196624968, tol = 0.000100))
test.Mod.25 <- function() assertThat(Mod(1.5-3i), identicalTo(3.35410196624968, tol = 0.000100))
test.Mod.26 <- function() assertThat(Mod(-1.5+3i), identicalTo(3.35410196624968, tol = 0.000100))
test.Mod.27 <- function() assertThat(Mod(1.5-3i), identicalTo(3.35410196624968, tol = 0.000100))
test.Mod.28 <- function() assertThat(Mod(structure(c(3+4i, 9+2i), .Names = c("a", "b"))), identicalTo(structure(c(5, 9.21954445729289), .Names = c("a", "b")), tol = 0.000100))
test.Mod.29 <- function() assertThat(Mod(structure(5+9i, rando.attr = "bazinga", class = "zarg")), identicalTo(structure(10.295630140987, rando.attr = "bazinga", class = "zarg"), tol = 0.000100))
test.Mod.30 <- function() assertThat(Mod(character(0)), throwsError())
test.Mod.31 <- function() assertThat(Mod(c("4.1", "blahh", "99.9", "-413", NA)), throwsError())
test.Mod.32 <- function() assertThat(Mod(list(1)), throwsError())
test.Mod.33 <- function() assertThat(Mod(structure(1:12, .Dim = 3:4)), identicalTo(structure(c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12), .Dim = 3:4)))
test.Mod.34 <- function() assertThat(Mod(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))), identicalTo(structure(c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12), .Dim = 3:4, .Dimnames = structure(list(    x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))))
test.Mod.35 <- function() assertThat(Mod(structure(1:3, rando.attrib = 941L)), identicalTo(structure(c(1, 2, 3), rando.attrib = 941L)))
test.Mod.36 <- function() assertThat(Mod(structure(c(1+4.5i, 2+4.5i, 3+4.5i), .Dim = 3L, .Dimnames = list(    c("a", "b", "c")))), identicalTo(structure(c(4.60977222864644, 4.92442890089805, 5.40832691319598), .Dim = 3L, .Dimnames = list(c("a", "b", "c"))), tol = 0.000100))
test.Mod.37 <- function() assertThat(Mod(structure(list("foo"), class = "foo")), identicalTo(41))
test.Mod.38 <- function() assertThat(Mod(structure(list("bar"), class = "foo")), identicalTo(41))
test.Mod.39 <- function() assertThat(Mod(structure("foo", class = "foo")), identicalTo(41))
test.Mod.40 <- function() assertThat(Mod(structure(list(1L, "bar"), class = "bar")), identicalTo(45))
