#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2016 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-summary-tests.R using GNU R version 3.3.1 (2016-06-21)
library(hamcrest)
Sys.setlocale('LC_COLLATE', 'C')
range.foo <- function(...) 41
Math.bar <- function(...) 44
Summary.bar <- function(...) 45
test.range.1 <- function() assertThat(range(NULL), identicalTo(c(Inf, -Inf)))
test.range.2 <- function() assertThat(range(logical(0)), identicalTo(c(Inf, -Inf)))
test.range.3 <- function() assertThat(range(c(TRUE, TRUE, FALSE, FALSE, TRUE)), identicalTo(0:1))
test.range.4 <- function() assertThat(range(c(TRUE, TRUE, TRUE)), identicalTo(c(1L, 1L)))
test.range.5 <- function() assertThat(range(c(TRUE, TRUE, NA)), identicalTo(c(NA_integer_, NA_integer_)))
test.range.6 <- function() assertThat(range(c(FALSE, FALSE, FALSE, FALSE)), identicalTo(c(0L, 0L)))
test.range.7 <- function() assertThat(range(c(FALSE, FALSE, FALSE, FALSE, NA)), identicalTo(c(NA_integer_, NA_integer_)))
test.range.8 <- function() assertThat(range(c(NA, NA, NA)), identicalTo(c(NA_integer_, NA_integer_)))
test.range.9 <- function() assertThat(range(structure(c(TRUE, FALSE), .Names = c("a", "b"))), identicalTo(0:1))
test.range.10 <- function() assertThat(range(integer(0)), identicalTo(c(Inf, -Inf)))
test.range.11 <- function() assertThat(range(structure(integer(0), .Names = character(0))), identicalTo(c(Inf, -Inf)))
test.range.12 <- function() assertThat(range(c(NA_integer_, NA_integer_, NA_integer_)), identicalTo(c(NA_integer_, NA_integer_)))
test.range.13 <- function() assertThat(range(1:3), identicalTo(c(1L, 3L)))
test.range.14 <- function() assertThat(range(c(1L, NA, 4L, NA, 999L)), identicalTo(c(NA_integer_, NA_integer_)))
test.range.15 <- function() assertThat(range(c(1L, 2L, 1073741824L, 1073741824L)), identicalTo(c(1L, 1073741824L)))
test.range.16 <- function() assertThat(range(structure(1:2, .Names = c("a", "b"))), identicalTo(1:2))
test.range.17 <- function() assertThat(range(numeric(0)), identicalTo(c(Inf, -Inf)))
test.range.18 <- function() assertThat(range(structure(numeric(0), .Names = character(0))), identicalTo(c(Inf, -Inf)))
test.range.19 <- function() assertThat(range(c(NA_real_, NA_real_)), identicalTo(c(NA_real_, NA_real_)))
test.range.20 <- function() assertThat(range(c(3.14159, 6.28319, 9.42478, 12.5664, 15.708)), identicalTo(c(3.14159, 15.708), tol = 0.000100))
test.range.21 <- function() assertThat(range(c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708)), identicalTo(c(-15.708, -3.14159), tol = 0.000100))
test.range.22 <- function() assertThat(range(c(1.5, 2.5)), identicalTo(c(1.5, 2.5), tol = 0.000100))
test.range.23 <- function() assertThat(range(c(1.5, NA)), identicalTo(c(NA_real_, NA_real_)))
test.range.24 <- function() assertThat(range(c(1.5, NaN)), identicalTo(c(NaN, NaN)))
test.range.25 <- function() assertThat(range(c(Inf, -1.5)), identicalTo(c(-1.5, Inf), tol = 0.000100))
test.range.26 <- function() assertThat(range(c(-Inf, -1.5)), identicalTo(c(-Inf, -1.5), tol = 0.000100))
test.range.27 <- function() assertThat(range(c(Inf, 1.5)), identicalTo(c(1.5, Inf), tol = 0.000100))
test.range.28 <- function() assertThat(range(c(Inf, -1.5)), identicalTo(c(-1.5, Inf), tol = 0.000100))
test.range.29 <- function() assertThat(range(structure(c(1.5, 2.5), .Names = c("a", "b"))), identicalTo(c(1.5, 2.5), tol = 0.000100))
test.range.30 <- function() assertThat(range(character(0)), identicalTo(c(NA_character_, NA_character_)))
test.range.31 <- function() assertThat(range(c(NA_character_, NA_character_)), identicalTo(c(NA_character_, NA_character_)))
test.range.32 <- function() assertThat(range(structure(character(0), .Names = character(0))), identicalTo(c(NA_character_, NA_character_)))
test.range.33 <- function() assertThat(range(c("a", "b")), identicalTo(c("a", "b")))
test.range.34 <- function() assertThat(range(c("4.1", "blahh", "99.9", "-413", NA)), identicalTo(c(NA_character_, NA_character_)))
test.range.35 <- function() assertThat(range(structure(c("4.1", "99.9"), .Names = c("a", "b"))), identicalTo(c("4.1", "99.9")))
test.range.36 <- function() assertThat(range(c("TRUE", "TRUE", "FALSE")), identicalTo(c("FALSE", "TRUE")))
test.range.37 <- function() assertThat(range(c("true", "false", "true")), identicalTo(c("false", "true")))
test.range.38 <- function() assertThat(range(c("true", "false", "true")), identicalTo(c("false", "true")))
test.range.39 <- function() assertThat(range(complex(0)), throwsError())
test.range.40 <- function() assertThat(range(c(NA_complex_, NA_complex_, NA_complex_)), throwsError())
test.range.41 <- function() assertThat(range(structure(complex(0), .Named = character(0))), throwsError())
test.range.42 <- function() assertThat(range(c(1+3i, 4+6i, 1-3i)), throwsError())
test.range.43 <- function() assertThat(range(structure(1:12, .Dim = 3:4)), identicalTo(c(1L, 12L)))
test.range.44 <- function() assertThat(range(structure(1:3, rando.attrib = 941L)), identicalTo(c(1L, 3L)))
test.range.45 <- function() assertThat(range(structure(1:3, .Dim = 3L, .Dimnames = list(c("a", "b", "c")))), identicalTo(c(1L, 3L)))
test.range.46 <- function() assertThat(range(structure("foo", class = "foo")), identicalTo(41))
test.range.47 <- function() assertThat(range(structure(list(1L, "bar"), class = "bar")), identicalTo(45))
