library(hamcrest)
as.environment.foo <- function(x) 41
Math.bar <- function(x) 44
test.as.environment.1 <- function() assertThat(as.environment(NULL), throwsError())
test.as.environment.2 <- function() assertThat(as.environment(logical(0)), throwsError())
test.as.environment.3 <- function() assertThat(as.environment(c(TRUE, TRUE, FALSE, FALSE, TRUE)), throwsError())
test.as.environment.4 <- function() assertThat(as.environment(structure(c(TRUE, FALSE), .Names = c("a", ""))), throwsError())
test.as.environment.5 <- function() assertThat(as.environment(c(TRUE, FALSE, NA)), throwsError())
test.as.environment.6 <- function() assertThat(as.environment(integer(0)), throwsError())
test.as.environment.7 <- function() assertThat(as.environment(structure(integer(0), .Names = character(0))), throwsError())
test.as.environment.8 <- function() assertThat(as.environment(1:3), identicalTo(list(<environment>, <environment>, <environment>)))
test.as.environment.9 <- function() assertThat(as.environment(c(1L, NA, 4L, NA, 999L)), throwsError())
test.as.environment.10 <- function() assertThat(as.environment(c(1L, 2L, 1073741824L, 1073741824L)), throwsError())
test.as.environment.11 <- function() assertThat(as.environment(numeric(0)), throwsError())
test.as.environment.12 <- function() assertThat(as.environment(c(3.14159, 6.28319, 9.42478, 12.5664, 15.708)), throwsError())
test.as.environment.13 <- function() assertThat(as.environment(c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708)), throwsError())
test.as.environment.14 <- function() assertThat(as.environment(structure(1:2, .Names = c("a", "b"))), identicalTo(list(<environment>, <environment>)))
test.as.environment.15 <- function() assertThat(as.environment(structure(c(1.5, 2.5), .Names = c("a", "b"))), identicalTo(list(<environment>, <environment>)))
test.as.environment.16 <- function() assertThat(as.environment(character(0)), throwsError())
test.as.environment.17 <- function() assertThat(as.environment(c("4.1", "blahh", "99.9", "-413", NA)), throwsError())
test.as.environment.18 <- function() assertThat(as.environment(list(1, 2, 3)), throwsError())
test.as.environment.19 <- function() assertThat(as.environment(list(1, 2, NULL)), throwsError())
test.as.environment.20 <- function() assertThat(as.environment(list(1L, 2L, 3L)), throwsError())
test.as.environment.21 <- function() assertThat(as.environment(list(1L, 2L, NULL)), throwsError())
test.as.environment.22 <- function() assertThat(as.environment(list(1, 2, list(3, 4))), throwsError())
test.as.environment.23 <- function() assertThat(as.environment(structure(1:12, .Dim = 3:4)), throwsError())
test.as.environment.24 <- function() assertThat(as.environment(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(    x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))), throwsError())
test.as.environment.25 <- function() assertThat(as.environment(structure(1:3, rando.attrib = 941L)), identicalTo(list(<environment>, <environment>, <environment>)))
test.as.environment.26 <- function() assertThat(as.environment(structure(1:3, .Dim = 3L, .Dimnames = list(c("a", "b", "c")))), identicalTo(list(<environment>, <environment>, <environment>)))
test.as.environment.27 <- function() assertThat(as.environment(structure(list("foo"), class = "foo")), identicalTo(41, tol = 0.000100))
test.as.environment.28 <- function() assertThat(as.environment(structure(list("bar"), class = "foo")), identicalTo(41, tol = 0.000100))
test.as.environment.29 <- function() assertThat(as.environment(xyz), throwsError())
test.as.environment.30 <- function() assertThat(as.environment(sin(3.14)), throwsError())
test.as.environment.31 <- function() assertThat(as.environment(structure("foo", class = "foo")), identicalTo(41))
test.as.environment.32 <- function() assertThat(as.environment(structure(list(1L, "bar"), class = "bar")), throwsError())
