#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2019 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by generate-apply-tests.R using GNU R version 3.2.0 (2015-04-16)
library(hamcrest)
f1 <- function(x) x
f2 <- function(x) x*2
f3 <- function(x) NULL
test.sapply.1 <- function() assertThat(sapply(integer(0), "f1"), identicalTo(list()))
test.sapply.2 <- function() assertThat(sapply(integer(0), "f2"), identicalTo(list()))
test.sapply.3 <- function() assertThat(sapply(integer(0), "f3"), identicalTo(list()))
test.sapply.4 <- function() assertThat(sapply(1:15, "f1"), identicalTo(1:15))
test.sapply.5 <- function() assertThat(sapply(1:15, "f2"), identicalTo(c(2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30)))
test.sapply.6 <- function() assertThat(sapply(1:15, "f3"), identicalTo(list(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,     NULL, NULL, NULL, NULL, NULL)))
test.sapply.7 <- function() assertThat(sapply(character(0), "f1"), identicalTo(structure(list(), .Names = character(0))))
test.sapply.8 <- function() assertThat(sapply(character(0), "f2"), identicalTo(structure(list(), .Names = character(0))))
test.sapply.9 <- function() assertThat(sapply(character(0), "f3"), identicalTo(structure(list(), .Names = character(0))))
test.sapply.10 <- function() assertThat(sapply(c("a", "b", "c", "d"), "f1"), identicalTo(structure(c("a", "b", "c", "d"), .Names = c("a", "b", "c", "d"))))
test.sapply.11 <- function() assertThat(sapply(c("a", "b", "c", "d"), "f2"), throwsError())
test.sapply.12 <- function() assertThat(sapply(c("a", "b", "c", "d"), "f3"), identicalTo(structure(list(a = NULL, b = NULL, c = NULL, d = NULL), .Names = c("a", "b", "c", "d"))))
test.sapply.13 <- function() assertThat(sapply(structure(c("a", "b"), .Names = c("x", "y")), "f1"), identicalTo(structure(c("a", "b"), .Names = c("x", "y"))))
test.sapply.14 <- function() assertThat(sapply(structure(c("a", "b"), .Names = c("x", "y")), "f2"), throwsError())
test.sapply.15 <- function() assertThat(sapply(structure(c("a", "b"), .Names = c("x", "y")), "f3"), identicalTo(structure(list(x = NULL, y = NULL), .Names = c("x", "y"))))
test.sapply.16 <- function() assertThat(sapply(list(), "f1"), identicalTo(list()))
test.sapply.17 <- function() assertThat(sapply(list(), "f2"), identicalTo(list()))
test.sapply.18 <- function() assertThat(sapply(list(), "f3"), identicalTo(list()))
test.sapply.19 <- function() assertThat(sapply(structure(list(a = 1, b = 2), .Names = c("a", "b")), "f1"), identicalTo(structure(c(1, 2), .Names = c("a", "b"))))
test.sapply.20 <- function() assertThat(sapply(structure(list(a = 1, b = 2), .Names = c("a", "b")), "f2"), identicalTo(structure(c(2, 4), .Names = c("a", "b"))))
test.sapply.21 <- function() assertThat(sapply(structure(list(a = 1, b = 2), .Names = c("a", "b")), "f3"), identicalTo(structure(list(a = NULL, b = NULL), .Names = c("a", "b"))))
test.sapply.22 <- function() assertThat(sapply(structure(1:12, .Dim = 3:4), "f1"), identicalTo(1:12))
test.sapply.23 <- function() assertThat(sapply(structure(1:12, .Dim = 3:4), "f2"), identicalTo(c(2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24)))
test.sapply.24 <- function() assertThat(sapply(structure(1:12, .Dim = 3:4), "f3"), identicalTo(list(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,     NULL, NULL)))
