#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2016 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-deparse-tests.R using GNU R version 3.3.2 (2016-10-31)
library(hamcrest)
test.deparse.1 <- function() assertThat(deparse(NULL, width.cutoff = 500L), identicalTo("NULL"))
test.deparse.2 <- function() assertThat(deparse(logical(0), width.cutoff = 500L), identicalTo("logical(0)"))
test.deparse.3 <- function() assertThat(deparse(c(TRUE, TRUE, FALSE, FALSE, TRUE), width.cutoff = 500L), identicalTo("c(TRUE, TRUE, FALSE, FALSE, TRUE)"))
test.deparse.4 <- function() assertThat(deparse(structure(c(TRUE, FALSE), .Names = c("a", "")), width.cutoff = 500L), identicalTo("structure(c(TRUE, FALSE), .Names = c(\"a\", \"\"))"))
test.deparse.5 <- function() assertThat(deparse(c(TRUE, FALSE, NA), width.cutoff = 500L), identicalTo("c(TRUE, FALSE, NA)"))
test.deparse.6 <- function() assertThat(deparse(integer(0), width.cutoff = 500L), identicalTo("integer(0)"))
test.deparse.7 <- function() assertThat(deparse(structure(integer(0), .Names = character(0)), width.cutoff = 500L), identicalTo("structure(integer(0), .Names = character(0))"))
test.deparse.8 <- function() assertThat(deparse(1:3, width.cutoff = 500L), identicalTo("1:3"))
test.deparse.9 <- function() assertThat(deparse(c(1L, NA, 4L, NA, 999L), width.cutoff = 500L), identicalTo("c(1L, NA, 4L, NA, 999L)"))
test.deparse.10 <- function() assertThat(deparse(c(1L, 2L, 1073741824L, 1073741824L), width.cutoff = 500L), identicalTo("c(1L, 2L, 1073741824L, 1073741824L)"))
test.deparse.11 <- function() assertThat(deparse(numeric(0), width.cutoff = 500L), identicalTo("numeric(0)"))
test.deparse.12 <- function() assertThat(deparse(c(3.14159, 6.28319, 9.42478, 12.5664, 15.708), width.cutoff = 500L), identicalTo("c(3.14159, 6.28319, 9.42478, 12.5664, 15.708)"))
test.deparse.13 <- function() assertThat(deparse(c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708), width.cutoff = 500L), identicalTo("c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708)"))
test.deparse.14 <- function() assertThat(deparse(structure(1:2, .Names = c("a", "b")), width.cutoff = 500L), identicalTo("structure(1:2, .Names = c(\"a\", \"b\"))"))
test.deparse.15 <- function() assertThat(deparse(structure(c(1.5, 2.5), .Names = c("a", "b")), width.cutoff = 500L), identicalTo("structure(c(1.5, 2.5), .Names = c(\"a\", \"b\"))"))
test.deparse.16 <- function() assertThat(deparse(c(1.5, 1.51, 0, 1.49, -30), width.cutoff = 500L), identicalTo("c(1.5, 1.51, 0, 1.49, -30)"))
test.deparse.17 <- function() assertThat(deparse(c(1.5, 1.51, 0, 1.49, -30, NA), width.cutoff = 500L), identicalTo("c(1.5, 1.51, 0, 1.49, -30, NA)"))
test.deparse.18 <- function() assertThat(deparse(c(1.5, 1.51, 0, 1.49, -30, NaN), width.cutoff = 500L), identicalTo("c(1.5, 1.51, 0, 1.49, -30, NaN)"))
test.deparse.19 <- function() assertThat(deparse(c(1.5, 1.51, 0, 1.49, -30, Inf), width.cutoff = 500L), identicalTo("c(1.5, 1.51, 0, 1.49, -30, Inf)"))
test.deparse.20 <- function() assertThat(deparse(c(1.5, 1.51, 0, 1.49, -30, -Inf), width.cutoff = 500L), identicalTo("c(1.5, 1.51, 0, 1.49, -30, -Inf)"))
test.deparse.21 <- function() assertThat(deparse(character(0), width.cutoff = 500L), identicalTo("character(0)"))
test.deparse.22 <- function() assertThat(deparse(c("4.1", "blahh", "99.9", "-413", NA), width.cutoff = 500L), identicalTo("c(\"4.1\", \"blahh\", \"99.9\", \"-413\", NA)"))
test.deparse.23 <- function() assertThat(deparse(complex(0), width.cutoff = 500L), identicalTo("complex(0)"))
test.deparse.24 <- function() assertThat(deparse(list(1, 2, 3), width.cutoff = 500L), identicalTo("list(1, 2, 3)"))
test.deparse.25 <- function() assertThat(deparse(list(1, 2, NULL), width.cutoff = 500L), identicalTo("list(1, 2, NULL)"))
test.deparse.26 <- function() assertThat(deparse(list(1L, 2L, 3L), width.cutoff = 500L), identicalTo("list(1L, 2L, 3L)"))
test.deparse.27 <- function() assertThat(deparse(list(1L, 2L, NULL), width.cutoff = 500L), identicalTo("list(1L, 2L, NULL)"))
test.deparse.28 <- function() assertThat(deparse(list(1, 2, list(3, 4)), width.cutoff = 500L), identicalTo("list(1, 2, list(3, 4))"))
test.deparse.29 <- function() assertThat(deparse(list(3, "a", structure(list("b", z = list(TRUE, "c")), .Names = c("", "z"))), width.cutoff = 500L), identicalTo("list(3, \"a\", structure(list(\"b\", z = list(TRUE, \"c\")), .Names = c(\"\", \"z\")))"))
test.deparse.30 <- function() assertThat(deparse(structure(list(`NA` = 1, 2, b = 3), .Names = c(NA, "", "b")), width.cutoff = 500L), identicalTo("structure(list(\"NA\" = 1, 2, b = 3), .Names = c(NA, \"\", \"b\"))"))
test.deparse.31 <- function() assertThat(deparse(pairlist(41, "a", 21L), width.cutoff = 500L), identicalTo("pairlist(41, \"a\", 21L)"))
test.deparse.32 <- function() assertThat(deparse(pairlist(a = 41, 42), width.cutoff = 500L), identicalTo("pairlist(a = 41, 42)"))
test.deparse.33 <- function() assertThat(deparse(pairlist(a = 41, NULL), width.cutoff = 500L), identicalTo("pairlist(a = 41, NULL)"))
test.deparse.34 <- function() assertThat(deparse(structure(1:12, .Dim = 3:4), width.cutoff = 500L), identicalTo("structure(1:12, .Dim = 3:4)"))
test.deparse.35 <- function() assertThat(deparse(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(    x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y"))), width.cutoff = 500L), identicalTo("structure(1:12, .Dim = 3:4, .Dimnames = structure(list(x = c(\"a\", \"b\", \"c\"), y = c(\"d\", \"e\", \"f\", \"g\")), .Names = c(\"x\", \"y\")))"))
test.deparse.36 <- function() assertThat(deparse(structure(1:3, rando.attrib = 941L), width.cutoff = 500L), identicalTo("structure(1:3, rando.attrib = 941L)"))
test.deparse.37 <- function() assertThat(deparse(structure(1:3, .Dim = 3L, .Dimnames = list(c("a", "b", "c"))), width.cutoff = 500L), identicalTo("structure(1:3, .Dim = 3L, .Dimnames = list(c(\"a\", \"b\", \"c\")))"))
test.deparse.38 <- function() assertThat(deparse(structure(1:3, .Dim = 3L, .Dimnames = structure(list(    z = c("a", "b", "c")), .Names = "z")), width.cutoff = 500L), identicalTo("structure(1:3, .Dim = 3L, .Dimnames = structure(list(z = c(\"a\", \"b\", \"c\")), .Names = \"z\"))"))
test.deparse.39 <- function() assertThat(deparse(structure(list("foo"), class = "foo"), width.cutoff = 500L), identicalTo("structure(list(\"foo\"), class = \"foo\")"))
test.deparse.40 <- function() assertThat(deparse(structure(list("bar"), class = "foo"), width.cutoff = 500L), identicalTo("structure(list(\"bar\"), class = \"foo\")"))
test.deparse.41 <- function() assertThat(deparse(quote(xyz), width.cutoff = 500L), identicalTo("xyz"))
test.deparse.42 <- function() assertThat(deparse(quote(sin(3.14)), width.cutoff = 500L), identicalTo("sin(3.14)"))
