#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2019 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-unary-tests.R using GNU R version 3.3.3 (2017-03-06)
library(hamcrest)
Sys.setlocale('LC_COLLATE', 'C')
is.na.foo <- function(...) 41L
as.vector.foo <- function(...) 99
Math.bar <- function(...) 44
Summary.bar <- function(...) 45
Ops.bar <- function(...) 46
test.is.na.1 <- function() assertThat(is.na(NULL), identicalTo(logical(0)))
test.is.na.2 <- function() assertThat(is.na(logical(0)), identicalTo(logical(0)))
test.is.na.3 <- function() assertThat(is.na(c(TRUE, TRUE, FALSE, FALSE, TRUE)), identicalTo(c(FALSE, FALSE, FALSE, FALSE, FALSE)))
test.is.na.4 <- function() assertThat(is.na(structure(c(TRUE, FALSE), .Names = c("a", ""))), identicalTo(structure(c(FALSE, FALSE), .Names = c("a", ""))))
test.is.na.5 <- function() assertThat(is.na(c(TRUE, FALSE, NA)), identicalTo(c(FALSE, FALSE, TRUE)))
test.is.na.6 <- function() assertThat(is.na(integer(0)), identicalTo(logical(0)))
test.is.na.7 <- function() assertThat(is.na(structure(integer(0), .Names = character(0))), identicalTo(structure(logical(0), .Names = character(0))))
test.is.na.8 <- function() assertThat(is.na(1:3), identicalTo(c(FALSE, FALSE, FALSE)))
test.is.na.9 <- function() assertThat(is.na(c(1L, NA, 4L, NA, 999L)), identicalTo(c(FALSE, TRUE, FALSE, TRUE, FALSE)))
test.is.na.10 <- function() assertThat(is.na(c(1L, 2L, 1073741824L, 1073741824L)), identicalTo(c(FALSE, FALSE, FALSE, FALSE)))
test.is.na.11 <- function() assertThat(is.na(numeric(0)), identicalTo(logical(0)))
test.is.na.12 <- function() assertThat(is.na(c(3.14159, 6.28319, 9.42478, 12.5664, 15.708)), identicalTo(c(FALSE, FALSE, FALSE, FALSE, FALSE)))
test.is.na.13 <- function() assertThat(is.na(c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708)), identicalTo(c(FALSE, FALSE, FALSE, FALSE, FALSE)))
test.is.na.14 <- function() assertThat(is.na(structure(1:2, .Names = c("a", "b"))), identicalTo(structure(c(FALSE, FALSE), .Names = c("a", "b"))))
test.is.na.15 <- function() assertThat(is.na(structure(c(1.5, 2.5), .Names = c("a", "b"))), identicalTo(structure(c(FALSE, FALSE), .Names = c("a", "b"))))
test.is.na.16 <- function() assertThat(is.na(c(1.5, 1.51, 0, 1.49, -30)), identicalTo(c(FALSE, FALSE, FALSE, FALSE, FALSE)))
test.is.na.17 <- function() assertThat(is.na(c(1.5, 1.51, 0, 1.49, -30, NA)), identicalTo(c(FALSE, FALSE, FALSE, FALSE, FALSE, TRUE)))
test.is.na.18 <- function() assertThat(is.na(c(1.5, 1.51, 0, 1.49, -30, NaN)), identicalTo(c(FALSE, FALSE, FALSE, FALSE, FALSE, TRUE)))
test.is.na.19 <- function() assertThat(is.na(c(1.5, 1.51, 0, 1.49, -30, Inf)), identicalTo(c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE)))
test.is.na.20 <- function() assertThat(is.na(c(1.5, 1.51, 0, 1.49, -30, -Inf)), identicalTo(c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE)))
test.is.na.21 <- function() assertThat(is.na(character(0)), identicalTo(logical(0)))
test.is.na.22 <- function() assertThat(is.na(c("4.1", "blahh", "99.9", "-413", NA)), identicalTo(c(FALSE, FALSE, FALSE, FALSE, TRUE)))
test.is.na.23 <- function() assertThat(is.na(complex(0)), identicalTo(logical(0)))
test.is.na.24 <- function() assertThat(is.na(list(1, 2, 3)), identicalTo(c(FALSE, FALSE, FALSE)))
test.is.na.25 <- function() assertThat(is.na(list(1, 2, NULL)), identicalTo(c(FALSE, FALSE, FALSE)))
test.is.na.26 <- function() assertThat(is.na(list(1L, 2L, 3L)), identicalTo(c(FALSE, FALSE, FALSE)))
test.is.na.27 <- function() assertThat(is.na(list(1L, 2L, NULL)), identicalTo(c(FALSE, FALSE, FALSE)))
test.is.na.28 <- function() assertThat(is.na(list(1, 2, list(3, 4))), identicalTo(c(FALSE, FALSE, FALSE)))
test.is.na.29 <- function() assertThat(is.na(list(1, 2, numeric(0))), identicalTo(c(FALSE, FALSE, FALSE)))
test.is.na.30 <- function() assertThat(is.na(list(3, "a", structure(list("b", z = list(TRUE, "c")), .Names = c("", "z")))), identicalTo(c(FALSE, FALSE, FALSE)))
test.is.na.31 <- function() assertThat(is.na(structure(list(`NA` = 1, 2, b = 3), .Names = c(NA, "", "b"))), identicalTo(structure(c(FALSE, FALSE, FALSE), .Names = c(NA, "", "b"))))
test.is.na.32 <- function() assertThat(is.na(pairlist(41, "a", 21L)), identicalTo(c(FALSE, FALSE, FALSE)))
test.is.na.33 <- function() assertThat(is.na(pairlist(a = 41, 42)), identicalTo(c(FALSE, FALSE)))
test.is.na.34 <- function() assertThat(is.na(pairlist(a = 41, NULL)), identicalTo(c(FALSE, FALSE)))
test.is.na.35 <- function() assertThat(is.na(structure(1:12, .Dim = 3:4)), identicalTo(structure(c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE), .Dim = 3:4)))
test.is.na.36 <- function() assertThat(is.na(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(    x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))), identicalTo(structure(c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE), .Dim = 3:4, .Dimnames = structure(list(    x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))))
test.is.na.37 <- function() assertThat(is.na(structure(1:3, rando.attrib = 941L)), identicalTo(c(FALSE, FALSE, FALSE)))
test.is.na.38 <- function() assertThat(is.na(structure(1:3, .Dim = 3L, .Dimnames = list(c("a", "b", "c")))), identicalTo(structure(c(FALSE, FALSE, FALSE), .Dim = 3L, .Dimnames = list(    c("a", "b", "c")))))
test.is.na.39 <- function() assertThat(is.na(structure(1:3, .Dim = 3L, .Dimnames = structure(list(z = c("a", "b", "c")), .Names = "z"))), identicalTo(structure(c(FALSE, FALSE, FALSE), .Dim = 3L, .Dimnames = structure(list(    z = c("a", "b", "c")), .Names = "z"))))
test.is.na.40 <- function() assertThat(is.na(structure(list("foo"), class = "foo")), identicalTo(41L))
test.is.na.41 <- function() assertThat(is.na(structure(list("bar"), class = "foo")), identicalTo(41L))
test.is.na.42 <- function() assertThat(is.na(quote(xyz)), identicalTo(FALSE))
test.is.na.43 <- function() assertThat(is.na(quote(sin(3.14))), identicalTo(c(FALSE, FALSE)))
test.is.na.44 <- function() assertThat(is.na("NaN"), identicalTo(FALSE))
test.is.na.45 <- function() assertThat(is.na("NABOOM!"), identicalTo(FALSE))
test.is.na.46 <- function() assertThat(is.na("NaNaNabooboo"), identicalTo(FALSE))
test.is.na.47 <- function() assertThat(is.na("-Inf"), identicalTo(FALSE))
test.is.na.48 <- function() assertThat(is.na("+Infinity"), identicalTo(FALSE))
test.is.na.49 <- function() assertThat(is.na("Infinity and beyond!"), identicalTo(FALSE))
test.is.na.50 <- function() assertThat(is.na("Infi"), identicalTo(FALSE))
test.is.na.51 <- function() assertThat(is.na("0.03f"), identicalTo(FALSE))
test.is.na.52 <- function() assertThat(is.na("  0.0330   "), identicalTo(FALSE))
test.is.na.53 <- function() assertThat(is.na(structure("foo", class = "foo")), identicalTo(41L))
test.is.na.54 <- function() assertThat(is.na(structure(list(1L, "bar"), class = "bar")), identicalTo(c(FALSE, FALSE)))
