library(hamcrest)
is.symbol.foo <- function(x) 41
Math.bar <- function(x) 44
test.is.symbol.1 <- function() assertThat(is.symbol(NULL), identicalTo(FALSE))
test.is.symbol.2 <- function() assertThat(is.symbol(logical(0)), identicalTo(FALSE))
test.is.symbol.3 <- function() assertThat(is.symbol(c(TRUE, TRUE, FALSE, FALSE, TRUE)), identicalTo(FALSE))
test.is.symbol.4 <- function() assertThat(is.symbol(structure(c(TRUE, FALSE), .Names = c("a", ""))), identicalTo(FALSE))
test.is.symbol.5 <- function() assertThat(is.symbol(c(TRUE, FALSE, NA)), identicalTo(FALSE))
test.is.symbol.6 <- function() assertThat(is.symbol(integer(0)), identicalTo(FALSE))
test.is.symbol.7 <- function() assertThat(is.symbol(structure(integer(0), .Names = character(0))), identicalTo(FALSE))
test.is.symbol.8 <- function() assertThat(is.symbol(1:3), identicalTo(FALSE))
test.is.symbol.9 <- function() assertThat(is.symbol(c(1L, NA, 4L, NA, 999L)), identicalTo(FALSE))
test.is.symbol.10 <- function() assertThat(is.symbol(c(1L, 2L, 1073741824L, 1073741824L)), identicalTo(FALSE))
test.is.symbol.11 <- function() assertThat(is.symbol(numeric(0)), identicalTo(FALSE))
test.is.symbol.12 <- function() assertThat(is.symbol(c(3.14159, 6.28319, 9.42478, 12.5664, 15.708)), identicalTo(FALSE))
test.is.symbol.13 <- function() assertThat(is.symbol(c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708)), identicalTo(FALSE))
test.is.symbol.14 <- function() assertThat(is.symbol(structure(1:2, .Names = c("a", "b"))), identicalTo(FALSE))
test.is.symbol.15 <- function() assertThat(is.symbol(structure(c(1.5, 2.5), .Names = c("a", "b"))), identicalTo(FALSE))
test.is.symbol.16 <- function() assertThat(is.symbol(character(0)), identicalTo(FALSE))
test.is.symbol.17 <- function() assertThat(is.symbol(c("4.1", "blahh", "99.9", "-413", NA)), identicalTo(FALSE))
test.is.symbol.18 <- function() assertThat(is.symbol(list(1, 2, 3)), identicalTo(FALSE))
test.is.symbol.19 <- function() assertThat(is.symbol(list(1, 2, NULL)), identicalTo(FALSE))
test.is.symbol.20 <- function() assertThat(is.symbol(list(1L, 2L, 3L)), identicalTo(FALSE))
test.is.symbol.21 <- function() assertThat(is.symbol(list(1L, 2L, NULL)), identicalTo(FALSE))
test.is.symbol.22 <- function() assertThat(is.symbol(list(1, 2, list(3, 4))), identicalTo(FALSE))
test.is.symbol.23 <- function() assertThat(is.symbol(structure(1:12, .Dim = 3:4)), identicalTo(FALSE))
test.is.symbol.24 <- function() assertThat(is.symbol(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(    x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))), identicalTo(FALSE))
test.is.symbol.25 <- function() assertThat(is.symbol(structure(1:3, rando.attrib = 941L)), identicalTo(FALSE))
test.is.symbol.26 <- function() assertThat(is.symbol(structure(1:3, .Dim = 3L, .Dimnames = list(c("a", "b", "c")))), identicalTo(FALSE))
test.is.symbol.27 <- function() assertThat(is.symbol(structure(list("foo"), class = "foo")), identicalTo(FALSE))
test.is.symbol.28 <- function() assertThat(is.symbol(structure(list("bar"), class = "foo")), identicalTo(FALSE))
test.is.symbol.29 <- function() assertThat(is.symbol(xyz), throwsError())
test.is.symbol.30 <- function() assertThat(is.symbol(sin(3.14)), identicalTo(FALSE))
test.is.symbol.31 <- function() assertThat(is.symbol(structure("foo", class = "foo")), identicalTo(FALSE))
test.is.symbol.32 <- function() assertThat(is.symbol(structure(list(1L, "bar"), class = "bar")), identicalTo(FALSE))
