#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2016 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-unary-tests.R using GNU R version 3.2.0 (2015-04-16)
library(hamcrest)
is.logical.foo <- function(...) 41
as.vector.foo <- function(...) 99
Math.bar <- function(...) 44
Summary.bar <- function(...) 45
Ops.bar <- function(...) 46
test.is.logical.1 <- function() assertThat(is.logical(NULL), identicalTo(FALSE))
test.is.logical.2 <- function() assertThat(is.logical(logical(0)), identicalTo(TRUE))
test.is.logical.3 <- function() assertThat(is.logical(c(TRUE, TRUE, FALSE, FALSE, TRUE)), identicalTo(TRUE))
test.is.logical.4 <- function() assertThat(is.logical(structure(c(TRUE, FALSE), .Names = c("a", ""))), identicalTo(TRUE))
test.is.logical.5 <- function() assertThat(is.logical(c(TRUE, FALSE, NA)), identicalTo(TRUE))
test.is.logical.6 <- function() assertThat(is.logical(integer(0)), identicalTo(FALSE))
test.is.logical.7 <- function() assertThat(is.logical(structure(integer(0), .Names = character(0))), identicalTo(FALSE))
test.is.logical.8 <- function() assertThat(is.logical(1:3), identicalTo(FALSE))
test.is.logical.9 <- function() assertThat(is.logical(c(1L, NA, 4L, NA, 999L)), identicalTo(FALSE))
test.is.logical.10 <- function() assertThat(is.logical(c(1L, 2L, 1073741824L, 1073741824L)), identicalTo(FALSE))
test.is.logical.11 <- function() assertThat(is.logical(numeric(0)), identicalTo(FALSE))
test.is.logical.12 <- function() assertThat(is.logical(c(3.14159, 6.28319, 9.42478, 12.5664, 15.708)), identicalTo(FALSE))
test.is.logical.13 <- function() assertThat(is.logical(c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708)), identicalTo(FALSE))
test.is.logical.14 <- function() assertThat(is.logical(structure(1:2, .Names = c("a", "b"))), identicalTo(FALSE))
test.is.logical.15 <- function() assertThat(is.logical(structure(c(1.5, 2.5), .Names = c("a", "b"))), identicalTo(FALSE))
test.is.logical.16 <- function() assertThat(is.logical(c(1.5, 1.51, 0, 1.49, -30)), identicalTo(FALSE))
test.is.logical.17 <- function() assertThat(is.logical(c(1.5, 1.51, 0, 1.49, -30, NA)), identicalTo(FALSE))
test.is.logical.18 <- function() assertThat(is.logical(c(1.5, 1.51, 0, 1.49, -30, NaN)), identicalTo(FALSE))
test.is.logical.19 <- function() assertThat(is.logical(c(1.5, 1.51, 0, 1.49, -30, Inf)), identicalTo(FALSE))
test.is.logical.20 <- function() assertThat(is.logical(c(1.5, 1.51, 0, 1.49, -30, -Inf)), identicalTo(FALSE))
test.is.logical.21 <- function() assertThat(is.logical(character(0)), identicalTo(FALSE))
test.is.logical.22 <- function() assertThat(is.logical(c("4.1", "blahh", "99.9", "-413", NA)), identicalTo(FALSE))
test.is.logical.23 <- function() assertThat(is.logical(list(1, 2, 3)), identicalTo(FALSE))
test.is.logical.24 <- function() assertThat(is.logical(list(1, 2, NULL)), identicalTo(FALSE))
test.is.logical.25 <- function() assertThat(is.logical(list(1L, 2L, 3L)), identicalTo(FALSE))
test.is.logical.26 <- function() assertThat(is.logical(list(1L, 2L, NULL)), identicalTo(FALSE))
test.is.logical.27 <- function() assertThat(is.logical(list(1, 2, list(3, 4))), identicalTo(FALSE))
test.is.logical.28 <- function() assertThat(is.logical(structure(1:12, .Dim = 3:4)), identicalTo(FALSE))
test.is.logical.29 <- function() assertThat(is.logical(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(    x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))), identicalTo(FALSE))
test.is.logical.30 <- function() assertThat(is.logical(structure(1:3, rando.attrib = 941L)), identicalTo(FALSE))
test.is.logical.31 <- function() assertThat(is.logical(structure(1:3, .Dim = 3L, .Dimnames = list(c("a", "b", "c")))), identicalTo(FALSE))
test.is.logical.32 <- function() assertThat(is.logical(structure(list("foo"), class = "foo")), identicalTo(FALSE))
test.is.logical.33 <- function() assertThat(is.logical(structure(list("bar"), class = "foo")), identicalTo(FALSE))
test.is.logical.34 <- function() assertThat(is.logical(quote(xyz)), identicalTo(FALSE))
test.is.logical.35 <- function() assertThat(is.logical(quote(sin(3.14))), identicalTo(FALSE))
test.is.logical.36 <- function() assertThat(is.logical(structure("foo", class = "foo")), identicalTo(FALSE))
test.is.logical.37 <- function() assertThat(is.logical(structure(list(1L, "bar"), class = "bar")), identicalTo(FALSE))
