#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2018 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-math-unary-tests.R using GNU R version 3.2.0 (2015-04-16)
library(hamcrest)
sinpi.foo <- function(...) 41
Math.bar <- function(...) 44
test.sinpi.1 <- function() assertThat(sinpi(-0.01), identicalTo(-0.0314107590781283, tol = 0.000100))
test.sinpi.2 <- function() assertThat(sinpi(-0.1), identicalTo(-0.309016994374947, tol = 0.000100))
test.sinpi.3 <- function() assertThat(sinpi(-1), identicalTo(0))
test.sinpi.4 <- function() assertThat(sinpi(-1.5), identicalTo(1))
test.sinpi.5 <- function() assertThat(sinpi(-2), identicalTo(0))
test.sinpi.6 <- function() assertThat(sinpi(-2.5), identicalTo(-1))
test.sinpi.7 <- function() assertThat(sinpi(-4), identicalTo(0))
test.sinpi.8 <- function() assertThat(sinpi(-10), identicalTo(0))
test.sinpi.9 <- function() assertThat(sinpi(-100), identicalTo(0))
test.sinpi.10 <- function() assertThat(sinpi(-0.785398), identicalTo(-0.624266353657729, tol = 0.000100))
test.sinpi.11 <- function() assertThat(sinpi(-1.5708), identicalTo(0.975365426541909, tol = 0.000100))
test.sinpi.12 <- function() assertThat(sinpi(-3.14159), identicalTo(0.430293691750245, tol = 0.000100))
test.sinpi.13 <- function() assertThat(sinpi(-6.28319), identicalTo(-0.776862502885196, tol = 0.000100))
test.sinpi.14 <- function() assertThat(sinpi(0.01), identicalTo(0.0314107590781283, tol = 0.000100))
test.sinpi.15 <- function() assertThat(sinpi(0.1), identicalTo(0.309016994374947, tol = 0.000100))
test.sinpi.16 <- function() assertThat(sinpi(1), identicalTo(0))
test.sinpi.17 <- function() assertThat(sinpi(1.5), identicalTo(-1))
test.sinpi.18 <- function() assertThat(sinpi(2), identicalTo(0))
test.sinpi.19 <- function() assertThat(sinpi(2.5), identicalTo(1))
test.sinpi.20 <- function() assertThat(sinpi(4), identicalTo(0))
test.sinpi.21 <- function() assertThat(sinpi(10), identicalTo(0))
test.sinpi.22 <- function() assertThat(sinpi(100), identicalTo(0))
test.sinpi.23 <- function() assertThat(sinpi(0.785398), identicalTo(0.624266353657729, tol = 0.000100))
test.sinpi.24 <- function() assertThat(sinpi(1.5708), identicalTo(-0.975365426541909, tol = 0.000100))
test.sinpi.25 <- function() assertThat(sinpi(3.14159), identicalTo(-0.430293691750245, tol = 0.000100))
test.sinpi.26 <- function() assertThat(sinpi(6.28319), identicalTo(0.776862502885196, tol = 0.000100))
test.sinpi.27 <- function() assertThat(sinpi(NULL), throwsError())
test.sinpi.28 <- function() assertThat(sinpi(c(0.01, 0.1, 1, 1.5)), identicalTo(c(0.0314107590781283, 0.309016994374947, 0, -1), tol = 0.000100))
test.sinpi.29 <- function() assertThat(sinpi(integer(0)), identicalTo(numeric(0)))
test.sinpi.30 <- function() assertThat(sinpi(numeric(0)), identicalTo(numeric(0)))
test.sinpi.31 <- function() assertThat(sinpi(NaN), identicalTo(NaN))
test.sinpi.32 <- function() assertThat(sinpi(NA_real_), identicalTo(NA_real_))
test.sinpi.33 <- function() assertThat(sinpi(Inf), identicalTo(NaN))
test.sinpi.34 <- function() assertThat(sinpi(-Inf), identicalTo(NaN))
test.sinpi.35 <- function() assertThat(sinpi(c(1L, 4L)), identicalTo(c(0, 0)))
test.sinpi.36 <- function() assertThat(sinpi(structure(1, class = "foo")), identicalTo(41))
test.sinpi.37 <- function() assertThat(sinpi(structure(1, class = "bar")), identicalTo(44))
test.sinpi.38 <- function() assertThat(sinpi(structure(list("a"), class = "foo")), identicalTo(41))
test.sinpi.39 <- function() assertThat(sinpi(structure(list("b"), class = "bar")), identicalTo(44))
test.sinpi.40 <- function() assertThat(sinpi(structure(c(1, 2, 3), .Names = c("a", "b", "c"))), identicalTo(structure(c(0, 0, 0), .Names = c("a", "b", "c"))))
test.sinpi.41 <- function() assertThat(sinpi(structure(c(1, 2), .Names = c("x", ""))), identicalTo(structure(c(0, 0), .Names = c("x", ""))))
test.sinpi.42 <- function() assertThat(sinpi(structure(1:12, .Dim = 3:4)), identicalTo(structure(c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), .Dim = 3:4)))
test.sinpi.43 <- function() assertThat(sinpi(structure(0, rando.attr = 4L)), identicalTo(structure(0, rando.attr = 4L)))
test.sinpi.44 <- function() assertThat(sinpi(structure(0, class = "zinga")), identicalTo(structure(0, class = "zinga")))
