#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2018 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-unary-tests.R using GNU R version 3.2.0 (2015-04-16)
library(hamcrest)
Re.foo <- function(...) 41
Complex.bar <- function(...) 45
test.Re.1 <- function() assertThat(Re(NULL), throwsError())
test.Re.2 <- function() assertThat(Re(logical(0)), identicalTo(numeric(0)))
test.Re.3 <- function() assertThat(Re(c(TRUE, TRUE, FALSE, FALSE, TRUE)), identicalTo(c(1, 1, 0, 0, 1)))
test.Re.4 <- function() assertThat(Re(structure(c(TRUE, FALSE), .Names = c("a", ""))), identicalTo(structure(c(1, 0), .Names = c("a", ""))))
test.Re.5 <- function() assertThat(Re(c(TRUE, FALSE, NA)), identicalTo(c(1, 0, NA)))
test.Re.6 <- function() assertThat(Re(integer(0)), identicalTo(numeric(0)))
test.Re.7 <- function() assertThat(Re(structure(integer(0), .Names = character(0))), identicalTo(structure(numeric(0), .Names = character(0))))
test.Re.8 <- function() assertThat(Re(1:3), identicalTo(c(1, 2, 3)))
test.Re.9 <- function() assertThat(Re(c(1L, NA, 4L, NA, 999L)), identicalTo(c(1, NA, 4, NA, 999)))
test.Re.10 <- function() assertThat(Re(c(1L, 2L, 1073741824L, 1073741824L)), identicalTo(c(1, 2, 1073741824, 1073741824), tol = 0.000100))
test.Re.11 <- function() assertThat(Re(numeric(0)), identicalTo(numeric(0)))
test.Re.12 <- function() assertThat(Re(NaN), identicalTo(NaN))
test.Re.13 <- function() assertThat(Re(NA_real_), identicalTo(NA_real_))
test.Re.14 <- function() assertThat(Re(1), identicalTo(1))
test.Re.15 <- function() assertThat(Re(1.5), identicalTo(1.5, tol = 0.000100))
test.Re.16 <- function() assertThat(Re(-1.5), identicalTo(-1.5, tol = 0.000100))
test.Re.17 <- function() assertThat(Re(3.14), identicalTo(3.14, tol = 0.000100))
test.Re.18 <- function() assertThat(Re(Inf), identicalTo(Inf))
test.Re.19 <- function() assertThat(Re(-Inf), identicalTo(-Inf))
test.Re.20 <- function() assertThat(Re(complex(0)), identicalTo(numeric(0)))
test.Re.21 <- function() assertThat(Re(structure(complex(0), .Names = character(0))), identicalTo(structure(numeric(0), .Names = character(0))))
test.Re.22 <- function() assertThat(Re(NA_complex_), identicalTo(NA_real_))
test.Re.23 <- function() assertThat(Re(NA_complex_), identicalTo(NA_real_))
test.Re.24 <- function() assertThat(Re(1.5+3i), identicalTo(1.5, tol = 0.000100))
test.Re.25 <- function() assertThat(Re(1.5-3i), identicalTo(1.5, tol = 0.000100))
test.Re.26 <- function() assertThat(Re(-1.5+3i), identicalTo(-1.5, tol = 0.000100))
test.Re.27 <- function() assertThat(Re(1.5-3i), identicalTo(1.5, tol = 0.000100))
test.Re.28 <- function() assertThat(Re(structure(c(3+4i, 9+2i), .Names = c("a", "b"))), identicalTo(structure(c(3, 9), .Names = c("a", "b"))))
test.Re.29 <- function() assertThat(Re(structure(5+9i, rando.attr = "bazinga", class = "zarg")), identicalTo(structure(5, rando.attr = "bazinga", class = "zarg")))
test.Re.30 <- function() assertThat(Re(character(0)), throwsError())
test.Re.31 <- function() assertThat(Re(c("4.1", "blahh", "99.9", "-413", NA)), throwsError())
test.Re.32 <- function() assertThat(Re(list(1)), throwsError())
test.Re.33 <- function() assertThat(Re(structure(1:12, .Dim = 3:4)), identicalTo(structure(c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12), .Dim = 3:4)))
test.Re.34 <- function() assertThat(Re(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))), identicalTo(structure(c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12), .Dim = 3:4, .Dimnames = structure(list(    x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))))
test.Re.35 <- function() assertThat(Re(structure(1:3, rando.attrib = 941L)), identicalTo(structure(c(1, 2, 3), rando.attrib = 941L)))
test.Re.36 <- function() assertThat(Re(structure(c(1+4.5i, 2+4.5i, 3+4.5i), .Dim = 3L, .Dimnames = list(    c("a", "b", "c")))), identicalTo(structure(c(1, 2, 3), .Dim = 3L, .Dimnames = list(c("a", "b", "c")))))
test.Re.37 <- function() assertThat(Re(structure(list("foo"), class = "foo")), identicalTo(41))
test.Re.38 <- function() assertThat(Re(structure(list("bar"), class = "foo")), identicalTo(41))
test.Re.39 <- function() assertThat(Re(structure("foo", class = "foo")), identicalTo(41))
test.Re.40 <- function() assertThat(Re(structure(list(1L, "bar"), class = "bar")), identicalTo(45))
