#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2016 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-unary-tests.R using GNU R version 3.3.2 (2016-10-31)
library(hamcrest)
Sys.setlocale('LC_COLLATE', 'C')
is.list.foo <- function(...) 41L
as.vector.foo <- function(...) 99
Math.bar <- function(...) 44
Summary.bar <- function(...) 45
Ops.bar <- function(...) 46
test.is.list.1 <- function() assertThat(is.list(NULL), identicalTo(FALSE))
test.is.list.2 <- function() assertThat(is.list(logical(0)), identicalTo(FALSE))
test.is.list.3 <- function() assertThat(is.list(c(TRUE, TRUE, FALSE, FALSE, TRUE)), identicalTo(FALSE))
test.is.list.4 <- function() assertThat(is.list(structure(c(TRUE, FALSE), .Names = c("a", ""))), identicalTo(FALSE))
test.is.list.5 <- function() assertThat(is.list(c(TRUE, FALSE, NA)), identicalTo(FALSE))
test.is.list.6 <- function() assertThat(is.list(integer(0)), identicalTo(FALSE))
test.is.list.7 <- function() assertThat(is.list(structure(integer(0), .Names = character(0))), identicalTo(FALSE))
test.is.list.8 <- function() assertThat(is.list(1:3), identicalTo(FALSE))
test.is.list.9 <- function() assertThat(is.list(c(1L, NA, 4L, NA, 999L)), identicalTo(FALSE))
test.is.list.10 <- function() assertThat(is.list(c(1L, 2L, 1073741824L, 1073741824L)), identicalTo(FALSE))
test.is.list.11 <- function() assertThat(is.list(numeric(0)), identicalTo(FALSE))
test.is.list.12 <- function() assertThat(is.list(c(3.14159, 6.28319, 9.42478, 12.5664, 15.708)), identicalTo(FALSE))
test.is.list.13 <- function() assertThat(is.list(c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708)), identicalTo(FALSE))
test.is.list.14 <- function() assertThat(is.list(structure(1:2, .Names = c("a", "b"))), identicalTo(FALSE))
test.is.list.15 <- function() assertThat(is.list(structure(c(1.5, 2.5), .Names = c("a", "b"))), identicalTo(FALSE))
test.is.list.16 <- function() assertThat(is.list(c(1.5, 1.51, 0, 1.49, -30)), identicalTo(FALSE))
test.is.list.17 <- function() assertThat(is.list(c(1.5, 1.51, 0, 1.49, -30, NA)), identicalTo(FALSE))
test.is.list.18 <- function() assertThat(is.list(c(1.5, 1.51, 0, 1.49, -30, NaN)), identicalTo(FALSE))
test.is.list.19 <- function() assertThat(is.list(c(1.5, 1.51, 0, 1.49, -30, Inf)), identicalTo(FALSE))
test.is.list.20 <- function() assertThat(is.list(c(1.5, 1.51, 0, 1.49, -30, -Inf)), identicalTo(FALSE))
test.is.list.21 <- function() assertThat(is.list(character(0)), identicalTo(FALSE))
test.is.list.22 <- function() assertThat(is.list(c("4.1", "blahh", "99.9", "-413", NA)), identicalTo(FALSE))
test.is.list.23 <- function() assertThat(is.list(complex(0)), identicalTo(FALSE))
test.is.list.24 <- function() assertThat(is.list(list(1, 2, 3)), identicalTo(TRUE))
test.is.list.25 <- function() assertThat(is.list(list(1, 2, NULL)), identicalTo(TRUE))
test.is.list.26 <- function() assertThat(is.list(list(1L, 2L, 3L)), identicalTo(TRUE))
test.is.list.27 <- function() assertThat(is.list(list(1L, 2L, NULL)), identicalTo(TRUE))
test.is.list.28 <- function() assertThat(is.list(list(1, 2, list(3, 4))), identicalTo(TRUE))
test.is.list.29 <- function() assertThat(is.list(list(3, "a", structure(list("b", z = list(TRUE, "c")), .Names = c("", "z")))), identicalTo(TRUE))
test.is.list.30 <- function() assertThat(is.list(structure(list(`NA` = 1, 2, b = 3), .Names = c(NA, "", "b"))), identicalTo(TRUE))
test.is.list.31 <- function() assertThat(is.list(pairlist(41, "a", 21L)), identicalTo(TRUE))
test.is.list.32 <- function() assertThat(is.list(pairlist(a = 41, 42)), identicalTo(TRUE))
test.is.list.33 <- function() assertThat(is.list(pairlist(a = 41, NULL)), identicalTo(TRUE))
test.is.list.34 <- function() assertThat(is.list(structure(1:12, .Dim = 3:4)), identicalTo(FALSE))
test.is.list.35 <- function() assertThat(is.list(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(    x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))), identicalTo(FALSE))
test.is.list.36 <- function() assertThat(is.list(structure(1:3, rando.attrib = 941L)), identicalTo(FALSE))
test.is.list.37 <- function() assertThat(is.list(structure(1:3, .Dim = 3L, .Dimnames = list(c("a", "b", "c")))), identicalTo(FALSE))
test.is.list.38 <- function() assertThat(is.list(structure(1:3, .Dim = 3L, .Dimnames = structure(list(    z = c("a", "b", "c")), .Names = "z"))), identicalTo(FALSE))
test.is.list.39 <- function() assertThat(is.list(structure(list("foo"), class = "foo")), identicalTo(TRUE))
test.is.list.40 <- function() assertThat(is.list(structure(list("bar"), class = "foo")), identicalTo(TRUE))
test.is.list.41 <- function() assertThat(is.list(quote(xyz)), identicalTo(FALSE))
test.is.list.42 <- function() assertThat(is.list(quote(sin(3.14))), identicalTo(FALSE))
test.is.list.43 <- function() assertThat(is.list(structure("foo", class = "foo")), identicalTo(FALSE))
test.is.list.44 <- function() assertThat(is.list(structure(list(1L, "bar"), class = "bar")), identicalTo(TRUE))
