library(hamcrest)

 
 
expected <- structure(list("$" = structure(list(), .Names = character(0)), 
    "$<-" = structure(list(), .Names = character(0)), Arith = list(), 
    Compare = list(), Complex = list(), Logic = list(), Math2 = structure(list(), .Names = character(0)), 
    Math = structure(list(), .Names = character(0)), Ops = structure(list(), .Names = character(0)), 
    Summary = list(), "[" = structure(list(), .Names = character(0)), 
    "[<-" = structure(list(), .Names = character(0)), "[[<-" = structure(list(), .Names = character(0)), 
    addNextMethod = structure(list(), .Names = character(0)), 
    "body<-" = structure(list(), .Names = character(0)), cbind2 = structure(list(), .Names = character(0)), 
    coerce = structure(list("oldClass#S3" = ""), .Names = "oldClass#S3"), 
    "coerce<-" = structure(list(), .Names = character(0)), initialize = structure(list(
        oldClass = ""), .Names = "oldClass"), kronecker = structure(list(), .Names = character(0)), 
    loadMethod = structure(list(), .Names = character(0)), rbind2 = structure(list(), .Names = character(0)), 
    show = structure(list(oldClass = ""), .Names = "oldClass"), 
    slotsFromS3 = structure(list(oldClass = ""), .Names = "oldClass")), .Names = c("$", 
"$<-", "Arith", "Compare", "Complex", "Logic", "Math2", "Math", 
"Ops", "Summary", "[", "[<-", "[[<-", "addNextMethod", "body<-", 
"cbind2", "coerce", "coerce<-", "initialize", "kronecker", "loadMethod", 
"rbind2", "show", "slotsFromS3")) 


assertThat(base:::mapply(FUN=function (elt, geom) 
elt[geom],structure(list("$" = structure(list("C++Class" = "Rcpp", envRefClass = "methods", 
    refObjectGenerator = "", Module = "Rcpp", ANY = ""), .Names = c("C++Class", 
"envRefClass", "refObjectGenerator", "Module", "ANY")), "$<-" = structure(list(
    localRefClass = "", data.frame = "", envRefClass = "methods", 
    refObjectGenerator = "", ANY = ""), .Names = c("localRefClass", 
"data.frame", "envRefClass", "refObjectGenerator", "ANY")), Arith = list(), 
    Compare = list(), Complex = list(), Logic = list(), Math2 = structure(list(
        structure = "", nonStructure = ""), .Names = c("structure", 
    "nonStructure")), Math = structure(list(structure = "", nonStructure = ""), .Names = c("structure", 
    "nonStructure")), Ops = structure(list("vector#nonStructure" = "", 
        "structure#vector" = "", "structure#array" = "", "vector#structure" = "", 
        "array#array" = "", "nonStructure#vector" = "", "array#structure" = "", 
        "structure#structure" = "", "nonStructure#nonStructure" = ""), .Names = c("vector#nonStructure", 
    "structure#vector", "structure#array", "vector#structure", 
    "array#array", "nonStructure#vector", "array#structure", 
    "structure#structure", "nonStructure#nonStructure")), Summary = list(), 
    "[" = structure(list(nonStructure = "", ANY = ""), .Names = c("nonStructure", 
    "ANY")), "[<-" = structure(list(data.frame = "", ANY = ""), .Names = c("data.frame", 
    "ANY")), "[[<-" = structure(list(data.frame = "", ANY = ""), .Names = c("data.frame", 
    "ANY")), addNextMethod = structure(list(MethodWithNext = "", 
        MethodDefinition = ""), .Names = c("MethodWithNext", 
    "MethodDefinition")), "body<-" = structure(list(MethodDefinition = "", 
        ANY = "base"), .Names = c("MethodDefinition", "ANY")), 
    cbind2 = structure(list("ANY#missing" = "", "ANY#ANY" = ""), .Names = c("ANY#missing", 
    "ANY#ANY")), coerce = structure(list("derivedDefaultMethod#function" = "methods", 
        "ANY#expression" = "methods", "ANY#vector" = "methods", 
        "ANY#NULL" = "methods", "ANY#logical" = "methods", "function#classGeneratorFunction" = "methods", 
        "ANY#call" = "methods", "ANY#array" = "methods", "ANY#ts" = "", 
        "NULL#OptionalFunction" = "methods", "function#OptionalFunction" = "methods", 
        "ANY#list" = "methods", "NULL#optionalMethod" = "methods", 
        "groupGenericFunction#genericFunction" = "methods", "ANY#environment" = "methods", 
        "ANY#function" = "methods", "ANY#complex" = "methods", 
        "oldClass#S3" = "", "character#signature" = "methods", 
        "ANY#name" = "methods", "character#SuperClassMethod" = "methods", 
        "ANY#integer" = "methods", "ANY#character" = "methods", 
        "ANY#S3" = "", "ANY#S4" = "", "ANY#numeric" = "methods", 
        "ANY#matrix" = "methods"), .Names = c("derivedDefaultMethod#function", 
    "ANY#expression", "ANY#vector", "ANY#NULL", "ANY#logical", 
    "function#classGeneratorFunction", "ANY#call", "ANY#array", 
    "ANY#ts", "NULL#OptionalFunction", "function#OptionalFunction", 
    "ANY#list", "NULL#optionalMethod", "groupGenericFunction#genericFunction", 
    "ANY#environment", "ANY#function", "ANY#complex", "oldClass#S3", 
    "character#signature", "ANY#name", "character#SuperClassMethod", 
    "ANY#integer", "ANY#character", "ANY#S3", "ANY#S4", "ANY#numeric", 
    "ANY#matrix")), "coerce<-" = structure(list("groupGenericFunction#function" = "methods", 
        "genericFunction#function" = "methods", "ClassUnionRepresentation#classRepresentation" = "methods", 
        "signature#character" = "methods", "ObjectsWithPackage#character" = "methods", 
        "MethodDefinition#function" = "methods", "classGeneratorFunction#function" = "methods", 
        "refMethodDef#function" = "methods", "refClassRepresentation#classRepresentation" = "methods", 
        "refObjectGenerator#classGeneratorFunction" = "methods"), .Names = c("groupGenericFunction#function", 
    "genericFunction#function", "ClassUnionRepresentation#classRepresentation", 
    "signature#character", "ObjectsWithPackage#character", "MethodDefinition#function", 
    "classGeneratorFunction#function", "refMethodDef#function", 
    "refClassRepresentation#classRepresentation", "refObjectGenerator#classGeneratorFunction"
    )), initialize = structure(list(mts = "", array = "", environment = "", 
        traceable = "", matrix = "", externalRefMethod = "", 
        envRefClass = "methods", MethodsList = "", Module = "Rcpp", 
        signature = "", ANY = "methods", ts = "", oldClass = ""), .Names = c("mts", 
    "array", "environment", "traceable", "matrix", "externalRefMethod", 
    "envRefClass", "MethodsList", "Module", "signature", "ANY", 
    "ts", "oldClass")), kronecker = structure(list(ANY = ""), .Names = "ANY"), 
    loadMethod = structure(list(MethodWithNext = "", MethodDefinition = "", 
        ANY = "methods"), .Names = c("MethodWithNext", "MethodDefinition", 
    "ANY")), rbind2 = structure(list("ANY#missing" = "", "ANY#ANY" = ""), .Names = c("ANY#missing", 
    "ANY#ANY")), show = structure(list(MethodWithNext = "", refClassRepresentation = "", 
        genericFunction = "", refMethodDef = "methods", signature = "", 
        "C++Function" = "Rcpp", classRepresentation = "", ObjectsWithPackage = "", 
        MethodDefinition = "", "C++Object" = "Rcpp", externalRefMethod = "methods", 
        sourceEnvironment = "methods", MethodDefinitionWithTrace = "methods", 
        namedList = "", envRefClass = "", genericFunctionWithTrace = "methods", 
        refObjectGenerator = "", "C++Class" = "Rcpp", oldClass = "", 
        ANY = "methods", traceable = "methods", Module = "Rcpp", 
        classGeneratorFunction = "", MethodWithNextWithTrace = "methods", 
        MethodSelectionReport = ""), .Names = c("MethodWithNext", 
    "refClassRepresentation", "genericFunction", "refMethodDef", 
    "signature", "C++Function", "classRepresentation", "ObjectsWithPackage", 
    "MethodDefinition", "C++Object", "externalRefMethod", "sourceEnvironment", 
    "MethodDefinitionWithTrace", "namedList", "envRefClass", 
    "genericFunctionWithTrace", "refObjectGenerator", "C++Class", 
    "oldClass", "ANY", "traceable", "Module", "classGeneratorFunction", 
    "MethodWithNextWithTrace", "MethodSelectionReport")), slotsFromS3 = structure(list(
        data.frame = "", factor = "", ANY = "methods", ts = "", 
        oldClass = ""), .Names = c("data.frame", "factor", "ANY", 
    "ts", "oldClass"))), .Names = c("$", "$<-", "Arith", "Compare", 
"Complex", "Logic", "Math2", "Math", "Ops", "Summary", "[", "[<-", 
"[[<-", "addNextMethod", "body<-", "cbind2", "coerce", "coerce<-", 
"initialize", "kronecker", "loadMethod", "rbind2", "show", "slotsFromS3"
)),structure(list("$" = structure(c(FALSE, FALSE, FALSE, FALSE, 
FALSE), .Names = c("C++Class", "envRefClass", "refObjectGenerator", 
"Module", "ANY")), "$<-" = structure(c(FALSE, FALSE, FALSE, FALSE, 
FALSE), .Names = c("localRefClass", "data.frame", "envRefClass", 
"refObjectGenerator", "ANY")), Arith = logical(0), Compare = logical(0), 
    Complex = logical(0), Logic = logical(0), Math2 = structure(c(FALSE, 
    FALSE), .Names = c("structure", "nonStructure")), Math = structure(c(FALSE, 
    FALSE), .Names = c("structure", "nonStructure")), Ops = structure(c(FALSE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE), .Names = c("vector#nonStructure", 
    "structure#vector", "structure#array", "vector#structure", 
    "array#array", "nonStructure#vector", "array#structure", 
    "structure#structure", "nonStructure#nonStructure")), Summary = logical(0), 
    "[" = structure(c(FALSE, FALSE), .Names = c("nonStructure", 
    "ANY")), "[<-" = structure(c(FALSE, FALSE), .Names = c("data.frame", 
    "ANY")), "[[<-" = structure(c(FALSE, FALSE), .Names = c("data.frame", 
    "ANY")), addNextMethod = structure(c(FALSE, FALSE), .Names = c("MethodWithNext", 
    "MethodDefinition")), "body<-" = structure(c(FALSE, FALSE
    ), .Names = c("MethodDefinition", "ANY")), cbind2 = structure(c(FALSE, 
    FALSE), .Names = c("ANY#missing", "ANY#ANY")), coerce = structure(c(FALSE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE), .Names = c("derivedDefaultMethod#function", 
    "ANY#expression", "ANY#vector", "ANY#NULL", "ANY#logical", 
    "function#classGeneratorFunction", "ANY#call", "ANY#array", 
    "ANY#ts", "NULL#OptionalFunction", "function#OptionalFunction", 
    "ANY#list", "NULL#optionalMethod", "groupGenericFunction#genericFunction", 
    "ANY#environment", "ANY#function", "ANY#complex", "oldClass#S3", 
    "character#signature", "ANY#name", "character#SuperClassMethod", 
    "ANY#integer", "ANY#character", "ANY#S3", "ANY#S4", "ANY#numeric", 
    "ANY#matrix")), "coerce<-" = structure(c(FALSE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE), .Names = c("groupGenericFunction#function", 
    "genericFunction#function", "ClassUnionRepresentation#classRepresentation", 
    "signature#character", "ObjectsWithPackage#character", "MethodDefinition#function", 
    "classGeneratorFunction#function", "refMethodDef#function", 
    "refClassRepresentation#classRepresentation", "refObjectGenerator#classGeneratorFunction"
    )), initialize = structure(c(FALSE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE
    ), .Names = c("mts", "array", "environment", "traceable", 
    "matrix", "externalRefMethod", "envRefClass", "MethodsList", 
    "Module", "signature", "ANY", "ts", "oldClass")), kronecker = structure(FALSE, .Names = "ANY"), 
    loadMethod = structure(c(FALSE, FALSE, FALSE), .Names = c("MethodWithNext", 
    "MethodDefinition", "ANY")), rbind2 = structure(c(FALSE, 
    FALSE), .Names = c("ANY#missing", "ANY#ANY")), show = structure(c(FALSE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, FALSE), .Names = c("MethodWithNext", 
    "refClassRepresentation", "genericFunction", "refMethodDef", 
    "signature", "C++Function", "classRepresentation", "ObjectsWithPackage", 
    "MethodDefinition", "C++Object", "externalRefMethod", "sourceEnvironment", 
    "MethodDefinitionWithTrace", "namedList", "envRefClass", 
    "genericFunctionWithTrace", "refObjectGenerator", "C++Class", 
    "oldClass", "ANY", "traceable", "Module", "classGeneratorFunction", 
    "MethodWithNextWithTrace", "MethodSelectionReport")), slotsFromS3 = structure(c(FALSE, 
    FALSE, FALSE, FALSE, TRUE), .Names = c("data.frame", "factor", 
    "ANY", "ts", "oldClass"))), .Names = c("$", "$<-", "Arith", 
"Compare", "Complex", "Logic", "Math2", "Math", "Ops", "Summary", 
"[", "[<-", "[[<-", "addNextMethod", "body<-", "cbind2", "coerce", 
"coerce<-", "initialize", "kronecker", "loadMethod", "rbind2", 
"show", "slotsFromS3")))
,  equalTo( expected ) ) 
 

