#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2016 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-math-unary-tests.R using GNU R version 3.2.0 (2015-04-16)
library(hamcrest)
atanh.foo <- function(...) 41
Math.bar <- function(...) 44
test.atanh.1 <- function() assertThat(atanh(-0.01), identicalTo(-0.0100003333533348, tol = 0.000100))
test.atanh.2 <- function() assertThat(atanh(-0.1), identicalTo(-0.100335347731076, tol = 0.000100))
test.atanh.3 <- function() assertThat(atanh(-1), identicalTo(-Inf))
test.atanh.4 <- function() assertThat(atanh(-1.5), identicalTo(NaN))
test.atanh.5 <- function() assertThat(atanh(-2), identicalTo(NaN))
test.atanh.6 <- function() assertThat(atanh(-2.5), identicalTo(NaN))
test.atanh.7 <- function() assertThat(atanh(-4), identicalTo(NaN))
test.atanh.8 <- function() assertThat(atanh(-10), identicalTo(NaN))
test.atanh.9 <- function() assertThat(atanh(-100), identicalTo(NaN))
test.atanh.10 <- function() assertThat(atanh(-0.785398), identicalTo(-1.05930574436491, tol = 0.000100))
test.atanh.11 <- function() assertThat(atanh(-1.5708), identicalTo(NaN))
test.atanh.12 <- function() assertThat(atanh(-3.14159), identicalTo(NaN))
test.atanh.13 <- function() assertThat(atanh(-6.28319), identicalTo(NaN))
test.atanh.14 <- function() assertThat(atanh(0.01), identicalTo(0.0100003333533348, tol = 0.000100))
test.atanh.15 <- function() assertThat(atanh(0.1), identicalTo(0.100335347731076, tol = 0.000100))
test.atanh.16 <- function() assertThat(atanh(1), identicalTo(Inf))
test.atanh.17 <- function() assertThat(atanh(1.5), identicalTo(NaN))
test.atanh.18 <- function() assertThat(atanh(2), identicalTo(NaN))
test.atanh.19 <- function() assertThat(atanh(2.5), identicalTo(NaN))
test.atanh.20 <- function() assertThat(atanh(4), identicalTo(NaN))
test.atanh.21 <- function() assertThat(atanh(10), identicalTo(NaN))
test.atanh.22 <- function() assertThat(atanh(100), identicalTo(NaN))
test.atanh.23 <- function() assertThat(atanh(0.785398), identicalTo(1.05930574436491, tol = 0.000100))
test.atanh.24 <- function() assertThat(atanh(1.5708), identicalTo(NaN))
test.atanh.25 <- function() assertThat(atanh(3.14159), identicalTo(NaN))
test.atanh.26 <- function() assertThat(atanh(6.28319), identicalTo(NaN))
test.atanh.27 <- function() assertThat(atanh(NULL), throwsError())
test.atanh.28 <- function() assertThat(atanh(c(0.01, 0.1, 1, 1.5)), identicalTo(c(0.0100003333533348, 0.100335347731076, Inf, NaN), tol = 0.000100))
test.atanh.29 <- function() assertThat(atanh(integer(0)), identicalTo(numeric(0)))
test.atanh.30 <- function() assertThat(atanh(numeric(0)), identicalTo(numeric(0)))
test.atanh.31 <- function() assertThat(atanh(NaN), identicalTo(NaN))
test.atanh.32 <- function() assertThat(atanh(NA_real_), identicalTo(NA_real_))
test.atanh.33 <- function() assertThat(atanh(Inf), identicalTo(NaN))
test.atanh.34 <- function() assertThat(atanh(-Inf), identicalTo(NaN))
test.atanh.35 <- function() assertThat(atanh(c(1L, 4L)), identicalTo(c(Inf, NaN)))
test.atanh.36 <- function() assertThat(atanh(structure(1, class = "foo")), identicalTo(41))
test.atanh.37 <- function() assertThat(atanh(structure(1, class = "bar")), identicalTo(44))
test.atanh.38 <- function() assertThat(atanh(structure(list("a"), class = "foo")), identicalTo(41))
test.atanh.39 <- function() assertThat(atanh(structure(list("b"), class = "bar")), identicalTo(44))
test.atanh.40 <- function() assertThat(atanh(structure(c(1, 2, 3), .Names = c("a", "b", "c"))), identicalTo(structure(c(Inf, NaN, NaN), .Names = c("a", "b", "c"))))
test.atanh.41 <- function() assertThat(atanh(structure(c(1, 2), .Names = c("x", ""))), identicalTo(structure(c(Inf, NaN), .Names = c("x", ""))))
test.atanh.42 <- function() assertThat(atanh(structure(1:12, .Dim = 3:4)), identicalTo(structure(c(Inf, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN), .Dim = 3:4)))
test.atanh.43 <- function() assertThat(atanh(structure(0, rando.attr = 4L)), identicalTo(structure(0, rando.attr = 4L)))
test.atanh.44 <- function() assertThat(atanh(structure(0, class = "zinga")), identicalTo(structure(0, class = "zinga")))
