#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2019 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-unary-tests.R using GNU R version 3.3.3 (2017-03-06)
library(hamcrest)
Sys.setlocale('LC_COLLATE', 'C')
as.single.foo <- function(...) 41L
as.vector.foo <- function(...) 99
Math.bar <- function(...) 44
Summary.bar <- function(...) 45
Ops.bar <- function(...) 46
test.as.single.1 <- function() assertThat(as.single(NULL), identicalTo(structure(numeric(0), Csingle = TRUE)))
test.as.single.2 <- function() assertThat(as.single(logical(0)), identicalTo(structure(numeric(0), Csingle = TRUE)))
test.as.single.3 <- function() assertThat(as.single(c(TRUE, TRUE, FALSE, FALSE, TRUE)), identicalTo(structure(c(1, 1, 0, 0, 1), Csingle = TRUE)))
test.as.single.4 <- function() assertThat(as.single(structure(c(TRUE, FALSE), .Names = c("a", ""))), identicalTo(structure(c(1, 0), Csingle = TRUE)))
test.as.single.5 <- function() assertThat(as.single(c(TRUE, FALSE, NA)), identicalTo(structure(c(1, 0, NA), Csingle = TRUE)))
test.as.single.6 <- function() assertThat(as.single(integer(0)), identicalTo(structure(numeric(0), Csingle = TRUE)))
test.as.single.7 <- function() assertThat(as.single(structure(integer(0), .Names = character(0))), identicalTo(structure(numeric(0), Csingle = TRUE)))
test.as.single.8 <- function() assertThat(as.single(1:3), identicalTo(structure(c(1, 2, 3), Csingle = TRUE)))
test.as.single.9 <- function() assertThat(as.single(c(1L, NA, 4L, NA, 999L)), identicalTo(structure(c(1, NA, 4, NA, 999), Csingle = TRUE)))
test.as.single.10 <- function() assertThat(as.single(c(1L, 2L, 1073741824L, 1073741824L)), identicalTo(structure(c(1, 2, 1073741824, 1073741824), Csingle = TRUE), tol = 0.000100))
test.as.single.11 <- function() assertThat(as.single(numeric(0)), identicalTo(structure(numeric(0), Csingle = TRUE)))
test.as.single.12 <- function() assertThat(as.single(c(3.14159, 6.28319, 9.42478, 12.5664, 15.708)), identicalTo(structure(c(3.14159, 6.28319, 9.42478, 12.5664, 15.708), Csingle = TRUE), tol = 0.000100))
test.as.single.13 <- function() assertThat(as.single(c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708)), identicalTo(structure(c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708), Csingle = TRUE), tol = 0.000100))
test.as.single.14 <- function() assertThat(as.single(structure(1:2, .Names = c("a", "b"))), identicalTo(structure(c(1, 2), Csingle = TRUE)))
test.as.single.15 <- function() assertThat(as.single(structure(c(1.5, 2.5), .Names = c("a", "b"))), identicalTo(structure(c(1.5, 2.5), Csingle = TRUE), tol = 0.000100))
test.as.single.16 <- function() assertThat(as.single(c(1.5, 1.51, 0, 1.49, -30)), identicalTo(structure(c(1.5, 1.51, 0, 1.49, -30), Csingle = TRUE), tol = 0.000100))
test.as.single.17 <- function() assertThat(as.single(c(1.5, 1.51, 0, 1.49, -30, NA)), identicalTo(structure(c(1.5, 1.51, 0, 1.49, -30, NA), Csingle = TRUE), tol = 0.000100))
test.as.single.18 <- function() assertThat(as.single(c(1.5, 1.51, 0, 1.49, -30, NaN)), identicalTo(structure(c(1.5, 1.51, 0, 1.49, -30, NaN), Csingle = TRUE), tol = 0.000100))
test.as.single.19 <- function() assertThat(as.single(c(1.5, 1.51, 0, 1.49, -30, Inf)), identicalTo(structure(c(1.5, 1.51, 0, 1.49, -30, Inf), Csingle = TRUE), tol = 0.000100))
test.as.single.20 <- function() assertThat(as.single(c(1.5, 1.51, 0, 1.49, -30, -Inf)), identicalTo(structure(c(1.5, 1.51, 0, 1.49, -30, -Inf), Csingle = TRUE), tol = 0.000100))
test.as.single.21 <- function() assertThat(as.single(character(0)), identicalTo(structure(numeric(0), Csingle = TRUE)))
test.as.single.22 <- function() assertThat(as.single(c("4.1", "blahh", "99.9", "-413", NA)), identicalTo(structure(c(4.1, NA, 99.9, -413, NA), Csingle = TRUE), tol = 0.000100))
test.as.single.23 <- function() assertThat(as.single(complex(0)), identicalTo(structure(numeric(0), Csingle = TRUE)))
test.as.single.24 <- function() assertThat(as.single(list(1, 2, 3)), identicalTo(structure(c(1, 2, 3), Csingle = TRUE)))
test.as.single.25 <- function() assertThat(as.single(list(1, 2, NULL)), throwsError())
test.as.single.26 <- function() assertThat(as.single(list(1L, 2L, 3L)), identicalTo(structure(c(1, 2, 3), Csingle = TRUE)))
test.as.single.27 <- function() assertThat(as.single(list(1L, 2L, NULL)), throwsError())
test.as.single.28 <- function() assertThat(as.single(list(1, 2, list(3, 4))), throwsError())
test.as.single.29 <- function() assertThat(as.single(list(1, 2, numeric(0))), identicalTo(structure(c(1, 2, NA), Csingle = TRUE)))
test.as.single.30 <- function() assertThat(as.single(list(3, "a", structure(list("b", z = list(TRUE, "c")), .Names = c("", "z")))), throwsError())
test.as.single.31 <- function() assertThat(as.single(structure(list(`NA` = 1, 2, b = 3), .Names = c(NA, "", "b"))), identicalTo(structure(c(1, 2, 3), Csingle = TRUE)))
test.as.single.32 <- function() assertThat(as.single(pairlist(41, "a", 21L)), identicalTo(structure(c(41, NA, 21), Csingle = TRUE)))
test.as.single.33 <- function() assertThat(as.single(pairlist(a = 41, 42)), identicalTo(structure(c(41, 42), Csingle = TRUE)))
test.as.single.34 <- function() assertThat(as.single(pairlist(a = 41, NULL)), throwsError())
test.as.single.35 <- function() assertThat(as.single(structure(1:12, .Dim = 3:4)), identicalTo(structure(c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12), Csingle = TRUE)))
test.as.single.36 <- function() assertThat(as.single(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(    x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))), identicalTo(structure(c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12), Csingle = TRUE)))
test.as.single.37 <- function() assertThat(as.single(structure(1:3, rando.attrib = 941L)), identicalTo(structure(c(1, 2, 3), Csingle = TRUE)))
test.as.single.38 <- function() assertThat(as.single(structure(1:3, .Dim = 3L, .Dimnames = list(c("a", "b", "c")))), identicalTo(structure(c(1, 2, 3), Csingle = TRUE)))
test.as.single.39 <- function() assertThat(as.single(structure(1:3, .Dim = 3L, .Dimnames = structure(list(    z = c("a", "b", "c")), .Names = "z"))), identicalTo(structure(c(1, 2, 3), Csingle = TRUE)))
test.as.single.40 <- function() assertThat(as.single(structure(list("foo"), class = "foo")), identicalTo(41L))
test.as.single.41 <- function() assertThat(as.single(structure(list("bar"), class = "foo")), identicalTo(41L))
test.as.single.42 <- function() assertThat(as.single(quote(xyz)), throwsError())
test.as.single.43 <- function() assertThat(as.single(quote(sin(3.14))), throwsError())
test.as.single.44 <- function() assertThat(as.single("NaN"), identicalTo(structure(NaN, Csingle = TRUE)))
test.as.single.45 <- function() assertThat(as.single("NABOOM!"), identicalTo(structure(NA_real_, Csingle = TRUE)))
test.as.single.46 <- function() assertThat(as.single("NaNaNabooboo"), identicalTo(structure(NA_real_, Csingle = TRUE)))
test.as.single.47 <- function() assertThat(as.single("-Inf"), identicalTo(structure(-Inf, Csingle = TRUE)))
test.as.single.48 <- function() assertThat(as.single("+Infinity"), identicalTo(structure(Inf, Csingle = TRUE)))
test.as.single.49 <- function() assertThat(as.single("Infinity and beyond!"), identicalTo(structure(NA_real_, Csingle = TRUE)))
test.as.single.50 <- function() assertThat(as.single("Infi"), identicalTo(structure(NA_real_, Csingle = TRUE)))
test.as.single.51 <- function() assertThat(as.single("0.03f"), identicalTo(structure(NA_real_, Csingle = TRUE)))
test.as.single.52 <- function() assertThat(as.single("  0.0330   "), identicalTo(structure(0.033, Csingle = TRUE), tol = 0.000100))
test.as.single.53 <- function() assertThat(as.single(structure("foo", class = "foo")), identicalTo(41L))
test.as.single.54 <- function() assertThat(as.single(structure(list(1L, "bar"), class = "bar")), identicalTo(structure(c(1, NA), Csingle = TRUE)))
