#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2018 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-unary-tests.R using GNU R version 3.5.3 (2019-03-11)
library(hamcrest)
Sys.setlocale('LC_COLLATE', 'C')
is.nan.foo <- function(...) 41L
as.vector.foo <- function(...) 99
as.vector.bar <- function(...) 98
Math.bar <- function(...) 44
Summary.bar <- function(...) 45
Ops.bar <- function(...) 46
test.is.nan.1 <- function() assertThat(is.nan(NULL), identicalTo(logical(0)))
test.is.nan.2 <- function() assertThat(is.nan(logical(0)), identicalTo(logical(0)))
test.is.nan.3 <- function() assertThat(is.nan(c(TRUE, TRUE, FALSE, FALSE, TRUE)), identicalTo(c(FALSE, FALSE, FALSE, FALSE, FALSE)))
test.is.nan.4 <- function() assertThat(is.nan(structure(c(TRUE, FALSE), .Names = c("a", ""))), identicalTo(structure(c(FALSE, FALSE), .Names = c("a", ""))))
test.is.nan.5 <- function() assertThat(is.nan(c(TRUE, FALSE, NA)), identicalTo(c(FALSE, FALSE, FALSE)))
test.is.nan.6 <- function() assertThat(is.nan(integer(0)), identicalTo(logical(0)))
test.is.nan.7 <- function() assertThat(is.nan(structure(integer(0), .Names = character(0))), identicalTo(structure(logical(0), .Names = character(0))))
test.is.nan.8 <- function() assertThat(is.nan(1:3), identicalTo(c(FALSE, FALSE, FALSE)))
test.is.nan.9 <- function() assertThat(is.nan(c(1L, NA, 4L, NA, 999L)), identicalTo(c(FALSE, FALSE, FALSE, FALSE, FALSE)))
test.is.nan.10 <- function() assertThat(is.nan(c(1L, 2L, 1073741824L, 1073741824L)), identicalTo(c(FALSE, FALSE, FALSE, FALSE)))
test.is.nan.11 <- function() assertThat(is.nan(numeric(0)), identicalTo(logical(0)))
test.is.nan.12 <- function() assertThat(is.nan(c(3.14159, 6.28319, 9.42478, 12.5664, 15.708)), identicalTo(c(FALSE, FALSE, FALSE, FALSE, FALSE)))
test.is.nan.13 <- function() assertThat(is.nan(c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708)), identicalTo(c(FALSE, FALSE, FALSE, FALSE, FALSE)))
test.is.nan.14 <- function() assertThat(is.nan(structure(1:2, .Names = c("a", "b"))), identicalTo(structure(c(FALSE, FALSE), .Names = c("a", "b"))))
test.is.nan.15 <- function() assertThat(is.nan(structure(c(1.5, 2.5), .Names = c("a", "b"))), identicalTo(structure(c(FALSE, FALSE), .Names = c("a", "b"))))
test.is.nan.16 <- function() assertThat(is.nan(c(1.5, 1.51, 0, 1.49, -30)), identicalTo(c(FALSE, FALSE, FALSE, FALSE, FALSE)))
test.is.nan.17 <- function() assertThat(is.nan(c(1.5, 1.51, 0, 1.49, -30, NA)), identicalTo(c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE)))
test.is.nan.18 <- function() assertThat(is.nan(c(1.5, 1.51, 0, 1.49, -30, NaN)), identicalTo(c(FALSE, FALSE, FALSE, FALSE, FALSE, TRUE)))
test.is.nan.19 <- function() assertThat(is.nan(c(1.5, 1.51, 0, 1.49, -30, Inf)), identicalTo(c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE)))
test.is.nan.20 <- function() assertThat(is.nan(c(1.5, 1.51, 0, 1.49, -30, -Inf)), identicalTo(c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE)))
test.is.nan.21 <- function() assertThat(is.nan(character(0)), identicalTo(logical(0)))
test.is.nan.22 <- function() assertThat(is.nan(c("4.1", "blahh", "99.9", "-413", NA)), identicalTo(c(FALSE, FALSE, FALSE, FALSE, FALSE)))
test.is.nan.23 <- function() assertThat(is.nan(complex(0)), identicalTo(logical(0)))
test.is.nan.24 <- function() assertThat(is.nan(list(1, 2, 3)), throwsError())
test.is.nan.25 <- function() assertThat(is.nan(list(1, 2, NULL)), throwsError())
test.is.nan.26 <- function() assertThat(is.nan(list(1L, 2L, 3L)), throwsError())
test.is.nan.27 <- function() assertThat(is.nan(list(1L, 2L, NULL)), throwsError())
test.is.nan.28 <- function() assertThat(is.nan(list(1, 2, list(3, 4))), throwsError())
test.is.nan.29 <- function() assertThat(is.nan(list(1, 2, numeric(0))), throwsError())
test.is.nan.30 <- function() assertThat(is.nan(list(3, "a", structure(list("b", list(TRUE, "c")), .Names = c("", "z")))), throwsError())
test.is.nan.31 <- function() assertThat(is.nan(structure(list(1, 2, 3), .Names = c(NA, "", "b"))), throwsError())
test.is.nan.32 <- function() assertThat(is.nan(pairlist(41, "a", 21L)), throwsError())
test.is.nan.33 <- function() assertThat(is.nan(structure(pairlist(a = 41, 42))), throwsError())
test.is.nan.34 <- function() assertThat(is.nan(structure(pairlist(a = 41, NULL))), throwsError())
test.is.nan.35 <- function() assertThat(is.nan(structure(1:12, .Dim = 3:4)), identicalTo(structure(c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE), .Dim = 3:4)))
test.is.nan.36 <- function() assertThat(is.nan(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(    c("a", "b", "c"), c("d", "e", "f", "g")), .Names = c("x", "y")))), identicalTo(structure(c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE), .Dim = 3:4, .Dimnames = structure(list(    c("a", "b", "c"), c("d", "e", "f", "g")), .Names = c("x", "y")))))
test.is.nan.37 <- function() assertThat(is.nan(structure(1:3, rando.attrib = 941L)), identicalTo(c(FALSE, FALSE, FALSE)))
test.is.nan.38 <- function() assertThat(is.nan(structure(1:3, .Dim = 3L, .Dimnames = list(c("a", "b", "c")))), identicalTo(structure(c(FALSE, FALSE, FALSE), .Dim = 3L, .Dimnames = list(    c("a", "b", "c")))))
test.is.nan.39 <- function() assertThat(is.nan(structure(1:3, .Dim = 3L, .Dimnames = structure(list(c("a", "b", "c")), .Names = "z"))), identicalTo(structure(c(FALSE, FALSE, FALSE), .Dim = 3L, .Dimnames = structure(list(    c("a", "b", "c")), .Names = "z"))))
test.is.nan.40 <- function() assertThat(is.nan(structure(list("foo"), class = "foo")), identicalTo(41L))
test.is.nan.41 <- function() assertThat(is.nan(structure(list("bar"), class = "foo")), identicalTo(41L))
test.is.nan.42 <- function() assertThat(is.nan(quote(xyz)), throwsError())
test.is.nan.43 <- function() assertThat(is.nan(quote(sin(3.14))), throwsError())
test.is.nan.44 <- function() assertThat(is.nan("NaN"), identicalTo(FALSE))
test.is.nan.45 <- function() assertThat(is.nan("NABOOM!"), identicalTo(FALSE))
test.is.nan.46 <- function() assertThat(is.nan("NaNaNabooboo"), identicalTo(FALSE))
test.is.nan.47 <- function() assertThat(is.nan("-Inf"), identicalTo(FALSE))
test.is.nan.48 <- function() assertThat(is.nan("+Infinity"), identicalTo(FALSE))
test.is.nan.49 <- function() assertThat(is.nan("Infinity and beyond!"), identicalTo(FALSE))
test.is.nan.50 <- function() assertThat(is.nan("Infi"), identicalTo(FALSE))
test.is.nan.51 <- function() assertThat(is.nan("0.03f"), identicalTo(FALSE))
test.is.nan.52 <- function() assertThat(is.nan("  0.0330   "), identicalTo(FALSE))
test.is.nan.53 <- function() assertThat(is.nan(structure("foo", class = "foo")), identicalTo(41L))
test.is.nan.54 <- function() assertThat(is.nan(structure(list(1L, "bar"), class = "bar")), throwsError())
