#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2016 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-unary-tests.R using GNU R version 3.3.3 (2017-03-06)
library(hamcrest)
Sys.setlocale('LC_COLLATE', 'C')
is.R.foo <- function(...) 41L
as.vector.foo <- function(...) 99
Math.bar <- function(...) 44
Summary.bar <- function(...) 45
Ops.bar <- function(...) 46
test.is.R.1 <- function() assertThat(is.R(NULL), throwsError())
test.is.R.2 <- function() assertThat(is.R(logical(0)), throwsError())
test.is.R.3 <- function() assertThat(is.R(c(TRUE, TRUE, FALSE, FALSE, TRUE)), throwsError())
test.is.R.4 <- function() assertThat(is.R(structure(c(TRUE, FALSE), .Names = c("a", ""))), throwsError())
test.is.R.5 <- function() assertThat(is.R(c(TRUE, FALSE, NA)), throwsError())
test.is.R.6 <- function() assertThat(is.R(integer(0)), throwsError())
test.is.R.7 <- function() assertThat(is.R(structure(integer(0), .Names = character(0))), throwsError())
test.is.R.8 <- function() assertThat(is.R(1:3), throwsError())
test.is.R.9 <- function() assertThat(is.R(c(1L, NA, 4L, NA, 999L)), throwsError())
test.is.R.10 <- function() assertThat(is.R(c(1L, 2L, 1073741824L, 1073741824L)), throwsError())
test.is.R.11 <- function() assertThat(is.R(numeric(0)), throwsError())
test.is.R.12 <- function() assertThat(is.R(c(3.14159, 6.28319, 9.42478, 12.5664, 15.708)), throwsError())
test.is.R.13 <- function() assertThat(is.R(c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708)), throwsError())
test.is.R.14 <- function() assertThat(is.R(structure(1:2, .Names = c("a", "b"))), throwsError())
test.is.R.15 <- function() assertThat(is.R(structure(c(1.5, 2.5), .Names = c("a", "b"))), throwsError())
test.is.R.16 <- function() assertThat(is.R(c(1.5, 1.51, 0, 1.49, -30)), throwsError())
test.is.R.17 <- function() assertThat(is.R(c(1.5, 1.51, 0, 1.49, -30, NA)), throwsError())
test.is.R.18 <- function() assertThat(is.R(c(1.5, 1.51, 0, 1.49, -30, NaN)), throwsError())
test.is.R.19 <- function() assertThat(is.R(c(1.5, 1.51, 0, 1.49, -30, Inf)), throwsError())
test.is.R.20 <- function() assertThat(is.R(c(1.5, 1.51, 0, 1.49, -30, -Inf)), throwsError())
test.is.R.21 <- function() assertThat(is.R(character(0)), throwsError())
test.is.R.22 <- function() assertThat(is.R(c("4.1", "blahh", "99.9", "-413", NA)), throwsError())
test.is.R.23 <- function() assertThat(is.R(complex(0)), throwsError())
test.is.R.24 <- function() assertThat(is.R(list(1, 2, 3)), throwsError())
test.is.R.25 <- function() assertThat(is.R(list(1, 2, NULL)), throwsError())
test.is.R.26 <- function() assertThat(is.R(list(1L, 2L, 3L)), throwsError())
test.is.R.27 <- function() assertThat(is.R(list(1L, 2L, NULL)), throwsError())
test.is.R.28 <- function() assertThat(is.R(list(1, 2, list(3, 4))), throwsError())
test.is.R.29 <- function() assertThat(is.R(list(1, 2, numeric(0))), throwsError())
test.is.R.30 <- function() assertThat(is.R(list(3, "a", structure(list("b", z = list(TRUE, "c")), .Names = c("", "z")))), throwsError())
test.is.R.31 <- function() assertThat(is.R(structure(list(`NA` = 1, 2, b = 3), .Names = c(NA, "", "b"))), throwsError())
test.is.R.32 <- function() assertThat(is.R(pairlist(41, "a", 21L)), throwsError())
test.is.R.33 <- function() assertThat(is.R(pairlist(a = 41, 42)), throwsError())
test.is.R.34 <- function() assertThat(is.R(pairlist(a = 41, NULL)), throwsError())
test.is.R.35 <- function() assertThat(is.R(structure(1:12, .Dim = 3:4)), throwsError())
test.is.R.36 <- function() assertThat(is.R(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))), throwsError())
test.is.R.37 <- function() assertThat(is.R(structure(1:3, rando.attrib = 941L)), throwsError())
test.is.R.38 <- function() assertThat(is.R(structure(1:3, .Dim = 3L, .Dimnames = list(c("a", "b", "c")))), throwsError())
test.is.R.39 <- function() assertThat(is.R(structure(1:3, .Dim = 3L, .Dimnames = structure(list(z = c("a", "b", "c")), .Names = "z"))), throwsError())
test.is.R.40 <- function() assertThat(is.R(structure(list("foo"), class = "foo")), throwsError())
test.is.R.41 <- function() assertThat(is.R(structure(list("bar"), class = "foo")), throwsError())
test.is.R.42 <- function() assertThat(is.R(quote(xyz)), throwsError())
test.is.R.43 <- function() assertThat(is.R(quote(sin(3.14))), throwsError())
test.is.R.44 <- function() assertThat(is.R("NaN"), throwsError())
test.is.R.45 <- function() assertThat(is.R("NABOOM!"), throwsError())
test.is.R.46 <- function() assertThat(is.R("NaNaNabooboo"), throwsError())
test.is.R.47 <- function() assertThat(is.R("-Inf"), throwsError())
test.is.R.48 <- function() assertThat(is.R("+Infinity"), throwsError())
test.is.R.49 <- function() assertThat(is.R("Infinity and beyond!"), throwsError())
test.is.R.50 <- function() assertThat(is.R("Infi"), throwsError())
test.is.R.51 <- function() assertThat(is.R("0.03f"), throwsError())
test.is.R.52 <- function() assertThat(is.R("  0.0330   "), throwsError())
test.is.R.53 <- function() assertThat(is.R(structure("foo", class = "foo")), throwsError())
test.is.R.54 <- function() assertThat(is.R(structure(list(1L, "bar"), class = "bar")), throwsError())
