# Generated by gen-dist-tests.R using GNU R version 3.2.0 (2015-04-16)
library(hamcrest)
library(stats)

test.rcauchy.1 <- function() assertThat({set.seed(1); rcauchy(n = 1, location = c(0, -2), scale = c(0, 0.5, 1, 2))}, identicalTo(0))
test.rcauchy.2 <- function() assertThat({set.seed(1); rcauchy(n = 1:5, location = c(0, -2), scale = c(0, 0.5, 1, 2))}, identicalTo(c(0x0p+0, -0x1.72e0a0b80357fp+0, 0x1.2d4a522fd8097p+1, -0x1.52ba636d7d983p+3, 0x0p+0), tol = 0.000100))
test.rcauchy.3 <- function() assertThat({set.seed(1); rcauchy(n = 15, location = c(0, -2), scale = c(0, 0.5, 1, 2))}, identicalTo(c(0x0p+0, -0x1.72e0a0b80357fp+0, 0x1.2d4a522fd8097p+1, -0x1.52ba636d7d983p+3, 0x0p+0, -0x1.12fc311089676p+1, 0x1.7823a22701e7ap-1, -0x1.549d16e5b9976p+1, 0x0p+0, -0x1.0b3cb14612b8ap+1, -0x1.cee904beced09p+0, -0x1.aa105d3584364p+2, 0x0p+0, -0x1.e6d662fc9d07ep+0, 0x1.82e09f9ecfcccp-1), tol = 0.000100))
test.rcauchy.4 <- function() assertThat({set.seed(1); rcauchy(n = numeric(0), location = c(0, -2), scale = c(0, 0.5, 1, 2))}, identicalTo(numeric(0)))
test.rcauchy.5 <- function() assertThat({set.seed(1); x = rcauchy(n = 3, location = c(NA, -2), scale = c(0, 0.5, 1, 2)); x}, identicalTo(c(NaN, -0x1.72e0a0b80357fp+0, NaN), tol = 1e-6))
