#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2016 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-dist-tests.R using GNU R version 3.3.1 (2016-06-21)
library(hamcrest)
library(stats)
set.seed(1)
test.rpois.1 <- function() assertThat({set.seed(1);rpois(n = 0x1p+0, lambda = c(0x1p+0, 0x1.8p+1, 0x1.6p+2, 0x0p+0))}, identicalTo(0L))
test.rpois.2 <- function() assertThat({set.seed(1);rpois(n = 1:5, lambda = c(0x1p+0, 0x1.8p+1, 0x1.6p+2, 0x0p+0))}, identicalTo(c(1L, 3L, 9L, 0L, 0L)))
test.rpois.3 <- function() assertThat({set.seed(1);rpois(n = 0x1.ep+3, lambda = c(0x1p+0, 0x1.8p+1, 0x1.6p+2, 0x0p+0))}, identicalTo(c(2L, 6L, 6L, 0L, 1L, 1L, 4L, 0L, 0L, 4L, 5L, 0L, 2L, 3L, 7L)))
test.rpois.4 <- function() assertThat({set.seed(1);rpois(n = numeric(0), lambda = c(0x1p+0, 0x1.8p+1, 0x1.6p+2, 0x0p+0))}, identicalTo(integer(0)))
test.rpois.5 <- function() assertThat({set.seed(1);rpois(n = 0x1.8p+1, lambda = c(NA, 0x1.8p+1, 0x1.6p+2, 0x0p+0))}, identicalTo(c(NA, 8L, 5L)))
