#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2016 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-unary-tests.R using GNU R version 3.3.1 (2016-06-21)
library(hamcrest)
as.pairlist.foo <- function(...) 41L
as.vector.foo <- function(...) 99
Math.bar <- function(...) 44
Summary.bar <- function(...) 45
Ops.bar <- function(...) 46
test.as.pairlist.1 <- function() assertThat(as.pairlist(NULL), identicalTo(NULL))
test.as.pairlist.2 <- function() assertThat(as.pairlist(logical(0)), identicalTo(NULL))
test.as.pairlist.3 <- function() assertThat(as.pairlist(c(TRUE, TRUE, FALSE, FALSE, TRUE)), identicalTo(pairlist(TRUE, TRUE, FALSE, FALSE, TRUE)))
test.as.pairlist.4 <- function() assertThat(as.pairlist(structure(c(TRUE, FALSE), .Names = c("a", ""))), identicalTo(pairlist(a = TRUE, FALSE)))
test.as.pairlist.5 <- function() assertThat(as.pairlist(c(TRUE, FALSE, NA)), identicalTo(pairlist(TRUE, FALSE, NA)))
test.as.pairlist.6 <- function() assertThat(as.pairlist(integer(0)), identicalTo(NULL))
test.as.pairlist.7 <- function() assertThat(as.pairlist(structure(integer(0), .Names = character(0))), throwsError())
test.as.pairlist.8 <- function() assertThat(as.pairlist(1:3), identicalTo(pairlist(1L, 2L, 3L)))
test.as.pairlist.9 <- function() assertThat(as.pairlist(c(1L, NA, 4L, NA, 999L)), identicalTo(pairlist(1L, NA_integer_, 4L, NA_integer_, 999L)))
test.as.pairlist.10 <- function() assertThat(as.pairlist(c(1L, 2L, 1073741824L, 1073741824L)), identicalTo(pairlist(1L, 2L, 1073741824L, 1073741824L)))
test.as.pairlist.11 <- function() assertThat(as.pairlist(numeric(0)), identicalTo(NULL))
test.as.pairlist.12 <- function() assertThat(as.pairlist(c(3.14159, 6.28319, 9.42478, 12.5664, 15.708)), identicalTo(pairlist(3.14159, 6.28319, 9.42478, 12.5664, 15.708)))
test.as.pairlist.13 <- function() assertThat(as.pairlist(c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708)), identicalTo(pairlist(-3.14159, -6.28319, -9.42478, -12.5664, -15.708)))
test.as.pairlist.14 <- function() assertThat(as.pairlist(structure(1:2, .Names = c("a", "b"))), identicalTo(pairlist(a = 1L, b = 2L)))
test.as.pairlist.15 <- function() assertThat(as.pairlist(structure(c(1.5, 2.5), .Names = c("a", "b"))), identicalTo(pairlist(a = 1.5, b = 2.5)))
test.as.pairlist.16 <- function() assertThat(as.pairlist(c(1.5, 1.51, 0, 1.49, -30)), identicalTo(pairlist(1.5, 1.51, 0, 1.49, -30)))
test.as.pairlist.17 <- function() assertThat(as.pairlist(c(1.5, 1.51, 0, 1.49, -30, NA)), identicalTo(pairlist(1.5, 1.51, 0, 1.49, -30, NA_real_)))
test.as.pairlist.18 <- function() assertThat(as.pairlist(c(1.5, 1.51, 0, 1.49, -30, NaN)), identicalTo(pairlist(1.5, 1.51, 0, 1.49, -30, NaN)))
test.as.pairlist.19 <- function() assertThat(as.pairlist(c(1.5, 1.51, 0, 1.49, -30, Inf)), identicalTo(pairlist(1.5, 1.51, 0, 1.49, -30, Inf)))
test.as.pairlist.20 <- function() assertThat(as.pairlist(c(1.5, 1.51, 0, 1.49, -30, -Inf)), identicalTo(pairlist(1.5, 1.51, 0, 1.49, -30, -Inf)))
test.as.pairlist.21 <- function() assertThat(as.pairlist(character(0)), identicalTo(NULL))
test.as.pairlist.22 <- function() assertThat(as.pairlist(c("4.1", "blahh", "99.9", "-413", NA)), identicalTo(pairlist("4.1", "blahh", "99.9", "-413", NA_character_)))
test.as.pairlist.23 <- function() assertThat(as.pairlist(complex(0)), identicalTo(NULL))
test.as.pairlist.24 <- function() assertThat(as.pairlist(list(1, 2, 3)), identicalTo(pairlist(1, 2, 3)))
test.as.pairlist.25 <- function() assertThat(as.pairlist(list(1, 2, NULL)), identicalTo(pairlist(1, 2, NULL)))
test.as.pairlist.26 <- function() assertThat(as.pairlist(list(1L, 2L, 3L)), identicalTo(pairlist(1L, 2L, 3L)))
test.as.pairlist.27 <- function() assertThat(as.pairlist(list(1L, 2L, NULL)), identicalTo(pairlist(1L, 2L, NULL)))
test.as.pairlist.28 <- function() assertThat(as.pairlist(list(1, 2, list(3, 4))), identicalTo(pairlist(1, 2, list(3, 4))))
test.as.pairlist.29 <- function() assertThat(as.pairlist(list(3, "a", structure(list("b", z = list(TRUE, "c")), .Names = c("", "z")))), identicalTo(pairlist(3, "a", structure(list("b", z = list(TRUE, "c")), .Names = c("", "z")))))
test.as.pairlist.30 <- function() assertThat(as.pairlist(structure(list(`NA` = 1, 2, b = 3), .Names = c(NA, "", "b"))), identicalTo(pairlist(NA = 1, 2, b = 3)))
test.as.pairlist.31 <- function() assertThat(as.pairlist(pairlist(41, "a", 21L)), identicalTo(pairlist(41, "a", 21L)))
test.as.pairlist.32 <- function() assertThat(as.pairlist(pairlist(a = 41, 42)), identicalTo(pairlist(a = 41, 42)))
test.as.pairlist.33 <- function() assertThat(as.pairlist(pairlist(a = 41, NULL)), identicalTo(pairlist(a = 41, NULL)))
test.as.pairlist.34 <- function() assertThat(as.pairlist(structure(1:12, .Dim = 3:4)), identicalTo(pairlist(1L, 2L, 3L, 4L, 5L, 6L, 7L, 8L, 9L, 10L, 11L, 12L)))
test.as.pairlist.35 <- function() assertThat(as.pairlist(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(    x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))), identicalTo(pairlist(1L, 2L, 3L, 4L, 5L, 6L, 7L, 8L, 9L, 10L, 11L, 12L)))
test.as.pairlist.36 <- function() assertThat(as.pairlist(structure(1:3, rando.attrib = 941L)), identicalTo(pairlist(1L, 2L, 3L)))
test.as.pairlist.37 <- function() assertThat(as.pairlist(structure(1:3, .Dim = 3L, .Dimnames = list(c("a", "b", "c")))), identicalTo(pairlist(a = 1L, b = 2L, c = 3L)))
test.as.pairlist.38 <- function() assertThat(as.pairlist(structure(1:3, .Dim = 3L, .Dimnames = structure(list(    z = c("a", "b", "c")), .Names = "z"))), identicalTo(pairlist(a = 1L, b = 2L, c = 3L)))
test.as.pairlist.39 <- function() assertThat(as.pairlist(structure(list("foo"), class = "foo")), identicalTo(99))
test.as.pairlist.40 <- function() assertThat(as.pairlist(structure(list("bar"), class = "foo")), identicalTo(99))
test.as.pairlist.41 <- function() assertThat(as.pairlist(quote(xyz)), throwsError())
test.as.pairlist.42 <- function() assertThat(as.pairlist(quote(sin(3.14))), deparsesTo("sin(3.14)"))
test.as.pairlist.43 <- function() assertThat(as.pairlist(structure("foo", class = "foo")), identicalTo(99))
test.as.pairlist.44 <- function() assertThat(as.pairlist(structure(list(1L, "bar"), class = "bar")), identicalTo(structure(pairlist(1L, "bar"), class = "bar")))
