#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2019 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-dist-tests.R using GNU R version 3.3.1 (2016-06-21)
library(hamcrest)
library(stats)
set.seed(1)
test.rexp.1 <- function() assertThat({set.seed(1);rexp(n = 0x1p+0, scale = c(0x0p+0, 0x1p-1, 0x1p+0, 0x1.8p+0))}, throwsError())
test.rexp.2 <- function() assertThat({set.seed(1);rexp(n = 1:5, scale = c(0x0p+0, 0x1p-1, 0x1p+0, 0x1.8p+0))}, throwsError())
test.rexp.3 <- function() assertThat({set.seed(1);rexp(n = 0x1.ep+3, scale = c(0x0p+0, 0x1p-1, 0x1p+0, 0x1.8p+0))}, throwsError())
test.rexp.4 <- function() assertThat({set.seed(1);rexp(n = numeric(0), scale = c(0x0p+0, 0x1p-1, 0x1p+0, 0x1.8p+0))}, throwsError())
test.rexp.5 <- function() assertThat({set.seed(1);rexp(n = 0x1.8p+1, scale = c(NA, 0x1p-1, 0x1p+0, 0x1.8p+0))}, throwsError())
