#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2018 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-unary-tests.R using GNU R version 3.5.3 (2019-03-11)
library(hamcrest)
Sys.setlocale('LC_COLLATE', 'C')
as.factor.foo <- function(...) 41L
as.vector.foo <- function(...) 99
as.vector.bar <- function(...) 98
Math.bar <- function(...) 44
Summary.bar <- function(...) 45
Ops.bar <- function(...) 46
test.as.factor.1 <- function() assertThat(as.factor(NULL), identicalTo(structure(integer(0), .Label = character(0), class = "factor")))
test.as.factor.2 <- function() assertThat(as.factor(logical(0)), identicalTo(structure(integer(0), .Label = character(0), class = "factor")))
test.as.factor.3 <- function() assertThat(as.factor(c(TRUE, TRUE, FALSE, FALSE, TRUE)), identicalTo(structure(c(2L, 2L, 1L, 1L, 2L), .Label = c("FALSE", "TRUE"), class = "factor")))
test.as.factor.4 <- function() assertThat(as.factor(structure(c(TRUE, FALSE), .Names = c("a", ""))), identicalTo(structure(2:1, .Names = c("a", ""), .Label = c("FALSE", "TRUE"), class = "factor")))
test.as.factor.5 <- function() assertThat(as.factor(c(TRUE, FALSE, NA)), identicalTo(structure(c(2L, 1L, NA), .Label = c("FALSE", "TRUE"), class = "factor")))
test.as.factor.6 <- function() assertThat(as.factor(integer(0)), identicalTo(structure(integer(0), .Label = character(0), class = "factor")))
test.as.factor.7 <- function() assertThat(as.factor(structure(integer(0), .Names = character(0))), identicalTo(structure(integer(0), .Label = character(0), .Names = character(0), class = "factor")))
test.as.factor.8 <- function() assertThat(as.factor(1:3), identicalTo(structure(1:3, .Label = c("1", "2", "3"), class = "factor")))
test.as.factor.9 <- function() assertThat(as.factor(c(1L, NA, 4L, NA, 999L)), identicalTo(structure(c(1L, NA, 2L, NA, 3L), .Label = c("1", "4", "999"), class = "factor")))
test.as.factor.10 <- function() assertThat(as.factor(c(1L, 2L, 1073741824L, 1073741824L)), identicalTo(structure(c(1L, 2L, 3L, 3L), .Label = c("1", "2", "1073741824"), class = "factor")))
test.as.factor.11 <- function() assertThat(as.factor(numeric(0)), identicalTo(structure(integer(0), .Label = character(0), class = "factor")))
test.as.factor.12 <- function() assertThat(as.factor(c(3.14159, 6.28319, 9.42478, 12.5664, 15.708)), identicalTo(structure(1:5, .Label = c("3.14159", "6.28319", "9.42478", "12.5664", "15.708"), class = "factor")))
test.as.factor.13 <- function() assertThat(as.factor(c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708)), identicalTo(structure(5:1, .Label = c("-15.708", "-12.5664", "-9.42478", "-6.28319", "-3.14159"), class = "factor")))
test.as.factor.14 <- function() assertThat(as.factor(structure(1:2, .Names = c("a", "b"))), identicalTo(structure(1:2, .Label = c("1", "2"), .Names = c("a", "b"), class = "factor")))
test.as.factor.15 <- function() assertThat(as.factor(structure(c(1.5, 2.5), .Names = c("a", "b"))), identicalTo(structure(1:2, .Names = c("a", "b"), .Label = c("1.5", "2.5"), class = "factor")))
test.as.factor.16 <- function() assertThat(as.factor(c(1.5, 1.51, 0, 1.49, -30)), identicalTo(structure(c(4L, 5L, 2L, 3L, 1L), .Label = c("-30", "0", "1.49", "1.5", "1.51"), class = "factor")))
test.as.factor.17 <- function() assertThat(as.factor(c(1.5, 1.51, 0, 1.49, -30, NA)), identicalTo(structure(c(4L, 5L, 2L, 3L, 1L, NA), .Label = c("-30", "0", "1.49", "1.5", "1.51"), class = "factor")))
test.as.factor.18 <- function() assertThat(as.factor(c(1.5, 1.51, 0, 1.49, -30, NaN)), identicalTo(structure(c(4L, 5L, 2L, 3L, 1L, 6L), .Label = c("-30", "0", "1.49", "1.5", "1.51", "NaN"), class = "factor")))
test.as.factor.19 <- function() assertThat(as.factor(c(1.5, 1.51, 0, 1.49, -30, Inf)), identicalTo(structure(c(4L, 5L, 2L, 3L, 1L, 6L), .Label = c("-30", "0", "1.49", "1.5", "1.51", "Inf"), class = "factor")))
test.as.factor.20 <- function() assertThat(as.factor(c(1.5, 1.51, 0, 1.49, -30, -Inf)), identicalTo(structure(c(5L, 6L, 3L, 4L, 2L, 1L), .Label = c("-Inf", "-30", "0", "1.49", "1.5", "1.51"), class = "factor")))
test.as.factor.21 <- function() assertThat(as.factor(character(0)), identicalTo(structure(integer(0), .Label = character(0), class = "factor")))
test.as.factor.22 <- function() assertThat(as.factor(c("4.1", "blahh", "99.9", "-413", NA)), identicalTo(structure(c(2L, 4L, 3L, 1L, NA), .Label = c("-413", "4.1", "99.9", "blahh"), class = "factor")))
test.as.factor.23 <- function() assertThat(as.factor(complex(0)), identicalTo(structure(integer(0), .Label = character(0), class = "factor")))
test.as.factor.24 <- function() assertThat(as.factor(list(1, 2, 3)), throwsError())
test.as.factor.25 <- function() assertThat(as.factor(list(1, 2, NULL)), throwsError())
test.as.factor.26 <- function() assertThat(as.factor(list(1L, 2L, 3L)), throwsError())
test.as.factor.27 <- function() assertThat(as.factor(list(1L, 2L, NULL)), throwsError())
test.as.factor.28 <- function() assertThat(as.factor(list(1, 2, list(3, 4))), throwsError())
test.as.factor.29 <- function() assertThat(as.factor(list(1, 2, numeric(0))), throwsError())
test.as.factor.30 <- function() assertThat(as.factor(list(3, "a", structure(list("b", list(TRUE, "c")), .Names = c("", "z")))), throwsError())
test.as.factor.31 <- function() assertThat(as.factor(structure(list(1, 2, 3), .Names = c(NA, "", "b"))), throwsError())
test.as.factor.32 <- function() assertThat(as.factor(pairlist(41, "a", 21L)), throwsError())
test.as.factor.33 <- function() assertThat(as.factor(structure(pairlist(a = 41, 42))), throwsError())
test.as.factor.34 <- function() assertThat(as.factor(structure(pairlist(a = 41, NULL))), throwsError())
test.as.factor.35 <- function() assertThat(as.factor(structure(1:12, .Dim = 3:4)), identicalTo(structure(1:12, .Label = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"), class = "factor")))
test.as.factor.36 <- function() assertThat(as.factor(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(    c("a", "b", "c"), c("d", "e", "f", "g")), .Names = c("x", "y")))), identicalTo(structure(1:12, .Label = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"), class = "factor")))
test.as.factor.37 <- function() assertThat(as.factor(structure(1:3, rando.attrib = 941L)), identicalTo(structure(1:3, .Label = c("1", "2", "3"), class = "factor")))
test.as.factor.38 <- function() assertThat(as.factor(structure(1:3, .Dim = 3L, .Dimnames = list(c("a", "b", "c")))), identicalTo(structure(1:3, .Label = c("1", "2", "3"), .Names = c("a", "b", "c"), class = "factor")))
test.as.factor.39 <- function() assertThat(as.factor(structure(1:3, .Dim = 3L, .Dimnames = structure(list(    c("a", "b", "c")), .Names = "z"))), identicalTo(structure(1:3, .Label = c("1", "2", "3"), .Names = c("a", "b", "c"), class = "factor")))
test.as.factor.40 <- function() assertThat(as.factor(structure(list("foo"), class = "foo")), identicalTo(structure(NA_integer_, .Label = "foo", class = "factor")))
test.as.factor.41 <- function() assertThat(as.factor(structure(list("bar"), class = "foo")), identicalTo(structure(NA_integer_, .Label = "bar", class = "factor")))
test.as.factor.42 <- function() assertThat(as.factor(quote(xyz)), throwsError())
test.as.factor.43 <- function() assertThat(as.factor(quote(sin(3.14))), throwsError())
test.as.factor.44 <- function() assertThat(as.factor("NaN"), identicalTo(structure(1L, .Label = "NaN", class = "factor")))
test.as.factor.45 <- function() assertThat(as.factor("NABOOM!"), identicalTo(structure(1L, .Label = "NABOOM!", class = "factor")))
test.as.factor.46 <- function() assertThat(as.factor("NaNaNabooboo"), identicalTo(structure(1L, .Label = "NaNaNabooboo", class = "factor")))
test.as.factor.47 <- function() assertThat(as.factor("-Inf"), identicalTo(structure(1L, .Label = "-Inf", class = "factor")))
test.as.factor.48 <- function() assertThat(as.factor("+Infinity"), identicalTo(structure(1L, .Label = "+Infinity", class = "factor")))
test.as.factor.49 <- function() assertThat(as.factor("Infinity and beyond!"), identicalTo(structure(1L, .Label = "Infinity and beyond!", class = "factor")))
test.as.factor.50 <- function() assertThat(as.factor("Infi"), identicalTo(structure(1L, .Label = "Infi", class = "factor")))
test.as.factor.51 <- function() assertThat(as.factor("0.03f"), identicalTo(structure(1L, .Label = "0.03f", class = "factor")))
test.as.factor.52 <- function() assertThat(as.factor("  0.0330   "), identicalTo(structure(1L, .Label = "  0.0330   ", class = "factor")))
test.as.factor.53 <- function() assertThat(as.factor(structure("foo", class = "foo")), identicalTo(structure(1L, .Label = "foo", class = "factor")))
test.as.factor.54 <- function() assertThat(as.factor(structure(list(1L, "bar"), class = "bar")), throwsError())
