#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2016 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-unary-tests.R using GNU R version 3.3.2 (2016-10-31)
library(hamcrest)
as.matrix.foo <- function(...) 41L
as.vector.foo <- function(...) 99
Math.bar <- function(...) 44
Summary.bar <- function(...) 45
Ops.bar <- function(...) 46
test.as.matrix.1 <- function() assertThat(as.matrix(NULL), throwsError())
test.as.matrix.2 <- function() assertThat(as.matrix(logical(0)), identicalTo(structure(logical(0), .Dim = 0:1)))
test.as.matrix.3 <- function() assertThat(as.matrix(c(TRUE, TRUE, FALSE, FALSE, TRUE)), identicalTo(structure(c(TRUE, TRUE, FALSE, FALSE, TRUE), .Dim = c(5L, 1L))))
test.as.matrix.4 <- function() assertThat(as.matrix(structure(c(TRUE, FALSE), .Names = c("a", ""))), identicalTo(structure(c(TRUE, FALSE), .Dim = c(2L, 1L), .Dimnames = list(    c("a", ""), NULL))))
test.as.matrix.5 <- function() assertThat(as.matrix(c(TRUE, FALSE, NA)), identicalTo(structure(c(TRUE, FALSE, NA), .Dim = c(3L, 1L))))
test.as.matrix.6 <- function() assertThat(as.matrix(integer(0)), identicalTo(structure(integer(0), .Dim = 0:1)))
test.as.matrix.7 <- function() assertThat(as.matrix(structure(integer(0), .Names = character(0))), identicalTo(structure(integer(0), .Dim = 0:1, .Dimnames = list(NULL, NULL))))
test.as.matrix.8 <- function() assertThat(as.matrix(1:3), identicalTo(structure(1:3, .Dim = c(3L, 1L))))
test.as.matrix.9 <- function() assertThat(as.matrix(c(1L, NA, 4L, NA, 999L)), identicalTo(structure(c(1L, NA, 4L, NA, 999L), .Dim = c(5L, 1L))))
test.as.matrix.10 <- function() assertThat(as.matrix(c(1L, 2L, 1073741824L, 1073741824L)), identicalTo(structure(c(1L, 2L, 1073741824L, 1073741824L), .Dim = c(4L, 1L))))
test.as.matrix.11 <- function() assertThat(as.matrix(numeric(0)), identicalTo(structure(numeric(0), .Dim = 0:1)))
test.as.matrix.12 <- function() assertThat(as.matrix(c(3.14159, 6.28319, 9.42478, 12.5664, 15.708)), identicalTo(structure(c(3.14159, 6.28319, 9.42478, 12.5664, 15.708), .Dim = c(5L, 1L)), tol = 0.000100))
test.as.matrix.13 <- function() assertThat(as.matrix(c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708)), identicalTo(structure(c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708), .Dim = c(5L, 1L)), tol = 0.000100))
test.as.matrix.14 <- function() assertThat(as.matrix(structure(1:2, .Names = c("a", "b"))), identicalTo(structure(1:2, .Dim = c(2L, 1L), .Dimnames = list(c("a", "b"),     NULL))))
test.as.matrix.15 <- function() assertThat(as.matrix(structure(c(1.5, 2.5), .Names = c("a", "b"))), identicalTo(structure(c(1.5, 2.5), .Dim = c(2L, 1L), .Dimnames = list(c("a", "b"), NULL)), tol = 0.000100))
test.as.matrix.16 <- function() assertThat(as.matrix(c(1.5, 1.51, 0, 1.49, -30)), identicalTo(structure(c(1.5, 1.51, 0, 1.49, -30), .Dim = c(5L, 1L)), tol = 0.000100))
test.as.matrix.17 <- function() assertThat(as.matrix(c(1.5, 1.51, 0, 1.49, -30, NA)), identicalTo(structure(c(1.5, 1.51, 0, 1.49, -30, NA), .Dim = c(6L, 1L)), tol = 0.000100))
test.as.matrix.18 <- function() assertThat(as.matrix(c(1.5, 1.51, 0, 1.49, -30, NaN)), identicalTo(structure(c(1.5, 1.51, 0, 1.49, -30, NaN), .Dim = c(6L, 1L)), tol = 0.000100))
test.as.matrix.19 <- function() assertThat(as.matrix(c(1.5, 1.51, 0, 1.49, -30, Inf)), identicalTo(structure(c(1.5, 1.51, 0, 1.49, -30, Inf), .Dim = c(6L, 1L)), tol = 0.000100))
test.as.matrix.20 <- function() assertThat(as.matrix(c(1.5, 1.51, 0, 1.49, -30, -Inf)), identicalTo(structure(c(1.5, 1.51, 0, 1.49, -30, -Inf), .Dim = c(6L, 1L)), tol = 0.000100))
test.as.matrix.21 <- function() assertThat(as.matrix(character(0)), identicalTo(structure(character(0), .Dim = 0:1)))
test.as.matrix.22 <- function() assertThat(as.matrix(c("4.1", "blahh", "99.9", "-413", NA)), identicalTo(structure(c("4.1", "blahh", "99.9", "-413", NA), .Dim = c(5L, 1L))))
test.as.matrix.23 <- function() assertThat(as.matrix(complex(0)), identicalTo(structure(complex(0), .Dim = 0:1)))
test.as.matrix.24 <- function() assertThat(as.matrix(list(1, 2, 3)), identicalTo(structure(list(1, 2, 3), .Dim = c(3L, 1L))))
test.as.matrix.25 <- function() assertThat(as.matrix(list(1, 2, NULL)), identicalTo(structure(list(1, 2, NULL), .Dim = c(3L, 1L))))
test.as.matrix.26 <- function() assertThat(as.matrix(list(1L, 2L, 3L)), identicalTo(structure(list(1L, 2L, 3L), .Dim = c(3L, 1L))))
test.as.matrix.27 <- function() assertThat(as.matrix(list(1L, 2L, NULL)), identicalTo(structure(list(1L, 2L, NULL), .Dim = c(3L, 1L))))
test.as.matrix.28 <- function() assertThat(as.matrix(list(1, 2, list(3, 4))), identicalTo(structure(list(1, 2, list(3, 4)), .Dim = c(3L, 1L))))
test.as.matrix.29 <- function() assertThat(as.matrix(list(3, "a", structure(list("b", z = list(TRUE, "c")), .Names = c("", "z")))), identicalTo(structure(list(3, "a", structure(list("b", z = list(TRUE, "c")), .Names = c("", "z"))), .Dim = c(3L, 1L))))
test.as.matrix.30 <- function() assertThat(as.matrix(structure(list(`NA` = 1, 2, b = 3), .Names = c(NA, "", "b"))), identicalTo(structure(list(1, 2, 3), .Dim = c(3L, 1L), .Dimnames = list(c(NA, "", "b"), NULL))))
test.as.matrix.31 <- function() assertThat(as.matrix(pairlist(41, "a", 21L)), throwsError())
test.as.matrix.32 <- function() assertThat(as.matrix(pairlist(a = 41, 42)), throwsError())
test.as.matrix.33 <- function() assertThat(as.matrix(pairlist(a = 41, NULL)), throwsError())
test.as.matrix.34 <- function() assertThat(as.matrix(structure(1:12, .Dim = 3:4)), identicalTo(structure(1:12, .Dim = 3:4)))
test.as.matrix.35 <- function() assertThat(as.matrix(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(    x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))), identicalTo(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))))
test.as.matrix.36 <- function() assertThat(as.matrix(structure(1:3, rando.attrib = 941L)), identicalTo(structure(1:3, .Dim = c(3L, 1L))))
test.as.matrix.37 <- function() assertThat(as.matrix(structure(1:3, .Dim = 3L, .Dimnames = list(c("a", "b", "c")))), identicalTo(structure(1:3, .Dim = c(3L, 1L), .Dimnames = list(c("a", "b", "c"), NULL))))
test.as.matrix.38 <- function() assertThat(as.matrix(structure(1:3, .Dim = 3L, .Dimnames = structure(list(    z = c("a", "b", "c")), .Names = "z"))), identicalTo(structure(1:3, .Dim = c(3L, 1L), .Dimnames = list(c("a", "b", "c"), NULL))))
test.as.matrix.39 <- function() assertThat(as.matrix(structure(list("foo"), class = "foo")), identicalTo(41L))
test.as.matrix.40 <- function() assertThat(as.matrix(structure(list("bar"), class = "foo")), identicalTo(41L))
test.as.matrix.41 <- function() assertThat(as.matrix(quote(xyz)), throwsError())
test.as.matrix.42 <- function() assertThat(as.matrix(quote(sin(3.14))), throwsError())
test.as.matrix.43 <- function() assertThat(as.matrix(structure("foo", class = "foo")), identicalTo(41L))
test.as.matrix.44 <- function() assertThat(as.matrix(structure(list(1L, "bar"), class = "bar")), identicalTo(structure(list(1L, "bar"), class = "bar", .Dim = c(2L, 1L))))
