#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2016 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-math-unary-tests.R using GNU R version 3.2.0 (2015-04-16)
library(hamcrest)
log10.foo <- function(...) 41
Math.bar <- function(...) 44
test.log10.1 <- function() assertThat(log10(-0.01), identicalTo(NaN))
test.log10.2 <- function() assertThat(log10(-0.1), identicalTo(NaN))
test.log10.3 <- function() assertThat(log10(-1), identicalTo(NaN))
test.log10.4 <- function() assertThat(log10(-1.5), identicalTo(NaN))
test.log10.5 <- function() assertThat(log10(-2), identicalTo(NaN))
test.log10.6 <- function() assertThat(log10(-2.5), identicalTo(NaN))
test.log10.7 <- function() assertThat(log10(-4), identicalTo(NaN))
test.log10.8 <- function() assertThat(log10(-10), identicalTo(NaN))
test.log10.9 <- function() assertThat(log10(-100), identicalTo(NaN))
test.log10.10 <- function() assertThat(log10(-0.785398), identicalTo(NaN))
test.log10.11 <- function() assertThat(log10(-1.5708), identicalTo(NaN))
test.log10.12 <- function() assertThat(log10(-3.14159), identicalTo(NaN))
test.log10.13 <- function() assertThat(log10(-6.28319), identicalTo(NaN))
test.log10.14 <- function() assertThat(log10(0.01), identicalTo(-2))
test.log10.15 <- function() assertThat(log10(0.1), identicalTo(-1))
test.log10.16 <- function() assertThat(log10(1), identicalTo(0))
test.log10.17 <- function() assertThat(log10(1.5), identicalTo(0.176091259055681, tol = 0.000100))
test.log10.18 <- function() assertThat(log10(2), identicalTo(0.301029995663981, tol = 0.000100))
test.log10.19 <- function() assertThat(log10(2.5), identicalTo(0.397940008672038, tol = 0.000100))
test.log10.20 <- function() assertThat(log10(4), identicalTo(0.602059991327962, tol = 0.000100))
test.log10.21 <- function() assertThat(log10(10), identicalTo(1))
test.log10.22 <- function() assertThat(log10(100), identicalTo(2))
test.log10.23 <- function() assertThat(log10(0.785398), identicalTo(-0.104910208986239, tol = 0.000100))
test.log10.24 <- function() assertThat(log10(1.5708), identicalTo(0.196120892598381, tol = 0.000100))
test.log10.25 <- function() assertThat(log10(3.14159), identicalTo(0.497149505861123, tol = 0.000100))
test.log10.26 <- function() assertThat(log10(6.28319), identicalTo(0.798180192726274, tol = 0.000100))
test.log10.27 <- function() assertThat(log10(NULL), throwsError())
test.log10.28 <- function() assertThat(log10(c(0.01, 0.1, 1, 1.5)), identicalTo(c(-2, -1, 0, 0.176091259055681), tol = 0.000100))
test.log10.29 <- function() assertThat(log10(integer(0)), identicalTo(numeric(0)))
test.log10.30 <- function() assertThat(log10(numeric(0)), identicalTo(numeric(0)))
test.log10.31 <- function() assertThat(log10(NaN), identicalTo(NaN))
test.log10.32 <- function() assertThat(log10(NA_real_), identicalTo(NA_real_))
test.log10.33 <- function() assertThat(log10(Inf), identicalTo(Inf))
test.log10.34 <- function() assertThat(log10(-Inf), identicalTo(NaN))
test.log10.35 <- function() assertThat(log10(c(1L, 4L)), identicalTo(c(0, 0.602059991327962), tol = 0.000100))
test.log10.36 <- function() assertThat(log10(structure(1, class = "foo")), identicalTo(41))
test.log10.37 <- function() assertThat(log10(structure(1, class = "bar")), identicalTo(44))
test.log10.38 <- function() assertThat(log10(structure(list("a"), class = "foo")), identicalTo(41))
test.log10.39 <- function() assertThat(log10(structure(list("b"), class = "bar")), identicalTo(44))
test.log10.40 <- function() assertThat(log10(structure(c(1, 2, 3), .Names = c("a", "b", "c"))), identicalTo(structure(c(0, 0.301029995663981, 0.477121254719662), .Names = c("a", "b", "c")), tol = 0.000100))
test.log10.41 <- function() assertThat(log10(structure(c(1, 2), .Names = c("x", ""))), identicalTo(structure(c(0, 0.301029995663981), .Names = c("x", "")), tol = 0.000100))
test.log10.42 <- function() assertThat(log10(structure(1:12, .Dim = 3:4)), identicalTo(structure(c(0, 0.301029995663981, 0.477121254719662, 0.602059991327962, 0.698970004336019, 0.778151250383644, 0.845098040014257, 0.903089986991944, 0.954242509439325, 1, 1.04139268515822, 1.07918124604762), .Dim = 3:4), tol = 0.000100))
test.log10.43 <- function() assertThat(log10(structure(0, rando.attr = 4L)), identicalTo(structure(-Inf, rando.attr = 4L)))
test.log10.44 <- function() assertThat(log10(structure(0, class = "zinga")), identicalTo(structure(-Inf, class = "zinga")))
