#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2019 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-math-unary-tests.R using GNU R version 3.2.0 (2015-04-16)
library(hamcrest)
tanh.foo <- function(...) 41
Math.bar <- function(...) 44
test.tanh.1 <- function() assertThat(tanh(-0.01), identicalTo(-0.00999966667999946, tol = 0.000100))
test.tanh.2 <- function() assertThat(tanh(-0.1), identicalTo(-0.0996679946249558, tol = 0.000100))
test.tanh.3 <- function() assertThat(tanh(-1), identicalTo(-0.761594155955765, tol = 0.000100))
test.tanh.4 <- function() assertThat(tanh(-1.5), identicalTo(-0.905148253644866, tol = 0.000100))
test.tanh.5 <- function() assertThat(tanh(-2), identicalTo(-0.964027580075817, tol = 0.000100))
test.tanh.6 <- function() assertThat(tanh(-2.5), identicalTo(-0.98661429815143, tol = 0.000100))
test.tanh.7 <- function() assertThat(tanh(-4), identicalTo(-0.999329299739067, tol = 0.000100))
test.tanh.8 <- function() assertThat(tanh(-10), identicalTo(-0.999999995877693, tol = 0.000100))
test.tanh.9 <- function() assertThat(tanh(-100), identicalTo(-1))
test.tanh.10 <- function() assertThat(tanh(-0.785398), identicalTo(-0.655794109506907, tol = 0.000100))
test.tanh.11 <- function() assertThat(tanh(-1.5708), identicalTo(-0.917152919086327, tol = 0.000100))
test.tanh.12 <- function() assertThat(tanh(-3.14159), identicalTo(-0.996272056472815, tol = 0.000100))
test.tanh.13 <- function() assertThat(tanh(-6.28319), identicalTo(-0.999993025405072, tol = 0.000100))
test.tanh.14 <- function() assertThat(tanh(0.01), identicalTo(0.00999966667999946, tol = 0.000100))
test.tanh.15 <- function() assertThat(tanh(0.1), identicalTo(0.0996679946249558, tol = 0.000100))
test.tanh.16 <- function() assertThat(tanh(1), identicalTo(0.761594155955765, tol = 0.000100))
test.tanh.17 <- function() assertThat(tanh(1.5), identicalTo(0.905148253644866, tol = 0.000100))
test.tanh.18 <- function() assertThat(tanh(2), identicalTo(0.964027580075817, tol = 0.000100))
test.tanh.19 <- function() assertThat(tanh(2.5), identicalTo(0.98661429815143, tol = 0.000100))
test.tanh.20 <- function() assertThat(tanh(4), identicalTo(0.999329299739067, tol = 0.000100))
test.tanh.21 <- function() assertThat(tanh(10), identicalTo(0.999999995877693, tol = 0.000100))
test.tanh.22 <- function() assertThat(tanh(100), identicalTo(1))
test.tanh.23 <- function() assertThat(tanh(0.785398), identicalTo(0.655794109506907, tol = 0.000100))
test.tanh.24 <- function() assertThat(tanh(1.5708), identicalTo(0.917152919086327, tol = 0.000100))
test.tanh.25 <- function() assertThat(tanh(3.14159), identicalTo(0.996272056472815, tol = 0.000100))
test.tanh.26 <- function() assertThat(tanh(6.28319), identicalTo(0.999993025405072, tol = 0.000100))
test.tanh.27 <- function() assertThat(tanh(NULL), throwsError())
test.tanh.28 <- function() assertThat(tanh(c(0.01, 0.1, 1, 1.5)), identicalTo(c(0.00999966667999946, 0.0996679946249558, 0.761594155955765, 0.905148253644866), tol = 0.000100))
test.tanh.29 <- function() assertThat(tanh(integer(0)), identicalTo(numeric(0)))
test.tanh.30 <- function() assertThat(tanh(numeric(0)), identicalTo(numeric(0)))
test.tanh.31 <- function() assertThat(tanh(NaN), identicalTo(NaN))
test.tanh.32 <- function() assertThat(tanh(NA_real_), identicalTo(NA_real_))
test.tanh.33 <- function() assertThat(tanh(Inf), identicalTo(1))
test.tanh.34 <- function() assertThat(tanh(-Inf), identicalTo(-1))
test.tanh.35 <- function() assertThat(tanh(c(1L, 4L)), identicalTo(c(0.761594155955765, 0.999329299739067), tol = 0.000100))
test.tanh.36 <- function() assertThat(tanh(structure(1, class = "foo")), identicalTo(41))
test.tanh.37 <- function() assertThat(tanh(structure(1, class = "bar")), identicalTo(44))
test.tanh.38 <- function() assertThat(tanh(structure(list("a"), class = "foo")), identicalTo(41))
test.tanh.39 <- function() assertThat(tanh(structure(list("b"), class = "bar")), identicalTo(44))
test.tanh.40 <- function() assertThat(tanh(structure(c(1, 2, 3), .Names = c("a", "b", "c"))), identicalTo(structure(c(0.761594155955765, 0.964027580075817, 0.99505475368673), .Names = c("a", "b", "c")), tol = 0.000100))
test.tanh.41 <- function() assertThat(tanh(structure(c(1, 2), .Names = c("x", ""))), identicalTo(structure(c(0.761594155955765, 0.964027580075817), .Names = c("x", "")), tol = 0.000100))
test.tanh.42 <- function() assertThat(tanh(structure(1:12, .Dim = 3:4)), identicalTo(structure(c(0.761594155955765, 0.964027580075817, 0.99505475368673, 0.999329299739067, 0.999909204262595, 0.999987711650796, 0.999998336943945, 0.999999774929676, 0.999999969540041, 0.999999995877693, 0.999999999442106, 0.999999999924497), .Dim = 3:4), tol = 0.000100))
test.tanh.43 <- function() assertThat(tanh(structure(0, rando.attr = 4L)), identicalTo(structure(0, rando.attr = 4L)))
test.tanh.44 <- function() assertThat(tanh(structure(0, class = "zinga")), identicalTo(structure(0, class = "zinga")))
