#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2016 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-dist-tests.R using GNU R version 3.3.1 (2016-06-21)
library(hamcrest)
library(stats)
set.seed(1)
test.rt.1 <- function() assertThat({set.seed(1);rt(n = 0x1p+0, df = c(0x0p+0, 0x1p-1, 0x1.4p+2, 0x1p+0), ncp = c(0x0p+0, 0x1p-1, 0x1.4p+2, -0x1.4p+2))}, identicalTo(c(NaN, -Inf, -Inf, -Inf)))
test.rt.2 <- function() assertThat({set.seed(1);rt(n = 1:5, df = c(0x0p+0, 0x1p-1, 0x1.4p+2, 0x1p+0), ncp = c(0x0p+0, 0x1p-1, 0x1.4p+2, -0x1.4p+2))}, identicalTo(c(NaN, -0x1.3153b94cf6c11p-2, 0x1.763b45613eec8p+2, -0x1.a4c4041adbbf3p+3, NaN), tol = 0.000100))
test.rt.3 <- function() assertThat({set.seed(1);rt(n = 0x1.ep+3, df = c(0x0p+0, 0x1p-1, 0x1.4p+2, 0x1p+0), ncp = c(0x0p+0, 0x1p-1, 0x1.4p+2, -0x1.4p+2))}, identicalTo(c(NaN, 0x1.7924ca73da1d7p+0, 0x1.341f0388b4d79p+3, -0x1.38756c39e125dp+2, NaN, -0x1.8f45561583dcfp-1, 0x1.560fdadc1df78p+2, -0x1.f239a0b85285fp+2, NaN, 0x1.9eb14628ab92ep+5, 0x1.aacf6020b40f9p+2, -0x1.44fd7928b672p+1, NaN, 0x1.834ef33dc248dp-2, 0x1.033aba4313d66p+3), tol = 0.000100))
test.rt.4 <- function() assertThat({set.seed(1);rt(n = numeric(0), df = c(0x0p+0, 0x1p-1, 0x1.4p+2, 0x1p+0),     ncp = c(0x0p+0, 0x1p-1, 0x1.4p+2, -0x1.4p+2))}, identicalTo(numeric(0)))
test.rt.5 <- function() assertThat({set.seed(1);rt(n = 0x1.8p+1, df = c(NA, 0x1p-1, 0x1.4p+2, 0x1p+0), ncp = c(0x0p+0, 0x1p-1, 0x1.4p+2, -0x1.4p+2))}, identicalTo(c(NaN, -0x1.88eee7b52e27fp-3, 0x1.3fd9ec192c481p+2, NaN)))
