#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2016 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-unary-tests.R using GNU R version 3.2.0 (2015-04-16)
library(hamcrest)
Im.foo <- function(...) 41
Complex.bar <- function(...) 45
test.Im.1 <- function() assertThat(Im(NULL), throwsError())
test.Im.2 <- function() assertThat(Im(logical(0)), identicalTo(numeric(0)))
test.Im.3 <- function() assertThat(Im(c(TRUE, TRUE, FALSE, FALSE, TRUE)), identicalTo(c(0, 0, 0, 0, 0)))
test.Im.4 <- function() assertThat(Im(structure(c(TRUE, FALSE), .Names = c("a", ""))), identicalTo(structure(c(0, 0), .Names = c("a", ""))))
test.Im.5 <- function() assertThat(Im(c(TRUE, FALSE, NA)), identicalTo(c(0, 0, 0)))
test.Im.6 <- function() assertThat(Im(integer(0)), identicalTo(numeric(0)))
test.Im.7 <- function() assertThat(Im(structure(integer(0), .Names = character(0))), identicalTo(structure(numeric(0), .Names = character(0))))
test.Im.8 <- function() assertThat(Im(1:3), identicalTo(c(0, 0, 0)))
test.Im.9 <- function() assertThat(Im(c(1L, NA, 4L, NA, 999L)), identicalTo(c(0, 0, 0, 0, 0)))
test.Im.10 <- function() assertThat(Im(c(1L, 2L, 1073741824L, 1073741824L)), identicalTo(c(0, 0, 0, 0)))
test.Im.11 <- function() assertThat(Im(numeric(0)), identicalTo(numeric(0)))
test.Im.12 <- function() assertThat(Im(NaN), identicalTo(0))
test.Im.13 <- function() assertThat(Im(NA_real_), identicalTo(0))
test.Im.14 <- function() assertThat(Im(1), identicalTo(0))
test.Im.15 <- function() assertThat(Im(1.5), identicalTo(0))
test.Im.16 <- function() assertThat(Im(-1.5), identicalTo(0))
test.Im.17 <- function() assertThat(Im(3.14), identicalTo(0))
test.Im.18 <- function() assertThat(Im(Inf), identicalTo(0))
test.Im.19 <- function() assertThat(Im(-Inf), identicalTo(0))
test.Im.20 <- function() assertThat(Im(complex(0)), identicalTo(numeric(0)))
test.Im.21 <- function() assertThat(Im(structure(complex(0), .Names = character(0))), identicalTo(structure(numeric(0), .Names = character(0))))
test.Im.22 <- function() assertThat(Im(NA_complex_), identicalTo(NA_real_))
test.Im.23 <- function() assertThat(Im(NA_complex_), identicalTo(NA_real_))
test.Im.24 <- function() assertThat(Im(1.5+3i), identicalTo(3))
test.Im.25 <- function() assertThat(Im(1.5-3i), identicalTo(-3))
test.Im.26 <- function() assertThat(Im(-1.5+3i), identicalTo(3))
test.Im.27 <- function() assertThat(Im(1.5-3i), identicalTo(-3))
test.Im.28 <- function() assertThat(Im(structure(c(3+4i, 9+2i), .Names = c("a", "b"))), identicalTo(structure(c(4, 2), .Names = c("a", "b"))))
test.Im.29 <- function() assertThat(Im(structure(5+9i, rando.attr = "bazinga", class = "zarg")), identicalTo(structure(9, rando.attr = "bazinga", class = "zarg")))
test.Im.30 <- function() assertThat(Im(character(0)), throwsError())
test.Im.31 <- function() assertThat(Im(c("4.1", "blahh", "99.9", "-413", NA)), throwsError())
test.Im.32 <- function() assertThat(Im(list(1)), throwsError())
test.Im.33 <- function() assertThat(Im(structure(1:12, .Dim = 3:4)), identicalTo(structure(c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), .Dim = 3:4)))
test.Im.34 <- function() assertThat(Im(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))), identicalTo(structure(c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), .Dim = 3:4, .Dimnames = structure(list(    x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))))
test.Im.35 <- function() assertThat(Im(structure(1:3, rando.attrib = 941L)), identicalTo(structure(c(0, 0, 0), rando.attrib = 941L)))
test.Im.36 <- function() assertThat(Im(structure(c(1+4.5i, 2+4.5i, 3+4.5i), .Dim = 3L, .Dimnames = list(    c("a", "b", "c")))), identicalTo(structure(c(4.5, 4.5, 4.5), .Dim = 3L, .Dimnames = list(c("a", "b", "c"))), tol = 0.000100))
test.Im.37 <- function() assertThat(Im(structure(list("foo"), class = "foo")), identicalTo(41))
test.Im.38 <- function() assertThat(Im(structure(list("bar"), class = "foo")), identicalTo(41))
test.Im.39 <- function() assertThat(Im(structure("foo", class = "foo")), identicalTo(41))
test.Im.40 <- function() assertThat(Im(structure(list(1L, "bar"), class = "bar")), identicalTo(45))
