#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2019 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-unary-tests.R using GNU R version 3.3.3 (2017-03-06)
library(hamcrest)
Sys.setlocale('LC_COLLATE', 'C')
as.logical.foo <- function(...) 41L
as.vector.foo <- function(...) 99
Math.bar <- function(...) 44
Summary.bar <- function(...) 45
Ops.bar <- function(...) 46
test.as.logical.1 <- function() assertThat(as.logical(NULL), identicalTo(logical(0)))
test.as.logical.2 <- function() assertThat(as.logical(logical(0)), identicalTo(logical(0)))
test.as.logical.3 <- function() assertThat(as.logical(c(TRUE, TRUE, FALSE, FALSE, TRUE)), identicalTo(c(TRUE, TRUE, FALSE, FALSE, TRUE)))
test.as.logical.4 <- function() assertThat(as.logical(structure(c(TRUE, FALSE), .Names = c("a", ""))), identicalTo(c(TRUE, FALSE)))
test.as.logical.5 <- function() assertThat(as.logical(c(TRUE, FALSE, NA)), identicalTo(c(TRUE, FALSE, NA)))
test.as.logical.6 <- function() assertThat(as.logical(integer(0)), identicalTo(logical(0)))
test.as.logical.7 <- function() assertThat(as.logical(structure(integer(0), .Names = character(0))), identicalTo(logical(0)))
test.as.logical.8 <- function() assertThat(as.logical(1:3), identicalTo(c(TRUE, TRUE, TRUE)))
test.as.logical.9 <- function() assertThat(as.logical(c(1L, NA, 4L, NA, 999L)), identicalTo(c(TRUE, NA, TRUE, NA, TRUE)))
test.as.logical.10 <- function() assertThat(as.logical(c(1L, 2L, 1073741824L, 1073741824L)), identicalTo(c(TRUE, TRUE, TRUE, TRUE)))
test.as.logical.11 <- function() assertThat(as.logical(numeric(0)), identicalTo(logical(0)))
test.as.logical.12 <- function() assertThat(as.logical(c(3.14159, 6.28319, 9.42478, 12.5664, 15.708)), identicalTo(c(TRUE, TRUE, TRUE, TRUE, TRUE)))
test.as.logical.13 <- function() assertThat(as.logical(c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708)), identicalTo(c(TRUE, TRUE, TRUE, TRUE, TRUE)))
test.as.logical.14 <- function() assertThat(as.logical(structure(1:2, .Names = c("a", "b"))), identicalTo(c(TRUE, TRUE)))
test.as.logical.15 <- function() assertThat(as.logical(structure(c(1.5, 2.5), .Names = c("a", "b"))), identicalTo(c(TRUE, TRUE)))
test.as.logical.16 <- function() assertThat(as.logical(c(1.5, 1.51, 0, 1.49, -30)), identicalTo(c(TRUE, TRUE, FALSE, TRUE, TRUE)))
test.as.logical.17 <- function() assertThat(as.logical(c(1.5, 1.51, 0, 1.49, -30, NA)), identicalTo(c(TRUE, TRUE, FALSE, TRUE, TRUE, NA)))
test.as.logical.18 <- function() assertThat(as.logical(c(1.5, 1.51, 0, 1.49, -30, NaN)), identicalTo(c(TRUE, TRUE, FALSE, TRUE, TRUE, NA)))
test.as.logical.19 <- function() assertThat(as.logical(c(1.5, 1.51, 0, 1.49, -30, Inf)), identicalTo(c(TRUE, TRUE, FALSE, TRUE, TRUE, TRUE)))
test.as.logical.20 <- function() assertThat(as.logical(c(1.5, 1.51, 0, 1.49, -30, -Inf)), identicalTo(c(TRUE, TRUE, FALSE, TRUE, TRUE, TRUE)))
test.as.logical.21 <- function() assertThat(as.logical(character(0)), identicalTo(logical(0)))
test.as.logical.22 <- function() assertThat(as.logical(c("4.1", "blahh", "99.9", "-413", NA)), identicalTo(c(NA, NA, NA, NA, NA)))
test.as.logical.23 <- function() assertThat(as.logical(complex(0)), identicalTo(logical(0)))
test.as.logical.24 <- function() assertThat(as.logical(list(1, 2, 3)), identicalTo(c(TRUE, TRUE, TRUE)))
test.as.logical.25 <- function() assertThat(as.logical(list(1, 2, NULL)), throwsError())
test.as.logical.26 <- function() assertThat(as.logical(list(1L, 2L, 3L)), identicalTo(c(TRUE, TRUE, TRUE)))
test.as.logical.27 <- function() assertThat(as.logical(list(1L, 2L, NULL)), throwsError())
test.as.logical.28 <- function() assertThat(as.logical(list(1, 2, list(3, 4))), throwsError())
test.as.logical.29 <- function() assertThat(as.logical(list(1, 2, numeric(0))), identicalTo(c(TRUE, TRUE, NA)))
test.as.logical.30 <- function() assertThat(as.logical(list(3, "a", structure(list("b", z = list(TRUE, "c")), .Names = c("", "z")))), throwsError())
test.as.logical.31 <- function() assertThat(as.logical(structure(list(`NA` = 1, 2, b = 3), .Names = c(NA, "", "b"))), identicalTo(c(TRUE, TRUE, TRUE)))
test.as.logical.32 <- function() assertThat(as.logical(pairlist(41, "a", 21L)), identicalTo(c(TRUE, NA, TRUE)))
test.as.logical.33 <- function() assertThat(as.logical(pairlist(a = 41, 42)), identicalTo(c(TRUE, TRUE)))
test.as.logical.34 <- function() assertThat(as.logical(pairlist(a = 41, NULL)), throwsError())
test.as.logical.35 <- function() assertThat(as.logical(structure(1:12, .Dim = 3:4)), identicalTo(c(TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE)))
test.as.logical.36 <- function() assertThat(as.logical(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(    x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))), identicalTo(c(TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE)))
test.as.logical.37 <- function() assertThat(as.logical(structure(1:3, rando.attrib = 941L)), identicalTo(c(TRUE, TRUE, TRUE)))
test.as.logical.38 <- function() assertThat(as.logical(structure(1:3, .Dim = 3L, .Dimnames = list(c("a", "b", "c")))), identicalTo(c(TRUE, TRUE, TRUE)))
test.as.logical.39 <- function() assertThat(as.logical(structure(1:3, .Dim = 3L, .Dimnames = structure(list(    z = c("a", "b", "c")), .Names = "z"))), identicalTo(c(TRUE, TRUE, TRUE)))
test.as.logical.40 <- function() assertThat(as.logical(structure(list("foo"), class = "foo")), identicalTo(41L))
test.as.logical.41 <- function() assertThat(as.logical(structure(list("bar"), class = "foo")), identicalTo(41L))
test.as.logical.42 <- function() assertThat(as.logical(quote(xyz)), throwsError())
test.as.logical.43 <- function() assertThat(as.logical(quote(sin(3.14))), throwsError())
test.as.logical.44 <- function() assertThat(as.logical("NaN"), identicalTo(NA))
test.as.logical.45 <- function() assertThat(as.logical("NABOOM!"), identicalTo(NA))
test.as.logical.46 <- function() assertThat(as.logical("NaNaNabooboo"), identicalTo(NA))
test.as.logical.47 <- function() assertThat(as.logical("-Inf"), identicalTo(NA))
test.as.logical.48 <- function() assertThat(as.logical("+Infinity"), identicalTo(NA))
test.as.logical.49 <- function() assertThat(as.logical("Infinity and beyond!"), identicalTo(NA))
test.as.logical.50 <- function() assertThat(as.logical("Infi"), identicalTo(NA))
test.as.logical.51 <- function() assertThat(as.logical("0.03f"), identicalTo(NA))
test.as.logical.52 <- function() assertThat(as.logical("  0.0330   "), identicalTo(NA))
test.as.logical.53 <- function() assertThat(as.logical(structure("foo", class = "foo")), identicalTo(41L))
test.as.logical.54 <- function() assertThat(as.logical(structure(list(1L, "bar"), class = "bar")), identicalTo(c(TRUE, NA)))
