#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2019 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-unary-tests.R using GNU R version 3.4.4 (2018-03-15)
library(hamcrest)


test.closure <- function() {

    definition <- function(x, value) 42L
    a <- args(definition)

    assertThat(environment(a), identicalTo(.GlobalEnv))
    assertThat(body(a), identicalTo(NULL))
    assertThat(formals(a), identicalTo(formals(definition)))
}

test.builtin <- function() {

    a <- args(sqrt)
    assertThat(typeof(a), identicalTo("closure"))
    assertThat(names(formals(a)), identicalTo("x"))
}

test.missing <- function() {

    a <- args("missing")
    assertThat(typeof(a), identicalTo("closure"))
    assertThat(names(formals(a)), identicalTo("x"))
}
