#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2019 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-unary-tests.R using GNU R version 3.2.0 (2015-04-16)
library(hamcrest)
is.unsorted.foo <- function(...) 41
as.vector.foo <- function(...) 99
Math.bar <- function(...) 44
Summary.bar <- function(...) 45
Ops.bar <- function(...) 46
test.is.unsorted.1 <- function() assertThat(is.unsorted(NULL), identicalTo(FALSE))
test.is.unsorted.2 <- function() assertThat(is.unsorted(logical(0)), identicalTo(FALSE))
test.is.unsorted.3 <- function() assertThat(is.unsorted(c(TRUE, TRUE, FALSE, FALSE, TRUE)), identicalTo(TRUE))
test.is.unsorted.4 <- function() assertThat(is.unsorted(structure(c(TRUE, FALSE), .Names = c("a", ""))), identicalTo(TRUE))
test.is.unsorted.5 <- function() assertThat(is.unsorted(c(TRUE, FALSE, NA)), identicalTo(NA))
test.is.unsorted.6 <- function() assertThat(is.unsorted(integer(0)), identicalTo(FALSE))
test.is.unsorted.7 <- function() assertThat(is.unsorted(structure(integer(0), .Names = character(0))), identicalTo(FALSE))
test.is.unsorted.8 <- function() assertThat(is.unsorted(1:3), identicalTo(FALSE))
test.is.unsorted.9 <- function() assertThat(is.unsorted(c(1L, NA, 4L, NA, 999L)), identicalTo(NA))
test.is.unsorted.10 <- function() assertThat(is.unsorted(c(1L, 2L, 1073741824L, 1073741824L)), identicalTo(FALSE))
test.is.unsorted.11 <- function() assertThat(is.unsorted(numeric(0)), identicalTo(FALSE))
test.is.unsorted.12 <- function() assertThat(is.unsorted(c(3.14159, 6.28319, 9.42478, 12.5664, 15.708)), identicalTo(FALSE))
test.is.unsorted.13 <- function() assertThat(is.unsorted(c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708)), identicalTo(TRUE))
test.is.unsorted.14 <- function() assertThat(is.unsorted(structure(1:2, .Names = c("a", "b"))), identicalTo(FALSE))
test.is.unsorted.15 <- function() assertThat(is.unsorted(structure(c(1.5, 2.5), .Names = c("a", "b"))), identicalTo(FALSE))
test.is.unsorted.16 <- function() assertThat(is.unsorted(c(1.5, 1.51, 0, 1.49, -30)), identicalTo(TRUE))
test.is.unsorted.17 <- function() assertThat(is.unsorted(c(1.5, 1.51, 0, 1.49, -30, NA)), identicalTo(NA))
test.is.unsorted.18 <- function() assertThat(is.unsorted(c(1.5, 1.51, 0, 1.49, -30, NaN)), identicalTo(NA))
test.is.unsorted.19 <- function() assertThat(is.unsorted(c(1.5, 1.51, 0, 1.49, -30, Inf)), identicalTo(TRUE))
test.is.unsorted.20 <- function() assertThat(is.unsorted(c(1.5, 1.51, 0, 1.49, -30, -Inf)), identicalTo(TRUE))
test.is.unsorted.21 <- function() assertThat(is.unsorted(character(0)), identicalTo(FALSE))
test.is.unsorted.22 <- function() assertThat(is.unsorted(c("4.1", "blahh", "99.9", "-413", NA)), identicalTo(NA))
test.is.unsorted.23 <- function() assertThat(is.unsorted(list(1, 2, 3)), identicalTo(NA))
test.is.unsorted.24 <- function() assertThat(is.unsorted(list(1, 2, NULL)), identicalTo(NA))
test.is.unsorted.25 <- function() assertThat(is.unsorted(list(1L, 2L, 3L)), identicalTo(NA))
test.is.unsorted.26 <- function() assertThat(is.unsorted(list(1L, 2L, NULL)), identicalTo(NA))
test.is.unsorted.27 <- function() assertThat(is.unsorted(list(1, 2, list(3, 4))), identicalTo(NA))
test.is.unsorted.28 <- function() assertThat(is.unsorted(structure(1:12, .Dim = 3:4)), identicalTo(FALSE))
test.is.unsorted.29 <- function() assertThat(is.unsorted(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(    x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))), identicalTo(FALSE))
test.is.unsorted.30 <- function() assertThat(is.unsorted(structure(1:3, rando.attrib = 941L)), identicalTo(FALSE))
test.is.unsorted.31 <- function() assertThat(is.unsorted(structure(1:3, .Dim = 3L, .Dimnames = list(c("a", "b", "c")))), identicalTo(FALSE))
test.is.unsorted.32 <- function() assertThat(is.unsorted(structure(list("foo"), class = "foo")), identicalTo(FALSE))
test.is.unsorted.33 <- function() assertThat(is.unsorted(structure(list("bar"), class = "foo")), identicalTo(FALSE))
#test.is.unsorted.34 <- function() assertThat(is.unsorted(quote(xyz)), identicalTo(FALSE))
test.is.unsorted.35 <- function() assertThat(is.unsorted(quote(sin(3.14))), throwsError())
test.is.unsorted.36 <- function() assertThat(is.unsorted(structure("foo", class = "foo")), identicalTo(FALSE))
#test.is.unsorted.37 <- function() assertThat(is.unsorted(structure(list(1L, "bar"), class = "bar")), throwsError())
