# Generated by gen-dist-tests.R using GNU R version 3.2.0 (2015-04-16)
library(hamcrest)
library(stats)

test.rchisq.1 <- function() assertThat({set.seed(1); rchisq(n = 1, df = c(1, 2, 3, 4))}, identicalTo(0x1.94bd88c398c42p-3, tol = 0.000100))
test.rchisq.2 <- function() assertThat({set.seed(1); rchisq(n = 1:5, df = c(1, 2, 3, 4))}, identicalTo(c(0x1.94bd88c398c42p-3, 0x1.46cd823ef4d7ep+0, 0x1.5b132294fbe7fp-1, 0x1.068100b13bcdap+2, 0x1.5eb0939be9dd7p-7), tol = 0.000100))
test.rchisq.3 <- function() assertThat({set.seed(1); rchisq(n = 15, df = c(1, 2, 3, 4))}, identicalTo(c(0x1.94bd88c398c42p-3, 0x1.46cd823ef4d7ep+0, 0x1.5b132294fbe7fp-1, 0x1.068100b13bcdap+2, 0x1.5eb0939be9dd7p-7, 0x1.e306a9618224cp-4, 0x1.dfe626302fd5fp+1, 0x1.24df5b420433ap+2, 0x1.9e9b6af708fb9p-2, 0x1.11f75bd9ab545p+2, 0x1.6d86c51058b56p+1, 0x1.abd6e04a61b6fp+0, 0x1.a3c1b1643823p-2, 0x1.637523ae26e75p+0, 0x1.3a53a48fe671ep-1), tol = 0.000100))
test.rchisq.4 <- function() assertThat({set.seed(1); rchisq(n = numeric(0), df = c(1, 2, 3, 4))}, identicalTo(numeric(0)))
test.rchisq.5 <- function() assertThat({set.seed(1); rchisq(n = 3, df = c(NA, 2, 3, 4))}, identicalTo(c(NaN, 0x1.3dbac065e1d86p-2, 0x1.62cd513230be6p+2)))
