#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2019 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-unary-tests.R using GNU R version 3.3.3 (2017-03-06)
library(hamcrest)
Sys.setlocale('LC_COLLATE', 'C')
is.primitive.foo <- function(...) 41L
as.vector.foo <- function(...) 99
Math.bar <- function(...) 44
Summary.bar <- function(...) 45
Ops.bar <- function(...) 46
test.is.primitive.1 <- function() assertThat(is.primitive(NULL), identicalTo(FALSE))
test.is.primitive.2 <- function() assertThat(is.primitive(logical(0)), identicalTo(FALSE))
test.is.primitive.3 <- function() assertThat(is.primitive(c(TRUE, TRUE, FALSE, FALSE, TRUE)), identicalTo(FALSE))
test.is.primitive.4 <- function() assertThat(is.primitive(structure(c(TRUE, FALSE), .Names = c("a", ""))), identicalTo(FALSE))
test.is.primitive.5 <- function() assertThat(is.primitive(c(TRUE, FALSE, NA)), identicalTo(FALSE))
test.is.primitive.6 <- function() assertThat(is.primitive(integer(0)), identicalTo(FALSE))
test.is.primitive.7 <- function() assertThat(is.primitive(structure(integer(0), .Names = character(0))), identicalTo(FALSE))
test.is.primitive.8 <- function() assertThat(is.primitive(1:3), identicalTo(FALSE))
test.is.primitive.9 <- function() assertThat(is.primitive(c(1L, NA, 4L, NA, 999L)), identicalTo(FALSE))
test.is.primitive.10 <- function() assertThat(is.primitive(c(1L, 2L, 1073741824L, 1073741824L)), identicalTo(FALSE))
test.is.primitive.11 <- function() assertThat(is.primitive(numeric(0)), identicalTo(FALSE))
test.is.primitive.12 <- function() assertThat(is.primitive(c(3.14159, 6.28319, 9.42478, 12.5664, 15.708)), identicalTo(FALSE))
test.is.primitive.13 <- function() assertThat(is.primitive(c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708)), identicalTo(FALSE))
test.is.primitive.14 <- function() assertThat(is.primitive(structure(1:2, .Names = c("a", "b"))), identicalTo(FALSE))
test.is.primitive.15 <- function() assertThat(is.primitive(structure(c(1.5, 2.5), .Names = c("a", "b"))), identicalTo(FALSE))
test.is.primitive.16 <- function() assertThat(is.primitive(c(1.5, 1.51, 0, 1.49, -30)), identicalTo(FALSE))
test.is.primitive.17 <- function() assertThat(is.primitive(c(1.5, 1.51, 0, 1.49, -30, NA)), identicalTo(FALSE))
test.is.primitive.18 <- function() assertThat(is.primitive(c(1.5, 1.51, 0, 1.49, -30, NaN)), identicalTo(FALSE))
test.is.primitive.19 <- function() assertThat(is.primitive(c(1.5, 1.51, 0, 1.49, -30, Inf)), identicalTo(FALSE))
test.is.primitive.20 <- function() assertThat(is.primitive(c(1.5, 1.51, 0, 1.49, -30, -Inf)), identicalTo(FALSE))
test.is.primitive.21 <- function() assertThat(is.primitive(character(0)), identicalTo(FALSE))
test.is.primitive.22 <- function() assertThat(is.primitive(c("4.1", "blahh", "99.9", "-413", NA)), identicalTo(FALSE))
test.is.primitive.23 <- function() assertThat(is.primitive(complex(0)), identicalTo(FALSE))
test.is.primitive.24 <- function() assertThat(is.primitive(list(1, 2, 3)), identicalTo(FALSE))
test.is.primitive.25 <- function() assertThat(is.primitive(list(1, 2, NULL)), identicalTo(FALSE))
test.is.primitive.26 <- function() assertThat(is.primitive(list(1L, 2L, 3L)), identicalTo(FALSE))
test.is.primitive.27 <- function() assertThat(is.primitive(list(1L, 2L, NULL)), identicalTo(FALSE))
test.is.primitive.28 <- function() assertThat(is.primitive(list(1, 2, list(3, 4))), identicalTo(FALSE))
test.is.primitive.29 <- function() assertThat(is.primitive(list(1, 2, numeric(0))), identicalTo(FALSE))
test.is.primitive.30 <- function() assertThat(is.primitive(list(3, "a", structure(list("b", z = list(TRUE,     "c")), .Names = c("", "z")))), identicalTo(FALSE))
test.is.primitive.31 <- function() assertThat(is.primitive(structure(list(`NA` = 1, 2, b = 3), .Names = c(NA, "", "b"))), identicalTo(FALSE))
test.is.primitive.32 <- function() assertThat(is.primitive(pairlist(41, "a", 21L)), identicalTo(FALSE))
test.is.primitive.33 <- function() assertThat(is.primitive(pairlist(a = 41, 42)), identicalTo(FALSE))
test.is.primitive.34 <- function() assertThat(is.primitive(pairlist(a = 41, NULL)), identicalTo(FALSE))
test.is.primitive.35 <- function() assertThat(is.primitive(structure(1:12, .Dim = 3:4)), identicalTo(FALSE))
test.is.primitive.36 <- function() assertThat(is.primitive(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(    x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))), identicalTo(FALSE))
test.is.primitive.37 <- function() assertThat(is.primitive(structure(1:3, rando.attrib = 941L)), identicalTo(FALSE))
test.is.primitive.38 <- function() assertThat(is.primitive(structure(1:3, .Dim = 3L, .Dimnames = list(c("a", "b", "c")))), identicalTo(FALSE))
test.is.primitive.39 <- function() assertThat(is.primitive(structure(1:3, .Dim = 3L, .Dimnames = structure(list(    z = c("a", "b", "c")), .Names = "z"))), identicalTo(FALSE))
test.is.primitive.40 <- function() assertThat(is.primitive(structure(list("foo"), class = "foo")), identicalTo(FALSE))
test.is.primitive.41 <- function() assertThat(is.primitive(structure(list("bar"), class = "foo")), identicalTo(FALSE))
test.is.primitive.42 <- function() assertThat(is.primitive(quote(xyz)), identicalTo(FALSE))
test.is.primitive.43 <- function() assertThat(is.primitive(quote(sin(3.14))), identicalTo(FALSE))
test.is.primitive.44 <- function() assertThat(is.primitive("NaN"), identicalTo(FALSE))
test.is.primitive.45 <- function() assertThat(is.primitive("NABOOM!"), identicalTo(FALSE))
test.is.primitive.46 <- function() assertThat(is.primitive("NaNaNabooboo"), identicalTo(FALSE))
test.is.primitive.47 <- function() assertThat(is.primitive("-Inf"), identicalTo(FALSE))
test.is.primitive.48 <- function() assertThat(is.primitive("+Infinity"), identicalTo(FALSE))
test.is.primitive.49 <- function() assertThat(is.primitive("Infinity and beyond!"), identicalTo(FALSE))
test.is.primitive.50 <- function() assertThat(is.primitive("Infi"), identicalTo(FALSE))
test.is.primitive.51 <- function() assertThat(is.primitive("0.03f"), identicalTo(FALSE))
test.is.primitive.52 <- function() assertThat(is.primitive("  0.0330   "), identicalTo(FALSE))
test.is.primitive.53 <- function() assertThat(is.primitive(structure("foo", class = "foo")), identicalTo(FALSE))
test.is.primitive.54 <- function() assertThat(is.primitive(structure(list(1L, "bar"), class = "bar")), identicalTo(FALSE))
