#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2016 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-unary-tests.R using GNU R version 3.3.2 (2016-10-31)
library(hamcrest)
Sys.setlocale('LC_COLLATE', 'C')
as.call.foo <- function(...) 41L
as.vector.foo <- function(...) 99
Math.bar <- function(...) 44
Summary.bar <- function(...) 45
Ops.bar <- function(...) 46
test.as.call.1 <- function() assertThat(as.call(NULL), throwsError())
test.as.call.2 <- function() assertThat(as.call(logical(0)), throwsError())
test.as.call.3 <- function() assertThat(as.call(c(TRUE, TRUE, FALSE, FALSE, TRUE)), throwsError())
test.as.call.4 <- function() assertThat(as.call(structure(c(TRUE, FALSE), .Names = c("a", ""))), throwsError())
test.as.call.5 <- function() assertThat(as.call(c(TRUE, FALSE, NA)), throwsError())
test.as.call.6 <- function() assertThat(as.call(integer(0)), throwsError())
test.as.call.7 <- function() assertThat(as.call(structure(integer(0), .Names = character(0))), throwsError())
test.as.call.8 <- function() assertThat(as.call(1:3), throwsError())
test.as.call.9 <- function() assertThat(as.call(c(1L, NA, 4L, NA, 999L)), throwsError())
test.as.call.10 <- function() assertThat(as.call(c(1L, 2L, 1073741824L, 1073741824L)), throwsError())
test.as.call.11 <- function() assertThat(as.call(numeric(0)), throwsError())
test.as.call.12 <- function() assertThat(as.call(c(3.14159, 6.28319, 9.42478, 12.5664, 15.708)), throwsError())
test.as.call.13 <- function() assertThat(as.call(c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708)), throwsError())
test.as.call.14 <- function() assertThat(as.call(structure(1:2, .Names = c("a", "b"))), throwsError())
test.as.call.15 <- function() assertThat(as.call(structure(c(1.5, 2.5), .Names = c("a", "b"))), throwsError())
test.as.call.16 <- function() assertThat(as.call(c(1.5, 1.51, 0, 1.49, -30)), throwsError())
test.as.call.17 <- function() assertThat(as.call(c(1.5, 1.51, 0, 1.49, -30, NA)), throwsError())
test.as.call.18 <- function() assertThat(as.call(c(1.5, 1.51, 0, 1.49, -30, NaN)), throwsError())
test.as.call.19 <- function() assertThat(as.call(c(1.5, 1.51, 0, 1.49, -30, Inf)), throwsError())
test.as.call.20 <- function() assertThat(as.call(c(1.5, 1.51, 0, 1.49, -30, -Inf)), throwsError())
test.as.call.21 <- function() assertThat(as.call(character(0)), throwsError())
test.as.call.22 <- function() assertThat(as.call(c("4.1", "blahh", "99.9", "-413", NA)), throwsError())
test.as.call.23 <- function() assertThat(as.call(complex(0)), throwsError())
test.as.call.24 <- function() assertThat(as.call(list(1, 2, 3)), deparsesTo("1(2, 3)"))
test.as.call.25 <- function() assertThat(as.call(list(1, 2, NULL)), deparsesTo("1(2, NULL)"))
test.as.call.26 <- function() assertThat(as.call(list(1L, 2L, 3L)), deparsesTo("1L(2L, 3L)"))
test.as.call.27 <- function() assertThat(as.call(list(1L, 2L, NULL)), deparsesTo("1L(2L, NULL)"))
test.as.call.28 <- function() assertThat(as.call(list(1, 2, list(3, 4))), deparsesTo("1(2, list(3, 4))"))
test.as.call.29 <- function() assertThat(as.call(list(3, "a", structure(list("b", z = list(TRUE, "c")), .Names = c("", "z")))), deparsesTo("3(\"a\", structure(list(\"b\", z = list(TRUE, \"c\")), .Names = c(\"\", \"z\")))"))
test.as.call.30 <- function() assertThat(as.call(structure(list(`NA` = 1, 2, b = 3), .Names = c(NA, "", "b"))), deparsesTo("1(2, b = 3)"))
test.as.call.31 <- function() assertThat(as.call(pairlist(41, "a", 21L)), deparsesTo("41(\"a\", 21L)"))
test.as.call.32 <- function() assertThat(as.call(pairlist(a = 41, 42)), deparsesTo("41(42)"))
test.as.call.33 <- function() assertThat(as.call(pairlist(a = 41, NULL)), deparsesTo("41(NULL)"))
test.as.call.34 <- function() assertThat(as.call(structure(1:12, .Dim = 3:4)), throwsError())
test.as.call.35 <- function() assertThat(as.call(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(    x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))), throwsError())
test.as.call.36 <- function() assertThat(as.call(structure(1:3, rando.attrib = 941L)), throwsError())
test.as.call.37 <- function() assertThat(as.call(structure(1:3, .Dim = 3L, .Dimnames = list(c("a", "b", "c")))), throwsError())
test.as.call.38 <- function() assertThat(as.call(structure(1:3, .Dim = 3L, .Dimnames = structure(list(    z = c("a", "b", "c")), .Names = "z"))), throwsError())
test.as.call.39 <- function() assertThat(as.call(structure(list("foo"), class = "foo")), deparsesTo("\"foo\"()"))
test.as.call.40 <- function() assertThat(as.call(structure(list("bar"), class = "foo")), deparsesTo("\"bar\"()"))
test.as.call.41 <- function() assertThat(as.call(quote(xyz)), throwsError())
test.as.call.42 <- function() assertThat(as.call(quote(sin(3.14))), deparsesTo("sin(3.14)"))
test.as.call.43 <- function() assertThat(as.call(structure("foo", class = "foo")), throwsError())
test.as.call.44 <- function() assertThat(as.call(structure(list(1L, "bar"), class = "bar")), deparsesTo("1L(\"bar\")"))
