#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2019 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-unary-tests.R using GNU R version 3.3.3 (2017-03-06)
library(hamcrest)
Sys.setlocale('LC_COLLATE', 'C')
is.element.foo <- function(...) 41L
as.vector.foo <- function(...) 99
Math.bar <- function(...) 44
Summary.bar <- function(...) 45
Ops.bar <- function(...) 46
test.is.element.1 <- function() assertThat(is.element(NULL), throwsError())
test.is.element.2 <- function() assertThat(is.element(logical(0)), throwsError())
test.is.element.3 <- function() assertThat(is.element(c(TRUE, TRUE, FALSE, FALSE, TRUE)), throwsError())
test.is.element.4 <- function() assertThat(is.element(structure(c(TRUE, FALSE), .Names = c("a", ""))), throwsError())
test.is.element.5 <- function() assertThat(is.element(c(TRUE, FALSE, NA)), throwsError())
test.is.element.6 <- function() assertThat(is.element(integer(0)), throwsError())
test.is.element.7 <- function() assertThat(is.element(structure(integer(0), .Names = character(0))), throwsError())
test.is.element.8 <- function() assertThat(is.element(1:3), throwsError())
test.is.element.9 <- function() assertThat(is.element(c(1L, NA, 4L, NA, 999L)), throwsError())
test.is.element.10 <- function() assertThat(is.element(c(1L, 2L, 1073741824L, 1073741824L)), throwsError())
test.is.element.11 <- function() assertThat(is.element(numeric(0)), throwsError())
test.is.element.12 <- function() assertThat(is.element(c(3.14159, 6.28319, 9.42478, 12.5664, 15.708)), throwsError())
test.is.element.13 <- function() assertThat(is.element(c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708)), throwsError())
test.is.element.14 <- function() assertThat(is.element(structure(1:2, .Names = c("a", "b"))), throwsError())
test.is.element.15 <- function() assertThat(is.element(structure(c(1.5, 2.5), .Names = c("a", "b"))), throwsError())
test.is.element.16 <- function() assertThat(is.element(c(1.5, 1.51, 0, 1.49, -30)), throwsError())
test.is.element.17 <- function() assertThat(is.element(c(1.5, 1.51, 0, 1.49, -30, NA)), throwsError())
test.is.element.18 <- function() assertThat(is.element(c(1.5, 1.51, 0, 1.49, -30, NaN)), throwsError())
test.is.element.19 <- function() assertThat(is.element(c(1.5, 1.51, 0, 1.49, -30, Inf)), throwsError())
test.is.element.20 <- function() assertThat(is.element(c(1.5, 1.51, 0, 1.49, -30, -Inf)), throwsError())
test.is.element.21 <- function() assertThat(is.element(character(0)), throwsError())
test.is.element.22 <- function() assertThat(is.element(c("4.1", "blahh", "99.9", "-413", NA)), throwsError())
test.is.element.23 <- function() assertThat(is.element(complex(0)), throwsError())
test.is.element.24 <- function() assertThat(is.element(list(1, 2, 3)), throwsError())
test.is.element.25 <- function() assertThat(is.element(list(1, 2, NULL)), throwsError())
test.is.element.26 <- function() assertThat(is.element(list(1L, 2L, 3L)), throwsError())
test.is.element.27 <- function() assertThat(is.element(list(1L, 2L, NULL)), throwsError())
test.is.element.28 <- function() assertThat(is.element(list(1, 2, list(3, 4))), throwsError())
test.is.element.29 <- function() assertThat(is.element(list(1, 2, numeric(0))), throwsError())
test.is.element.30 <- function() assertThat(is.element(list(3, "a", structure(list("b", z = list(TRUE, "c")), .Names = c("", "z")))), throwsError())
test.is.element.31 <- function() assertThat(is.element(structure(list(`NA` = 1, 2, b = 3), .Names = c(NA, "", "b"))), throwsError())
test.is.element.32 <- function() assertThat(is.element(pairlist(41, "a", 21L)), throwsError())
test.is.element.33 <- function() assertThat(is.element(pairlist(a = 41, 42)), throwsError())
test.is.element.34 <- function() assertThat(is.element(pairlist(a = 41, NULL)), throwsError())
test.is.element.35 <- function() assertThat(is.element(structure(1:12, .Dim = 3:4)), throwsError())
test.is.element.36 <- function() assertThat(is.element(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(    x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))), throwsError())
test.is.element.37 <- function() assertThat(is.element(structure(1:3, rando.attrib = 941L)), throwsError())
test.is.element.38 <- function() assertThat(is.element(structure(1:3, .Dim = 3L, .Dimnames = list(c("a", "b", "c")))), throwsError())
test.is.element.39 <- function() assertThat(is.element(structure(1:3, .Dim = 3L, .Dimnames = structure(list(    z = c("a", "b", "c")), .Names = "z"))), throwsError())
test.is.element.40 <- function() assertThat(is.element(structure(list("foo"), class = "foo")), throwsError())
test.is.element.41 <- function() assertThat(is.element(structure(list("bar"), class = "foo")), throwsError())
test.is.element.42 <- function() assertThat(is.element(quote(xyz)), throwsError())
test.is.element.43 <- function() assertThat(is.element(quote(sin(3.14))), throwsError())
test.is.element.44 <- function() assertThat(is.element("NaN"), throwsError())
test.is.element.45 <- function() assertThat(is.element("NABOOM!"), throwsError())
test.is.element.46 <- function() assertThat(is.element("NaNaNabooboo"), throwsError())
test.is.element.47 <- function() assertThat(is.element("-Inf"), throwsError())
test.is.element.48 <- function() assertThat(is.element("+Infinity"), throwsError())
test.is.element.49 <- function() assertThat(is.element("Infinity and beyond!"), throwsError())
test.is.element.50 <- function() assertThat(is.element("Infi"), throwsError())
test.is.element.51 <- function() assertThat(is.element("0.03f"), throwsError())
test.is.element.52 <- function() assertThat(is.element("  0.0330   "), throwsError())
test.is.element.53 <- function() assertThat(is.element(structure("foo", class = "foo")), throwsError())
test.is.element.54 <- function() assertThat(is.element(structure(list(1L, "bar"), class = "bar")), throwsError())
