
library(hamcrest)

test.easy <- function() {
    x <- c("alice", "bob", "terry")
    assertThat(abbreviate(x, 2), equalTo(c(alice = "al", bob = "bb", terry = "tr")))
}


test.ambig <- function() {
    x <- c("abcd", "efgh", "abce")
    assertThat(abbreviate(x, 2), equalTo(c("abcd", "ef", "abce")))
}

test.states <- function() {
    as <- abbreviate(state.name, 3, strict = TRUE)
    assertThat(as['Alabama'], equalTo('Alb'))
    assertThat(as['Alaska'], equalTo('Als'))
    assertThat(as['Arizona'], equalTo('Arz'))
    assertThat(as['Arkansas'], equalTo('Ark'))
    assertThat(as['California'], equalTo('Clf'))
    assertThat(as['Colorado'], equalTo('Clr'))
    assertThat(as['Connecticut'], equalTo('Cnn'))
    assertThat(as['Delaware'], equalTo('Dlw'))
    assertThat(as['Florida'], equalTo('Flr'))
    assertThat(as['Georgia'], equalTo('Grg'))
    assertThat(as['Hawaii'], equalTo('Haw'))
    assertThat(as['Idaho'], equalTo('Idh'))
    assertThat(as['Illinois'], equalTo('Ill'))
    assertThat(as['Indiana'], equalTo('Ind'))
    assertThat(as['Iowa'], equalTo('Iow'))
    assertThat(as['Kansas'], equalTo('Kns'))
    assertThat(as['Kentucky'], equalTo('Knt'))
    assertThat(as['Louisiana'], equalTo('Lsn'))
    assertThat(as['Maine'], equalTo('Man'))
    assertThat(as['Maryland'], equalTo('Mry'))
    assertThat(as['Massachusetts'], equalTo('Mss'))
    assertThat(as['Michigan'], equalTo('Mch'))
    assertThat(as['Minnesota'], equalTo('Mnn'))
    assertThat(as['Mississippi'], equalTo('Mss'))
    assertThat(as['Missouri'], equalTo('Mss'))
    assertThat(as['Montana'], equalTo('Mnt'))
    assertThat(as['Nebraska'], equalTo('Nbr'))
    assertThat(as['Nevada'], equalTo('Nvd'))
    assertThat(as['New Hampshire'], equalTo('NwH'))
    assertThat(as['New Jersey'], equalTo('NwJ'))
    assertThat(as['New Mexico'], equalTo('NwM'))
    assertThat(as['New York'], equalTo('NwY'))
    assertThat(as['North Carolina'], equalTo('NrC'))
    assertThat(as['North Dakota'], equalTo('NrD'))
    assertThat(as['Ohio'], equalTo('Ohi'))
    assertThat(as['Oklahoma'], equalTo('Okl'))
    assertThat(as['Oregon'], equalTo('Org'))
    assertThat(as['Pennsylvania'], equalTo('Pnn'))
    assertThat(as['Rhode Island'], equalTo('RhI'))
    assertThat(as['South Carolina'], equalTo('StC'))
    assertThat(as['South Dakota'], equalTo('StD'))
    assertThat(as['Tennessee'], equalTo('Tnn'))
    assertThat(as['Texas'], equalTo('Txs'))
    assertThat(as['Utah'], equalTo('Uth'))
    assertThat(as['Vermont'], equalTo('Vrm'))
    assertThat(as['Virginia'], equalTo('Vrg'))
    assertThat(as['Washington'], equalTo('Wsh'))
    assertThat(as['West Virginia'], equalTo('WsV'))
    assertThat(as['Wisconsin'], equalTo('Wsc'))
    assertThat(as['Wyoming'], equalTo('Wym'))
}