#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2016 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-unary-tests.R using GNU R version 3.3.2 (2016-10-31)
library(hamcrest)
Sys.setlocale('LC_COLLATE', 'C')
as.integer.foo <- function(...) 41L
as.vector.foo <- function(...) 99
Math.bar <- function(...) 44
Summary.bar <- function(...) 45
Ops.bar <- function(...) 46
test.as.integer.1 <- function() assertThat(as.integer(NULL), identicalTo(integer(0)))
test.as.integer.2 <- function() assertThat(as.integer(logical(0)), identicalTo(integer(0)))
test.as.integer.3 <- function() assertThat(as.integer(c(TRUE, TRUE, FALSE, FALSE, TRUE)), identicalTo(c(1L, 1L, 0L, 0L, 1L)))
test.as.integer.4 <- function() assertThat(as.integer(structure(c(TRUE, FALSE), .Names = c("a", ""))), identicalTo(c(1L, 0L)))
test.as.integer.5 <- function() assertThat(as.integer(c(TRUE, FALSE, NA)), identicalTo(c(1L, 0L, NA)))
test.as.integer.6 <- function() assertThat(as.integer(integer(0)), identicalTo(integer(0)))
test.as.integer.7 <- function() assertThat(as.integer(structure(integer(0), .Names = character(0))), identicalTo(integer(0)))
test.as.integer.8 <- function() assertThat(as.integer(1:3), identicalTo(1:3))
test.as.integer.9 <- function() assertThat(as.integer(c(1L, NA, 4L, NA, 999L)), identicalTo(c(1L, NA, 4L, NA, 999L)))
test.as.integer.10 <- function() assertThat(as.integer(c(1L, 2L, 1073741824L, 1073741824L)), identicalTo(c(1L, 2L, 1073741824L, 1073741824L)))
test.as.integer.11 <- function() assertThat(as.integer(numeric(0)), identicalTo(integer(0)))
test.as.integer.12 <- function() assertThat(as.integer(c(3.14159, 6.28319, 9.42478, 12.5664, 15.708)), identicalTo(c(3L, 6L, 9L, 12L, 15L)))
test.as.integer.13 <- function() assertThat(as.integer(c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708)), identicalTo(c(-3L, -6L, -9L, -12L, -15L)))
test.as.integer.14 <- function() assertThat(as.integer(structure(1:2, .Names = c("a", "b"))), identicalTo(1:2))
test.as.integer.15 <- function() assertThat(as.integer(structure(c(1.5, 2.5), .Names = c("a", "b"))), identicalTo(1:2))
test.as.integer.16 <- function() assertThat(as.integer(c(1.5, 1.51, 0, 1.49, -30)), identicalTo(c(1L, 1L, 0L, 1L, -30L)))
test.as.integer.17 <- function() assertThat(as.integer(c(1.5, 1.51, 0, 1.49, -30, NA)), identicalTo(c(1L, 1L, 0L, 1L, -30L, NA)))
test.as.integer.18 <- function() assertThat(as.integer(c(1.5, 1.51, 0, 1.49, -30, NaN)), identicalTo(c(1L, 1L, 0L, 1L, -30L, NA)))
test.as.integer.19 <- function() assertThat(as.integer(c(1.5, 1.51, 0, 1.49, -30, Inf)), identicalTo(c(1L, 1L, 0L, 1L, -30L, NA)))
test.as.integer.20 <- function() assertThat(as.integer(c(1.5, 1.51, 0, 1.49, -30, -Inf)), identicalTo(c(1L, 1L, 0L, 1L, -30L, NA)))
test.as.integer.21 <- function() assertThat(as.integer(character(0)), identicalTo(integer(0)))
test.as.integer.22 <- function() assertThat(as.integer(c("4.1", "blahh", "99.9", "-413", NA)), identicalTo(c(4L, NA, 99L, -413L, NA)))
test.as.integer.23 <- function() assertThat(as.integer(complex(0)), identicalTo(integer(0)))
test.as.integer.24 <- function() assertThat(as.integer(list(1, 2, 3)), identicalTo(1:3))
test.as.integer.25 <- function() assertThat(as.integer(list(1, 2, NULL)), throwsError())
test.as.integer.26 <- function() assertThat(as.integer(list(1L, 2L, 3L)), identicalTo(1:3))
test.as.integer.27 <- function() assertThat(as.integer(list(1L, 2L, NULL)), throwsError())
test.as.integer.28 <- function() assertThat(as.integer(list(1, 2, list(3, 4))), throwsError())
test.as.integer.29 <- function() assertThat(as.integer(list(3, "a", structure(list("b", z = list(TRUE, "c")), .Names = c("", "z")))), throwsError())
test.as.integer.30 <- function() assertThat(as.integer(structure(list(`NA` = 1, 2, b = 3), .Names = c(NA, "", "b"))), identicalTo(1:3))
test.as.integer.31 <- function() assertThat(as.integer(pairlist(41, "a", 21L)), identicalTo(c(41L, NA, 21L)))
test.as.integer.32 <- function() assertThat(as.integer(pairlist(a = 41, 42)), identicalTo(41:42))
test.as.integer.33 <- function() assertThat(as.integer(pairlist(a = 41, NULL)), throwsError())
test.as.integer.34 <- function() assertThat(as.integer(structure(1:12, .Dim = 3:4)), identicalTo(1:12))
test.as.integer.35 <- function() assertThat(as.integer(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(    x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))), identicalTo(1:12))
test.as.integer.36 <- function() assertThat(as.integer(structure(1:3, rando.attrib = 941L)), identicalTo(1:3))
test.as.integer.37 <- function() assertThat(as.integer(structure(1:3, .Dim = 3L, .Dimnames = list(c("a", "b", "c")))), identicalTo(1:3))
test.as.integer.38 <- function() assertThat(as.integer(structure(1:3, .Dim = 3L, .Dimnames = structure(list(    z = c("a", "b", "c")), .Names = "z"))), identicalTo(1:3))
test.as.integer.39 <- function() assertThat(as.integer(structure(list("foo"), class = "foo")), identicalTo(41L))
test.as.integer.40 <- function() assertThat(as.integer(structure(list("bar"), class = "foo")), identicalTo(41L))
test.as.integer.41 <- function() assertThat(as.integer(quote(xyz)), throwsError())
test.as.integer.42 <- function() assertThat(as.integer(quote(sin(3.14))), throwsError())
test.as.integer.43 <- function() assertThat(as.integer("NaN"), identicalTo(NA_integer_))
test.as.integer.44 <- function() assertThat(as.integer("NABOOM!"), identicalTo(NA_integer_))
test.as.integer.45 <- function() assertThat(as.integer("NaNaNabooboo"), identicalTo(NA_integer_))
test.as.integer.46 <- function() assertThat(as.integer("-Inf"), identicalTo(NA_integer_))
test.as.integer.47 <- function() assertThat(as.integer("+Infinity"), identicalTo(NA_integer_))
test.as.integer.48 <- function() assertThat(as.integer("Infinity and beyond!"), identicalTo(NA_integer_))
test.as.integer.49 <- function() assertThat(as.integer("Infi"), identicalTo(NA_integer_))
test.as.integer.50 <- function() assertThat(as.integer("0.03f"), identicalTo(NA_integer_))
test.as.integer.51 <- function() assertThat(as.integer("  0.0330   "), identicalTo(0L))
test.as.integer.52 <- function() assertThat(as.integer(structure("foo", class = "foo")), identicalTo(41L))
test.as.integer.53 <- function() assertThat(as.integer(structure(list(1L, "bar"), class = "bar")), identicalTo(c(1L, NA)))
