#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2019 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-unary-tests.R using GNU R version 3.3.3 (2017-03-06)
library(hamcrest)
Sys.setlocale('LC_COLLATE', 'C')
is.name.foo <- function(...) 41L
as.vector.foo <- function(...) 99
Math.bar <- function(...) 44
Summary.bar <- function(...) 45
Ops.bar <- function(...) 46
test.is.name.1 <- function() assertThat(is.name(NULL), identicalTo(FALSE))
test.is.name.2 <- function() assertThat(is.name(logical(0)), identicalTo(FALSE))
test.is.name.3 <- function() assertThat(is.name(c(TRUE, TRUE, FALSE, FALSE, TRUE)), identicalTo(FALSE))
test.is.name.4 <- function() assertThat(is.name(structure(c(TRUE, FALSE), .Names = c("a", ""))), identicalTo(FALSE))
test.is.name.5 <- function() assertThat(is.name(c(TRUE, FALSE, NA)), identicalTo(FALSE))
test.is.name.6 <- function() assertThat(is.name(integer(0)), identicalTo(FALSE))
test.is.name.7 <- function() assertThat(is.name(structure(integer(0), .Names = character(0))), identicalTo(FALSE))
test.is.name.8 <- function() assertThat(is.name(1:3), identicalTo(FALSE))
test.is.name.9 <- function() assertThat(is.name(c(1L, NA, 4L, NA, 999L)), identicalTo(FALSE))
test.is.name.10 <- function() assertThat(is.name(c(1L, 2L, 1073741824L, 1073741824L)), identicalTo(FALSE))
test.is.name.11 <- function() assertThat(is.name(numeric(0)), identicalTo(FALSE))
test.is.name.12 <- function() assertThat(is.name(c(3.14159, 6.28319, 9.42478, 12.5664, 15.708)), identicalTo(FALSE))
test.is.name.13 <- function() assertThat(is.name(c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708)), identicalTo(FALSE))
test.is.name.14 <- function() assertThat(is.name(structure(1:2, .Names = c("a", "b"))), identicalTo(FALSE))
test.is.name.15 <- function() assertThat(is.name(structure(c(1.5, 2.5), .Names = c("a", "b"))), identicalTo(FALSE))
test.is.name.16 <- function() assertThat(is.name(c(1.5, 1.51, 0, 1.49, -30)), identicalTo(FALSE))
test.is.name.17 <- function() assertThat(is.name(c(1.5, 1.51, 0, 1.49, -30, NA)), identicalTo(FALSE))
test.is.name.18 <- function() assertThat(is.name(c(1.5, 1.51, 0, 1.49, -30, NaN)), identicalTo(FALSE))
test.is.name.19 <- function() assertThat(is.name(c(1.5, 1.51, 0, 1.49, -30, Inf)), identicalTo(FALSE))
test.is.name.20 <- function() assertThat(is.name(c(1.5, 1.51, 0, 1.49, -30, -Inf)), identicalTo(FALSE))
test.is.name.21 <- function() assertThat(is.name(character(0)), identicalTo(FALSE))
test.is.name.22 <- function() assertThat(is.name(c("4.1", "blahh", "99.9", "-413", NA)), identicalTo(FALSE))
test.is.name.23 <- function() assertThat(is.name(complex(0)), identicalTo(FALSE))
test.is.name.24 <- function() assertThat(is.name(list(1, 2, 3)), identicalTo(FALSE))
test.is.name.25 <- function() assertThat(is.name(list(1, 2, NULL)), identicalTo(FALSE))
test.is.name.26 <- function() assertThat(is.name(list(1L, 2L, 3L)), identicalTo(FALSE))
test.is.name.27 <- function() assertThat(is.name(list(1L, 2L, NULL)), identicalTo(FALSE))
test.is.name.28 <- function() assertThat(is.name(list(1, 2, list(3, 4))), identicalTo(FALSE))
test.is.name.29 <- function() assertThat(is.name(list(1, 2, numeric(0))), identicalTo(FALSE))
test.is.name.30 <- function() assertThat(is.name(list(3, "a", structure(list("b", z = list(TRUE, "c")), .Names = c("", "z")))), identicalTo(FALSE))
test.is.name.31 <- function() assertThat(is.name(structure(list(`NA` = 1, 2, b = 3), .Names = c(NA, "", "b"))), identicalTo(FALSE))
test.is.name.32 <- function() assertThat(is.name(pairlist(41, "a", 21L)), identicalTo(FALSE))
test.is.name.33 <- function() assertThat(is.name(pairlist(a = 41, 42)), identicalTo(FALSE))
test.is.name.34 <- function() assertThat(is.name(pairlist(a = 41, NULL)), identicalTo(FALSE))
test.is.name.35 <- function() assertThat(is.name(structure(1:12, .Dim = 3:4)), identicalTo(FALSE))
test.is.name.36 <- function() assertThat(is.name(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(    x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))), identicalTo(FALSE))
test.is.name.37 <- function() assertThat(is.name(structure(1:3, rando.attrib = 941L)), identicalTo(FALSE))
test.is.name.38 <- function() assertThat(is.name(structure(1:3, .Dim = 3L, .Dimnames = list(c("a", "b", "c")))), identicalTo(FALSE))
test.is.name.39 <- function() assertThat(is.name(structure(1:3, .Dim = 3L, .Dimnames = structure(list(    z = c("a", "b", "c")), .Names = "z"))), identicalTo(FALSE))
test.is.name.40 <- function() assertThat(is.name(structure(list("foo"), class = "foo")), identicalTo(FALSE))
test.is.name.41 <- function() assertThat(is.name(structure(list("bar"), class = "foo")), identicalTo(FALSE))
test.is.name.42 <- function() assertThat(is.name(quote(xyz)), identicalTo(TRUE))
test.is.name.43 <- function() assertThat(is.name(quote(sin(3.14))), identicalTo(FALSE))
test.is.name.44 <- function() assertThat(is.name("NaN"), identicalTo(FALSE))
test.is.name.45 <- function() assertThat(is.name("NABOOM!"), identicalTo(FALSE))
test.is.name.46 <- function() assertThat(is.name("NaNaNabooboo"), identicalTo(FALSE))
test.is.name.47 <- function() assertThat(is.name("-Inf"), identicalTo(FALSE))
test.is.name.48 <- function() assertThat(is.name("+Infinity"), identicalTo(FALSE))
test.is.name.49 <- function() assertThat(is.name("Infinity and beyond!"), identicalTo(FALSE))
test.is.name.50 <- function() assertThat(is.name("Infi"), identicalTo(FALSE))
test.is.name.51 <- function() assertThat(is.name("0.03f"), identicalTo(FALSE))
test.is.name.52 <- function() assertThat(is.name("  0.0330   "), identicalTo(FALSE))
test.is.name.53 <- function() assertThat(is.name(structure("foo", class = "foo")), identicalTo(FALSE))
test.is.name.54 <- function() assertThat(is.name(structure(list(1L, "bar"), class = "bar")), identicalTo(FALSE))
