library(hamcrest)
is.logical.foo <- function(x) 41
Math.bar <- function(x) 44
test.is.logical.1 <- function() assertThat(is.logical(NULL), identicalTo(FALSE))
test.is.logical.2 <- function() assertThat(is.logical(logical(0)), identicalTo(TRUE))
test.is.logical.3 <- function() assertThat(is.logical(c(TRUE, TRUE, FALSE, FALSE, TRUE)), identicalTo(TRUE))
test.is.logical.4 <- function() assertThat(is.logical(structure(c(TRUE, FALSE), .Names = c("a", ""))), identicalTo(TRUE))
test.is.logical.5 <- function() assertThat(is.logical(c(TRUE, FALSE, NA)), identicalTo(TRUE))
test.is.logical.6 <- function() assertThat(is.logical(integer(0)), identicalTo(FALSE))
test.is.logical.7 <- function() assertThat(is.logical(structure(integer(0), .Names = character(0))), identicalTo(FALSE))
test.is.logical.8 <- function() assertThat(is.logical(1:3), identicalTo(FALSE))
test.is.logical.9 <- function() assertThat(is.logical(c(1L, NA, 4L, NA, 999L)), identicalTo(FALSE))
test.is.logical.10 <- function() assertThat(is.logical(c(1L, 2L, 1073741824L, 1073741824L)), identicalTo(FALSE))
test.is.logical.11 <- function() assertThat(is.logical(numeric(0)), identicalTo(FALSE))
test.is.logical.12 <- function() assertThat(is.logical(c(3.14159, 6.28319, 9.42478, 12.5664, 15.708)), identicalTo(FALSE))
test.is.logical.13 <- function() assertThat(is.logical(c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708)), identicalTo(FALSE))
test.is.logical.14 <- function() assertThat(is.logical(structure(1:2, .Names = c("a", "b"))), identicalTo(FALSE))
test.is.logical.15 <- function() assertThat(is.logical(structure(c(1.5, 2.5), .Names = c("a", "b"))), identicalTo(FALSE))
test.is.logical.16 <- function() assertThat(is.logical(character(0)), identicalTo(FALSE))
test.is.logical.17 <- function() assertThat(is.logical(c("4.1", "blahh", "99.9", "-413", NA)), identicalTo(FALSE))
test.is.logical.18 <- function() assertThat(is.logical(list(1, 2, 3)), identicalTo(FALSE))
test.is.logical.19 <- function() assertThat(is.logical(list(1, 2, NULL)), identicalTo(FALSE))
test.is.logical.20 <- function() assertThat(is.logical(list(1L, 2L, 3L)), identicalTo(FALSE))
test.is.logical.21 <- function() assertThat(is.logical(list(1L, 2L, NULL)), identicalTo(FALSE))
test.is.logical.22 <- function() assertThat(is.logical(list(1, 2, list(3, 4))), identicalTo(FALSE))
test.is.logical.23 <- function() assertThat(is.logical(structure(1:12, .Dim = 3:4)), identicalTo(FALSE))
test.is.logical.24 <- function() assertThat(is.logical(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(    x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))), identicalTo(FALSE))
test.is.logical.25 <- function() assertThat(is.logical(structure(1:3, rando.attrib = 941L)), identicalTo(FALSE))
test.is.logical.26 <- function() assertThat(is.logical(structure(1:3, .Dim = 3L, .Dimnames = list(c("a", "b", "c")))), identicalTo(FALSE))
test.is.logical.27 <- function() assertThat(is.logical(structure(list("foo"), class = "foo")), identicalTo(FALSE))
test.is.logical.28 <- function() assertThat(is.logical(structure(list("bar"), class = "foo")), identicalTo(FALSE))
test.is.logical.29 <- function() assertThat(is.logical(xyz), throwsError())
test.is.logical.30 <- function() assertThat(is.logical(sin(3.14)), identicalTo(FALSE))
test.is.logical.31 <- function() assertThat(is.logical(structure("foo", class = "foo")), identicalTo(FALSE))
test.is.logical.32 <- function() assertThat(is.logical(structure(list(1L, "bar"), class = "bar")), identicalTo(FALSE))
