#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2016 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-unary-tests.R using GNU R version 3.3.2 (2016-10-31)
library(hamcrest)
Sys.setlocale('LC_COLLATE', 'C')
is.atomic.foo <- function(...) 41L
as.vector.foo <- function(...) 99
Math.bar <- function(...) 44
Summary.bar <- function(...) 45
Ops.bar <- function(...) 46
test.is.atomic.1 <- function() assertThat(is.atomic(NULL), identicalTo(TRUE))
test.is.atomic.2 <- function() assertThat(is.atomic(logical(0)), identicalTo(TRUE))
test.is.atomic.3 <- function() assertThat(is.atomic(c(TRUE, TRUE, FALSE, FALSE, TRUE)), identicalTo(TRUE))
test.is.atomic.4 <- function() assertThat(is.atomic(structure(c(TRUE, FALSE), .Names = c("a", ""))), identicalTo(TRUE))
test.is.atomic.5 <- function() assertThat(is.atomic(c(TRUE, FALSE, NA)), identicalTo(TRUE))
test.is.atomic.6 <- function() assertThat(is.atomic(integer(0)), identicalTo(TRUE))
test.is.atomic.7 <- function() assertThat(is.atomic(structure(integer(0), .Names = character(0))), identicalTo(TRUE))
test.is.atomic.8 <- function() assertThat(is.atomic(1:3), identicalTo(TRUE))
test.is.atomic.9 <- function() assertThat(is.atomic(c(1L, NA, 4L, NA, 999L)), identicalTo(TRUE))
test.is.atomic.10 <- function() assertThat(is.atomic(c(1L, 2L, 1073741824L, 1073741824L)), identicalTo(TRUE))
test.is.atomic.11 <- function() assertThat(is.atomic(numeric(0)), identicalTo(TRUE))
test.is.atomic.12 <- function() assertThat(is.atomic(c(3.14159, 6.28319, 9.42478, 12.5664, 15.708)), identicalTo(TRUE))
test.is.atomic.13 <- function() assertThat(is.atomic(c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708)), identicalTo(TRUE))
test.is.atomic.14 <- function() assertThat(is.atomic(structure(1:2, .Names = c("a", "b"))), identicalTo(TRUE))
test.is.atomic.15 <- function() assertThat(is.atomic(structure(c(1.5, 2.5), .Names = c("a", "b"))), identicalTo(TRUE))
test.is.atomic.16 <- function() assertThat(is.atomic(c(1.5, 1.51, 0, 1.49, -30)), identicalTo(TRUE))
test.is.atomic.17 <- function() assertThat(is.atomic(c(1.5, 1.51, 0, 1.49, -30, NA)), identicalTo(TRUE))
test.is.atomic.18 <- function() assertThat(is.atomic(c(1.5, 1.51, 0, 1.49, -30, NaN)), identicalTo(TRUE))
test.is.atomic.19 <- function() assertThat(is.atomic(c(1.5, 1.51, 0, 1.49, -30, Inf)), identicalTo(TRUE))
test.is.atomic.20 <- function() assertThat(is.atomic(c(1.5, 1.51, 0, 1.49, -30, -Inf)), identicalTo(TRUE))
test.is.atomic.21 <- function() assertThat(is.atomic(character(0)), identicalTo(TRUE))
test.is.atomic.22 <- function() assertThat(is.atomic(c("4.1", "blahh", "99.9", "-413", NA)), identicalTo(TRUE))
test.is.atomic.23 <- function() assertThat(is.atomic(complex(0)), identicalTo(TRUE))
test.is.atomic.24 <- function() assertThat(is.atomic(list(1, 2, 3)), identicalTo(FALSE))
test.is.atomic.25 <- function() assertThat(is.atomic(list(1, 2, NULL)), identicalTo(FALSE))
test.is.atomic.26 <- function() assertThat(is.atomic(list(1L, 2L, 3L)), identicalTo(FALSE))
test.is.atomic.27 <- function() assertThat(is.atomic(list(1L, 2L, NULL)), identicalTo(FALSE))
test.is.atomic.28 <- function() assertThat(is.atomic(list(1, 2, list(3, 4))), identicalTo(FALSE))
test.is.atomic.29 <- function() assertThat(is.atomic(list(3, "a", structure(list("b", z = list(TRUE, "c")), .Names = c("", "z")))), identicalTo(FALSE))
test.is.atomic.30 <- function() assertThat(is.atomic(structure(list(`NA` = 1, 2, b = 3), .Names = c(NA, "", "b"))), identicalTo(FALSE))
test.is.atomic.31 <- function() assertThat(is.atomic(pairlist(41, "a", 21L)), identicalTo(FALSE))
test.is.atomic.32 <- function() assertThat(is.atomic(pairlist(a = 41, 42)), identicalTo(FALSE))
test.is.atomic.33 <- function() assertThat(is.atomic(pairlist(a = 41, NULL)), identicalTo(FALSE))
test.is.atomic.34 <- function() assertThat(is.atomic(structure(1:12, .Dim = 3:4)), identicalTo(TRUE))
test.is.atomic.35 <- function() assertThat(is.atomic(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(    x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))), identicalTo(TRUE))
test.is.atomic.36 <- function() assertThat(is.atomic(structure(1:3, rando.attrib = 941L)), identicalTo(TRUE))
test.is.atomic.37 <- function() assertThat(is.atomic(structure(1:3, .Dim = 3L, .Dimnames = list(c("a", "b", "c")))), identicalTo(TRUE))
test.is.atomic.38 <- function() assertThat(is.atomic(structure(1:3, .Dim = 3L, .Dimnames = structure(list(    z = c("a", "b", "c")), .Names = "z"))), identicalTo(TRUE))
test.is.atomic.39 <- function() assertThat(is.atomic(structure(list("foo"), class = "foo")), identicalTo(FALSE))
test.is.atomic.40 <- function() assertThat(is.atomic(structure(list("bar"), class = "foo")), identicalTo(FALSE))
test.is.atomic.41 <- function() assertThat(is.atomic(quote(xyz)), identicalTo(FALSE))
test.is.atomic.42 <- function() assertThat(is.atomic(quote(sin(3.14))), identicalTo(FALSE))
test.is.atomic.43 <- function() assertThat(is.atomic(structure("foo", class = "foo")), identicalTo(TRUE))
test.is.atomic.44 <- function() assertThat(is.atomic(structure(list(1L, "bar"), class = "bar")), identicalTo(FALSE))
