#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2016 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-unary-tests.R using GNU R version 3.3.1 (2016-06-21)
library(hamcrest)
is.raw.foo <- function(...) 41L
as.vector.foo <- function(...) 99
Math.bar <- function(...) 44
Summary.bar <- function(...) 45
Ops.bar <- function(...) 46
test.is.raw.1 <- function() assertThat(is.raw(NULL), identicalTo(FALSE))
test.is.raw.2 <- function() assertThat(is.raw(logical(0)), identicalTo(FALSE))
test.is.raw.3 <- function() assertThat(is.raw(c(TRUE, TRUE, FALSE, FALSE, TRUE)), identicalTo(FALSE))
test.is.raw.4 <- function() assertThat(is.raw(structure(c(TRUE, FALSE), .Names = c("a", ""))), identicalTo(FALSE))
test.is.raw.5 <- function() assertThat(is.raw(c(TRUE, FALSE, NA)), identicalTo(FALSE))
test.is.raw.6 <- function() assertThat(is.raw(integer(0)), identicalTo(FALSE))
test.is.raw.7 <- function() assertThat(is.raw(structure(integer(0), .Names = character(0))), identicalTo(FALSE))
test.is.raw.8 <- function() assertThat(is.raw(1:3), identicalTo(FALSE))
test.is.raw.9 <- function() assertThat(is.raw(c(1L, NA, 4L, NA, 999L)), identicalTo(FALSE))
test.is.raw.10 <- function() assertThat(is.raw(c(1L, 2L, 1073741824L, 1073741824L)), identicalTo(FALSE))
test.is.raw.11 <- function() assertThat(is.raw(numeric(0)), identicalTo(FALSE))
test.is.raw.12 <- function() assertThat(is.raw(c(3.14159, 6.28319, 9.42478, 12.5664, 15.708)), identicalTo(FALSE))
test.is.raw.13 <- function() assertThat(is.raw(c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708)), identicalTo(FALSE))
test.is.raw.14 <- function() assertThat(is.raw(structure(1:2, .Names = c("a", "b"))), identicalTo(FALSE))
test.is.raw.15 <- function() assertThat(is.raw(structure(c(1.5, 2.5), .Names = c("a", "b"))), identicalTo(FALSE))
test.is.raw.16 <- function() assertThat(is.raw(c(1.5, 1.51, 0, 1.49, -30)), identicalTo(FALSE))
test.is.raw.17 <- function() assertThat(is.raw(c(1.5, 1.51, 0, 1.49, -30, NA)), identicalTo(FALSE))
test.is.raw.18 <- function() assertThat(is.raw(c(1.5, 1.51, 0, 1.49, -30, NaN)), identicalTo(FALSE))
test.is.raw.19 <- function() assertThat(is.raw(c(1.5, 1.51, 0, 1.49, -30, Inf)), identicalTo(FALSE))
test.is.raw.20 <- function() assertThat(is.raw(c(1.5, 1.51, 0, 1.49, -30, -Inf)), identicalTo(FALSE))
test.is.raw.21 <- function() assertThat(is.raw(character(0)), identicalTo(FALSE))
test.is.raw.22 <- function() assertThat(is.raw(c("4.1", "blahh", "99.9", "-413", NA)), identicalTo(FALSE))
test.is.raw.23 <- function() assertThat(is.raw(complex(0)), identicalTo(FALSE))
test.is.raw.24 <- function() assertThat(is.raw(list(1, 2, 3)), identicalTo(FALSE))
test.is.raw.25 <- function() assertThat(is.raw(list(1, 2, NULL)), identicalTo(FALSE))
test.is.raw.26 <- function() assertThat(is.raw(list(1L, 2L, 3L)), identicalTo(FALSE))
test.is.raw.27 <- function() assertThat(is.raw(list(1L, 2L, NULL)), identicalTo(FALSE))
test.is.raw.28 <- function() assertThat(is.raw(list(1, 2, list(3, 4))), identicalTo(FALSE))
test.is.raw.29 <- function() assertThat(is.raw(list(3, "a", structure(list("b", z = list(TRUE, "c")), .Names = c("", "z")))), identicalTo(FALSE))
test.is.raw.30 <- function() assertThat(is.raw(structure(list(`NA` = 1, 2, b = 3), .Names = c(NA, "", "b"))), identicalTo(FALSE))
test.is.raw.31 <- function() assertThat(is.raw(pairlist(41, "a", 21L)), identicalTo(FALSE))
test.is.raw.32 <- function() assertThat(is.raw(pairlist(a = 41, 42)), identicalTo(FALSE))
test.is.raw.33 <- function() assertThat(is.raw(pairlist(a = 41, NULL)), identicalTo(FALSE))
test.is.raw.34 <- function() assertThat(is.raw(structure(1:12, .Dim = 3:4)), identicalTo(FALSE))
test.is.raw.35 <- function() assertThat(is.raw(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(    x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))), identicalTo(FALSE))
test.is.raw.36 <- function() assertThat(is.raw(structure(1:3, rando.attrib = 941L)), identicalTo(FALSE))
test.is.raw.37 <- function() assertThat(is.raw(structure(1:3, .Dim = 3L, .Dimnames = list(c("a", "b", "c")))), identicalTo(FALSE))
test.is.raw.38 <- function() assertThat(is.raw(structure(1:3, .Dim = 3L, .Dimnames = structure(list(z = c("a", "b", "c")), .Names = "z"))), identicalTo(FALSE))
test.is.raw.39 <- function() assertThat(is.raw(structure(list("foo"), class = "foo")), identicalTo(FALSE))
test.is.raw.40 <- function() assertThat(is.raw(structure(list("bar"), class = "foo")), identicalTo(FALSE))
test.is.raw.41 <- function() assertThat(is.raw(quote(xyz)), identicalTo(FALSE))
test.is.raw.42 <- function() assertThat(is.raw(quote(sin(3.14))), identicalTo(FALSE))
test.is.raw.43 <- function() assertThat(is.raw(structure("foo", class = "foo")), identicalTo(FALSE))
test.is.raw.44 <- function() assertThat(is.raw(structure(list(1L, "bar"), class = "bar")), identicalTo(FALSE))
