#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2016 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-dist-tests.R using GNU R version 3.3.1 (2016-06-21)
library(hamcrest)
library(stats)
set.seed(1)
test.rweibull.1 <- function() assertThat({set.seed(1);rweibull(n = 0x1p+0, shape = c(0x1.999999999999ap-4, 0x1p-1, 0x1.4p+2), scale = c(0x0p+0, 0x1p+0, 0x1p-1, 0x1.4p+2))}, identicalTo(0x0p+0))
test.rweibull.2 <- function() assertThat({set.seed(1);rweibull(n = 1:5, shape = c(0x1.999999999999ap-4, 0x1p-1, 0x1.4p+2), scale = c(0x0p+0, 0x1p+0, 0x1p-1, 0x1.4p+2))}, identicalTo(c(0x0p+0, 0x1.c2311d3670c55p+0, 0x1.fed1e3cd69812p-2, 0x1.d80252d6027acp-7, 0x0p+0), tol = 0.000100))
test.rweibull.3 <- function() assertThat({set.seed(1);rweibull(n = 0x1.ep+3, shape = c(0x1.999999999999ap-4, 0x1p-1, 0x1.4p+2), scale = c(0x0p+0, 0x1p+0, 0x1p-1, 0x1.4p+2))}, identicalTo(c(0x0p+0, 0x1.c2311d3670c55p+0, 0x1.fed1e3cd69812p-2, 0x1.d80252d6027acp-7, 0x0p+0, 0x1.409c89596a991p-1, 0x1.babc8c8e9cfdap+5, 0x1.d64758454d19p-5, 0x0p+0, 0x1.9182036c80c27p-42, 0x1.5f8a5c2b7e8b4p-4, 0x1.1260c0bf4cceep+2, 0x0p+0, 0x1.f0118201e5d7cp+2, 0x1.18866456f9094p-1), tol = 0.000100))
test.rweibull.4 <- function() assertThat({set.seed(1);rweibull(n = numeric(0), shape = c(0x1.999999999999ap-4, 0x1p-1, 0x1.4p+2), scale = c(0x0p+0, 0x1p+0, 0x1p-1, 0x1.4p+2))}, identicalTo(numeric(0)))
test.rweibull.5 <- function() assertThat({set.seed(1);rweibull(n = 0x1.8p+1, shape = c(NA, 0x1p-1, 0x1.4p+2), scale = c(0x0p+0, 0x1p+0, 0x1p-1, 0x1.4p+2))}, identicalTo(c(0x0p+0, 0x1.c2311d3670c55p+0, 0x1.fed1e3cd69812p-2)))
