library(hamcrest)
as.logical.foo <- function(x) 41
Math.bar <- function(x) 44
test.as.logical.1 <- function() assertThat(as.logical(NULL), identicalTo(logical(0)))
test.as.logical.2 <- function() assertThat(as.logical(logical(0)), identicalTo(logical(0)))
test.as.logical.3 <- function() assertThat(as.logical(c(TRUE, TRUE, FALSE, FALSE, TRUE)), identicalTo(c(TRUE, TRUE, FALSE, FALSE, TRUE)))
test.as.logical.4 <- function() assertThat(as.logical(structure(c(TRUE, FALSE), .Names = c("a", ""))), identicalTo(c(TRUE, FALSE)))
test.as.logical.5 <- function() assertThat(as.logical(c(TRUE, FALSE, NA)), identicalTo(c(TRUE, FALSE, NA)))
test.as.logical.6 <- function() assertThat(as.logical(integer(0)), identicalTo(logical(0)))
test.as.logical.7 <- function() assertThat(as.logical(structure(integer(0), .Names = character(0))), identicalTo(logical(0)))
test.as.logical.8 <- function() assertThat(as.logical(1:3), identicalTo(c(TRUE, TRUE, TRUE)))
test.as.logical.9 <- function() assertThat(as.logical(c(1L, NA, 4L, NA, 999L)), identicalTo(c(TRUE, NA, TRUE, NA, TRUE)))
test.as.logical.10 <- function() assertThat(as.logical(c(1L, 2L, 1073741824L, 1073741824L)), identicalTo(c(TRUE, TRUE, TRUE, TRUE)))
test.as.logical.11 <- function() assertThat(as.logical(numeric(0)), identicalTo(logical(0)))
test.as.logical.12 <- function() assertThat(as.logical(c(3.14159, 6.28319, 9.42478, 12.5664, 15.708)), identicalTo(c(TRUE, TRUE, TRUE, TRUE, TRUE)))
test.as.logical.13 <- function() assertThat(as.logical(c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708)), identicalTo(c(TRUE, TRUE, TRUE, TRUE, TRUE)))
test.as.logical.14 <- function() assertThat(as.logical(structure(1:2, .Names = c("a", "b"))), identicalTo(c(TRUE, TRUE)))
test.as.logical.15 <- function() assertThat(as.logical(structure(c(1.5, 2.5), .Names = c("a", "b"))), identicalTo(c(TRUE, TRUE)))
test.as.logical.16 <- function() assertThat(as.logical(character(0)), identicalTo(logical(0)))
test.as.logical.17 <- function() assertThat(as.logical(c("4.1", "blahh", "99.9", "-413", NA)), identicalTo(c(NA, NA, NA, NA, NA)))
test.as.logical.18 <- function() assertThat(as.logical(list(1, 2, 3)), identicalTo(c(TRUE, TRUE, TRUE)))
test.as.logical.19 <- function() assertThat(as.logical(list(1, 2, NULL)), throwsError())
test.as.logical.20 <- function() assertThat(as.logical(list(1L, 2L, 3L)), identicalTo(c(TRUE, TRUE, TRUE)))
test.as.logical.21 <- function() assertThat(as.logical(list(1L, 2L, NULL)), throwsError())
test.as.logical.22 <- function() assertThat(as.logical(list(1, 2, list(3, 4))), throwsError())
test.as.logical.23 <- function() assertThat(as.logical(structure(1:12, .Dim = 3:4)), identicalTo(c(TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE)))
test.as.logical.24 <- function() assertThat(as.logical(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(    x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))), identicalTo(c(TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE)))
test.as.logical.25 <- function() assertThat(as.logical(structure(1:3, rando.attrib = 941L)), identicalTo(c(TRUE, TRUE, TRUE)))
test.as.logical.26 <- function() assertThat(as.logical(structure(1:3, .Dim = 3L, .Dimnames = list(c("a", "b", "c")))), identicalTo(c(TRUE, TRUE, TRUE)))
test.as.logical.27 <- function() assertThat(as.logical(structure(list("foo"), class = "foo")), identicalTo(41, tol = 0.000100))
test.as.logical.28 <- function() assertThat(as.logical(structure(list("bar"), class = "foo")), identicalTo(41, tol = 0.000100))
test.as.logical.29 <- function() assertThat(as.logical(xyz), throwsError())
test.as.logical.30 <- function() assertThat(as.logical(sin(3.14)), identicalTo(TRUE))
test.as.logical.31 <- function() assertThat(as.logical(structure("foo", class = "foo")), identicalTo(41))
test.as.logical.32 <- function() assertThat(as.logical(structure(list(1L, "bar"), class = "bar")), identicalTo(c(TRUE, NA)))
