library(hamcrest)
is.atomic.foo <- function(x) 41
Math.bar <- function(x) 44
test.is.atomic.1 <- function() assertThat(is.atomic(NULL), identicalTo(TRUE))
test.is.atomic.2 <- function() assertThat(is.atomic(logical(0)), identicalTo(TRUE))
test.is.atomic.3 <- function() assertThat(is.atomic(c(TRUE, TRUE, FALSE, FALSE, TRUE)), identicalTo(TRUE))
test.is.atomic.4 <- function() assertThat(is.atomic(structure(c(TRUE, FALSE), .Names = c("a", ""))), identicalTo(TRUE))
test.is.atomic.5 <- function() assertThat(is.atomic(c(TRUE, FALSE, NA)), identicalTo(TRUE))
test.is.atomic.6 <- function() assertThat(is.atomic(integer(0)), identicalTo(TRUE))
test.is.atomic.7 <- function() assertThat(is.atomic(structure(integer(0), .Names = character(0))), identicalTo(TRUE))
test.is.atomic.8 <- function() assertThat(is.atomic(1:3), identicalTo(TRUE))
test.is.atomic.9 <- function() assertThat(is.atomic(c(1L, NA, 4L, NA, 999L)), identicalTo(TRUE))
test.is.atomic.10 <- function() assertThat(is.atomic(c(1L, 2L, 1073741824L, 1073741824L)), identicalTo(TRUE))
test.is.atomic.11 <- function() assertThat(is.atomic(numeric(0)), identicalTo(TRUE))
test.is.atomic.12 <- function() assertThat(is.atomic(c(3.14159, 6.28319, 9.42478, 12.5664, 15.708)), identicalTo(TRUE))
test.is.atomic.13 <- function() assertThat(is.atomic(c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708)), identicalTo(TRUE))
test.is.atomic.14 <- function() assertThat(is.atomic(structure(1:2, .Names = c("a", "b"))), identicalTo(TRUE))
test.is.atomic.15 <- function() assertThat(is.atomic(structure(c(1.5, 2.5), .Names = c("a", "b"))), identicalTo(TRUE))
test.is.atomic.16 <- function() assertThat(is.atomic(character(0)), identicalTo(TRUE))
test.is.atomic.17 <- function() assertThat(is.atomic(c("4.1", "blahh", "99.9", "-413", NA)), identicalTo(TRUE))
test.is.atomic.18 <- function() assertThat(is.atomic(list(1, 2, 3)), identicalTo(FALSE))
test.is.atomic.19 <- function() assertThat(is.atomic(list(1, 2, NULL)), identicalTo(FALSE))
test.is.atomic.20 <- function() assertThat(is.atomic(list(1L, 2L, 3L)), identicalTo(FALSE))
test.is.atomic.21 <- function() assertThat(is.atomic(list(1L, 2L, NULL)), identicalTo(FALSE))
test.is.atomic.22 <- function() assertThat(is.atomic(list(1, 2, list(3, 4))), identicalTo(FALSE))
test.is.atomic.23 <- function() assertThat(is.atomic(structure(1:12, .Dim = 3:4)), identicalTo(TRUE))
test.is.atomic.24 <- function() assertThat(is.atomic(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(    x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))), identicalTo(TRUE))
test.is.atomic.25 <- function() assertThat(is.atomic(structure(1:3, rando.attrib = 941L)), identicalTo(TRUE))
test.is.atomic.26 <- function() assertThat(is.atomic(structure(1:3, .Dim = 3L, .Dimnames = list(c("a", "b", "c")))), identicalTo(TRUE))
test.is.atomic.27 <- function() assertThat(is.atomic(structure(list("foo"), class = "foo")), identicalTo(FALSE))
test.is.atomic.28 <- function() assertThat(is.atomic(structure(list("bar"), class = "foo")), identicalTo(FALSE))
test.is.atomic.29 <- function() assertThat(is.atomic(xyz), throwsError())
test.is.atomic.30 <- function() assertThat(is.atomic(sin(3.14)), identicalTo(TRUE))
test.is.atomic.31 <- function() assertThat(is.atomic(structure("foo", class = "foo")), identicalTo(TRUE))
test.is.atomic.32 <- function() assertThat(is.atomic(structure(list(1L, "bar"), class = "bar")), identicalTo(FALSE))
