#
# Renjin : JVM-based interpreter for the R language for the statistical analysis
# Copyright © 2010-2016 BeDataDriven Groep B.V. and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, a copy is available at
# https://www.gnu.org/licenses/gpl-2.0.txt
#

# Generated by gen-unary-tests.R using GNU R version 3.3.1 (2016-06-21)
library(hamcrest)
is.numeric.foo <- function(...) 41L
as.vector.foo <- function(...) 99
Math.bar <- function(...) 44
Summary.bar <- function(...) 45
Ops.bar <- function(...) 46
test.is.numeric.1 <- function() assertThat(is.numeric(NULL), identicalTo(FALSE))
test.is.numeric.2 <- function() assertThat(is.numeric(logical(0)), identicalTo(FALSE))
test.is.numeric.3 <- function() assertThat(is.numeric(c(TRUE, TRUE, FALSE, FALSE, TRUE)), identicalTo(FALSE))
test.is.numeric.4 <- function() assertThat(is.numeric(structure(c(TRUE, FALSE), .Names = c("a", ""))), identicalTo(FALSE))
test.is.numeric.5 <- function() assertThat(is.numeric(c(TRUE, FALSE, NA)), identicalTo(FALSE))
test.is.numeric.6 <- function() assertThat(is.numeric(integer(0)), identicalTo(TRUE))
test.is.numeric.7 <- function() assertThat(is.numeric(structure(integer(0), .Names = character(0))), identicalTo(TRUE))
test.is.numeric.8 <- function() assertThat(is.numeric(1:3), identicalTo(TRUE))
test.is.numeric.9 <- function() assertThat(is.numeric(c(1L, NA, 4L, NA, 999L)), identicalTo(TRUE))
test.is.numeric.10 <- function() assertThat(is.numeric(c(1L, 2L, 1073741824L, 1073741824L)), identicalTo(TRUE))
test.is.numeric.11 <- function() assertThat(is.numeric(numeric(0)), identicalTo(TRUE))
test.is.numeric.12 <- function() assertThat(is.numeric(c(3.14159, 6.28319, 9.42478, 12.5664, 15.708)), identicalTo(TRUE))
test.is.numeric.13 <- function() assertThat(is.numeric(c(-3.14159, -6.28319, -9.42478, -12.5664, -15.708)), identicalTo(TRUE))
test.is.numeric.14 <- function() assertThat(is.numeric(structure(1:2, .Names = c("a", "b"))), identicalTo(TRUE))
test.is.numeric.15 <- function() assertThat(is.numeric(structure(c(1.5, 2.5), .Names = c("a", "b"))), identicalTo(TRUE))
test.is.numeric.16 <- function() assertThat(is.numeric(c(1.5, 1.51, 0, 1.49, -30)), identicalTo(TRUE))
test.is.numeric.17 <- function() assertThat(is.numeric(c(1.5, 1.51, 0, 1.49, -30, NA)), identicalTo(TRUE))
test.is.numeric.18 <- function() assertThat(is.numeric(c(1.5, 1.51, 0, 1.49, -30, NaN)), identicalTo(TRUE))
test.is.numeric.19 <- function() assertThat(is.numeric(c(1.5, 1.51, 0, 1.49, -30, Inf)), identicalTo(TRUE))
test.is.numeric.20 <- function() assertThat(is.numeric(c(1.5, 1.51, 0, 1.49, -30, -Inf)), identicalTo(TRUE))
test.is.numeric.21 <- function() assertThat(is.numeric(character(0)), identicalTo(FALSE))
test.is.numeric.22 <- function() assertThat(is.numeric(c("4.1", "blahh", "99.9", "-413", NA)), identicalTo(FALSE))
test.is.numeric.23 <- function() assertThat(is.numeric(complex(0)), identicalTo(FALSE))
test.is.numeric.24 <- function() assertThat(is.numeric(list(1, 2, 3)), identicalTo(FALSE))
test.is.numeric.25 <- function() assertThat(is.numeric(list(1, 2, NULL)), identicalTo(FALSE))
test.is.numeric.26 <- function() assertThat(is.numeric(list(1L, 2L, 3L)), identicalTo(FALSE))
test.is.numeric.27 <- function() assertThat(is.numeric(list(1L, 2L, NULL)), identicalTo(FALSE))
test.is.numeric.28 <- function() assertThat(is.numeric(list(1, 2, list(3, 4))), identicalTo(FALSE))
test.is.numeric.29 <- function() assertThat(is.numeric(list(3, "a", structure(list("b", z = list(TRUE, "c")), .Names = c("", "z")))), identicalTo(FALSE))
test.is.numeric.30 <- function() assertThat(is.numeric(structure(list(`NA` = 1, 2, b = 3), .Names = c(NA, "", "b"))), identicalTo(FALSE))
test.is.numeric.31 <- function() assertThat(is.numeric(pairlist(41, "a", 21L)), identicalTo(FALSE))
test.is.numeric.32 <- function() assertThat(is.numeric(pairlist(a = 41, 42)), identicalTo(FALSE))
test.is.numeric.33 <- function() assertThat(is.numeric(pairlist(a = 41, NULL)), identicalTo(FALSE))
test.is.numeric.34 <- function() assertThat(is.numeric(structure(1:12, .Dim = 3:4)), identicalTo(TRUE))
test.is.numeric.35 <- function() assertThat(is.numeric(structure(1:12, .Dim = 3:4, .Dimnames = structure(list(    x = c("a", "b", "c"), y = c("d", "e", "f", "g")), .Names = c("x", "y")))), identicalTo(TRUE))
test.is.numeric.36 <- function() assertThat(is.numeric(structure(1:3, rando.attrib = 941L)), identicalTo(TRUE))
test.is.numeric.37 <- function() assertThat(is.numeric(structure(1:3, .Dim = 3L, .Dimnames = list(c("a", "b", "c")))), identicalTo(TRUE))
test.is.numeric.38 <- function() assertThat(is.numeric(structure(1:3, .Dim = 3L, .Dimnames = structure(list(    z = c("a", "b", "c")), .Names = "z"))), identicalTo(TRUE))
test.is.numeric.39 <- function() assertThat(is.numeric(structure(list("foo"), class = "foo")), identicalTo(41L))
test.is.numeric.40 <- function() assertThat(is.numeric(structure(list("bar"), class = "foo")), identicalTo(41L))
test.is.numeric.41 <- function() assertThat(is.numeric(quote(xyz)), identicalTo(FALSE))
test.is.numeric.42 <- function() assertThat(is.numeric(quote(sin(3.14))), identicalTo(FALSE))
test.is.numeric.43 <- function() assertThat(is.numeric(structure("foo", class = "foo")), identicalTo(41L))
test.is.numeric.44 <- function() assertThat(is.numeric(structure(list(1L, "bar"), class = "bar")), identicalTo(FALSE))
